// What the 2-XM (and the Oberheim SEM it follows) names or does differently from most synths. Attached with annotate() in the SynthDef.
export default {
  'xm1_vcf.notch': 'Most multimode filters switch between low-pass, band-pass and high-pass. On the SEM one knob sweeps continuously from low-pass through a notch to high-pass, so every setting in between is available.',
  'xm2_vcf.notch': 'Most multimode filters switch between low-pass, band-pass and high-pass. On the SEM one knob sweeps continuously from low-pass through a notch to high-pass, so every setting in between is available.',
  'xm1_vcf.mix_vco1': 'There are no oscillator level knobs. Each mixer knob is a crossfade that is silent at the centre: one waveform to the left, the other to the right. To mix a saw and a pulse, use both VCOs.',
  'xm2_vcf.mix_vco1': 'There are no oscillator level knobs. Each mixer knob is a crossfade that is silent at the centre: one waveform to the left, the other to the right. To mix a saw and a pulse, use both VCOs.',
  'xm1_vcf.mix_ext': 'With nothing in the EXT jack, turning this left brings in a 440 Hz tuning tone rather than silence. If a steady A appears under every note, this knob is the reason.',
  'xm2_vcf.mix_ext': 'With nothing in the EXT jack, turning this left brings in a 440 Hz tuning tone rather than silence. If a steady A appears under every note, this knob is the reason.',
  'xm1_vco1.modulation': 'One bipolar knob does two jobs: vibrato or pitch sweeps to the left, pulse-width modulation to the right. You cannot have both from the same oscillator at once.',
  'xm2_vco1.modulation': 'One bipolar knob does two jobs: vibrato or pitch sweeps to the left, pulse-width modulation to the right. You cannot have both from the same oscillator at once.',
  'xm1_vco2.mod_source': 'VCO 2 is modulated by ENV 2, the filter envelope, while VCO 1 is modulated by ENV 1, the loudness envelope. Pick the oscillator by which envelope you want to shape it.',
  'xm2_vco2.mod_source': 'VCO 2 is modulated by ENV 2, the filter envelope, while VCO 1 is modulated by ENV 1, the loudness envelope. Pick the oscillator by which envelope you want to shape it.',
  'xm1_vcf.mod_source': 'The middle position is labelled EXT, but with no cable in VCF CV it gives ENV 2 scaled by velocity: the “velocity to filter” most synths have.',
  'xm2_vcf.mod_source': 'The middle position is labelled EXT, but with no cable in VCF CV it gives ENV 2 scaled by velocity: the “velocity to filter” most synths have.',
  'xm1_env1.decay': 'The envelopes are ADS: DECAY sets both the decay and the release, so a note that decays slowly also dies away slowly after you let go.',
  'xm2_env1.decay': 'The envelopes are ADS: DECAY sets both the decay and the release, so a note that decays slowly also dies away slowly after you let go.',
  'xm1_vca.mode': 'ON/EXT holds the amplifier open, so the module sounds with no key held. It is the easy way to a drone, and a surprise if left there by mistake.',
  'xm2_vca.mode': 'ON/EXT holds the amplifier open, so the module sounds with no key held. It is the easy way to a drone, and a surprise if left there by mistake.',
  'alloc.assign': 'The two modules are separate synths with separate panels, not two copies of one patch. In UNI or DUO they only sound alike if you set their knobs alike.',
  'j.xm1.cv_out': 'CV 1 is printed in the input column, but the guide lists it as an output: the MIDI pitch of XM1 as a voltage.',
  'j.xm2.cv_out': 'CV 2 is printed in the input column, but the guide lists it as an output: the MIDI pitch of XM2 as a voltage.',
  'j.xm1.vco1_cv': 'A cable here replaces the MIDI pitch rather than adding to it, and it drives VCO 2 as well until VCO 2 CV gets its own cable.',
  'j.xm2.vco1_cv': 'A cable here replaces the MIDI pitch rather than adding to it, and it drives VCO 2 as well until VCO 2 CV gets its own cable.',
};
