// More sounds for the Buchla Music Easel library. Same Preset shape as the ones in ../buchla-easel.js (see CONTRACT.md → Preset).
// Cords are [output jack, input jack].

export default [
  {
    id: 'easel-fm-bell', name: 'FM Bell', ref: 'Classic technique: audio-rate FM with an envelope on the index', artist: 'Classic technique',
    tags: ['keys', 'fm', 'bell'], level: 2,
    blurb: 'The modulation oscillator, at audio rate and following the keys, frequency-modulates the complex oscillator: a struck, glassy bell.',
    how: 'With both oscillators following the keyboard, their ratio stays the same on every key, so every note has the same bell-like colour. The envelope goes to two places: LEVEL 1, to strike the gate, and the modulation input, so the clangy sidebands are strongest at the strike and die away first, the way a real bell’s overtones do.',
    phrase: { bpm: 72, loop: true, steps: [[0, 60, 1.5], [1.5, 67, 1.5], [3, 64, 1], [4, 72, 3]] },
    steps: [
      { title: 'A struck sine', module: 'env',
        why: 'A sine through Gate 1, struck by a transient envelope with a long decay.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- waveshape 0, TIMBRE 0.\n- Envelope transient: attack 10, sustain 8, decay 3.\n- Gate 1 combination.',
        set: { 'cosc.shape': 0, 'cosc.timbre': 0, 'env.trig': 'kbd', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 8, 'env.decay': 3, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo' },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'An audio-rate modulator that follows the keys', module: 'lfo',
        why: 'Switch the modulation oscillator to its high range and its KEYBOARD switch on, and tune it well above the complex oscillator. f.m. osc. mode, index 0 for now.\n- range high, KEYBOARD on, waveshape triangle.\n- FREQUENCY 3.6: about 1.4 times the complex oscillator’s pitch, a ratio that gives inharmonic, bell-like partials.\n- modulation: f.m. osc.',
        set: { 'mosc.range': 'high', 'mosc.kbd': true, 'mosc.wave': 'tri', 'mosc.freq': 3.6, 'mosc.mode': 'fm', 'mosc.index': 0 } },
      { title: 'The envelope on the index', module: 'lfo',
        why: 'A second orange jack into the black modulation jack, with its processing slider at 6. The FM is deepest at the strike and fades with the envelope.\n- Cord: envelope 1 → modulation input.\n- modulation processing 6.\n- Listen for: a bright, clangy strike that settles into a purer tone.',
        set: { 'mosc.indexCv': 6, 'out.rev': 4 }, cables: [['j.env1', 'j.index']] },
    ],
    context: {
      'mosc.freq': 'In this sound: the ratio between the oscillators, which sets the bell’s colour. Small moves give very different bells.',
      'mosc.indexCv': 'In this sound: how clangy the strike is.',
      'env.decay': 'In this sound: how long the bell rings. Lower on the slider is longer.',
    },
    tweaks: [
      { id: 'mosc.freq', try: 'Move FREQUENCY to 4.6', hear: 'A different set of partials: more like a gong.' },
      { id: 'mosc.index', try: 'Raise the modulation offset to 3', hear: 'The sound keeps some clang all the way through.' },
    ],
  },
  {
    id: 'easel-ring-am', name: 'Ring-Modulated Voice', ref: 'From the Easel manual — AM up to full ring modulation', artist: 'Buchla',
    tags: ['lead', 'am', 'ring mod', 'manual'], level: 2,
    blurb: 'The modulation oscillator in AM at full index: the complex oscillator ring-modulated into a hollow, metallic tone.',
    how: 'In a.m. osc. mode the modulation oscillator multiplies the complex oscillator. At low index it is a tremolo; at 1.0 the fundamental disappears and only the sum and difference frequencies are left, which is ring modulation. With the modulator following the keys, the metallic colour stays the same up the keyboard.',
    phrase: { bpm: 90, loop: true, steps: [[0, 52, 1], [1, 55, 1], [2, 59, 2], [4, 57, 1], [5, 55, 2]] },
    steps: [
      { title: 'A note on Gate 1', module: 'env',
        why: 'The envelope into LEVEL 1, sustained.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- waveshape 2, TIMBRE 1.',
        set: { 'env.trig': 'kbd', 'env.mode': 'sus', 'env.attack': 8.5, 'env.decay': 6, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 2, 'cosc.timbre': 1 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'Slow AM first', module: 'lfo',
        why: 'In a.m. osc. mode with the low range, the modulation oscillator is a tremolo.\n- modulation: a.m. osc., index 4.\n- range low, FREQUENCY 6 (5 Hz), triangle.\n- Listen for: the note pulsing in volume.',
        set: { 'mosc.mode': 'am', 'mosc.index': 4, 'mosc.range': 'low', 'mosc.freq': 6, 'mosc.wave': 'tri' } },
      { title: 'Up to audio rate and full index', module: 'lfo',
        why: 'Switch to the high range, follow the keys, and take the index to 10. The tremolo becomes too fast to hear as a pulse and turns into new frequencies.\n- range high, KEYBOARD on, FREQUENCY 5.2.\n- index 10: full ring modulation.\n- Listen for: a hollow, robotic, bell-like tone with no clear fundamental.',
        set: { 'mosc.range': 'high', 'mosc.kbd': true, 'mosc.freq': 5.2, 'mosc.index': 10, 'out.rev': 3 } },
    ],
    context: {
      'mosc.index': 'In this sound: at 10 only the sidebands are left. Below 5 the original note returns underneath.',
      'mosc.freq': 'In this sound: the ratio that sets the metallic colour.',
      'mosc.wave': 'In this sound: triangle for a smoother ring; square or sawtooth adds many more sidebands.',
    },
    tweaks: [
      { id: 'mosc.wave', try: 'Set the modulation oscillator to square', hear: 'A much harsher, buzzier ring.' },
      { id: 'mosc.kbd', try: 'Switch the modulation oscillator’s KEYBOARD off', hear: 'Each note now has a different, clashing colour.' },
    ],
  },
  {
    id: 'easel-random', name: 'Random Pitch, Timbre and Level', ref: 'From the Easel manual — Patch-chart 16', artist: 'Buchla',
    tags: ['fx', 'random', 'manual'], level: 2,
    blurb: 'The self-running pulser calls up a new random pitch, timbre and loudness on every cycle.',
    how: 'Three of the four white random jacks go to PITCH, TIMBRE and LEVEL 1. The pulser, running on its own, triggers the random source, so every period brings a new combination. The processing sliders decide how wide each random range is. Nothing is played: the Easel improvises.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 4]] },
    steps: [
      { title: 'The pulser triggers the random source', module: 'lfo',
        why: 'Set the pulser to self and the random source’s trigger to pulser.\n- Pulser trigger self, mode trans, PERIOD 6.8.\n- Random trigger source pulser.',
        set: { 'pulser.trig': 'self', 'pulser.mode': 'trans', 'pulser.period': 6.8, 'rvs.trig': 'pulser' } },
      { title: 'Random pitch and timbre', module: 'mod',
        why: 'Random 1 into PITCH and random 2 into TIMBRE. With the KEYBOARD switch off the pitch comes only from the sliders and the random voltage.\n- Cords: random 1 → PITCH, random 2 → TIMBRE.\n- PITCH processing 5 (about 20 semitones of spread), TIMBRE processing 7.\n- KEYBOARD off.',
        set: { 'cosc.kbd': false, 'cosc.pitch': 4, 'cosc.pitchCv': 5, 'cosc.timbreCv': 7, 'cosc.timbre': 0, 'cosc.shape': 0 },
        cables: [['j.rnd1', 'j.pitch'], ['j.rnd2', 'j.timbre']] },
      { title: 'Random loudness', module: 'filter',
        why: 'Random 3 into LEVEL 1, so each new note has its own loudness and brightness; some are almost silent.\n- Cord: random 3 → LEVEL 1, processing 9.\n- Gate 1 combination.\n- REVERBERATION 5.\n- Listen for: an endless, chattering stream of notes, each one different.',
        set: { 'lpg1.levelCv': 9, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'out.rev': 5 }, cables: [['j.rnd3', 'j.lvl1']] },
    ],
    context: {
      'pulser.period': 'In this sound: how often a new note arrives.',
      'cosc.pitchCv': 'In this sound: how wide the random melody ranges. Low values give small, close steps.',
      'cosc.timbreCv': 'In this sound: how much the brightness varies from note to note.',
    },
    tweaks: [
      { id: 'cosc.pitchCv', try: 'Lower PITCH processing to 1', hear: 'A murmur of nearly the same note, varying in tone and loudness.' },
      { id: 'pulser.period', try: 'Push PERIOD up to 8', hear: 'A fast, bubbling stream of random notes.' },
    ],
  },
  {
    id: 'easel-echo', name: 'Gates in Series: Echoes', ref: 'From the Easel manual — Figure 16, simulated echo with changing timbre', artist: 'Buchla',
    tags: ['fx', 'lpg', 'manual'], level: 3,
    blurb: 'Gate 1 shapes each note, and Gate 2, struck over and over by the pulser, chops it into echoes, each with a different tone.',
    how: 'With the gate 2 source switch at series, Gate 1’s output feeds Gate 2, and with channel A down only Gate 2 is heard, so both gates must be open for sound. Gate 1 opens with the envelope on each touch and dies away slowly; the pulser’s falling ramp strikes Gate 2 again and again, turning the long note into repeats. The pulser also steps the sequencer, whose voltage on TIMBRE gives each repeat its own colour.',
    phrase: { bpm: 40, loop: true, steps: [[0, 50, 0.5], [2, 57, 0.5]] },
    steps: [
      { title: 'Gate 1: a long fading note', module: 'env',
        why: 'The envelope into LEVEL 1, transient with a long decay.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- Envelope transient: attack 10, sustain 8, decay 1.5.\n- waveshape 1, TIMBRE 2.',
        set: { 'env.trig': 'kbd', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 8, 'env.decay': 1.5, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 1, 'cosc.timbre': 2 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'Gate 2 after Gate 1, struck by the pulser', module: 'filter',
        why: 'Gate 2 source at series, channel A down and channel B up. The pulser’s ramp into LEVEL 2 strikes Gate 2 on every cycle.\n- gate 2 source: series.\n- channel A 0, channel B 10.\n- Cord: pulser 1 → LEVEL 2, processing 10. Gate 2 combination.\n- Pulser trigger self, mode trans, PERIOD 6.2.\n- Listen for: each note broken into fading repeats.',
        set: { 'lpg.src': 'series', 'out.a': 0, 'out.b': 10, 'lpg2.levelCv': 10, 'lpg2.level': 0, 'lpg2.mode': 'combo', 'pulser.trig': 'self', 'pulser.mode': 'trans', 'pulser.period': 6.2 },
        cables: [['j.pul3', 'j.lvl2']] },
      { title: 'A different tone on each echo', module: 'mod',
        why: 'The pulser steps the sequencer, and a blue sequencer jack goes to TIMBRE, so each repeat has its own brightness.\n- Sequencer trigger source pulser; levels 10, 8, 5, 3, 0.5.\n- Cord: sequencer 2 → TIMBRE, processing 8.\n- REVERBERATION 4.',
        set: { 'seq.trig': 'pulser', 'seq.l1': 10, 'seq.l2': 8, 'seq.l3': 5, 'seq.l4': 3, 'seq.l5': 0.5, 'cosc.timbreCv': 8, 'out.rev': 4 },
        cables: [['j.seq2', 'j.timbre']] },
    ],
    context: {
      'pulser.period': 'In this sound: the time between echoes.',
      'env.decay': 'In this sound: how many echoes you hear before the note has gone.',
      'out.a': 'In this sound: at 0, so only the chopped sound of Gate 2 is heard. Bring it up and the plain note comes back underneath; the gates are out of phase, so they also partly cancel.',
    },
    tweaks: [
      { id: 'out.a', try: 'Bring channel A up to 6', hear: 'The plain note returns under the echoes, thinned where the two gates cancel.' },
      { id: 'pulser.period', try: 'Move PERIOD to 7.5', hear: 'Fast repeats, like a flutter.' },
    ],
  },
  {
    id: 'easel-surf', name: 'Noise Surf', ref: 'Classic technique: the preamp’s noise through Gate 2', artist: 'Classic technique',
    tags: ['fx', 'noise', 'lpg'], level: 1,
    blurb: 'The Easel’s noise source, through Gate 2 as a lowpass filter, opened and closed by a slow modulation oscillator: waves on a beach.',
    how: 'With nothing plugged into the aux jack, the preamp hears the Easel’s own noise. Setting the gate 2 source to the preamp sends that noise to Gate 2. A slow triangle from the modulation oscillator’s green jack sweeps Gate 2’s LEVEL, and in lo pass filter mode that sweeps the brightness of the noise, rising and falling like surf.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 4]] },
    steps: [
      { title: 'Noise into Gate 2', module: 'filter',
        why: 'Gate 2 source to the centre position, the preamp, which hears noise when nothing is plugged into aux in.\n- gate 2 source: preamp.\n- channel A 0, channel B 8.\n- Gate 2 lo pass filter, LEVEL 5.\n- Listen for: a steady, muffled hiss.',
        set: { 'lpg.src': 'ext', 'out.a': 0, 'out.b': 8, 'lpg2.mode': 'lp', 'lpg2.level': 5, 'mosc.mode': 'fm' } },
      { title: 'A slow sweep', module: 'lfo',
        why: 'The green mod out jack carries the modulation oscillator as a voltage. Into LEVEL 2 it sweeps the filter.\n- Cord: mod out → LEVEL 2, processing 6.\n- range low, FREQUENCY 1 (about 0.6 Hz), triangle.\n- Gate 2 LEVEL 3.5.\n- REVERBERATION 5.\n- Listen for: the hiss swelling and falling back every couple of seconds.',
        set: { 'mosc.range': 'low', 'mosc.freq': 1, 'mosc.wave': 'tri', 'lpg2.levelCv': 6, 'lpg2.level': 3.5, 'out.rev': 5 }, cables: [['j.modOut', 'j.lvl2']] },
    ],
    context: {
      'mosc.freq': 'In this sound: how often a wave arrives.',
      'lpg2.level': 'In this sound: the brightness at the bottom of each wave.',
      'preamp.gain': 'In this sound: high makes the noise rougher and louder.',
    },
    tweaks: [
      { id: 'mosc.wave', try: 'Set the modulation oscillator to sawtooth', hear: 'Each wave rises slowly and drops away at once.' },
      { id: 'preamp.gain', try: 'Switch the preamp gain to high', hear: 'Rougher, louder surf.' },
    ],
  },
  {
    id: 'easel-arp-plucks', name: 'Arpeggiated Plucks', ref: 'In the style of Kaitlyn Aurelia Smith', artist: 'Kaitlyn Aurelia Smith',
    tags: ['seq', 'arpeggio', 'lpg'], level: 1,
    blurb: 'Held chords broken into bright, rippling lowpass-gate plucks by the 218e’s arpeggiator.',
    how: 'The 218e’s arpeggiator plays the held keys one after another, and each step is a new touch, so the envelope strikes Gate 1 for every note. A little FM from a slow modulation oscillator keeps the tone moving. Hold a chord and let it run.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 2], [0, 55, 2], [0, 60, 2], [0, 64, 2], [2, 45, 2], [2, 52, 2], [2, 57, 2], [2, 60, 2]] },
    steps: [
      { title: 'A pluck on Gate 1', module: 'env',
        why: 'The envelope into LEVEL 1, transient and short.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- Envelope transient: attack 10, sustain 9, decay 6.\n- waveshape 3 with the triangle, TIMBRE 4.',
        set: { 'env.trig': 'kbd', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 9, 'env.decay': 6, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 3, 'cosc.wave': 'tri', 'cosc.timbre': 4 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'Arpeggiator on', module: 'mode',
        why: 'Set the pattern to ascending and the rate to about eight notes a second.\n- ARPEGGIATION PATTERN: ascending.\n- RATE 6.\n- Listen for: the held chord broken into a rising ripple.',
        set: { 'kbd.arp': 'up', 'kbd.arpRate': 6 } },
      { title: 'A slow wobble and some space', module: 'lfo',
        why: 'A little FM from a slow modulation oscillator, and reverb.\n- modulation f.m. osc., index 1; range low, FREQUENCY 3.\n- REVERBERATION 5.',
        set: { 'mosc.mode': 'fm', 'mosc.index': 1, 'mosc.range': 'low', 'mosc.freq': 3, 'out.rev': 5 } },
    ],
    context: {
      'kbd.arpRate': 'In this sound: the speed of the ripple.',
      'cosc.timbre': 'In this sound: the brightness of each pluck.',
      'kbd.arp': 'In this sound: ascending. Random scatters the same notes.',
    },
    tweaks: [
      { id: 'kbd.arp', try: 'Set the pattern to random', hear: 'The same notes in a scattered, shifting order.' },
      { id: 'env.decay', try: 'Lower the decay slider to 4.5', hear: 'Longer notes that overlap into a shimmer.' },
    ],
  },
  {
    id: 'easel-marimba', name: 'Vactrol Marimba', ref: 'Classic technique: a struck bar from a sine and a lowpass gate', artist: 'Various',
    tags: ['pluck', 'lpg', 'velocity'], level: 1,
    blurb: 'A sine struck through Gate 1, with the 218e’s velocity adding harmonics to the harder notes, like a mallet on a wooden bar.',
    how: 'A short envelope strikes Gate 1 in combination mode, and the vactrol’s slow fall gives each note a woody ring that darkens as it dies. A little TIMBRE folds the sine into a rounder bar tone. The green vel. jack, how hard the last key was struck, goes to TIMBRE, so loud notes are brighter as well as louder, as with a real mallet.',
    phrase: { bpm: 104, loop: true, steps: [[0, 60, 0.5, 1], [0.5, 64, 0.5, 0.55], [1, 67, 0.5, 0.7], [1.5, 72, 0.5, 0.5], [2, 71, 0.5, 0.95], [2.5, 67, 0.5, 0.5], [3, 64, 0.5, 0.7], [3.5, 62, 0.5, 0.45]] },
    steps: [
      { title: 'A sine with a touch of folding', module: 'osc',
        why: 'Turn the waveshape knob fully left for the sine and add a little TIMBRE.\n- waveshape 0.\n- TIMBRE 1.5: the sine starts to fold, which adds a few soft upper harmonics.\n- Listen for: nothing yet; the gate is still shut.',
        set: { 'cosc.shape': 0, 'cosc.timbre': 1.5 } },
      { title: 'Strike the gate', module: 'env',
        why: 'The envelope into LEVEL 1, transient, with a fast attack and a decay of about half a second.\n- Cord: envelope 3 → LEVEL 1, processing 10, LEVEL offset 0.\n- Envelope trigger source keyboard, mode transient; attack 10, sustain 9.5, decay 5.\n- Gate 1 combination.\n- Listen for: a round, wooden note that dulls as it fades.',
        set: { 'env.trig': 'kbd', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 9.5, 'env.decay': 5, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo' },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'Velocity into TIMBRE', module: 'osc',
        why: 'The green vel. jack on the 218e carries how hard the last key was struck. Into the TIMBRE jack it folds the sine further on the harder notes.\n- Cord: vel. → TIMBRE, TIMBRE processing 4.\n- REVERBERATION 2.\n- Listen for: the accented notes of the riff coming out brighter and more knocking than the soft ones.',
        set: { 'cosc.timbreCv': 4, 'out.rev': 2 }, cables: [['j.vel', 'j.timbre']] },
    ],
    context: {
      'cosc.timbre': 'In this sound: the colour of a soft note. Up for a harder, more metallic bar; 0 for a plain sine.',
      'cosc.timbreCv': 'In this sound: how much brighter a hard note is than a soft one. At 0 every note has the same colour.',
      'env.decay': 'In this sound: the length of the ring. Lower on the slider gives a longer bar, like a vibraphone without its motor.',
      'lpg1.mode': 'In this sound: combination, so each note loses its top as it fades.',
    },
    tweaks: [
      { id: 'cosc.timbreCv', try: 'Push TIMBRE processing to 9 and play some notes hard and some soft', hear: 'Hard notes turn into a clanging metal bar; soft ones stay wooden.' },
      { id: 'env.decay', try: 'Lower the decay slider to 3.5', hear: 'Each bar rings for a couple of seconds and the notes overlap.' },
    ],
  },
  {
    id: 'easel-gong', name: 'Blooming Gong', ref: 'Classic technique: FM with an inverted envelope on the index', artist: 'Various',
    tags: ['perc', 'fm', 'inverter'], level: 3,
    blurb: 'A low FM strike whose clangy overtones grow as the note fades instead of dying first, the way a large gong blooms after it is hit.',
    how: 'The modulation oscillator, at audio rate but not following the keys, frequency-modulates the complex oscillator, so each note gets its own set of inharmonic partials. The envelope strikes Gate 1, and a copy of it goes through the INVERTER into the modulation input: while the envelope is high the index is low, and as it falls the index rises. So the note starts fairly plain and turns more metallic as it rings out. The inverter is what makes this possible on the Easel without a second envelope.',
    phrase: { bpm: 60, loop: true, steps: [[0, 36, 1, 1], [4, 43, 1, 0.8]] },
    steps: [
      { title: 'A long, low strike', module: 'env',
        why: 'A sine through Gate 1, struck by a transient envelope with a decay of several seconds.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- waveshape 0, TIMBRE 1.\n- Envelope transient: attack 10, sustain 8, decay 0.8.\n- Gate 1 combination.\n- Listen for: a deep, plain note that rings for a long time.',
        set: { 'cosc.shape': 0, 'cosc.timbre': 1, 'env.trig': 'kbd', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 8, 'env.decay': 0.8, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo' },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'A fixed audio-rate modulator', module: 'lfo',
        why: 'Switch the modulation oscillator to its high range with its KEYBOARD switch off, so it stays on one frequency while the keys move the complex oscillator. The ratio between them then changes from key to key, which gives every note different, inharmonic partials.\n- range high, KEYBOARD off, waveshape triangle.\n- FREQUENCY 3.3.\n- modulation: f.m. osc., index 1.5.\n- Listen for: a slightly rough, clangy edge on the note.',
        set: { 'mosc.range': 'high', 'mosc.kbd': false, 'mosc.wave': 'tri', 'mosc.freq': 3.3, 'mosc.mode': 'fm', 'mosc.index': 1.5 } },
      { title: 'The envelope, turned upside down, on the index', module: 'util',
        why: 'Patch a second orange jack into the INVERTER’s input and its blue output into the black modulation jack. The inverter gives 10 minus the envelope, so the modulation is lightest at the strike and deepest as the note dies.\n- Cords: envelope 1 → INVERTER input; INVERTER output → modulation input.\n- modulation processing 5.\n- REVERBERATION 5.\n- Listen for: the overtones swelling and churning a second or two after each strike.',
        set: { 'mosc.indexCv': 5, 'out.rev': 5 }, cables: [['j.env1', 'j.invIn'], ['j.invOut', 'j.index']] },
    ],
    context: {
      'mosc.indexCv': 'In this sound: how far the gong blooms. At 0 the note stays as plain as at the strike; at 10 it ends in a roar of partials.',
      'mosc.index': 'In this sound: the clang at the moment of the strike, before the inverted envelope adds to it.',
      'mosc.freq': 'In this sound: the modulator’s fixed frequency. Small moves change the whole set of partials.',
      'mosc.kbd': 'In this sound: off, so each key gives a different ratio and a different gong.',
      'env.decay': 'In this sound: how long the gong rings, and so how long the bloom takes.',
    },
    tweaks: [
      { id: 'mosc.indexCv', try: 'Push modulation processing to 9', hear: 'A much wilder tail: the note breaks up into noise-like clang as it fades.' },
      { id: 'mosc.kbd', try: 'Switch the modulation oscillator’s KEYBOARD on', hear: 'Every note now has the same colour: more of a tuned bell than a gong.' },
    ],
  },
  {
    id: 'easel-folded-glide', name: 'Folded Glide Lead', ref: 'Classic technique: a wavefolded triangle with a new colour on every touch', artist: 'Various',
    tags: ['lead', 'timbre', 'random', 'portamento'], level: 2,
    blurb: 'A folded triangle lead that glides between notes, with the random source picking a new brightness each time you touch a key.',
    how: 'The waveshape knob turned fully right takes the triangle, which TIMBRE folds back on itself into a reedy, buzzing tone. A white random jack goes to TIMBRE, and the random source is triggered from the keyboard, so every note gets a different amount of folding: some soft, some snarling. PORTAMENTO SLOPE on the 218e makes the pitch slide from note to note, and a slow modulation oscillator adds a light vibrato.',
    phrase: { bpm: 84, loop: true, steps: [[0, 55, 1.5], [1.5, 58, 0.5], [2, 62, 2], [4, 60, 1], [5, 58, 1], [6, 55, 2]] },
    steps: [
      { title: 'A sustained triangle on Gate 1', module: 'env',
        why: 'The envelope into LEVEL 1, sustained, so the note holds while the key is held.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- Envelope sustained: attack 8.5, decay 6.\n- waveshape 10 with the switch on triangle, TIMBRE 3.\n- Gate 1 combination.\n- Listen for: a hollow, slightly reedy tone.',
        set: { 'env.trig': 'kbd', 'env.mode': 'sus', 'env.attack': 8.5, 'env.decay': 6, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 10, 'cosc.wave': 'tri', 'cosc.timbre': 3 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'A random brightness on each touch', module: 'mod',
        why: 'Random 2 into TIMBRE, with the random source triggered by the keyboard.\n- Cord: random 2 → TIMBRE, TIMBRE processing 6.\n- Random trigger source keyboard.\n- Listen for: each note of the riff with its own colour, from soft to buzzing.',
        set: { 'rvs.trig': 'kbd', 'cosc.timbreCv': 6 }, cables: [['j.rnd2', 'j.timbre']] },
      { title: 'Glide and vibrato', module: 'glide',
        why: 'Turn up PORTAMENTO SLOPE so the pitch slides between notes, and give the modulation oscillator a slow, shallow FM.\n- PORTAMENTO SLOPE 6.\n- modulation f.m. osc., index 1; range low, FREQUENCY 6 (about 5 Hz), triangle.\n- REVERBERATION 3.\n- Listen for: notes that bend into each other, with a gentle waver.',
        set: { 'kbd.porta': 6, 'mosc.mode': 'fm', 'mosc.index': 1, 'mosc.range': 'low', 'mosc.freq': 6, 'mosc.wave': 'tri', 'out.rev': 3 } },
    ],
    context: {
      'cosc.timbre': 'In this sound: the least folding any note gets. Raise it for a harder lead overall.',
      'cosc.timbreCv': 'In this sound: how far apart the random colours are. At 2 the notes differ only a little; at 10 some are pure and some are harsh.',
      'kbd.porta': 'In this sound: how long the slide between notes takes. 0 for clean jumps.',
      'mosc.index': 'In this sound: the depth of the vibrato. At 2 it becomes a wide wobble.',
    },
    tweaks: [
      { id: 'cosc.timbreCv', try: 'Push TIMBRE processing to 10', hear: 'Some notes nearly pure, others growling: the riff turns unpredictable.' },
      { id: 'rvs.trig', try: 'Set the random trigger source to pulser, with the pulser on self', hear: 'The colour now changes in the middle of held notes, on the pulser’s clock.' },
    ],
  },
  {
    id: 'easel-chance-melody', name: 'Sequence with Chance', ref: 'In the style of Charles Cohen’s Music Easel improvisations', artist: 'Charles Cohen',
    tags: ['seq', 'sequencer', 'random', 'west coast'], level: 3,
    blurb: 'The pulser runs the sequencer, the sequencer plays the tune through the keyboard pitch input, and the random source colours every note differently.',
    how: 'The pulser, set to self, clocks the sequencer. A blue sequencer jack goes into the black keyboard pitch input, which the complex oscillator follows in semitones exactly as it follows the keys: a full voltage is 28 semitones, so each level slider is a note. The sequencer also triggers the random source, whose voltages go to TIMBRE and to the modulation input, so the same five notes come round with a different brightness and clang each time. A stage switched off leaves a rest.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 8]] },
    steps: [
      { title: 'A pluck fired by the sequencer', module: 'env',
        why: 'The envelope into LEVEL 1, transient and short, fired by the sequencer’s pulses.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- Envelope trigger source sequencer, transient: attack 10, sustain 9, decay 6.\n- waveshape 2, TIMBRE 1. Gate 1 combination.',
        set: { 'env.trig': 'seq', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 9, 'env.decay': 6, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 2, 'cosc.timbre': 1 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'The pulser clocks the sequencer', module: 'lfo',
        why: 'Pulser on self, sequencer stepped by the pulser.\n- Pulser trigger self, mode trans, PERIOD 6.3.\n- Sequencer trigger source pulser, STAGES 5.\n- Listen for: a steady run of plucks on one note.',
        set: { 'pulser.trig': 'self', 'pulser.mode': 'trans', 'pulser.period': 6.3, 'seq.trig': 'pulser', 'seq.stages': 5 } },
      { title: 'The sequence plays the keyboard input', module: 'mod',
        why: 'Patch a blue sequencer jack into the black pitch jack under KEYBOARD INPUTS. It replaces the 218e’s key voltage, so the complex oscillator, whose KEYBOARD switch is on, plays the sequencer in semitones. One step of the level slider is 2.8 semitones.\n- Cord: sequencer 1 → keyboard input pitch.\n- Levels 0, 2.5, 4.29, 3.57, 6.79: root, fifth, octave, seventh and twelfth.\n- PULSE SEQUENCE 3 down: a rest on stage 3.\n- Listen for: a five-step figure with a gap in it.',
        set: { 'cosc.kbd': true, 'seq.l1': 0, 'seq.l2': 2.5, 'seq.l3': 4.29, 'seq.l4': 3.57, 'seq.l5': 6.79, 'seq.p3': false },
        cables: [['j.seq1', 'j.kPitch']] },
      { title: 'Chance on timbre and clang', module: 'mod',
        why: 'Set the random source to fire on the sequencer’s pulses. Random 1 goes to TIMBRE and random 2 to the modulation input, with the modulation oscillator at audio rate following the keys.\n- Random trigger source sequencer.\n- Cords: random 1 → TIMBRE, processing 7; random 2 → modulation input, processing 4.\n- modulation f.m. osc., range high, KEYBOARD on, FREQUENCY 4.7, index 0.\n- REVERBERATION 4.\n- Listen for: the same tune, but every note a little different, some soft, some bright, some bell-like.',
        set: { 'rvs.trig': 'seq', 'cosc.timbreCv': 7, 'mosc.indexCv': 4, 'mosc.mode': 'fm', 'mosc.range': 'high', 'mosc.kbd': true, 'mosc.freq': 4.7, 'mosc.index': 0, 'out.rev': 4 },
        cables: [['j.rnd1', 'j.timbre'], ['j.rnd2', 'j.index']] },
    ],
    context: {
      'pulser.period': 'In this sound: the tempo. Up the slider is faster.',
      'seq.l5': 'In this sound: the highest note. Each step of the slider is 2.8 semitones, so small moves make big intervals.',
      'seq.p3': 'In this sound: down, so stage 3 is a rest. Its level still sets a pitch, but nothing strikes the gate.',
      'cosc.timbreCv': 'In this sound: how much the random brightness varies.',
      'mosc.indexCv': 'In this sound: how clangy the most metallic notes get. At 0 every note is clean.',
      'rvs.trig': 'In this sound: sequencer, so the random values change only on notes that play.',
    },
    tweaks: [
      { id: 'seq.stages', try: 'Set STAGES to 4', hear: 'A four-step loop that drops the twelfth; with the rest it now sounds like three notes and a gap.' },
      { id: 'mosc.indexCv', try: 'Push modulation processing to 9', hear: 'Some notes turn into ringing bells, others stay plain.' },
      { id: 'cosc.kbd', try: 'Switch the complex oscillator’s KEYBOARD off', hear: 'The tune stops: the oscillator no longer follows the keyboard input, so only the colours change.' },
    ],
  },
  {
    id: 'easel-breathing-drone', name: 'Breathing Drone', ref: 'Classic technique: a self-cycling envelope and the inverter on two gates', artist: 'Various',
    tags: ['drone', 'envelope', 'inverter', 'lpg'], level: 2,
    blurb: 'The envelope in self mode swells and fades the complex oscillator by itself, while the inverter brings the modulation oscillator up a fifth in the gaps.',
    how: 'In self mode the envelope starts again each time it finishes, so it cycles without anyone touching a key. It opens Gate 1 and adds TIMBRE, so each swell grows brighter as it gets louder. A copy of the envelope goes through the INVERTER to Gate 2, which carries the modulation oscillator tuned a fifth above: as one voice breathes in, the other breathes out. Hold one key to choose the note.',
    phrase: { bpm: 60, loop: true, steps: [[0, 43, 16]] },
    steps: [
      { title: 'An envelope that repeats itself', module: 'env',
        why: 'Set the envelope to self, with slow attack and decay, and patch it into LEVEL 1.\n- Envelope mode self; attack 3, sustain 4, decay 3 (about two seconds up, one held, two down).\n- Cord: envelope 3 → LEVEL 1, processing 8, LEVEL 1 offset 1.\n- waveshape 1, TIMBRE 1. Gate 1 combination.\n- Listen for: a note that swells and fades every five seconds or so, never quite silent.',
        set: { 'env.trig': 'kbd', 'env.mode': 'self', 'env.attack': 3, 'env.sustain': 4, 'env.decay': 3, 'lpg1.levelCv': 8, 'lpg1.level': 1, 'lpg1.mode': 'combo', 'cosc.shape': 1, 'cosc.timbre': 1 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'Brighter as it swells', module: 'osc',
        why: 'A second orange jack into TIMBRE, so the folding follows the envelope too.\n- Cord: envelope 2 → TIMBRE, processing 5.\n- Listen for: the tone opening up at the top of each breath.',
        set: { 'cosc.timbreCv': 5 }, cables: [['j.env2', 'j.timbre']] },
      { title: 'A second voice, the other way round', module: 'util',
        why: 'Tune the modulation oscillator a fifth above the complex oscillator, following the keys, and send it through Gate 2. The inverted envelope opens Gate 2, so it is loudest while Gate 1 is quietest.\n- range high, KEYBOARD on, FREQUENCY 3.95, triangle; modulation f.m. osc. with index 0, so it does not touch the complex oscillator.\n- gate 2 source mod osc; channel B 6.\n- Cords: envelope 1 → INVERTER input; INVERTER output → LEVEL 2, processing 6. Gate 2 combination.\n- REVERBERATION 5.\n- Listen for: two notes trading places, the fifth rising as the root falls away.',
        set: { 'mosc.range': 'high', 'mosc.kbd': true, 'mosc.freq': 3.95, 'mosc.wave': 'tri', 'mosc.mode': 'fm', 'mosc.index': 0, 'lpg.src': 'mosc', 'out.b': 6, 'lpg2.levelCv': 6, 'lpg2.level': 0, 'lpg2.mode': 'combo', 'out.rev': 5 },
        cables: [['j.env1', 'j.invIn'], ['j.invOut', 'j.lvl2']] },
    ],
    context: {
      'env.mode': 'In this sound: self, which makes the envelope repeat with no keys touched. Sustained would give one swell per touch.',
      'env.attack': 'In this sound: how long the breath in takes. Lower on the slider is slower.',
      'env.decay': 'In this sound: how long the breath out takes.',
      'lpg1.level': 'In this sound: at 1, so the root never quite disappears between swells.',
      'mosc.freq': 'In this sound: the second voice’s interval. 3.95 is a fifth above; 4.7 is about an octave.',
      'lpg2.levelCv': 'In this sound: how loud the second voice gets in the gaps.',
    },
    tweaks: [
      { id: 'env.sustain', try: 'Push the sustain slider up to 8', hear: 'No pause at the top: a continuous rise and fall.' },
      { id: 'mosc.freq', try: 'Move FREQUENCY to 4.7', hear: 'The second voice an octave up instead of a fifth: plainer, more like an organ.' },
    ],
  },
  {
    id: 'easel-pressure-voice', name: 'Pressure Voice', ref: 'Classic technique: the 218e’s pressure on loudness and timbre', artist: 'Various',
    tags: ['lead', 'pressure', 'expressive'], level: 2,
    blurb: 'No envelope at all: keyboard pressure opens Gate 1 and folds the tone, so every note is as loud and as bright as you play it.',
    how: 'The 218e gives a pressure voltage on the violet jacks. Here one goes to LEVEL 1 and another to TIMBRE, so the gate opens and the tone brightens together with the pressure. In this app pressure comes from how hard you strike a key and holds while the key is down, so play some notes hard and some soft: on the hardware you would press harder or lighter into the touch plate as the note sounds. When you let go, the gate closes on its own slow fall.',
    phrase: { bpm: 76, loop: true, steps: [[0, 57, 1.5, 0.45], [1.5, 60, 0.5, 0.7], [2, 64, 2, 1], [4, 62, 1, 0.6], [5, 60, 1, 0.4], [6, 57, 2, 0.85]] },
    steps: [
      { title: 'Pressure opens the gate', module: 'filter',
        why: 'Patch a violet pressure jack into LEVEL 1. With no envelope, the gate is only as open as the key is pressed.\n- Cord: pressure 1 → LEVEL 1, processing 10, LEVEL offset 0.\n- Gate 1 combination.\n- waveshape 3, square; TIMBRE 1.\n- Listen for: soft notes that are quiet and dark, hard ones loud and open.',
        set: { 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 3, 'cosc.wave': 'sq', 'cosc.timbre': 1 },
        cables: [['j.prs1', 'j.lvl1']] },
      { title: 'Pressure on TIMBRE as well', module: 'osc',
        why: 'A second violet jack into TIMBRE, so pressing harder also folds the sine.\n- Cord: pressure 3 → TIMBRE, processing 6.\n- Listen for: the hard notes gaining a buzzing edge, not just volume.',
        set: { 'cosc.timbreCv': 6 }, cables: [['j.prs3', 'j.timbre']] },
      { title: 'A little vibrato and glide', module: 'lfo',
        why: 'A slow, shallow FM from the modulation oscillator and a short portamento make it sing.\n- modulation f.m. osc., index 1; range low, FREQUENCY 5.5, triangle.\n- PORTAMENTO SLOPE 4.\n- REVERBERATION 3.',
        set: { 'mosc.mode': 'fm', 'mosc.index': 1, 'mosc.range': 'low', 'mosc.freq': 5.5, 'mosc.wave': 'tri', 'kbd.porta': 4, 'out.rev': 3 } },
    ],
    context: {
      'lpg1.levelCv': 'In this sound: how far the hardest touch opens the gate. Lower it and even hard notes stay muted.',
      'cosc.timbreCv': 'In this sound: how much brighter a hard note gets. At 0 pressure changes only loudness and the gate’s filter.',
      'lpg1.mode': 'In this sound: combination, so pressure brings both volume and brightness. Voltage cntrld amp leaves only the volume.',
      'mosc.index': 'In this sound: the vibrato depth.',
    },
    tweaks: [
      { id: 'lpg1.mode', try: 'Set Gate 1 to lo pass filter', hear: 'Soft notes are still there but muffled, like a hand over a horn.' },
      { id: 'cosc.timbreCv', try: 'Push TIMBRE processing to 10 and play hard', hear: 'Hard notes snarl; soft ones stay close to a sine.' },
    ],
  },
  {
    id: 'easel-tremolo-ring', name: 'Tremolo into Ring', ref: 'Classic technique: a keyboard-tracking AM oscillator crossing into audio rate', artist: 'Various',
    tags: ['fx', 'am', 'ring mod', 'portamento'], level: 2,
    blurb: 'Low notes pulse with a tremolo; as the line glides up the keyboard the tremolo speeds up until it turns into a growling ring modulation.',
    how: 'The modulation oscillator is in its low range, in a.m. osc. mode, with its KEYBOARD switch on. It follows the keys in semitones just as the complex oscillator does, so every octave up doubles its rate. At the bottom of the keyboard that is a slow tremolo; three octaves up it is fast enough to be heard as new frequencies, which is ring modulation. Portamento lets you hear the change happen in one slide.',
    phrase: { bpm: 60, loop: true, steps: [[0, 36, 1.8], [2, 60, 1.8], [4, 84, 3.8]] },
    steps: [
      { title: 'A held note on Gate 1', module: 'env',
        why: 'The envelope into LEVEL 1, sustained.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- Envelope sustained: attack 8.5, decay 6.\n- waveshape 3 with the triangle, TIMBRE 2.\n- Gate 1 combination.',
        set: { 'env.trig': 'kbd', 'env.mode': 'sus', 'env.attack': 8.5, 'env.decay': 6, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 3, 'cosc.wave': 'tri', 'cosc.timbre': 2 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'A tremolo that follows the keys', module: 'lfo',
        why: 'a.m. osc. mode, low range, KEYBOARD on. At the lowest notes the modulation oscillator runs at a few hertz.\n- modulation: a.m. osc., index 7.\n- range low, FREQUENCY 6.3 (about 6 Hz at the lowest key of the 218e), triangle.\n- KEYBOARD on.\n- Listen for: low notes pulsing; higher notes pulsing faster, then buzzing.',
        set: { 'mosc.mode': 'am', 'mosc.index': 7, 'mosc.range': 'low', 'mosc.freq': 6.3, 'mosc.wave': 'tri', 'mosc.kbd': true } },
      { title: 'Glide through the change', module: 'glide',
        why: 'A long portamento makes each jump a slide, so you hear the tremolo speed up continuously until it becomes a tone of its own.\n- PORTAMENTO SLOPE 9.\n- REVERBERATION 3.\n- Listen for: a pulse that blurs into a rough, metallic hum as the pitch rises.',
        set: { 'kbd.porta': 9, 'out.rev': 3 } },
    ],
    context: {
      'mosc.kbd': 'In this sound: on, so the AM rate rises with the notes. Off, every note has the same slow tremolo.',
      'mosc.freq': 'In this sound: the tremolo speed at the bottom of the keyboard. Higher on the slider moves the change to ring modulation further down.',
      'mosc.index': 'In this sound: the depth. At 10 the plain note disappears once the AM is fast; at 4 it stays underneath.',
      'kbd.porta': 'In this sound: how slowly the line slides, and so how slowly the tremolo changes.',
    },
    tweaks: [
      { id: 'mosc.wave', try: 'Set the modulation oscillator to square', hear: 'The low notes chop on and off; the high ones become a harsh, buzzing ring.' },
      { id: 'mosc.freq', try: 'Move FREQUENCY to 9', hear: 'Even the lowest notes are past tremolo: the whole range growls.' },
    ],
  },
  {
    id: 'easel-preset-arp', name: 'Random Arpeggio and Presets', ref: 'Classic technique: the 218e arpeggiator with preset voltages on timbre', artist: 'Various',
    tags: ['seq', 'arpeggio', 'preset', 'fm'], level: 2,
    blurb: 'Held notes picked out at random by the arpeggiator, as FM plucks whose brightness you switch by touching the four preset plates.',
    how: 'With the ARPEGGIATION PATTERN at random, the 218e plays one of the held keys at a time in no fixed order, and each step is a new touch, so the envelope strikes for every note. The envelope also drives the FM index, so each note has a short clangy start. The PRESET VOLTAGE SOURCE output goes to TIMBRE: each of the four plates has its own knob, so a touch on a plate changes the brightness of the whole pattern at once.',
    phrase: { bpm: 60, loop: true, steps: [[0, 50, 4], [0, 57, 4], [0, 62, 4], [0, 65, 4], [4, 48, 4], [4, 55, 4], [4, 60, 4], [4, 64, 4]] },
    steps: [
      { title: 'A pluck with an FM strike', module: 'env',
        why: 'The envelope into LEVEL 1 and into the modulation input, with the modulation oscillator an octave above the complex oscillator and following the keys.\n- Cords: envelope 3 → LEVEL 1, processing 10; envelope 1 → modulation input, processing 4.\n- Envelope transient: attack 10, sustain 9, decay 6.5.\n- range high, KEYBOARD on, FREQUENCY 4.7, triangle; modulation f.m. osc., index 0.\n- waveshape 0, TIMBRE 1. Gate 1 combination.',
        set: { 'env.trig': 'kbd', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 9, 'env.decay': 6.5, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'mosc.range': 'high', 'mosc.kbd': true, 'mosc.freq': 4.7, 'mosc.wave': 'tri', 'mosc.mode': 'fm', 'mosc.index': 0, 'mosc.indexCv': 4, 'cosc.shape': 0, 'cosc.timbre': 1 },
        cables: [['j.env3', 'j.lvl1'], ['j.env1', 'j.index']] },
      { title: 'Random arpeggio', module: 'mode',
        why: 'Set the pattern to random and the rate to about seven notes a second.\n- ARPEGGIATION PATTERN: random.\n- RATE 7.\n- Listen for: the held chord scattered into a restless, never-repeating line.',
        set: { 'kbd.arp': 'random', 'kbd.arpRate': 7 } },
      { title: 'Preset plates on TIMBRE', module: 'mode',
        why: 'Patch the blue PRESET VOLTAGE SOURCE output into TIMBRE. The four knobs are already at 0, 3, 6 and 9; touch plate 3 to start.\n- Cord: preset output → TIMBRE, processing 8.\n- Preset plates: 3.\n- REVERBERATION 4.\n- Listen for: a brighter, folded pluck. Touch plate 1 for plain sines and plate 4 for a hard buzz.',
        set: { 'cosc.timbreCv': 8, 'kbd.plate': 3, 'out.rev': 4 }, cables: [['j.presetOut', 'j.timbre']] },
    ],
    context: {
      'kbd.plate': 'In this sound: which preset knob is feeding TIMBRE. Plate 1 is the darkest, plate 4 the brightest.',
      'kbd.p3': 'In this sound: the brightness of plate 3. Set the four knobs to any four colours you want to switch between.',
      'kbd.arpRate': 'In this sound: how fast the notes come.',
      'mosc.indexCv': 'In this sound: the clang at the start of each note.',
    },
    tweaks: [
      { id: 'kbd.plate', try: 'Touch plate 1, then plate 4, while the chord is held', hear: 'The same pattern switches from soft sines to a hard, buzzing pluck at a touch.' },
      { id: 'kbd.add', try: 'Set ADD TO PITCH to octaves and touch the plates', hear: 'Each plate now also shifts the arpeggio up by octaves.' },
    ],
  },
  {
    id: 'easel-kit', name: 'One-Patch Drum Kit', ref: 'Classic technique: drums and a shaker from one self-running patch', artist: 'Various',
    tags: ['perc', 'sequencer', 'noise', 'lpg'], level: 3,
    blurb: 'Gate 1 plays kick and toms from the sequencer, Gate 2 shakes noise on every pulse, all clocked by the pulser.',
    how: 'The pulser is the clock. Its falling ramp, from the yellow jack, strikes Gate 2, which carries the preamp’s noise, so every pulse is a short shaker hit. The pulser also steps the sequencer, whose voltage goes into the keyboard pitch input to give each drum stage its own pitch and into TIMBRE to give it its own colour. The sequencer’s pulses fire the envelope, which strikes Gate 1, and a PULSE SEQUENCE switch turned down leaves a stage for the shaker alone.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 8]] },
    steps: [
      { title: 'Clock and sequencer', module: 'lfo',
        why: 'Pulser on self, sequencer on the pulser, four stages.\n- Pulser trigger self, mode trans, PERIOD 6.3.\n- Sequencer trigger source pulser, STAGES 4.\n- Envelope trigger source sequencer.',
        set: { 'pulser.trig': 'self', 'pulser.mode': 'trans', 'pulser.period': 6.3, 'seq.trig': 'pulser', 'seq.stages': 4, 'env.trig': 'seq' } },
      { title: 'Kick and toms on Gate 1', module: 'filter',
        why: 'A low sine struck hard by a short envelope. A blue sequencer jack into the keyboard pitch input tunes each stage.\n- PITCH 1 (about 54 Hz), waveshape 0, TIMBRE 1.\n- Cord: envelope 3 → LEVEL 1, processing 10. Gate 1 combination.\n- Envelope transient: attack 10, sustain 9.5, decay 7.\n- Cord: sequencer 1 → keyboard input pitch.\n- Levels 0, 0, 5, 3.6: kick, (rest), high tom, low tom. PULSE SEQUENCE 2 down.\n- Listen for: a short four-step drum pattern.',
        set: { 'cosc.pitch': 1, 'cosc.kbd': true, 'cosc.shape': 0, 'cosc.timbre': 1, 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 9.5, 'env.decay': 7, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'seq.l1': 0, 'seq.l2': 0, 'seq.l3': 5, 'seq.l4': 3.6, 'seq.p2': false },
        cables: [['j.env3', 'j.lvl1'], ['j.seq1', 'j.kPitch']] },
      { title: 'Colour per stage', module: 'osc',
        why: 'The second blue jack into TIMBRE, so the toms are knockier than the kick.\n- Cord: sequencer 2 → TIMBRE, processing 6.',
        set: { 'cosc.timbreCv': 6 }, cables: [['j.seq2', 'j.timbre']] },
      { title: 'A shaker on Gate 2', module: 'filter',
        why: 'Gate 2 takes the preamp, which hears the Easel’s noise with nothing in aux in. The pulser’s ramp jumps up at each pulse and falls away, so patched into LEVEL 2 it strikes the noise on every step.\n- gate 2 source preamp; Gate 2 voltage cntrld amp.\n- Cord: pulser 3 → LEVEL 2, processing 5. channel B 4.\n- REVERBERATION 2.\n- Listen for: a hiss on every step, under the drums.',
        set: { 'lpg.src': 'ext', 'lpg2.mode': 'vca', 'lpg2.levelCv': 5, 'lpg2.level': 0, 'out.b': 4, 'out.rev': 2 }, cables: [['j.pul3', 'j.lvl2']] },
    ],
    context: {
      'pulser.period': 'In this sound: the tempo of the whole kit.',
      'seq.l3': 'In this sound: the high tom’s pitch. Each step of the slider is 2.8 semitones.',
      'seq.p2': 'In this sound: down, so stage 2 is the shaker alone. Put it up for a second kick.',
      'lpg2.levelCv': 'In this sound: how loud the shaker is.',
      'env.decay': 'In this sound: the length of the drums. Lower on the slider gives booming toms.',
      'cosc.pitch': 'In this sound: the kick’s pitch; the sequencer adds to it for the toms.',
    },
    tweaks: [
      { id: 'seq.stages', try: 'Set STAGES to 3', hear: 'A three-step pattern against the steady shaker: the toms fall in a different place each bar.' },
      { id: 'lpg2.mode', try: 'Set Gate 2 to combination', hear: 'The shaker turns into a soft, dark brush.' },
    ],
  },
  {
    id: 'easel-seven-eight', name: 'Seven from Three Stages', ref: 'Classic technique: the sequencer setting the pulser’s period', artist: 'Various',
    tags: ['seq', 'rhythm', 'sequencer', 'inverter'], level: 3,
    blurb: 'A three-stage sequence sets the length of each beat, long-short-short, for a limping seven-eighths pulse that you play notes over.',
    how: 'A blue sequencer jack goes to the pulser’s PERIOD input, so the stage the sequencer is on sets how long the next beat lasts. With three stages, a low first level gives one long beat and two higher levels two short ones, in the ratio three to two: 3 + 2 + 2, seven eighths. The other blue jack goes through the INVERTER to TIMBRE, so the long beat, the lowest voltage, is the brightest: the accent falls on the one. The keys still choose the note.',
    phrase: { bpm: 60, loop: true, steps: [[0, 45, 3.9], [4, 50, 3.9]] },
    steps: [
      { title: 'A pluck fired by the sequencer', module: 'env',
        why: 'The envelope into LEVEL 1, transient and short, fired by the sequencer.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- Envelope trigger source sequencer; transient: attack 10, sustain 9, decay 6.\n- waveshape 2, TIMBRE 1. Gate 1 combination.',
        set: { 'env.trig': 'seq', 'env.mode': 'trans', 'env.attack': 10, 'env.sustain': 9, 'env.decay': 6, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 2, 'cosc.timbre': 1 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'Three stages, steady at first', module: 'lfo',
        why: 'Pulser on self stepping a three-stage sequence.\n- Pulser trigger self, mode trans, PERIOD 5.\n- Sequencer trigger source pulser, STAGES 3.\n- Levels 0, 5, 5, 5, 0.\n- Listen for: a slow, even pulse; nothing tells the stages apart yet.',
        set: { 'pulser.trig': 'self', 'pulser.mode': 'trans', 'pulser.period': 5, 'seq.trig': 'pulser', 'seq.stages': 3, 'seq.l1': 0, 'seq.l2': 5, 'seq.l3': 5, 'seq.l4': 5, 'seq.l5': 0 } },
      { title: 'The sequence sets the beat lengths', module: 'lfo',
        why: 'Patch sequencer 1 into the black PERIOD jack. At PERIOD processing 1, a stage at 5 shortens its beat by half a slider division: two thirds of the long beat.\n- Cord: sequencer 1 → PERIOD, PERIOD processing 1.\n- Listen for: long, short, short: one-two-three, one-two, one-two.',
        set: { 'pulser.periodCv': 1 }, cables: [['j.seq1', 'j.period']] },
      { title: 'An accent on the long beat', module: 'util',
        why: 'Sequencer 2 into the INVERTER and the inverter into TIMBRE. Stage 1 is at 0, so the inverter gives 10 there and about 5 on the short beats.\n- Cords: sequencer 2 → INVERTER input; INVERTER output → TIMBRE, processing 6.\n- REVERBERATION 3.\n- Listen for: a bright, buzzy note on the one and softer notes after it.',
        set: { 'cosc.timbreCv': 6, 'out.rev': 3 }, cables: [['j.seq2', 'j.invIn'], ['j.invOut', 'j.timbre']] },
    ],
    context: {
      'seq.stages': 'In this sound: the length of the bar. 4 gives 3 + 2 + 2 + 2, nine eighths; 5 adds a second long beat for twelve.',
      'seq.l1': 'In this sound: at 0, the long beat. Raise it to 5 and the bar evens out.',
      'pulser.periodCv': 'In this sound: how much shorter the high stages make their beats. At 2 the short beats are about half the long one.',
      'pulser.period': 'In this sound: the tempo; the long beat is this period.',
      'cosc.timbreCv': 'In this sound: how strong the accent on the one is.',
    },
    tweaks: [
      { id: 'seq.stages', try: 'Set STAGES to 5', hear: 'Long-short-short-short-long: three, two, two, two, three, a bar of twelve eighths grouped unevenly.' },
      { id: 'pulser.periodCv', try: 'Raise PERIOD processing to 2', hear: 'The short beats are now half the long one: a skipping, swung feel instead of seven.' },
    ],
  },
  {
    id: 'easel-spring-pad', name: 'Two Voices in the Spring', ref: 'In the style of Kaitlyn Aurelia Smith’s slower Easel pieces', artist: 'Kaitlyn Aurelia Smith',
    tags: ['pad', 'reverb', 'portamento', 'lpg'], level: 2,
    blurb: 'Both oscillators, a fifth apart, swell slowly through both gates and slide between notes into a full spring reverberation.',
    how: 'The complex oscillator plays through Gate 1 and the modulation oscillator, tuned a fifth above and following the keys, through Gate 2. One slow envelope opens both gates, so the two voices swell together. A long PORTAMENTO SLOPE makes each new note slide, and REVERBERATION turned right up smears the slides together. The Easel is monophonic, so the pad is made from one note and its fifth, not chords.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 3.8], [4, 53, 3.8], [8, 51, 3.8], [12, 46, 3.8]] },
    steps: [
      { title: 'A slow swell on Gate 1', module: 'env',
        why: 'The envelope into LEVEL 1, sustained, with slow attack and decay.\n- Cord: envelope 3 → LEVEL 1, processing 10.\n- Envelope sustained: attack 4.5, decay 3.\n- waveshape 4 with the triangle, TIMBRE 2.\n- Gate 1 combination.\n- Listen for: notes fading in over most of a second and out over two.',
        set: { 'env.trig': 'kbd', 'env.mode': 'sus', 'env.attack': 4.5, 'env.decay': 3, 'lpg1.levelCv': 10, 'lpg1.level': 0, 'lpg1.mode': 'combo', 'cosc.shape': 4, 'cosc.wave': 'tri', 'cosc.timbre': 2 },
        cables: [['j.env3', 'j.lvl1']] },
      { title: 'The fifth through Gate 2', module: 'filter',
        why: 'Tune the modulation oscillator a fifth up, following the keys, and send it through Gate 2 with the same envelope.\n- range high, KEYBOARD on, FREQUENCY 3.95, triangle; modulation f.m. osc., index 0.\n- gate 2 source mod osc; Gate 2 lo pass filter; channel B 6.\n- Cord: envelope 2 → LEVEL 2, processing 7.\n- Listen for: an open fifth on every key.',
        set: { 'mosc.range': 'high', 'mosc.kbd': true, 'mosc.freq': 3.95, 'mosc.wave': 'tri', 'mosc.mode': 'fm', 'mosc.index': 0, 'lpg.src': 'mosc', 'lpg2.mode': 'lp', 'lpg2.levelCv': 7, 'lpg2.level': 0, 'out.b': 6 },
        cables: [['j.env2', 'j.lvl2']] },
      { title: 'Slide and spring', module: 'fx',
        why: 'A long portamento and full reverberation.\n- PORTAMENTO SLOPE 8.\n- REVERBERATION 10.\n- channel A 6.\n- Listen for: each change of note sliding into place inside a long spring tail.',
        set: { 'kbd.porta': 8, 'out.rev': 10, 'out.a': 6 } },
    ],
    context: {
      'out.rev': 'In this sound: turned fully up, so the spring tail holds one note into the next.',
      'kbd.porta': 'In this sound: how long each slide takes. Turn it down for clean changes of note.',
      'mosc.freq': 'In this sound: the upper voice’s interval. 3.95 is a fifth; 4.7 an octave.',
      'lpg2.mode': 'In this sound: lo pass filter, so the fifth stays in the background, softer than the root.',
      'env.attack': 'In this sound: how slowly each note arrives.',
    },
    tweaks: [
      { id: 'mosc.index', try: 'Raise the modulation offset to 2', hear: 'The upper voice now also bends the lower one: a slow, beating, slightly sour pad.' },
      { id: 'kbd.porta', try: 'Turn PORTAMENTO SLOPE down to 0', hear: 'Clean steps between notes; the reverb still joins them up.' },
    ],
  },
];
