// More sounds for the Behringer CAT library. Same Preset shape as the ones in ../cat.js (see CONTRACT.md → Preset).

export default [
  {
    id: 'cat-singing-filter', name: 'Singing Filter', ref: 'The self-oscillating filter played as an oscillator', artist: 'Classic technique',
    tags: ['lead', 'fx', 'whistle'], level: 2,
    blurb: 'A pure whistling tone from the filter alone, with a vibrato that arrives late.',
    how: 'With Q at the top the filter rings on its own as a sine wave. VCO 1 AUDIO is off and VCO 2’s sliders are down, so the filter is the only sound. KEYBOARD CONTROL at MAX makes the whistle follow the keys in tune, and the LFO sine on the filter, faded in by LFO DELAY, adds a singer’s late vibrato.',
    phrase: { bpm: 72, loop: true, steps: [[0, 72, 1.8], [2, 76, 0.9], [3, 79, 0.9], [4, 77, 1.8], [6, 74, 1.8]] },
    steps: [
      { title: 'Silence the VCOs', module: 'mixer', why: 'Every sound source is taken out of the VCF (voltage-controlled filter), so that in the next step the filter itself becomes the only sound.\n- VCO 1 AUDIO off: VCO 1 keeps running but no longer reaches the filter.\n- VCO 2 SUB OCTAVE, SQUARE and SAWTOOTH 0: VCO 2 has no on/off switch, so its sliders all go down.\n- NOISE LEVEL 0: no hiss either.\n- Listen for: silence. That is the point: nothing is reaching the filter.',
        set: { 'vcf.vco1Audio': false, 'vco2.sub': 0, 'vco2.square': 0, 'vco2.saw': 0, 'noise.level': 0 } },
      { title: 'Q to the top', module: 'filter', why: 'Q at the top makes the filter ring on its own as a pure sine: it is now the oscillator. KEYBOARD CONTROL keeps that whistle in tune with the keys.\n- Q 10 (100 %): Q is resonance. At the top the filter self-oscillates. Pull it down and you are back to silence.\n- KEYBOARD CONTROL 10 (MAX): the cutoff follows the keys one to one, so the whistle plays in tune. At half way each octave on the keys moves it only half an octave.\n- Fc 4.4 (about 370 Hz): Fc is the cutoff, and now it sets the pitch of the whistle, which octave it plays in.\n- Filter DEPTH 0: no envelope on the cutoff, so the pitch does not swoop at the start of each note.\n- Listen for: a pure, whistling tone. Move Fc to retune it; play up the keyboard to hear it follow.',
        set: { 'vcf.q': 10, 'vcf.kbd': 10, 'vcf.fc': 4.4, 'vcf.mod2Depth': 0 } },
      { title: 'A late vibrato', module: 'lfo', why: 'A late vibrato, like a singer who starts a note straight and then lets it wobble. The LFO (low-frequency oscillator) moves the cutoff, which is now the pitch.\n- Filter LFO SINE, DEPTH 0.4 (4 %): a very small depth, because every bit of cutoff movement is heard as pitch. More soon sounds like a siren.\n- LFO FREQUENCY 6.6 (2.9 Hz): the vibrato speed.\n- LFO DELAY 4 (2.0 s): after each new note the sine is silent, then fades in over two seconds. Every new note restarts the delay.\n- Listen for: a long note that starts dead straight and grows a vibrato. Set LFO DELAY to 0 to hear it wobble from the start.',
        set: { 'vcf.mod1Src': 'sine', 'vcf.mod1Depth': 0.4, 'lfo.rate': 6.6, 'lfo.delay': 4 } },
      { title: 'A smooth line', module: 'amp', why: 'The ADSR (attack, decay, sustain, release envelope) shapes the VCA (voltage-controlled amplifier) so the whistle starts softly and holds, for a smooth, legato line.\n- VCA ADSR: the ADSR sets the loudness.\n- ATTACK 3 (29 ms): a slight fade-in that takes the click off the start of the whistle.\n- DECAY 5 (190 ms), SUSTAIN 10 (100 %): full sustain, so a held note stays at full level.\n- RELEASE 5 (190 ms): a short fade after you let go.\n- Listen for: notes that start gently rather than with a click. Play a slow melody and let the late vibrato arrive on the long notes.',
        set: { 'vca.mode': 'adsr', 'adsr.attack': 3, 'adsr.decay': 5, 'adsr.sustain': 10, 'adsr.release': 5 } },
    ],
    context: {
      'vcf.q': 'In this sound: at the top, the filter is the oscillator. Pull it down and there is silence.',
      'vcf.fc': 'In this sound: sets which octave the whistle plays in.',
      'vcf.kbd': 'In this sound: at MAX the whistle follows the keys in tune. Half way, each octave on the keys moves it only half an octave.',
      'lfo.delay': 'In this sound: how long each note waits before its vibrato.',
    },
    tweaks: [
      { id: 'vcf.kbd', try: 'Set to 5', hear: 'The scale is squashed: every key moves the whistle only half as far.' },
      { id: 'vco2.saw', try: 'Raise to 2', hear: 'A little oscillator under the whistle, coloured by the ringing filter.' },
      { id: 'lfo.delay', try: 'Set to 0', hear: 'Vibrato from the very start of each note.' },
    ],
  },
  {
    id: 'cat-sh-sequence', name: 'VCO 1 Sequence', ref: 'The Octave manual’s trick: a short sequence from the sample and hold', artist: 'Classic technique',
    tags: ['seq', 'modular', '70s'], level: 3,
    blurb: 'A held key that plays a looping pattern of four notes.',
    how: 'VCO 1 is slowed right down with KEYBOARD CONTROL off, and its sub octave and pulse are mixed. The sample and hold measures that mix once per LFO cycle; because VCO 1 runs at about half the LFO’s speed, the measurements repeat in a pattern of four. Those steps move VCO 2’s pitch, and ADSR REPEAT plays a new note on each step.',
    phrase: { bpm: 100, loop: true, steps: [[0, 48, 7.8]] },
    steps: [
      { title: 'VCO 1 as a slow pattern', module: 'osc', why: 'VCO 1 (voltage-controlled oscillator 1) is slowed down to a few cycles a second and hidden. It is not a sound here but a slow repeating shape for the sample and hold to measure.\n- KEYBOARD CONTROL OFF: VCO 1 ignores the keys and runs where COARSE puts it.\n- VCO 1 COARSE 2.7 (about 2.4 Hz): with the keys off, COARSE sets VCO 1’s speed directly, from 0.2 Hz to 2 kHz. Small moves change the pattern later.\n- SAWTOOTH 0, SUB OCTAVE 8, PULSE 6: the sub is a square at half VCO 1’s speed. Added to the pulse, the mix passes through four different levels in each cycle.\n- PULSE WIDTH 0: a square pulse, so the four levels are evenly spaced in time.\n- VCO 1 AUDIO off: VCO 1 is not heard.\n- Listen for: silence. VCO 2’s sliders are still down.',
        set: { 'pitch.kbdCtrl': 'off', 'vco1.coarse': 2.66, 'vco1.saw': 0, 'vco1.sub': 8, 'vco1.pulse': 6, 'vco1.pw': 0, 'vcf.vco1Audio': false } },
      { title: 'Sample VCO 1', module: 'mod', why: 'The S+H (sample and hold) takes a reading once per LFO (low-frequency oscillator) cycle and holds it until the next. Pointed at the slow VCO 1, it reads that four-level shape.\n- SAMPLE AND HOLD source VCO 1: it measures VCO 1’s mix of waves rather than noise. With all of VCO 1’s sliders down there would be nothing to sample.\n- LFO FREQUENCY 7.3 (about 4.7 Hz): the S+H clock, just under twice VCO 1’s speed. The readings land at slightly different points of each VCO 1 cycle and repeat in a short pattern that slowly shifts.\n- Listen for: still nothing. The S+H is running but no switch uses it yet.',
        set: { 'sh.src': 'vco1', 'lfo.rate': 7.3 } },
      { title: 'Steps move VCO 2', module: 'mod', why: 'The S+H steps now move VCO 2’s pitch, and VCO 2 is made audible. The readings become a short, looping run of notes on one held key.\n- VCO 2 left switch S+H, DEPTH 6 (60 %): the steps move VCO 2’s pitch. More depth makes wider intervals; less squeezes the pattern into a narrow range.\n- VCO 2 SAWTOOTH 7 and SUB OCTAVE 3: a bright saw with a little weight an octave below.\n- Listen for: hold a key and VCO 2 steps through a repeating pattern of pitches about four to five times a second. Nudge VCO 1 COARSE and the pattern drifts or changes.',
        set: { 'vco2.mod1Src': 'sh', 'vco2.mod1Depth': 6, 'vco2.saw': 7, 'vco2.sub': 3 } },
      { title: 'One note per step', module: 'env', why: 'ADSR REPEAT fires the envelope on every LFO cycle, so each pitch step gets its own plucked note, and the filter and VCA (voltage-controlled amplifier) turn the stream into a sequence.\n- ADSR REPEAT GATED: the envelopes restart every LFO cycle while the key is held.\n- ADSR 0 / 4.8 / 3 / 4: attack 3 ms, decay 160 ms, sustain 30 %, release 91 ms. A quick pluck on each step that falls to a lower level.\n- VCA ADSR: the same ADSR (attack, decay, sustain, release) shapes loudness, so the notes are separated.\n- Fc 4.4 (about 370 Hz), Q 5 (50 %): Fc is the cutoff, Q the resonance. A darkish, resonant filter so each pluck has a squelch.\n- Filter ADSR, DEPTH 5 (+3 oct): each pluck opens the filter by up to three octaves.\n- Listen for: a looping, sequencer-like pattern from one held key. LFO FREQUENCY sets the tempo, and also changes the pattern.',
        set: { 'trig.repeat': 'gated', 'adsr.attack': 0, 'adsr.decay': 4.8, 'adsr.sustain': 3, 'adsr.release': 4, 'vca.mode': 'adsr', 'vcf.fc': 4.4, 'vcf.q': 5, 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 5 } },
    ],
    context: {
      'vco1.coarse': 'In this sound: VCO 1’s speed against the LFO. Small moves make the pattern drift or change length.',
      'vco1.pulse': 'In this sound: one of the two waves being sampled. Change its level and the notes of the pattern change.',
      'vco2.mod1Depth': 'In this sound: how wide the pattern’s intervals are.',
      'lfo.rate': 'In this sound: the tempo, and also the S&H clock, so it changes the pattern as well.',
    },
    tweaks: [
      { id: 'vco1.coarse', try: 'Nudge between 2.5 and 2.8', hear: 'The pattern slowly rotates or changes its notes.' },
      { id: 'vco1.tri', try: 'Raise to 5', hear: 'More, less regular steps: the triangle adds values in between.' },
      { id: 'sh.src', try: 'Switch to NOISE', hear: 'The pattern becomes random and never repeats.' },
    ],
  },
  {
    id: 'cat-vco-lfo-pad', name: 'VCO 1 as a Second LFO', ref: 'Using a free-running VCO 1 as a slow modulator', artist: 'Classic technique',
    tags: ['pad', 'ambient', 'modular'], level: 3,
    blurb: 'A soft pad whose filter sweeps slowly by itself, with vibrato from the real LFO.',
    how: 'With KEYBOARD CONTROL off and COARSE near the bottom, VCO 1 runs at under a cycle a second. VCO 1 AUDIO off hides it, and the filter’s right switch on VCO 1 turns it into a slow filter sweep. That leaves the LFO free for a separate vibrato: two modulators at two speeds on a synth with one LFO.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 3.8], [0, 55, 3.8], [4, 51, 3.8], [4, 58, 3.8]] },
    steps: [
      { title: 'Slow VCO 1 right down', module: 'osc', why: 'VCO 1 (voltage-controlled oscillator 1) is slowed below one cycle a second and hidden, so it can work as a second LFO (low-frequency oscillator). The CAT has only one real LFO.\n- KEYBOARD CONTROL OFF: VCO 1 ignores the keys and runs where COARSE puts it.\n- VCO 1 COARSE 1 (about 0.5 Hz): with the keys off, COARSE sets the speed directly. About one cycle every two seconds; turn it up and the sweep becomes a wobble, then a growl.\n- SAWTOOTH 0, TRIANGLE 8: a triangle rises and falls evenly, so the sweep will be smooth.\n- VCO 1 AUDIO off: VCO 1 is not heard.\n- Listen for: silence. VCO 2 is still down.',
        set: { 'pitch.kbdCtrl': 'off', 'vco1.coarse': 1, 'vco1.saw': 0, 'vco1.tri': 8, 'vcf.vco1Audio': false } },
      { title: 'VCO 2 is the sound', module: 'osc', why: 'VCO 2 becomes the only thing you hear: a sawtooth with a sub octave for a warm pad tone.\n- VCO 2 SAWTOOTH 7: bright and full of harmonics, so the filter sweep will have something to move through.\n- VCO 2 SUB OCTAVE 4: a square an octave down that adds body without muddying the pad.\n- Listen for: a plain, bright saw on each key. The default filter and envelope are still in place.',
        set: { 'vco2.saw': 7, 'vco2.sub': 4 } },
      { title: 'VCO 1 sweeps the filter', module: 'filter', why: 'The VCF (voltage-controlled filter) takes the slow VCO 1 as its modulation, so the pad’s brightness rises and falls on its own.\n- Filter right switch VCO 1, DEPTH 4: the right switch usually picks an envelope; here it picks VCO 1, and the depth sets how wide the sweep is.\n- Fc 4.6 (about 425 Hz): Fc is the cutoff, the centre of the sweep. Lower is darker overall.\n- Q 4 (40 %): Q is resonance. Enough to make the sweep audible as a vowel-like movement.\n- KEYBOARD CONTROL 5 (50 %): the cutoff follows the keys half way.\n- Listen for: a slow “wah” rising and falling about every two seconds, whether you play or not. Turn up VCO 1 COARSE to hear it speed up into a wobble.',
        set: { 'vcf.mod2Src': 'vco1', 'vcf.mod2Depth': 4, 'vcf.fc': 4.6, 'vcf.q': 4, 'vcf.kbd': 5 } },
      { title: 'Vibrato from the LFO', module: 'lfo', why: 'The real LFO (low-frequency oscillator) is still free, so it adds a vibrato to VCO 2: two modulators at two speeds on a synth with one LFO.\n- VCO 2 LFO SINE, DEPTH 1.6 (16 %): a gentle pitch wobble.\n- LFO FREQUENCY 6.2 (2.2 Hz): much faster than the filter sweep, so you hear the two separately.\n- LFO DELAY 2 (1.0 s): the vibrato fades in over a second after each new note.\n- Listen for: held notes gaining a light vibrato on top of the slow filter sweep. Change LFO FREQUENCY and only the vibrato speed changes.',
        set: { 'vco2.mod1Src': 'sine', 'vco2.mod1Depth': 1.6, 'lfo.rate': 6.2, 'lfo.delay': 2 } },
      { title: 'A slow swell', module: 'amp', why: 'The ADSR (attack, decay, sustain, release envelope) on the VCA (voltage-controlled amplifier) gets a slow start and a long tail, which turns the tone into a pad.\n- VCA ADSR: the ADSR sets the loudness.\n- ATTACK 5.5 (200 ms): each note fades in rather than starting hard.\n- DECAY 5 (190 ms), SUSTAIN 10 (100 %): full level while the key is held.\n- RELEASE 6.5 (550 ms): notes fade out slowly, so changes blur together.\n- Listen for: soft, swelling notes with the slow sweep underneath. Hold a note for several seconds to hear the sweep and vibrato together.',
        set: { 'vca.mode': 'adsr', 'adsr.attack': 5.5, 'adsr.decay': 5, 'adsr.sustain': 10, 'adsr.release': 6.5 } },
    ],
    context: {
      'vco1.coarse': 'In this sound: the speed of the filter sweep. Turn it up and the sweep becomes a fast wobble, then a growl.',
      'vcf.mod2Depth': 'In this sound: how far VCO 1 sweeps the filter.',
      'vcf.vco1Audio': 'In this sound: off, so VCO 1 works as a modulator only.',
      'lfo.rate': 'In this sound: the vibrato speed, separate from the sweep.',
    },
    tweaks: [
      { id: 'vco1.coarse', try: 'Raise to 4', hear: 'The sweep speeds up into a wobble, then a rough buzz.' },
      { id: 'vco1.tri', try: 'Bring down, and raise PULSE instead', hear: 'The sweep jumps between two brightnesses.' },
      { id: 'vcf.q', try: 'Raise to 7', hear: 'The sweep whistles as it passes each harmonic.' },
    ],
  },
  {
    id: 'cat-trill', name: 'Square-Wave Trill', ref: 'The LFO square as a trill between two notes', artist: 'Classic technique',
    tags: ['lead', 'trill', '70s'], level: 1,
    blurb: 'A bright lead that flutters between two notes a tone apart.',
    how: 'The LFO square jumps between two values, so on a VCO’s pitch it gives a trill: the pitch flips between just above and just below the note played. The depth sets the interval; here both VCOs trill by a whole tone together.',
    phrase: { bpm: 84, loop: true, steps: [[0, 67, 1.9], [2, 72, 1.9], [4, 70, 1.9], [6, 65, 1.9]] },
    steps: [
      { title: 'A bright tone', module: 'osc', why: 'A bright tone from two sawtooths on the same key. The VCOs (voltage-controlled oscillators) are the raw tone; the trill comes next.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key, so they trill together.\n- VCO 1 SAWTOOTH 7, VCO 2 SAWTOOTH 6: two saws, VCO 2 a little lower in level.\n- VCO 2 FINE TUNE 0 (about +0.1 st): the slightest detune, so the two beat gently instead of sounding like one oscillator.\n- Listen for: a bright, buzzy lead with a slight movement on held notes.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 7, 'vco2.saw': 6, 'vco2.fine': 0.04 } },
      { title: 'Trill both VCOs', module: 'mod', why: 'The LFO (low-frequency oscillator) square jumps between two values, so on pitch it makes a trill: the note flips between two pitches at the LFO rate.\n- VCO 1 and VCO 2 left switch LFO SQUARE: the square jumps rather than glides. On sine it would be a wide vibrato instead.\n- DEPTH 2 (20 %) on both: the trill interval, about a whole tone. Higher gives a third, then a fourth; much higher sounds like a siren. Keep both the same so the VCOs move together.\n- LFO FREQUENCY 7.2 (4.3 Hz): how fast the trill flutters, about four flips a second.\n- Listen for: a held note fluttering between two pitches a tone apart. Sweep LFO FREQUENCY to hear it go from a slow alternation to a buzz.',
        set: { 'vco1.mod1Src': 'square', 'vco1.mod1Depth': 2.04, 'vco2.mod1Src': 'square', 'vco2.mod1Depth': 2.04, 'lfo.rate': 7.2 } },
      { title: 'Filter and loudness', module: 'filter', why: 'The VCF (voltage-controlled filter) takes the edge off, and the ADSR (attack, decay, sustain, release) envelope is set close to an organ so the trill does not fade.\n- Fc 5.6 (about 870 Hz), Q 2 (20 %): Fc is the cutoff, Q the resonance. Bright but not harsh, with a little edge.\n- Filter DEPTH 2 (+1.2 oct): the ADSR lifts the cutoff a little at the start of each note.\n- ATTACK 0.5 (4 ms): almost instant.\n- SUSTAIN 9 (90 %): held notes stay nearly at full level, since the VCA (voltage-controlled amplifier) follows the ADSR.\n- RELEASE 3.5 (63 ms): a short tail.\n- Listen for: a slight brightening at the start of each note, then a steady trill for as long as you hold it.',
        set: { 'vcf.fc': 5.6, 'vcf.q': 2, 'vcf.mod2Depth': 2, 'adsr.attack': 0.5, 'adsr.sustain': 9, 'adsr.release': 3.5 } },
    ],
    context: {
      'vco1.mod1Depth': 'In this sound: the trill interval. Higher gives a third, then a fourth; much higher sounds like a siren.',
      'lfo.rate': 'In this sound: how fast the trill flutters.',
      'vco2.mod1Src': 'In this sound: the square, so the pitch jumps instead of gliding. On sine it becomes a wide vibrato.',
    },
    tweaks: [
      { id: 'vco2.mod1Depth', try: 'Set to 0', hear: 'Only VCO 1 trills, against a steady VCO 2.' },
      { id: 'lfo.rate', try: 'Lower to 6', hear: 'A slow, deliberate alternation.' },
      { id: 'vco1.mod1Src', try: 'Switch to S+H', hear: 'VCO 1 jumps to random notes instead.' },
    ],
  },
  {
    id: 'cat-wind', name: 'Wind and Surf', ref: 'A noise sound effect', artist: 'Classic technique',
    tags: ['fx', 'noise', 'ambient'], level: 1,
    blurb: 'Gusts of wind that rise and fall on their own.',
    how: 'The VCOs are silent and the noise does the work. A resonant filter picks a whistling band out of the hiss, and the slow LFO sine moves it up and down like gusts. A long attack and release on the AR let each gust swell and fade.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 7.8]] },
    steps: [
      { title: 'Noise only', module: 'mixer', why: 'The VCOs (voltage-controlled oscillators) are silenced and white noise takes over. Wind and surf are just hiss with a moving filter on it.\n- VCO 1 SAWTOOTH 0: VCO 1’s only raised slider goes down. VCO 2’s sliders are already at 0.\n- VCO 1 AUDIO off: VCO 1 is taken out of the filter altogether.\n- NOISE LEVEL 8: white noise, an even hiss across all frequencies, into the filter.\n- Listen for: plain hiss on every key, the same whichever note you play.',
        set: { 'vco1.saw': 0, 'vcf.vco1Audio': false, 'noise.level': 8 } },
      { title: 'A whistling band', module: 'filter', why: 'The VCF (voltage-controlled filter) picks a band out of the hiss. With high resonance it starts to whistle, the way wind does through a gap.\n- Fc 5 (about 570 Hz): Fc is the cutoff, the centre of the band. Lower sounds like distant rumble, higher like a thin whistle.\n- Q 7 (70 %): Q is resonance. High Q narrows the band into a whistle; low Q sounds more like surf.\n- Filter DEPTH 0: no envelope on the filter, so the colour does not jump at the start of each note.\n- KEYBOARD CONTROL 0: the cutoff ignores the keys, so every key gives the same wind.\n- Listen for: the hiss turning into a hollow, whistling rush. Sweep Q to move between surf and wind.',
        set: { 'vcf.fc': 5, 'vcf.q': 7, 'vcf.mod2Depth': 0, 'vcf.kbd': 0 } },
      { title: 'Slow gusts', module: 'lfo', why: 'The LFO (low-frequency oscillator) moves the cutoff slowly up and down, which is heard as gusts.\n- Filter LFO SINE, DEPTH 6 (60 %): a deep sweep of the cutoff, so the gusts rise and fall a long way.\n- LFO FREQUENCY 2.6 (0.18 Hz): very slow, about one gust every five or six seconds.\n- LFO DELAY 0: the sine runs at full depth at once. With a delay, each new key would start with still air.\n- Listen for: the whistle rising and falling on its own while you hold a key. Speed up LFO FREQUENCY and the gusts turn into a wobble.',
        set: { 'vcf.mod1Src': 'sine', 'vcf.mod1Depth': 6, 'lfo.rate': 2.6, 'lfo.delay': 0 } },
      { title: 'Swell and fade', module: 'amp', why: 'The AR envelope gives the VCA (voltage-controlled amplifier) a slow rise and fall, so the wind swells in and dies away instead of switching on and off.\n- VCA AR: the AR (attack, release) envelope sets the loudness. It rises over ATTACK, holds at full level while the key is down, and falls over RELEASE.\n- AR ATTACK 7 (680 ms): the wind fades in over most of a second.\n- AR RELEASE 8 (1.6 s): let go and it dies away slowly.\n- Listen for: tap a key briefly and you get a short puff; hold it for a sustained gust. The release carries on after you let go.',
        set: { 'vca.mode': 'ar', 'ar.attack': 7, 'ar.release': 8 } },
    ],
    context: {
      'vcf.q': 'In this sound: how whistly the wind is. Low Q sounds like surf; high Q like wind through a gap.',
      'vcf.mod1Depth': 'In this sound: the size of the gusts.',
      'lfo.rate': 'In this sound: how often a gust comes.',
    },
    tweaks: [
      { id: 'vcf.q', try: 'Lower to 2', hear: 'The wind turns into breaking waves.' },
      { id: 'vcf.mod1Src', try: 'Switch to S+H', hear: 'The wind jumps between pitches: a stormy, broken sound.' },
      { id: 'lfo.rate', try: 'Raise to 4', hear: 'Faster, more restless gusts.' },
    ],
  },
  {
    id: 'cat-repeat-pulse', name: 'Pulsing Chord', ref: 'ADSR REPEAT turning held keys into a rhythm', artist: 'Classic technique',
    tags: ['keys', 'rhythm', '70s'], level: 2,
    blurb: 'Two held keys that pulse in time with the LFO.',
    how: 'ADSR REPEAT on GATED fires the envelopes again every LFO cycle while keys are held, so a held two-note chord pulses like a chopped organ. The ADSR has no sustain, so each repeat is a short pluck, and it shapes both the filter and the VCA.',
    phrase: { bpm: 90, loop: true, steps: [[0, 57, 3.9], [0, 64, 3.9], [4, 55, 3.9], [4, 62, 3.9]] },
    steps: [
      { title: 'Two notes', module: 'osc', why: 'Two notes from two VCOs (voltage-controlled oscillators), on hollow, organ-like waves. Hold two keys and each VCO takes one.\n- KEYBOARD CONTROL POLY: VCO 1 plays the higher key, VCO 2 the lower.\n- VCO 1 SAWTOOTH 0, PULSE 7: VCO 1 on its pulse only.\n- PULSE WIDTH 3 (30 %): a slightly narrow, fixed pulse, a little reedier than a square.\n- VCO 2 SQUARE 7: a hollow, woody square for the lower note.\n- Listen for: hold two keys a fifth apart. A reedy upper note over a hollow lower one.',
        set: { 'pitch.kbdCtrl': 'poly', 'vco1.saw': 0, 'vco1.pulse': 7, 'vco1.pw': 3, 'vco2.square': 7 } },
      { title: 'A plucked envelope', module: 'env', why: 'The ADSR (attack, decay, sustain, release envelope) becomes a short pluck with no sustain, and drives both the filter and the VCA (voltage-controlled amplifier).\n- VCA ADSR: the ADSR sets the loudness.\n- ATTACK 0, DECAY 4.2, SUSTAIN 0: each note is a quick pluck that dies away. Longer DECAY blurs the pulses together once they repeat.\n- RELEASE 3 (44 ms): a short tail.\n- Fc 4 (about 280 Hz), Q 3 (30 %): Fc is the cutoff, Q the resonance. Dark at rest, with a little edge.\n- Filter ADSR, DEPTH 5 (+3 oct): the pluck opens the filter wide and shuts it again.\n- Listen for: each chord is now a single short pluck, however long you hold it.',
        set: { 'vca.mode': 'adsr', 'adsr.attack': 0, 'adsr.decay': 4.2, 'adsr.sustain': 0, 'adsr.release': 3, 'vcf.fc': 4, 'vcf.q': 3, 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 5 } },
      { title: 'Repeat it', module: 'mod', why: 'ADSR REPEAT uses the LFO (low-frequency oscillator) as a clock to refire the envelopes, so held keys keep plucking in time.\n- ADSR REPEAT GATED: the envelopes restart every LFO cycle while keys are held. AUTO keeps going on its own with no key down.\n- LFO FREQUENCY 7.4 (about 5 Hz): the pulse tempo, about five plucks a second.\n- Listen for: a held chord chopping into a steady pulse, like a gated organ. Move LFO FREQUENCY to set the tempo, and lengthen DECAY to hear the pulses run together.',
        set: { 'trig.repeat': 'gated', 'lfo.rate': 7.4 } },
    ],
    context: {
      'lfo.rate': 'In this sound: the pulse tempo.',
      'adsr.decay': 'In this sound: the length of each pulse. Longer decays blur the pulses together.',
      'trig.repeat': 'In this sound: GATED pulses only while keys are held. AUTO keeps going on its own.',
    },
    tweaks: [
      { id: 'adsr.decay', try: 'Raise to 5.5', hear: 'Longer, overlapping pulses, more like a strummed chord.' },
      { id: 'lfo.rate', try: 'Move between 6.5 and 8', hear: 'From a slow throb to a fast flutter.' },
      { id: 'vcf.mod1Src', try: 'Switch to S+H with the filter’s left depth at 3', hear: 'Each pulse has a different brightness.' },
    ],
  },
  {
    id: 'cat-gated-sync', name: 'Gated Sync Growl', ref: 'SYNC MODE A, swept by the LFO', artist: 'Classic technique',
    tags: ['lead', 'sync', 'aggressive'], level: 3,
    blurb: 'A rough, gappy sync tone that sweeps up and down under the LFO.',
    how: 'SYNC MODE A is hard sync with VCO 1 silenced for half of every VCO 2 cycle, which adds a hollow, broken edge. The LFO sine on VCO 1’s pitch sweeps the sync tone back and forth instead of changing the note, and VCO 2’s sub octave keeps a solid note underneath.',
    phrase: { bpm: 100, loop: true, steps: [[0, 52, 1.9], [2, 55, 0.9], [3, 57, 0.9], [4, 52, 3.8]] },
    steps: [
      { title: 'Gated sync', module: 'osc', why: 'Sync on MODE A: VCO 1 (voltage-controlled oscillator 1) is locked to VCO 2 and also silenced for half of every VCO 2 cycle. That gives a rougher, gappier tone than ordinary sync.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key.\n- SYNC MODE A: hard sync with gaps. MODE B is smoother; OFF loses the sync. The switch is in VCO 2’s section but acts on VCO 1.\n- VCO 1 COARSE 6.2 (+17.3 st): VCO 1 well above VCO 2. Its tuning now sets tone, not pitch. Below VCO 2 it goes quiet.\n- VCO 1 SAWTOOTH 8: the synced wave you hear.\n- VCO 2 SUB OCTAVE 5: a square an octave below, a solid note under the rough sync.\n- Listen for: a hard, hollow, broken buzz. Flip SYNC to MODE B to hear it smooth out.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.sync': 'mode_a', 'vco1.coarse': 6.2, 'vco1.saw': 8, 'vco2.sub': 5 } },
      { title: 'Sweep with the LFO', module: 'mod', why: 'The LFO (low-frequency oscillator) sine moves VCO 1’s pitch. Because VCO 1 is synced, that moves the tone back and forth rather than the note.\n- VCO 1 LFO SINE, DEPTH 5 (50 %): plenty of depth, so the sweep is wide. More makes it more extreme.\n- LFO FREQUENCY 4.8 (0.83 Hz): a little under one sweep a second.\n- LFO DELAY 0: the sweep runs from the start of every note.\n- Listen for: a slow, growling up-and-down sweep while the note stays put. Switch SYNC to OFF and the same LFO bends the pitch instead.',
        set: { 'vco1.mod1Src': 'sine', 'vco1.mod1Depth': 5, 'lfo.rate': 4.8, 'lfo.delay': 0 } },
      { title: 'Filter and loudness', module: 'filter', why: 'The VCF (voltage-controlled filter) stays mostly open so the sync tone comes through, and the AR envelope holds the level steady.\n- Fc 7 (2.4 kHz), Q 2 (20 %): Fc is the cutoff, Q the resonance. Open enough for the rough top end, with a little edge.\n- Filter DEPTH 1.5 (+0.9 oct): the ADSR lifts the cutoff slightly at the start of each note.\n- VCA AR: the VCA (voltage-controlled amplifier) follows the AR (attack, release) envelope, which holds full level while the key is down.\n- AR ATTACK 0.3, RELEASE 4: a 4 ms start and a 91 ms tail.\n- Listen for: a steady level while the tone sweeps. Pull Fc down to hear the growl go dark and distant.',
        set: { 'vcf.fc': 7, 'vcf.q': 2, 'vcf.mod2Depth': 1.5, 'vca.mode': 'ar', 'ar.attack': 0.3, 'ar.release': 4 } },
    ],
    context: {
      'vco1.sync': 'In this sound: MODE A gives the gaps. MODE B is smoother; OFF loses the sync and the LFO bends the pitch instead.',
      'vco1.mod1Depth': 'In this sound: how far the sync tone sweeps.',
      'vco2.sub': 'In this sound: the solid note under the sweep.',
    },
    tweaks: [
      { id: 'vco1.sync', try: 'Switch to MODE B', hear: 'A smoother, more familiar sync sweep.' },
      { id: 'vco1.mod1Src', try: 'Switch to S+H', hear: 'The sync tone jumps between random timbres.' },
      { id: 'lfo.rate', try: 'Lower to 3.5', hear: 'A slow, grinding sweep.' },
    ],
  },
  {
    id: 'cat-brass', name: 'Duo Brass', ref: 'In the style of 70s synth brass', artist: 'Classic technique',
    tags: ['brass', 'lead', '70s'], level: 1,
    blurb: 'A warm brass sound that blooms open at the start of each note.',
    how: 'Two sawtooths, slightly detuned, give the buzzing harmonics of brass. The ADSR opens the filter with a slow-ish attack, which copies the way a player’s tone brightens as they blow harder, and the AR shapes the loudness.',
    phrase: { bpm: 84, loop: true, steps: [[0, 60, 1.5], [1.5, 67, 0.5], [2, 65, 1], [3, 63, 0.9], [4, 60, 2.8]] },
    steps: [
      { title: 'Two sawtooths', module: 'osc', why: 'Two sawtooths, slightly detuned, give the buzzing harmonics of a brass section. VCO stands for voltage-controlled oscillator, the part that makes the raw tone.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key.\n- VCO 1 and VCO 2 SAWTOOTH 7: a saw is the brightest, buzziest wave, the closest to brass.\n- VCO 1 FINE +0.6 (about +12 cents): VCO 1 a little sharp, so the two beat slowly. That movement makes it sound like more than one player.\n- Listen for: a bright, raw buzz with a slow swirl on held notes. Set FINE back to 0 and it sounds like a single, static oscillator.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 7, 'vco2.saw': 7, 'vco1.fine': 0.6 } },
      { title: 'A darker filter', module: 'filter', why: 'The VCF (voltage-controlled filter) is set low, so the resting tone is mellow. The next step opens it on each note.\n- Fc 3.8 (about 240 Hz): Fc is the cutoff. This low the saws become soft and muted. Higher gives a brighter resting tone.\n- Q 1.5 (15 %): Q is resonance. Just a touch, so the brass keeps a warm edge without squelching.\n- KEYBOARD CONTROL 6 (60 %): the cutoff follows the keys part way, so high notes are brighter, as they are on a real horn.\n- Listen for: a mellow, muted tone. The default envelope still lifts it a little on each note.',
        set: { 'vcf.fc': 3.8, 'vcf.q': 1.5, 'vcf.kbd': 6 } },
      { title: 'Let the ADSR open it', module: 'env', why: 'The ADSR (attack, decay, sustain, release envelope) opens the filter with a slow-ish attack. That copies the way a player’s tone brightens as they blow harder: the brass bloom.\n- Filter ADSR, DEPTH 4 (+2.4 oct): how bright the peak of each note gets.\n- ATTACK 4.6 (99 ms): the bloom. At 0 it becomes a stab; higher, each note swells more slowly.\n- DECAY 5.6 (290 ms) to SUSTAIN 5 (50 %): after the peak the tone settles part way back.\n- RELEASE 4 (91 ms): a short tail.\n- Listen for: each note swelling bright, then settling. For now the VCA (voltage-controlled amplifier) also follows this ADSR, so loudness dips with it. The next step fixes that.',
        set: { 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 4, 'adsr.attack': 4.6, 'adsr.decay': 5.6, 'adsr.sustain': 5, 'adsr.release': 4 } },
      { title: 'Loudness from the AR', module: 'amp', why: 'The VCA (voltage-controlled amplifier) moves to the AR envelope, so loudness holds steady while the ADSR only shapes the filter.\n- VCA AR: the AR (attack, release) envelope rises, holds at full level while the key is down, then falls.\n- AR ATTACK 2.5 (21 ms): a short fade-in that removes the click, like the soft start of a breath.\n- AR RELEASE 3.5 (63 ms): a short tail.\n- Listen for: the notes now stay at full level while the tone blooms and settles. Try AR ATTACK at 0 for a harder, stabbier section.',
        set: { 'vca.mode': 'ar', 'ar.attack': 2.5, 'ar.release': 3.5 } },
    ],
    context: {
      'adsr.attack': 'In this sound: this is the bloom. At 0 it becomes a stab; turned up, each note swells more slowly.',
      'vcf.mod2Depth': 'In this sound: how bright the peak of each note gets.',
      'vco1.fine': 'In this sound: the slow beating between the VCOs that makes it sound like a section.',
    },
    tweaks: [
      { id: 'adsr.attack', try: 'Sweep from 0 to 6', hear: 'From a bright stab to a slow swell.' },
      { id: 'vco2.square', try: 'Raise to 5 and SAWTOOTH to 0', hear: 'A hollower, reedier horn.' },
      { id: 'pitch.kbdCtrl', try: 'Switch to POLY and play two keys', hear: 'A two-part brass line through one filter.' },
    ],
  },
  {
    id: 'cat-flute', name: 'Delayed-Vibrato Flute', ref: 'A flute from a triangle, a little noise and LFO DELAY', artist: 'Classic technique',
    tags: ['wind', 'lead', 'acoustic'], level: 2,
    blurb: 'A soft, breathy flute whose vibrato arrives after the note starts.',
    how: 'A triangle is close to a flute’s pure tone, and a little noise through the same filter is the breath. The vibrato is the LFO sine at a small depth, but LFO DELAY holds it back and fades it in, the way a player starts a note straight and then adds vibrato.',
    phrase: { bpm: 76, loop: true, steps: [[0, 72, 1.4], [1.5, 74, 0.4], [2, 76, 1.8], [4, 79, 0.9], [5, 77, 0.9], [6, 74, 1.8]] },
    steps: [
      { title: 'Triangle and breath', module: 'osc', why: 'A flute is close to a pure tone plus breath. VCO 1 (voltage-controlled oscillator 1) gives the tone on a triangle, and a little noise is the breath.\n- KEYBOARD CONTROL MONO: VCO 1 follows the lowest key, one note at a time.\n- VCO 1 SAWTOOTH 0, TRIANGLE 8: a triangle has few harmonics, so it sounds soft and flute-like. VCO 2 stays silent.\n- NOISE LEVEL 2.5: a little white noise. Too much and it sounds like hiss rather than breath.\n- Listen for: a soft, round tone with a faint hiss around it.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 0, 'vco1.tri': 8, 'noise.level': 2.5 } },
      { title: 'Filter just above the note', module: 'filter', why: 'The VCF (voltage-controlled filter) softens the noise so it sits under the tone, and follows the keys so the breath stays even across the range.\n- Fc 4.6 (about 425 Hz), Q 1 (10 %): Fc is the cutoff, Q the resonance. Low, so the breath is gentle rather than hissy.\n- KEYBOARD CONTROL 10 (MAX): the cutoff follows the keys exactly, so high notes do not go dull.\n- Filter AR, DEPTH 1 (+0.6 oct): the AR (attack, release) envelope lifts the cutoff slightly while a note is held.\n- Listen for: the hiss becoming a soft breath around the note. Raise Fc and the breath gets brighter and more obvious.',
        set: { 'vcf.fc': 4.6, 'vcf.q': 1, 'vcf.kbd': 10, 'vcf.mod2Src': 'ar', 'vcf.mod2Depth': 1 } },
      { title: 'A late vibrato', module: 'lfo', why: 'A late vibrato from the LFO (low-frequency oscillator), held back by LFO DELAY the way a player starts a note straight and then adds vibrato.\n- Both VCOs LFO SINE, DEPTH 1.5 (15 %): a small wobble. VCO 2 is silent here, so only VCO 1’s setting is heard. Keep it small or it sounds seasick.\n- LFO FREQUENCY 6.8 (3.3 Hz): a natural vibrato speed.\n- LFO DELAY 2.4 (1.2 s): each new note starts straight and the vibrato fades in over about a second.\n- Listen for: long notes growing a gentle vibrato; short ones stay straight. Set LFO DELAY to 0 to hear the difference.',
        set: { 'vco1.mod1Src': 'sine', 'vco1.mod1Depth': 1.5, 'vco2.mod1Src': 'sine', 'vco2.mod1Depth': 1.5, 'lfo.rate': 6.8, 'lfo.delay': 2.4 } },
      { title: 'A blown attack', module: 'amp', why: 'The VCA (voltage-controlled amplifier) moves to the AR envelope with a gentle attack, so each note is blown in rather than switched on.\n- VCA AR: the AR (attack, release) envelope sets the loudness and holds full level while the key is down.\n- AR ATTACK 3.6 (49 ms): a soft start, the breath before the tone. Longer is a lazier flute.\n- AR RELEASE 4 (91 ms): a short fade after you let go.\n- Listen for: notes starting with a soft push instead of a click.',
        set: { 'vca.mode': 'ar', 'ar.attack': 3.6, 'ar.release': 4 } },
    ],
    context: {
      'lfo.delay': 'In this sound: how long each note stays straight before the vibrato comes in.',
      'noise.level': 'In this sound: the breath. Too much and it sounds like hiss.',
      'vco1.mod1Depth': 'In this sound: the vibrato depth. Keep it small.',
    },
    tweaks: [
      { id: 'lfo.delay', try: 'Set to 0', hear: 'Vibrato from the start: more like a synth, less like a player.' },
      { id: 'noise.level', try: 'Raise to 5', hear: 'A breathier, pan-pipe tone.' },
      { id: 'vcf.fc', try: 'Raise to 6', hear: 'A brighter, recorder-like tone.' },
    ],
  },
  {
    id: 'cat-synth-tom', name: 'Synth Tom', ref: 'In the style of late-70s disco synth drums', artist: 'Classic technique',
    tags: ['perc', 'drum', 'disco'], level: 2,
    blurb: 'A pitched drum that drops in pitch as it dies away.',
    how: 'The ADSR, through VCO 2’s right-hand modulation knob, starts each note high and falls quickly, which is the “pew” of 70s synth drums. A little noise adds the stick, and the ADSR with no sustain also shapes the loudness, so each hit dies away.',
    phrase: { bpm: 104, loop: true, steps: [[0, 48, 0.3], [1, 45, 0.3], [2, 43, 0.3], [2.5, 43, 0.3], [3, 40, 0.3]] },
    steps: [
      { title: 'A square and a little noise', module: 'osc', why: 'A square from VCO 2 (voltage-controlled oscillator 2) is the body of the drum, and a touch of noise is the stick.\n- VCO 1 SAWTOOTH 0 and VCO 1 AUDIO off: VCO 1 is taken out of the sound.\n- VCO 2 SQUARE 8: a hollow, woody square for the drum’s tone.\n- NOISE LEVEL 3: a little white noise, the click of the stick.\n- Listen for: a steady square with hiss on it. Nothing drum-like yet.',
        set: { 'vco1.saw': 0, 'vcf.vco1Audio': false, 'vco2.square': 8, 'noise.level': 3 } },
      { title: 'The pitch drop', module: 'mod', why: 'The ADSR (attack, decay, sustain, release envelope) is sent to VCO 2’s pitch, so each hit starts high and drops: the “pew” of 70s disco synth drums.\n- VCO 2 right switch ADSR, DEPTH 5 (50 %): the size of the pitch drop, several semitones. More is a laser-like zap.\n- ATTACK 0 (3 ms): the pitch starts at the top.\n- DECAY 4.4 (120 ms), SUSTAIN 0: the pitch falls back fast. The same ADSR is on the VCA (voltage-controlled amplifier), so the hit dies away over the same time.\n- RELEASE 4.4 (120 ms): a matching tail if you let go early.\n- Listen for: a short “pew” on each key. Sweep DECAY to change both the drop and the length of the hit.',
        set: { 'vco2.mod2Src': 'adsr', 'vco2.mod2Depth': 5, 'adsr.attack': 0, 'adsr.decay': 4.4, 'adsr.sustain': 0, 'adsr.release': 4.4 } },
      { title: 'A dark, round filter', module: 'filter', why: 'The VCF (voltage-controlled filter) is set low and round, with some resonance for body and a little lift at the start of each hit.\n- Fc 4.2 (about 320 Hz): Fc is the cutoff. Low, so the drum sounds dark and round.\n- Q 4 (40 %): Q is resonance. It adds a ringing body to the tom.\n- KEYBOARD CONTROL 8 (80 %): the cutoff follows the keys closely, so higher toms are brighter.\n- Filter ADSR, DEPTH 3 (+1.8 oct): the hit opens the filter briefly, which gives the stick more click.\n- Listen for: play a fill down the keys, from high toms to low.',
        set: { 'vcf.fc': 4.2, 'vcf.q': 4, 'vcf.kbd': 8, 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 3 } },
      { title: 'A struck loudness shape', module: 'amp', why: 'The VCA (voltage-controlled amplifier) is on the ADSR, which has no sustain, so each note is a struck hit rather than a held tone.\n- VCA ADSR: the ADSR (attack, decay, sustain, release) sets the loudness. With SUSTAIN at 0, the hit dies away however long you hold the key. The VCA was already on ADSR, so this step confirms it.\n- Listen for: switch the VCA to AR and the drum turns into a held tone with a pitch dip at the front.',
        set: { 'vca.mode': 'adsr' } },
    ],
    context: {
      'vco2.mod2Depth': 'In this sound: the size of the pitch drop.',
      'adsr.decay': 'In this sound: both the length of the drop and of the hit.',
      'noise.level': 'In this sound: the stick sound at the start of each hit.',
    },
    tweaks: [
      { id: 'vco2.mod2Depth', try: 'Raise to 7', hear: 'A laser-like zap.' },
      { id: 'adsr.decay', try: 'Lower to 3.5', hear: 'A short, tight hit.' },
      { id: 'vcf.q', try: 'Raise to 8', hear: 'A ringing, electronic tom.' },
    ],
  },
  {
    id: 'devo-buzz-riff', name: 'New Wave Buzz Riff', ref: 'In the style of Devo — tight, buzzy synth riffs of the late 70s', artist: 'Devo',
    tags: ['lead', 'new wave', '70s'], level: 1,
    blurb: 'A thin, nasal pulse that snaps on every note: a riff instrument, not a solo voice.',
    how: 'A narrow pulse from VCO 1 gives the nasal buzz, and VCO 2’s square an octave down keeps it from sounding weedy. The ADSR opens the filter with a quick snap and falls to a low sustain, so short notes bark and nothing lingers. There is no vibrato and no glide: the riff should sound mechanical.',
    phrase: { bpm: 138, loop: true, steps: [[0, 57, 0.3], [0.5, 57, 0.3], [1, 60, 0.3], [1.5, 57, 0.3], [2, 62, 0.3], [2.5, 60, 0.3], [3, 64, 0.3], [3.5, 62, 0.3]] },
    steps: [
      { title: 'A narrow pulse', module: 'osc', why: 'A narrow pulse from VCO 1 (voltage-controlled oscillator 1) gives the thin, nasal buzz of a late-70s new wave riff.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key, so the riff is one line.\n- VCO 1 SAWTOOTH 0, PULSE 8: the pulse only.\n- PULSE WIDTH source DC: nothing moves the width, so it stays fixed. A riff instrument should sound the same on every note.\n- PULSE WIDTH 7 (70 %): well right, a thin, nasal pulse. Turn it left and it becomes a hollow square.\n- Listen for: a thin, nasal buzz. Sweep PULSE WIDTH to hear it go from hollow to reedy to thin.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 0, 'vco1.pulse': 8, 'vco1.pwmSrc': 'dc', 'vco1.pw': 7 } },
      { title: 'A square an octave down', module: 'osc', why: 'VCO 2 is dropped an octave to put a floor under the thin pulse, so the riff does not sound weedy.\n- VCO 2 FINE TUNE −4 (−12 st): VCO 2’s one tuning knob spans about two and a half octaves, so it can set intervals. Here it puts VCO 2 a full octave down.\n- VCO 2 SQUARE 5: a hollow square at half level, under the pulse rather than beside it.\n- Listen for: the riff gaining weight underneath. Pull VCO 2 SQUARE down to hear how thin the pulse is on its own.',
        set: { 'vco2.fine': -4, 'vco2.square': 5 } },
      { title: 'A snapping filter', module: 'filter', why: 'The VCF (voltage-controlled filter) snaps open on every note and closes again, which gives each note its bark.\n- Fc 5.2 (about 650 Hz): Fc is the cutoff, the resting tone between barks.\n- Q 4 (40 %): Q is resonance. Enough to give the snap a nasal edge.\n- KEYBOARD CONTROL 6 (60 %): the cutoff follows the keys part way, so higher notes stay bright.\n- Filter ADSR, DEPTH 4 (+2.4 oct): the ADSR (attack, decay, sustain, release) envelope opens the filter at the start of each note. More is a harder bark.\n- Listen for: a bright bite on each note of the riff.',
        set: { 'vcf.fc': 5.2, 'vcf.q': 4, 'vcf.kbd': 6, 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 4 } },
      { title: 'Short and dry', module: 'env', why: 'The ADSR is made short and dry, so short notes bark and nothing lingers. It shapes the filter and the VCA (voltage-controlled amplifier).\n- ATTACK 0 (3 ms): each note starts at once, right on the beat.\n- DECAY 3.6 (68 ms): the bark falls away fast to the thinner held tone.\n- SUSTAIN 3 (30 %): held notes drop to a quieter, duller level.\n- RELEASE 2.5 (31 ms): notes stop almost as soon as the key comes up.\n- VCA ADSR: the same ADSR sets the loudness.\n- Listen for: a tight, mechanical riff with clean gaps. Lengthen DECAY and the bark turns into a softer “wow”.',
        set: { 'adsr.attack': 0, 'adsr.decay': 3.6, 'adsr.sustain': 3, 'adsr.release': 2.5, 'vca.mode': 'adsr' } },
    ],
    context: {
      'vco1.pw': 'In this sound: the nasal buzz. Turn it left and the pulse becomes a hollow square.',
      'vco2.fine': 'In this sound: an octave down, so VCO 2 is a floor under the pulse rather than a second voice.',
      'vcf.mod2Depth': 'In this sound: the bark at the start of each note.',
      'adsr.decay': 'In this sound: how quickly the bark falls to the thinner held tone.',
    },
    tweaks: [
      { id: 'vco1.pw', try: 'Move between 3 and 9', hear: 'From a hollow square to a thin, reedy whine.' },
      { id: 'vco1.sync', try: 'Switch to MODE B and raise VCO 1 COARSE to 6', hear: 'A harder, more metallic buzz.' },
      { id: 'vcf.q', try: 'Raise to 7', hear: 'Each note quacks as the filter snaps open.' },
    ],
  },
  {
    id: 'enz-break-lead', name: 'New Wave Break Lead', ref: 'In the style of Split Enz — the keyboard break in "I Got You"', artist: 'Split Enz',
    tags: ['lead', 'new wave', '80s'], level: 1,
    blurb: 'A bright, reedy lead with a slight slide between notes and a vibrato that arrives late.',
    how: 'VCO 1’s pulse gives a reedy top and VCO 2’s sawtooth an octave below fills it out. A little GLIDE joins the notes, and LFO DELAY holds the vibrato back so quick notes stay straight and held ones wobble. The filter is fairly open with some Q, so the sound is bright without being harsh.',
    phrase: { bpm: 132, loop: true, steps: [[0, 76, 0.4], [0.5, 74, 0.4], [1, 72, 0.4], [1.5, 74, 0.9], [2.5, 71, 0.4], [3, 72, 1.9], [5, 67, 0.4], [5.5, 69, 0.4], [6, 71, 1.9]] },
    steps: [
      { title: 'A pulse over a sawtooth', module: 'osc', why: 'A reedy pulse on top with a sawtooth an octave below. The VCOs (voltage-controlled oscillators) together give a bright lead with body.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key.\n- VCO 1 SAWTOOTH 0, PULSE 8: VCO 1 on its pulse only.\n- PULSE WIDTH source DC, WIDTH 3: a fixed, slightly narrow pulse, the reedy edge. Fully left is a hollow square; further right is thinner.\n- VCO 2 FINE TUNE −4 (−12 st): VCO 2 an octave below VCO 1.\n- VCO 2 SAWTOOTH 5: a saw at a lower level, filling out the pulse.\n- Listen for: a reedy, bright tone with weight underneath.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 0, 'vco1.pulse': 8, 'vco1.pwmSrc': 'dc', 'vco1.pw': 3, 'vco2.fine': -4, 'vco2.saw': 5 } },
      { title: 'A bright filter', module: 'filter', why: 'The VCF (voltage-controlled filter) is left fairly open, with some resonance and a small lift on each note: bright without being harsh.\n- Fc 6 (about 1.2 kHz): Fc is the cutoff. Well up, so the lead is bright.\n- Q 3 (30 %): Q is resonance. A little edge on top.\n- KEYBOARD CONTROL 7 (70 %): the cutoff follows the keys closely, so the high notes of the break stay bright.\n- Filter ADSR, DEPTH 3 (+1.8 oct): the ADSR (attack, decay, sustain, release) envelope brightens the start of each note.\n- Listen for: a little extra bite at the start of each note.',
        set: { 'vcf.fc': 6, 'vcf.q': 3, 'vcf.kbd': 7, 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 3 } },
      { title: 'An organ-like envelope', module: 'env', why: 'The ADSR is set close to an organ: quick to start and high sustain, so held notes stay loud. It shapes the VCA (voltage-controlled amplifier) and the filter lift.\n- ATTACK 0.5 (4 ms): almost instant.\n- DECAY 4.5 (130 ms) to SUSTAIN 7 (70 %): a small dip after the start, then 70 % while held.\n- RELEASE 3.5 (63 ms): a short tail, so quick notes stay separate.\n- VCA ADSR: the ADSR sets the loudness.\n- Listen for: long notes holding their level instead of fading.',
        set: { 'adsr.attack': 0.5, 'adsr.decay': 4.5, 'adsr.sustain': 7, 'adsr.release': 3.5, 'vca.mode': 'adsr' } },
      { title: 'Slide and late vibrato', module: 'glide', why: 'A touch of GLIDE joins the notes, and a delayed vibrato from the LFO (low-frequency oscillator) wobbles only the long ones.\n- GLIDE 2 (47 ms): each note slides in from the last, very briefly. Much more and the line smears.\n- LFO FREQUENCY 6.4 (2.5 Hz): the vibrato speed.\n- LFO DELAY 2 (1.0 s): the sine fades in over a second after each new note, so fast notes stay straight.\n- Both VCOs LFO SINE, DEPTH 1.5 (15 %): the same small vibrato on both, so they wobble together.\n- Listen for: quick notes landing clean, and held notes starting to wobble after a moment. Set GLIDE to 0 to hear the line turn stepped.',
        set: { 'pitch.glide': 2, 'lfo.rate': 6.4, 'lfo.delay': 2, 'vco1.mod1Src': 'sine', 'vco1.mod1Depth': 1.5, 'vco2.mod1Src': 'sine', 'vco2.mod1Depth': 1.5 } },
    ],
    context: {
      'vco1.pw': 'In this sound: the reedy edge. Fully left is a hollow square; further right is thinner.',
      'pitch.glide': 'In this sound: a short slide that joins the notes. Much more and the line smears.',
      'lfo.delay': 'In this sound: keeps the fast notes straight and gives the long ones their wobble.',
      'vco2.fine': 'In this sound: an octave below VCO 1, filling out the pulse.',
    },
    tweaks: [
      { id: 'pitch.glide', try: 'Raise to 4', hear: 'Every note slides noticeably into the next.' },
      { id: 'lfo.delay', try: 'Set to 0', hear: 'Vibrato on every note, even the short ones.' },
      { id: 'vco1.mod1Depth', try: 'Raise to 3', hear: 'A wide, wobbly vibrato, like a worn tape.' },
    ],
  },
  {
    id: 'big-beat-squelch', name: 'Big Beat Squelch', ref: 'In the style of The Chemical Brothers — resonant 90s big-beat riffs', artist: 'The Chemical Brothers',
    tags: ['bass', 'big beat', '90s'], level: 2,
    blurb: 'A low, resonant riff that squelches on each note and slides between some of them.',
    how: 'Two sawtooths and a sub octave give a thick, bright source. High Q and a big ADSR sweep make each note squelch, and a slow LFO sine on the cutoff keeps the tone moving under the riff. The AR holds the loudness steady, so the ADSR only shapes the filter, and a little GLIDE slides between notes.',
    phrase: { bpm: 112, loop: true, steps: [[0, 40, 0.4], [0.5, 40, 0.2], [0.75, 52, 0.2], [1, 43, 0.4], [1.5, 45, 0.9], [2.5, 40, 0.2], [3, 50, 0.4], [3.5, 48, 0.4]] },
    steps: [
      { title: 'Two saws and a sub', module: 'osc', why: 'Two sawtooths and a sub octave give a thick, bright source for the squelch. VCO stands for voltage-controlled oscillator, the part that makes the raw tone.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key.\n- VCO 1 SAWTOOTH 7, VCO 2 SAWTOOTH 5: two saws, full of harmonics for a resonant filter to pick out.\n- VCO 2 FINE TUNE +0.1 (about +0.2 st): VCO 2 very slightly off, so the saws beat and thicken.\n- VCO 2 SUB OCTAVE 4: a square an octave below for weight.\n- Listen for: a thick, raw saw bass.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 7, 'vco2.saw': 5, 'vco2.fine': 0.05, 'vco2.sub': 4 } },
      { title: 'A resonant, closed filter', module: 'filter', why: 'The VCF (voltage-controlled filter) is shut low with high resonance, so it rings at the cutoff. The next step sweeps it.\n- Fc 3.4 (about 180 Hz): Fc is the cutoff. Very low, so the resting tone is dark.\n- Q 7.5 (75 %): Q is resonance, a boost right at the cutoff. This high it rings: that ring is the squelch once the cutoff moves. Lower it and the riff becomes a plain, round bass.\n- KEYBOARD CONTROL 5 (50 %): the cutoff follows the keys half way.\n- Listen for: a dark, slightly hollow tone with a ring at the bottom.',
        set: { 'vcf.fc': 3.4, 'vcf.q': 7.5, 'vcf.kbd': 5 } },
      { title: 'The squelch', module: 'env', why: 'The ADSR (attack, decay, sustain, release envelope) sweeps the resonant filter a long way up and brings it back fast. That is the squelch on each note.\n- Filter ADSR, DEPTH 6 (+3.6 oct): how far each squelch reaches. More is wilder, less is a gentler “bow”.\n- ATTACK 0 (3 ms): the sweep starts at the top straight away.\n- DECAY 4 (91 ms): the cutoff falls back fast.\n- SUSTAIN 1 (10 %), RELEASE 3 (44 ms): almost closed while held, with a short tail.\n- Listen for: a rubbery squelch on every note. For now the VCA (voltage-controlled amplifier) also follows this ADSR, so notes shrink to 10 % level. The next step fixes that.',
        set: { 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 6, 'adsr.attack': 0, 'adsr.decay': 4, 'adsr.sustain': 1, 'adsr.release': 3 } },
      { title: 'Steady loudness, moving tone', module: 'amp', why: 'The VCA moves to the AR envelope, so notes hold at full level while the ADSR only moves the filter. A slow LFO (low-frequency oscillator) and a little GLIDE keep the riff moving.\n- VCA AR, AR ATTACK 0, RELEASE 2.5: the AR (attack, release) envelope holds full level while the key is down, starts in 3 ms and stops 31 ms after.\n- Filter LFO SINE, DEPTH 1.5 (15 %): a slow drift in brightness under the riff.\n- LFO FREQUENCY 3.5 (0.34 Hz): about one drift every three seconds. LFO DELAY 0, so it never restarts.\n- GLIDE 2.5 (59 ms): a short slide between notes.\n- Listen for: full-length notes, the squelch only at the front, and the tone slowly brightening and darkening over a few bars.',
        set: { 'vca.mode': 'ar', 'ar.attack': 0, 'ar.release': 2.5, 'vcf.mod1Src': 'sine', 'vcf.mod1Depth': 1.5, 'lfo.rate': 3.5, 'lfo.delay': 0, 'pitch.glide': 2.5 } },
    ],
    context: {
      'vcf.q': 'In this sound: the squelch. Lower it and the riff becomes a plain, round bass.',
      'vcf.mod2Depth': 'In this sound: how far each note’s squelch reaches.',
      'vcf.mod1Depth': 'In this sound: the slow drift in brightness under the riff.',
      'vca.mode': 'In this sound: AR, so the notes hold while the ADSR only moves the filter.',
    },
    tweaks: [
      { id: 'vcf.fc', try: 'Sweep slowly from 2.5 to 5.5 while the riff plays', hear: 'The riff builds from a muffled throb to a screaming squelch.' },
      { id: 'adsr.decay', try: 'Move between 3 and 5.5', hear: 'From short blips to long, rubbery wah-wahs.' },
      { id: 'vcf.mod1Src', try: 'Switch to S+H', hear: 'Each note lands at a random brightness.' },
    ],
  },
  {
    id: 'bubble-life-kit', name: 'Hand-Played Drum Kit', ref: 'In the style of Squarepusher — the hand-played CAT drums of "Bubble Life"', artist: 'Squarepusher',
    tags: ['perc', 'drum', 'idm'], level: 3,
    blurb: 'One patch that plays a kick on low keys and a snare or tick on high ones.',
    how: 'The filter follows the keys at MAX, so low notes are dark and high notes let the noise through. The ADSR drops VCO 2’s pitch on every hit and also shapes the loudness with no sustain, so each note is a short drum. Squarepusher built the drums of "Bubble Life" layer by layer from CAT sounds played by hand; here the whole kit is on one keyboard.',
    phrase: { bpm: 120, loop: true, steps: [[0, 36, 0.2], [0.5, 84, 0.1], [0.75, 36, 0.2], [1, 67, 0.2], [1.5, 84, 0.1], [2.25, 36, 0.2], [2.5, 84, 0.1], [3, 67, 0.2], [3.25, 84, 0.1], [3.5, 72, 0.2]] },
    steps: [
      { title: 'A square, a sub and noise', module: 'osc', why: 'A square, a sub octave and noise are the parts of the kit: body, kick weight and snare. VCO 2 (voltage-controlled oscillator 2) makes all the pitched sound.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key, one hit at a time.\n- VCO 1 SAWTOOTH 0 and VCO 1 AUDIO off: VCO 1 is out of the sound.\n- VCO 2 SQUARE 8 and SUB OCTAVE 6: a hollow square with a deep square an octave below, the body and weight of the kick.\n- NOISE LEVEL 6: plenty of white noise, the snare. It will only get through on higher keys once the filter follows the keys.\n- Listen for: a buzzy square with hiss on top. It is not a drum yet.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 0, 'vcf.vco1Audio': false, 'vco2.square': 8, 'vco2.sub': 6, 'noise.level': 6 } },
      { title: 'The pitch drop', module: 'mod', why: 'The ADSR (attack, decay, sustain, release envelope) is sent to VCO 2’s pitch, so each hit starts high and falls fast. That fast drop is the punch of a synth kick.\n- VCO 2 right switch ADSR, DEPTH 6 (60 %): the size of the drop, about an octave. Turn it up for a laser-like zap.\n- ATTACK 0 (3 ms): the pitch starts at the top.\n- DECAY 4.2 (100 ms), SUSTAIN 0: the pitch falls back fast. The VCA (voltage-controlled amplifier) already follows the ADSR, so the hit dies away with it.\n- RELEASE 4.2 (100 ms): the same fall if you let go early.\n- Listen for: a short, punchy “boom” on each key.',
        set: { 'vco2.mod2Src': 'adsr', 'vco2.mod2Depth': 6, 'adsr.attack': 0, 'adsr.decay': 4.2, 'adsr.sustain': 0, 'adsr.release': 4.2 } },
      { title: 'A filter that follows the keys', module: 'filter', why: 'The VCF (voltage-controlled filter) follows the keys exactly. That turns one patch into a kit: low keys stay dark, high keys open up and let the noise through as a snare.\n- Fc 3.4 (about 180 Hz): Fc is the cutoff. Low, so the bottom keys are a dark thump.\n- Q 2 (20 %): Q is resonance. A little body.\n- KEYBOARD CONTROL 10 (MAX): the cutoff follows the keys one to one. At OFF every key sounds like the same muffled drum.\n- Filter ADSR, DEPTH 4 (+2.4 oct): the ADSR opens the filter briefly on each hit, a click at the front.\n- Listen for: low keys as kicks, middle keys as toms, high keys as snares and ticks.',
        set: { 'vcf.fc': 3.4, 'vcf.q': 2, 'vcf.kbd': 10, 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 4 } },
      { title: 'Struck, not held', module: 'amp', why: 'The VCA (voltage-controlled amplifier) stays on the ADSR, which has no sustain, so every note is a hit that dies away. VOLUME goes up, because short hits sound quieter than held notes.\n- VCA ADSR: the ADSR (attack, decay, sustain, release) sets the loudness. On AR the drums would hold as long as the key.\n- VOLUME 10 (100 %): the output level at full.\n- Listen for: play a beat by hand, kick low, snare high, in the style of the hand-played drums on “Bubble Life”.',
        set: { 'vca.mode': 'adsr', 'out.volume': 10 } },
    ],
    context: {
      'vcf.kbd': 'In this sound: what turns one patch into a kit. At OFF every key sounds like the same muffled drum.',
      'vco2.mod2Depth': 'In this sound: the punch of the kick. Turn it up for a laser-like zap.',
      'noise.level': 'In this sound: the snare. It is only heard on keys high enough to open the filter.',
      'adsr.decay': 'In this sound: the length of every hit and of its pitch drop.',
    },
    tweaks: [
      { id: 'noise.level', try: 'Raise to 8', hear: 'The high keys become a hissing snare; the kick gets a dirty edge.' },
      { id: 'adsr.decay', try: 'Lower to 3.2', hear: 'A tight, clicky kit.' },
      { id: 'vcf.q', try: 'Raise to 6', hear: 'Every hit rings with a pitched, electronic tone.' },
    ],
  },
  {
    id: 'daftpunk-voyager-bass', name: 'Gliding Funk Bass', ref: 'In the style of Daft Punk — "Voyager"', artist: 'Daft Punk',
    tags: ['bass', 'house', '2000s'], level: 1,
    blurb: 'A round, warm bass that slides a little into every note, with a soft pluck at the start of each one.',
    how: 'VCO 1’s sawtooth and VCO 2’s square play the same key, with VCO 2’s sub octave underneath for weight. A short GLIDE makes each note slide in from the last, which is what makes a busy line sound fluid rather than stepped. The ADSR opens the filter a little on each note and falls back to a mellow level, while the AR holds the loudness steady so notes keep their full body for as long as they are held.',
    phrase: { bpm: 116, loop: true, steps: [[0, 40, 0.4], [0.75, 40, 0.2], [1, 47, 0.4], [1.5, 52, 0.4], [2, 50, 0.7], [2.75, 47, 0.2], [3, 45, 0.4], [3.5, 43, 0.4]] },
    steps: [
      { title: 'A sawtooth, a square and a sub', module: 'osc', why: 'A sawtooth, a square and a sub octave on one key give a round bass with an edge on top. VCO stands for voltage-controlled oscillator, the part that makes the raw tone.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key.\n- VCO 1 SAWTOOTH 6: the saw is the edge that lets the line cut through.\n- VCO 1 FINE +0.3 (about +6 cents): VCO 1 a hair sharp, so the two beat slowly and the tone keeps moving.\n- VCO 2 SQUARE 6: a hollow, woody middle.\n- VCO 2 SUB OCTAVE 5: the floor. Take it down and the bass sounds thinner and higher.\n- Listen for: a full, slightly moving bass tone.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 6, 'vco1.fine': 0.3, 'vco2.square': 6, 'vco2.sub': 5 } },
      { title: 'A warm filter with a soft pluck', module: 'filter', why: 'The VCF (voltage-controlled filter) rounds the sawtooth off, and the ADSR (attack, decay, sustain, release envelope) opens it at the start of each note for a soft pluck.\n- Fc 3.4 (about 180 Hz), Q 3.5 (35 %): Fc is the cutoff, Q the resonance. Low and warm, with a slight edge.\n- KEYBOARD CONTROL 5 (50 %): the cutoff follows the keys half way.\n- Filter ADSR, DEPTH 4 (+2.4 oct): each note opens the filter by about two octaves. More is a sharper pluck.\n- ATTACK 0, DECAY 4.4 (120 ms): the pluck starts at once and settles quickly.\n- SUSTAIN 3 (30 %), RELEASE 3 (44 ms): a mellow held tone and a short tail.\n- Listen for: a soft “dow” at the front of each note. The VCA (voltage-controlled amplifier) still follows this ADSR for now, so held notes also get quieter.',
        set: { 'vcf.fc': 3.4, 'vcf.q': 3.5, 'vcf.kbd': 5, 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 4, 'adsr.attack': 0, 'adsr.decay': 4.4, 'adsr.sustain': 3, 'adsr.release': 3 } },
      { title: 'Steady loudness from the AR', module: 'amp', why: 'The VCA (voltage-controlled amplifier) moves to the AR envelope, so the notes keep their full body while the ADSR only moves the filter.\n- VCA AR: the AR (attack, release) envelope holds full level for as long as the key is down.\n- AR ATTACK 0 (3 ms): full level at once, lined up with the pluck.\n- AR RELEASE 2.8 (38 ms): a short tail, so a busy line stays tight.\n- Listen for: long notes now holding their weight, with the pluck only at the start.',
        set: { 'vca.mode': 'ar', 'ar.attack': 0, 'ar.release': 2.8 } },
      { title: 'A short slide between notes', module: 'glide', why: 'GLIDE makes each note slide in from the last one, which is what makes a busy funk line sound fluid rather than stepped.\n- GLIDE 3.5 (91 ms): about a tenth of a second. Jumps up to an octave sound smooth and a little lazy. Much more and the notes smear into each other; at 0 the line steps.\n- Listen for: octave jumps and runs sliding into place. Play the line with GLIDE at 0 and then back up to hear the difference.',
        set: { 'pitch.glide': 3.5 } },
    ],
    context: {
      'pitch.glide': 'In this sound: the slide that makes the line fluid. Much more and the notes smear into each other.',
      'vcf.mod2Depth': 'In this sound: the soft pluck at the start of each note.',
      'adsr.decay': 'In this sound: how quickly the pluck settles to the mellow held tone.',
      'vco2.sub': 'In this sound: the weight under the line. Take it down and the bass sounds thinner and higher.',
      'vca.mode': 'In this sound: AR, so the notes hold at full level while the ADSR only shapes the filter.',
      'vco1.fine': 'In this sound: a slow beat between the two VCOs that keeps the tone moving.',
    },
    tweaks: [
      { id: 'pitch.glide', try: 'Raise to 5', hear: 'Every note swoops into the next, like a fretless bass.' },
      { id: 'vcf.q', try: 'Raise to 6', hear: 'A rubbery, funkier pluck on each note.' },
      { id: 'vcf.fc', try: 'Lower to 2.6', hear: 'A darker, rounder bass that sits further back.' },
    ],
  },
  {
    id: 'kraftwerk-dummies-pulse', name: 'Stiff Marching Pulse', ref: 'In the style of Kraftwerk — "Showroom Dummies"', artist: 'Kraftwerk',
    tags: ['bass', 'electronic', '70s'], level: 1,
    blurb: 'A hollow, clipped bass pulse that starts and stops exactly with the keys, with no slide, no sweep and no tail.',
    how: 'Two squares, one from each VCO, and VCO 2’s sub octave give a hollow, woody tone. The filter is set once and left alone: with the envelope depth at 0 every note has exactly the same colour. The VCA is on AR with no attack and almost no release, so each note is cut off the moment the key is let go. Short, even notes then sound stiff and mechanical, like a march played by a machine.',
    phrase: { bpm: 128, loop: true, steps: [[0, 45, 0.25], [0.5, 45, 0.25], [1, 57, 0.25], [1.5, 45, 0.25], [2, 43, 0.25], [2.5, 43, 0.25], [3, 55, 0.25], [3.5, 47, 0.25]] },
    steps: [
      { title: 'Two squares and a sub', module: 'osc', why: 'Two squares and a sub octave give a hollow, woody tone for a stiff, marching bass. VCO stands for voltage-controlled oscillator, the part that makes the raw tone.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key.\n- VCO 1 SAWTOOTH 0, PULSE 7: VCO 1 on its pulse only.\n- PULSE WIDTH source DC, WIDTH 0: a fixed width, fully left, which is a square, the hollow part of the tone. Turn it right for a thinner, nasal pulse.\n- VCO 2 SQUARE 6: a second square on the same note.\n- VCO 2 SUB OCTAVE 5: weight an octave below.\n- Listen for: a hollow, woody tone, like a clarinet an octave down.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 0, 'vco1.pulse': 7, 'vco1.pwmSrc': 'dc', 'vco1.pw': 0, 'vco2.square': 6, 'vco2.sub': 5 } },
      { title: 'A fixed filter', module: 'filter', why: 'The VCF (voltage-controlled filter) is set once and left alone. With no envelope on it, every note has exactly the same colour.\n- Fc 5.2 (about 650 Hz): Fc is the cutoff, the one tone setting for the whole line. Lower is duller and more distant.\n- Q 2 (20 %): Q is resonance. A little edge.\n- KEYBOARD CONTROL 5 (50 %): the cutoff follows the keys half way.\n- Filter DEPTH 0: at 0 on purpose, so no note is brighter than any other.\n- Listen for: every note sounding the same, with no pluck or sweep at the front.',
        set: { 'vcf.fc': 5.2, 'vcf.q': 2, 'vcf.kbd': 5, 'vcf.mod2Depth': 0 } },
      { title: 'Clipped by the AR', module: 'amp', why: 'The VCA (voltage-controlled amplifier) moves to the AR envelope with both times at the minimum, so notes start and stop exactly with the keys.\n- VCA AR: the AR (attack, release) envelope holds full level while the key is down.\n- AR ATTACK 0 (3 ms): each note starts at full level.\n- AR RELEASE 0 (5 ms): each note stops dead when the key comes up. Raise it and the notes get a tail and the stiffness goes.\n- Listen for: play short, even notes. The keys alone decide how clipped the line sounds.',
        set: { 'vca.mode': 'ar', 'ar.attack': 0, 'ar.release': 0 } },
      { title: 'No glide, no vibrato', module: 'glide', why: 'Nothing wavers and nothing slides: the line should sound mechanical, like a march played by a machine.\n- GLIDE 0: each note jumps straight to its pitch.\n- VCO 1 and VCO 2 left DEPTH 0: no LFO (low-frequency oscillator) on either VCO’s pitch, so no vibrato. They were already at 0; this makes sure.\n- Listen for: a dead-steady line. Try a little GLIDE to hear how quickly it stops sounding stiff.',
        set: { 'pitch.glide': 0, 'vco1.mod1Depth': 0, 'vco2.mod1Depth': 0 } },
    ],
    context: {
      'ar.release': 'In this sound: at 0 each note stops dead. Raise it and the notes get a tail and the stiffness goes.',
      'vcf.mod2Depth': 'In this sound: at 0 on purpose, so no note is brighter than any other.',
      'vco1.pw': 'In this sound: fully left gives a square, the hollow part of the tone. Turn it right for a thinner, nasal pulse.',
      'vcf.fc': 'In this sound: the one setting for the tone of the whole line. Lower is duller and more distant.',
      'vco2.sub': 'In this sound: the weight an octave below.',
    },
    tweaks: [
      { id: 'ar.release', try: 'Raise to 3', hear: 'Each note gets a short tail and the march loosens up.' },
      { id: 'vco1.pw', try: 'Turn to 7', hear: 'A thin, nasal pulse on top of the squares.' },
      { id: 'vcf.fc', try: 'Lower to 3.2', hear: 'A duller, thudding pulse, more felt than heard.' },
    ],
  },
  {
    id: 'rubber-glide-squelch-lead', name: 'Rubbery Squelch Lead', ref: 'In the style of Bernie Worrell — "P-Funk (Wants to Get Funked Up)" (Mothership Connection)', artist: 'Bernie Worrell',
    tags: ['lead', 'funk', '70s'], level: 2,
    blurb: 'A fat, squelchy lead that slides into every note, with a wobble that only comes in on held notes.',
    how: 'Two sawtooths on one key, VCO 1 slightly sharp, with a little of VCO 2’s sub octave underneath. The filter sits low with high Q, and a fast ADSR sweep opens it on every note, so each note starts with a squelch and falls back to a rounder tone. GLIDE makes every note slide into the next, and a delayed vibrato adds a wobble to the long notes. Play it in short bursts with big jumps, so the slides and squelches are heard.',
    phrase: { bpm: 104, loop: true, steps: [[0, 64, 0.4], [0.5, 67, 0.2], [0.75, 69, 0.4], [1.5, 76, 0.4], [2, 74, 0.2], [2.5, 71, 0.4], [3, 69, 0.2], [3.5, 67, 0.4], [4, 64, 1.4], [5.5, 62, 0.4], [6, 64, 1.8]] },
    steps: [
      { title: 'Two sawtooths and a little sub', module: 'osc', why: 'Two sawtooths on one key, slightly detuned, with a little sub underneath: a fat, buzzy lead. VCO stands for voltage-controlled oscillator, the part that makes the raw tone.\n- KEYBOARD CONTROL MONO: both VCOs follow the lowest key.\n- VCO 1 SAWTOOTH 7, VCO 2 SAWTOOTH 6: two bright saws.\n- VCO 1 FINE +0.4 (about +8 cents): VCO 1 slightly sharp, so the two beat and the lead sounds fatter.\n- VCO 2 SUB OCTAVE 3: a little weight an octave below.\n- Listen for: a thick, buzzy tone with a slow swirl.',
        set: { 'pitch.kbdCtrl': 'mono', 'vco1.saw': 7, 'vco2.saw': 6, 'vco1.fine': 0.4, 'vco2.sub': 3 } },
      { title: 'A low, resonant filter', module: 'filter', why: 'The VCF (voltage-controlled filter) sits low with high resonance, so it rings at the cutoff. The squelch comes when the next step sweeps it.\n- Fc 3.6 (about 210 Hz): Fc is the cutoff. Low, so the resting tone is dark.\n- Q 6.5 (65 %): Q is resonance. The ring that turns a sweep into a squelch. Lower it and the lead becomes a plain, round tone.\n- KEYBOARD CONTROL 6 (60 %): the cutoff follows the keys part way, so high notes do not go dull.\n- Listen for: a darker tone with a ringing, hollow quality.',
        set: { 'vcf.fc': 3.6, 'vcf.q': 6.5, 'vcf.kbd': 6 } },
      { title: 'The squelch', module: 'env', why: 'The ADSR (attack, decay, sustain, release envelope) sweeps the resonant filter wide open and brings it back fast. Each note starts with a squelch and falls back to a rounder tone.\n- Filter ADSR, DEPTH 5 (+3 oct): how far the filter opens at the start of each note.\n- ATTACK 0 (3 ms): the squelch lands on the beat.\n- DECAY 4.6 (140 ms): how quickly it falls back. Longer gives a slower wah on each note.\n- SUSTAIN 3 (30 %), RELEASE 3.5 (63 ms): a rounder held tone and a short tail.\n- Listen for: a rubbery “wow” on every note. For now the VCA (voltage-controlled amplifier) follows this ADSR too, so held notes drop in level.',
        set: { 'vcf.mod2Src': 'adsr', 'vcf.mod2Depth': 5, 'adsr.attack': 0, 'adsr.decay': 4.6, 'adsr.sustain': 3, 'adsr.release': 3.5 } },
      { title: 'Steady loudness from the AR', module: 'amp', why: 'The VCA (voltage-controlled amplifier) moves to the AR envelope, so loudness holds while the ADSR only shapes the filter.\n- VCA AR: the AR (attack, release) envelope holds full level while the key is down.\n- AR ATTACK 0 (3 ms): full level at once.\n- AR RELEASE 3 (44 ms): a short tail.\n- Listen for: held notes now keep their weight after the squelch.',
        set: { 'vca.mode': 'ar', 'ar.attack': 0, 'ar.release': 3 } },
      { title: 'Slides and a late wobble', module: 'glide', why: 'GLIDE makes every note slide into the next, and a delayed vibrato from the LFO (low-frequency oscillator) wobbles only the held notes.\n- GLIDE 4 (110 ms): about a tenth of a second. The bigger the jump, the more you hear it. Much more and fast lines smear.\n- LFO FREQUENCY 6.6 (2.9 Hz): the wobble speed.\n- LFO DELAY 2 (1.0 s): the sine fades in over a second, so short notes stay straight.\n- Both VCOs LFO SINE, DEPTH 2 (20 %): the same vibrato on both VCOs.\n- Listen for: play short bursts with big jumps. The slides and squelches come through, and long notes start to wobble.',
        set: { 'pitch.glide': 4, 'lfo.rate': 6.6, 'lfo.delay': 2, 'vco1.mod1Src': 'sine', 'vco1.mod1Depth': 2, 'vco2.mod1Src': 'sine', 'vco2.mod1Depth': 2 } },
    ],
    context: {
      'pitch.glide': 'In this sound: the slide into every note. The bigger the jump, the more you hear it. Much more and fast lines smear.',
      'vcf.q': 'In this sound: the squelch. Lower it and the lead turns into a plain, round tone.',
      'vcf.mod2Depth': 'In this sound: how far the filter opens at the start of each note.',
      'adsr.decay': 'In this sound: how quickly the squelch falls back. Longer gives a slower wah on each note.',
      'lfo.delay': 'In this sound: keeps short notes straight and gives the held ones their wobble.',
      'vca.mode': 'In this sound: AR, so the loudness holds while the ADSR only shapes the filter.',
    },
    tweaks: [
      { id: 'pitch.glide', try: 'Raise to 6', hear: 'Long, lazy swoops between notes.' },
      { id: 'adsr.decay', try: 'Move between 3.5 and 6', hear: 'From a short blip to a slow, rubbery wah on each note.' },
      { id: 'vco1.mod1Depth', try: 'Raise to 3.5 on both VCOs', hear: 'A wide, wobbling vibrato on the held notes.' },
    ],
  },
  {
    id: 'slow-wavering-dusk-pad', name: 'Wavering Dusk Pad', ref: 'In the style of Brian Eno — "Subterraneans" (David Bowie, Low)', artist: 'Brian Eno',
    tags: ['pad', 'ambient', '70s'], level: 2,
    blurb: 'A dark, slow two-note pad whose lower note drifts in pitch like an old tape.',
    how: 'Hold two keys on POLY: VCO 1 plays the upper note on a soft triangle and VCO 2 the lower on a sawtooth with its sub octave. A very slow LFO sine moves only VCO 2’s pitch, by a fraction of a semitone, so the interval slowly goes in and out of tune and the pad sounds worn. The filter is low and also drifts with the LFO, and a slow attack and long release let each chord fade in and out.',
    phrase: { bpm: 50, loop: true, steps: [[0, 50, 3.8], [0, 57, 3.8], [4, 46, 3.8], [4, 53, 3.8]] },
    steps: [
      { title: 'Two notes, two colours', module: 'osc', why: 'Two keys, two colours: on POLY each VCO (voltage-controlled oscillator) takes one note, and each gets a different wave.\n- KEYBOARD CONTROL POLY: VCO 1 plays the higher key, VCO 2 the lower.\n- VCO 1 SAWTOOTH 0, TRIANGLE 8: a soft, flute-like upper note. Swap it for the saw and the pad gets brighter and harder.\n- VCO 2 SAWTOOTH 7 and SUB OCTAVE 5: a buzzier lower note with a dark floor an octave below.\n- Listen for: hold two keys. A soft top over a fuller, buzzier bottom.',
        set: { 'pitch.kbdCtrl': 'poly', 'vco1.saw': 0, 'vco1.tri': 8, 'vco2.saw': 7, 'vco2.sub': 5 } },
      { title: 'A low filter', module: 'filter', why: 'The VCF (voltage-controlled filter) is set low to take the buzz off the sawtooth and keep the pad dark.\n- Fc 4 (about 280 Hz): Fc is the cutoff. Raise it and the pad starts to sound like strings.\n- Q 2 (20 %): Q is resonance. Just a little.\n- KEYBOARD CONTROL 5 (50 %): the cutoff follows the keys half way.\n- Filter DEPTH 0: no envelope on the filter, so chords do not brighten at the start.\n- Listen for: a dark, muted two-note pad.',
        set: { 'vcf.fc': 4, 'vcf.q': 2, 'vcf.kbd': 5, 'vcf.mod2Depth': 0 } },
      { title: 'A slow drift in pitch', module: 'mod', why: 'A very slow LFO (low-frequency oscillator) moves only VCO 2’s pitch, by a fraction of a semitone, so the interval slowly goes in and out of tune like worn tape.\n- VCO 2 LFO SINE, DEPTH 1.2 (12 %): how far the lower note drifts. A little sounds like worn tape; much more sounds seasick.\n- VCO 1 left DEPTH 0: VCO 1 stays steady, so the two notes pull apart and back.\n- LFO FREQUENCY 3 (0.24 Hz): about one cycle every four seconds. Faster turns it into an ordinary vibrato.\n- LFO DELAY 0: the drift runs all the time.\n- Listen for: hold two keys for a while. The interval slowly sours and comes back into tune.',
        set: { 'vco2.mod1Src': 'sine', 'vco2.mod1Depth': 1.2, 'vco1.mod1Depth': 0, 'lfo.rate': 3, 'lfo.delay': 0 } },
      { title: 'The filter drifts too', module: 'filter', why: 'The filter drifts with the same slow LFO, so the pad darkens and brightens along with the pitch drift.\n- Filter LFO SINE, DEPTH 1.5 (15 %): a gentle movement of the cutoff. More makes it an obvious wah.\n- Listen for: a slow change in brightness that rises and falls with the tuning drift.',
        set: { 'vcf.mod1Src': 'sine', 'vcf.mod1Depth': 1.5 } },
      { title: 'Fade in, fade out', module: 'amp', why: 'The ADSR (attack, decay, sustain, release envelope) gives the VCA (voltage-controlled amplifier) a slow rise and a long tail, so each chord fades in and dies away slowly.\n- VCA ADSR: the ADSR sets the loudness.\n- ATTACK 7.5 (900 ms): the slow fade-in of each chord.\n- DECAY 5 (190 ms), SUSTAIN 10 (100 %): full level while held.\n- RELEASE 7.5 (1.1 s): chords fade out slowly after the keys come up.\n- Listen for: chords swelling in from nothing and hanging after you let go.',
        set: { 'vca.mode': 'adsr', 'adsr.attack': 7.5, 'adsr.decay': 5, 'adsr.sustain': 10, 'adsr.release': 7.5 } },
    ],
    context: {
      'vco2.mod1Depth': 'In this sound: how far the lower note drifts. A little sounds like worn tape; much more sounds seasick.',
      'lfo.rate': 'In this sound: how slowly the drift and the filter move. Faster and it becomes an ordinary vibrato.',
      'pitch.kbdCtrl': 'In this sound: POLY, so two keys play two notes. On MONO both VCOs play the lower key.',
      'vco1.tri': 'In this sound: the soft upper note. Swap it for the sawtooth and the pad gets brighter and harder.',
      'vcf.fc': 'In this sound: keeps the pad dark. Raise it and it starts to sound like strings.',
      'adsr.attack': 'In this sound: the slow fade-in of each chord.',
    },
    tweaks: [
      { id: 'vco2.mod1Depth', try: 'Raise to 2.5', hear: 'The lower note wavers much further out of tune and back.' },
      { id: 'vco1.mod1Src', try: 'Set to S+H with VCO 1’s left depth at 1', hear: 'The upper note steps to slightly different pitches: a more broken, unsettled pad.' },
      { id: 'vcf.fc', try: 'Lower to 3', hear: 'A muffled pad, as if heard through a wall.' },
    ],
  },
  {
    id: 'duo-steel-swell', name: 'Steel Swell over a Drone', ref: 'In the style of Daniel Lanois — "The Maker" (Acadie)', artist: 'Daniel Lanois',
    tags: ['lead', 'ambient', 'steel'], level: 3,
    blurb: 'A pedal-steel style line that swells in and bends between notes over a steady low drone.',
    how: 'Hold a low key and play a line above it on POLY: VCO 2 keeps the drone on the lowest key while VCO 1 plays the upper note. A slow GLIDE makes VCO 1 bend into each new note rather than jump, the way a steel player slides the bar or pushes a pedal, and the drone does not move because its key is held. A slow ADSR attack gives the volume-pedal swell on each phrase. Overlap the upper notes slightly so VCO 1 bends straight from one to the next.',
    phrase: { bpm: 60, loop: true, steps: [[0, 45, 3.7], [0, 64, 2.1], [2, 66, 1.7], [4, 45, 3.7], [4, 69, 2.1], [6, 68, 1.7]] },
    steps: [
      { title: 'A line over a drone', module: 'osc', why: 'POLY splits the keys: VCO 2 (voltage-controlled oscillator 2) holds a low drone on the lowest key while VCO 1 plays a line above it.\n- KEYBOARD CONTROL POLY: VCO 2 takes the lowest key held, VCO 1 the highest. On MONO the whole sound follows the lowest key and the line disappears.\n- VCO 1 SAWTOOTH 6 and TRIANGLE 5: the saw gives edge, the triangle a rounder, singing top.\n- VCO 2 SAWTOOTH 5 and SUB OCTAVE 4: the drone, with depth an octave below.\n- Listen for: hold a low key, then play notes above it. The drone stays put while the upper line moves.',
        set: { 'pitch.kbdCtrl': 'poly', 'vco1.saw': 6, 'vco1.tri': 5, 'vco2.saw': 5, 'vco2.sub': 4 } },
      { title: 'A warm filter', module: 'filter', why: 'The VCF (voltage-controlled filter) is set warm and left still, so the tone stays even while the volume swells.\n- Fc 4.8 (about 490 Hz), Q 1.5 (15 %): Fc is the cutoff, Q the resonance. Warm, with a slight edge.\n- KEYBOARD CONTROL 6 (60 %): the cutoff follows the keys part way, so the upper line stays brighter than the drone.\n- Filter DEPTH 0: no envelope on the filter, so notes do not brighten at the start.\n- Listen for: a smooth, rounded tone.',
        set: { 'vcf.fc': 4.8, 'vcf.q': 1.5, 'vcf.kbd': 6, 'vcf.mod2Depth': 0 } },
      { title: 'Bends from GLIDE', module: 'glide', why: 'GLIDE makes VCO 1 bend into each new note, the way a steel player slides the bar. The drone does not move because its key is held.\n- GLIDE 6.5 (330 ms): about a third of a second. Lower and the line steps like a keyboard; higher and every bend is slower.\n- Listen for: overlap the upper notes slightly so VCO 1 bends straight from one to the next.',
        set: { 'pitch.glide': 6.5 } },
      { title: 'The volume swell', module: 'amp', why: 'The ADSR (attack, decay, sustain, release envelope) gives the VCA (voltage-controlled amplifier) a slow rise, the volume-pedal swell of a pedal steel.\n- VCA ADSR: the ADSR sets the loudness.\n- ATTACK 7.5 (900 ms): nearly a second of swell at the start of each phrase. At 0 the notes start with a hard edge.\n- DECAY 5, SUSTAIN 10 (100 %): full level while keys are held.\n- RELEASE 7.5 (1.1 s): the sound rings on after the keys are let go.\n- VOLUME 8.5 (85 %): a little up, because each phrase starts quietly.\n- Listen for: each phrase fading in. Keep the drone key held and the line stays at full level.',
        set: { 'vca.mode': 'adsr', 'adsr.attack': 7.5, 'adsr.decay': 5, 'adsr.sustain': 10, 'adsr.release': 7.5, 'out.volume': 8.5 } },
      { title: 'A slight shimmer', module: 'lfo', why: 'A very small, late vibrato on VCO 1 only, so long upper notes move a little while the drone stays still.\n- VCO 1 LFO SINE, DEPTH 0.8 (8 %): a slight shimmer from the LFO (low-frequency oscillator). Keep it small; a steel is held steady.\n- VCO 2 left DEPTH 0: the drone stays still.\n- LFO FREQUENCY 5.8 (1.7 Hz): a slow, gentle movement.\n- LFO DELAY 3 (1.5 s): it only fades in on notes held for a second or more.\n- Listen for: long upper notes gaining a faint waver while the drone underneath stays steady.',
        set: { 'vco1.mod1Src': 'sine', 'vco1.mod1Depth': 0.8, 'vco2.mod1Depth': 0, 'lfo.rate': 5.8, 'lfo.delay': 3 } },
    ],
    context: {
      'pitch.glide': 'In this sound: the bend between notes. Lower and the line steps like a keyboard; higher and every bend is slower.',
      'pitch.kbdCtrl': 'In this sound: POLY is what keeps the drone under the line. On MONO the whole sound follows the lowest key and the line disappears.',
      'adsr.attack': 'In this sound: the swell at the start of each phrase. At 0 the notes start with a hard edge and it no longer sounds like a steel.',
      'adsr.release': 'In this sound: how long the sound rings after the keys are let go.',
      'vco2.sub': 'In this sound: the depth of the drone.',
      'vco1.mod1Depth': 'In this sound: a small movement on long upper notes. Keep it small; a steel is held steady.',
    },
    tweaks: [
      { id: 'pitch.glide', try: 'Raise to 7.5', hear: 'Slow bends that take a moment to arrive.' },
      { id: 'adsr.attack', try: 'Raise to 8.5', hear: 'Each phrase fades in more slowly, almost from nothing.' },
      { id: 'vco1.tri', try: 'Raise to 8 and SAWTOOTH to 3', hear: 'A softer, rounder upper line.' },
    ],
  },
];
