// More sounds for the EMS VCS3 library. Same Preset shape as the ones in ../ems-vcs3.js (see CONTRACT.md → Preset).
// Pins are cables [row jack, column jack]; the manual names a pin by its column letter and row number (B12 = row 12 → column B).

export default [
  {
    id: 'vcs3-clangs', name: 'Ring-Modulated Clangs', ref: 'From the EMS manual — the reverberation unit', artist: 'EMS',
    tags: ['perc', 'ring mod', 'manual'], level: 3,
    blurb: 'Two oscillators ring-modulated, chopped by the repeating envelope and thrown into the spring reverb.',
    how: 'The manual’s reverb example: E2 F4 D13 G12 B14 I15 J16 (the manual prints the envelope pin as B13; it has to be D13). The ring modulator gives a metallic clang, the envelope shaper strikes it over and over, and the spring reverb catches every strike. The joystick retunes the two oscillators, which changes the clang completely. Row 14 also goes to channel 2 here, so it plays on both sides.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 4]] },
    steps: [
      { title: 'Ramp times triangle', module: 'util',
        why: 'Oscillator 1’s ramp into ring modulator input A, Oscillator 2’s triangle into input B.\n- Pins E2 and F4.\n- Oscillator 1 FREQUENCY 6.3 (370 Hz), ramp LEVEL 6.\n- Oscillator 2 FREQUENCY 6.75 (560 Hz), triangle LEVEL 6.\n- Ring modulator LEVEL 7.\n- Nothing is heard yet: row 13 is not pinned to an output.',
        set: { 'osc1.freq': 6.3, 'osc1.ramp': 6, 'osc2.freq': 6.75, 'osc2.tri': 6, 'ring.level': 7 }, cables: [['r.osc1ramp', 'c.ringA'], ['r.osc2tri', 'c.ringB']] },
      { title: 'Strike it with the envelope', module: 'env',
        why: 'The ring modulator goes into the envelope shaper (D13). The envelope repeats on its own, so the clang is struck again and again.\n- Pin D13.\n- ATTACK 0, ON 0, DECAY 5 (0.2 s), OFF 2.5 (0.13 s): short strikes, about three a second.\n- SIGNAL LEVEL 8.\n- Still not heard: the shaped signal goes to the reverb next.',
        set: { 'env.attack': 0, 'env.on': 0, 'env.decay': 5, 'env.off': 2.5, 'env.sigLevel': 8 }, cables: [['r.ring', 'c.env']] },
      { title: 'Through the spring reverb', module: 'fx',
        why: 'The shaped signal (row 12) into the reverb (G12), and the reverb (row 14) to both outputs.\n- Pins G12, B14 and C14.\n- Reverb MIX 5, LEVEL 9.\n- Listen for: metallic strikes ringing on into a twangy spring echo.',
        set: { 'rev.mix': 5, 'rev.level': 9 }, cables: [['r.envsig', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'The joystick changes the clang', module: 'mod',
        why: 'The joystick’s horizontal moves Oscillator 1 (I15), its vertical Oscillator 2 (J16).\n- Pins I15 and J16.\n- RANGE 3 on both.\n- Try: move the stick while it plays. Each position gives a different metal.',
        set: { 'joy.rangeX': 3, 'joy.rangeY': 3 }, cables: [['r.joyx', 'c.osc1'], ['r.joyy', 'c.osc2']] },
    ],
    context: {
      'env.decay': 'In this sound: the length of each strike. Longer strikes blur together in the reverb.',
      'env.off': 'In this sound: the gap between strikes.',
      'rev.mix': 'In this sound: how much spring is in the result. Towards 10 the strikes turn into a wash.',
      'osc2.freq': 'In this sound: the ratio to Oscillator 1 decides the metal. Simple ratios sound more musical; odd ones clang.',
    },
    tweaks: [
      { id: 'joy.x', try: 'Drag the joystick in circles', hear: 'The clang slides through different metallic tones.' },
      { id: 'env.off', try: 'Turn OFF to 10 and play keys', hear: 'One strike per key, each left ringing in the spring.' },
    ],
  },
  {
    id: 'vcs3-filter-whistle', name: 'Filter Whistle Lead', ref: 'Classic technique: the filter played as a sine oscillator', artist: 'Classic technique',
    tags: ['lead', 'filter', 'sine'], level: 2,
    blurb: 'The purest tone in the VCS3: the filter whistling on its own, played from the keys.',
    how: 'With RESPONSE past 6 the filter makes its own sine wave, cleaner than any of the oscillators. Pinning the keyboard voltage (row 8) into the filter frequency column N plays it, and the envelope shaper gives each note a soft start and end. The filter is more sensitive than the oscillators, so INPUT LEVEL CHANNEL 1 is turned down to about 3 to keep it in tune.',
    phrase: { bpm: 84, loop: true, steps: [[0, 67, 1.5], [1.5, 69, 0.5], [2, 72, 2], [4, 71, 1], [5, 67, 1], [6, 64, 2]] },
    steps: [
      { title: 'Make the filter whistle', module: 'filter',
        why: 'Nothing goes into the filter: RESPONSE 8 makes it oscillate on its own.\n- Filter FREQUENCY 5.2 (about middle C), RESPONSE 8, LEVEL 5.\n- Not heard yet: the filter’s row is not pinned.',
        set: { 'vcf.freq': 5.2, 'vcf.response': 8, 'vcf.level': 5 } },
      { title: 'Shape it and send it out', module: 'env',
        why: 'The filter (row 10) into the envelope shaper (D10), and the shaped signal to both outputs.\n- Pins D10, B12 and C12.\n- ATTACK 2.5, ON 0, DECAY 5.5, OFF 10: a soft start, a gentle fade after each key, and no repeats.\n- SIGNAL LEVEL 7.\n- Listen for: a pure, flute-like tone when you press a key, all at one pitch.',
        set: { 'env.attack': 2.5, 'env.on': 0, 'env.decay': 5.5, 'env.off': 10, 'env.sigLevel': 7 }, cables: [['r.vcf', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2']] },
      { title: 'Play it from the keys', module: 'util',
        why: 'The keyboard voltage (row 8) into the filter frequency (N8).\n- Pin N8.\n- INPUT LEVEL CHANNEL 1 at 3.1: the filter moves an octave for every 0.2 V, more than the oscillators, so it needs less voltage to stay in tune.\n- Listen for: a clean melody. If it drifts out of tune going up, nudge INPUT LEVEL CHANNEL 1.',
        set: { 'in.ch1': 3.1 }, cables: [['r.in1', 'c.cutoff']] },
    ],
    context: {
      'vcf.response': 'In this sound: past 6.6 the filter oscillates. Below about 6 it stops, and with nothing pinned into it there is silence.',
      'in.ch1': 'In this sound: the tuning of the keyboard for the filter. 3.1 is about one semitone per key.',
      'vcf.freq': 'In this sound: where the keyboard starts. Turn it to transpose.',
      'env.attack': 'In this sound: the soft start of each note.',
    },
    tweaks: [
      { id: 'vcf.response', try: 'Bring RESPONSE down to 6.8', hear: 'The tone gets weaker: the filter is only just oscillating.' },
      { id: 'in.ch1', try: 'Set INPUT LEVEL CHANNEL 1 to 1.5', hear: 'Quarter-tone steps: every key is half a semitone apart.' },
    ],
  },
  {
    id: 'vcs3-machine-throb', name: 'Machine Throb', ref: 'In the style of Pink Floyd — "Welcome to the Machine"', artist: 'Pink Floyd',
    tags: ['bass', 'drone', '70s'], level: 2,
    blurb: 'A low, filtered drone that pulses on and off through the output amplifiers.',
    how: 'Two low oscillators, almost in tune, go through the filter and the reverb. Oscillator 3’s square, at a little under twice a second, moves both output levels, so the drone throbs like a machine. The keyboard is pinned to both oscillators so you can move the drone around.',
    phrase: { bpm: 70, loop: true, steps: [[0, 40, 4], [4, 43, 2], [6, 38, 2]] },
    steps: [
      { title: 'Two low oscillators through the filter', module: 'osc',
        why: 'Oscillator 1’s ramp and Oscillator 2’s square into the filter, both following the keys.\n- Pins H2, H3, I8 and J8.\n- Oscillator 1 FREQUENCY 6, ramp LEVEL 6; Oscillator 2 FREQUENCY 6.02, square LEVEL 5: almost in tune, so they beat slowly. With the keyboard pinned, the dial sets the pitch of middle C; the riff plays low E, about 82 Hz.\n- INPUT LEVEL CHANNEL 1 at 5.\n- Filter FREQUENCY 5 (220 Hz), RESPONSE 5, LEVEL 7: dark, with a ringing edge.',
        set: { 'osc1.freq': 6, 'osc1.ramp': 6, 'osc2.freq': 6.02, 'osc2.square': 5, 'in.ch1': 5, 'vcf.freq': 5, 'vcf.response': 5, 'vcf.level': 7 },
        cables: [['r.osc1ramp', 'c.vcf'], ['r.osc2sq', 'c.vcf'], ['r.in1', 'c.osc1'], ['r.in1', 'c.osc2']] },
      { title: 'Into the reverb and out', module: 'fx',
        why: 'The filter into the reverb (G10), and the reverb to both outputs (B14, C14).\n- Reverb MIX 4, LEVEL 8: mostly dry, with a spring tail.\n- Listen for: a dark, steady drone.',
        set: { 'rev.mix': 4, 'rev.level': 8 }, cables: [['r.vcf', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'Oscillator 3 throbs the outputs', module: 'out',
        why: 'Oscillator 3’s square into both output level columns (O5, P5). The amplifiers open and shut with it.\n- Oscillator 3 FREQUENCY 4.5 (1.6 Hz), square LEVEL 6.\n- OUTPUT LEVEL 6.5 on both: set so the square nearly shuts the channels on its low half.\n- Listen for: the drone pulsing, with the reverb filling the gaps.',
        set: { 'osc3.freq': 4.5, 'osc3.square': 6, 'out1.level': 6.5, 'out2.level': 6.5 }, cables: [['r.osc3sq', 'c.lvl1'], ['r.osc3sq', 'c.lvl2']] },
    ],
    context: {
      'osc3.freq': 'In this sound: the speed of the throb.',
      'out1.level': 'In this sound: lower and the gaps go silent; higher and the throb gets shallower.',
      'vcf.freq': 'In this sound: how dark the drone is.',
      'osc2.freq': 'In this sound: tuned a hair above Oscillator 1, so the two beat slowly.',
    },
    tweaks: [
      { id: 'osc3.shape', try: 'Turn Oscillator 3 SHAPE to 2', hear: 'Short pulses of sound with longer gaps between them.' },
      { id: 'vcf.response', try: 'Raise RESPONSE to 6', hear: 'A whistling ring on top of the drone.' },
    ],
  },
  {
    id: 'vcs3-organ-chop', name: 'Pulsing Organ Filter', ref: 'In the style of The Who — "Won’t Get Fooled Again"', artist: 'The Who',
    tags: ['keys', 'filter', '70s'], level: 3,
    blurb: 'An organ-like tone whose filter opens and shuts in fast, even pulses.',
    how: 'On the record an organ was fed into a VCS3 and its filter pulsed by the envelope shaper. There is no outside input here, so two oscillators an octave apart stand in for the organ. The repeating trapezoid is pinned to the filter frequency (N11): it goes negative while the envelope is up, and a falling voltage raises the filter, so every cycle is a quick bright burst.',
    phrase: { bpm: 120, loop: true, steps: [[0, 57, 2], [2, 55, 1], [3, 57, 1], [4, 52, 2], [6, 55, 2]] },
    steps: [
      { title: 'An organ from two oscillators', module: 'osc',
        why: 'Oscillator 1’s sine an octave above Oscillator 2’s square, both into the filter and both following the keys.\n- Pins H1, H3, I8 and J8.\n- Oscillator 1 FREQUENCY 6.67 (an octave above middle C), sine LEVEL 5.\n- Oscillator 2 FREQUENCY 6, square LEVEL 5.\n- INPUT LEVEL CHANNEL 1 at 5.',
        set: { 'osc1.freq': 6.67, 'osc1.sine': 5, 'osc2.freq': 6, 'osc2.square': 5, 'in.ch1': 5 },
        cables: [['r.osc1sine', 'c.vcf'], ['r.osc2sq', 'c.vcf'], ['r.in1', 'c.osc1'], ['r.in1', 'c.osc2']] },
      { title: 'A dark filter to both outputs', module: 'filter',
        why: 'The filter (row 10) to both outputs.\n- Pins B10 and C10.\n- Filter FREQUENCY 5.5 (330 Hz), RESPONSE 4.5, LEVEL 8: muffled, with a little ring.\n- Listen for: a dull organ tone.',
        set: { 'vcf.freq': 5.5, 'vcf.response': 4.5, 'vcf.level': 8 }, cables: [['r.vcf', 'c.out1'], ['r.vcf', 'c.out2']] },
      { title: 'The trapezoid pulses the filter', module: 'env',
        why: 'The envelope’s own voltage, row 11, into the filter frequency (N11). The envelope repeats on its own about five times a second.\n- Pin N11.\n- TRAPEZOID LEVEL 4: the knob marked 11. Turning it up both deepens the pulse and closes the filter further between pulses.\n- ATTACK 0, ON 1, DECAY 4, OFF 2: a fast rise, a short hold, a quick fall and a short rest.\n- Listen for: the organ chopped into even, bright pulses.',
        set: { 'env.trapLevel': 4, 'env.attack': 0, 'env.on': 1, 'env.decay': 4, 'env.off': 2 }, cables: [['r.trap', 'c.cutoff']] },
    ],
    context: {
      'env.off': 'In this sound: the gap between pulses, and so their speed.',
      'env.trapLevel': 'In this sound: how far each pulse opens the filter.',
      'vcf.freq': 'In this sound: where the pulses start from. Higher gives brighter, shallower pulses.',
      'vcf.response': 'In this sound: a little ring on each pulse. Higher gives a squelch.',
    },
    tweaks: [
      { id: 'env.decay', try: 'Raise DECAY to 5.5', hear: 'Each pulse fades more slowly, so they run into each other.' },
      { id: 'vcf.response', try: 'Raise RESPONSE to 6', hear: 'Each pulse squelches and whistles.' },
    ],
  },
  {
    id: 'vcs3-silver-swoop', name: 'Space Swoops', ref: 'In the style of Hawkwind — "Silver Machine"', artist: 'Hawkwind',
    tags: ['fx', 'space rock', '70s'], level: 2,
    blurb: 'Two oscillators swooping up and down together, filtered and drenched in spring reverb.',
    how: 'Oscillator 3’s slow triangle is pinned to both audio oscillators’ frequency columns (I6, J6), so they glide up and down over more than an octave every few seconds. The filter takes the edge off and the reverb smears the swoops into a space-rock whoosh.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 4]] },
    steps: [
      { title: 'Two oscillators through the filter', module: 'osc',
        why: 'Oscillator 1’s ramp and Oscillator 2’s square into the filter.\n- Pins H2 and H3.\n- Oscillator 1 FREQUENCY 5.5 (156 Hz), ramp LEVEL 6; Oscillator 2 FREQUENCY 5.52, square LEVEL 5.\n- Filter FREQUENCY 6.5 (700 Hz), RESPONSE 3, LEVEL 8.',
        set: { 'osc1.freq': 5.5, 'osc1.ramp': 6, 'osc2.freq': 5.52, 'osc2.square': 5, 'vcf.freq': 6.5, 'vcf.response': 3, 'vcf.level': 8 },
        cables: [['r.osc1ramp', 'c.vcf'], ['r.osc2sq', 'c.vcf']] },
      { title: 'Into the reverb', module: 'fx',
        why: 'The filter into the reverb (G10), and the reverb to both outputs.\n- Pins G10, B14 and C14.\n- Reverb MIX 6, LEVEL 8: more spring than dry.\n- Listen for: a buzzing drone in a metallic space.',
        set: { 'rev.mix': 6, 'rev.level': 8 }, cables: [['r.vcf', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'Oscillator 3 makes it swoop', module: 'lfo',
        why: 'Oscillator 3’s triangle into both oscillators’ frequency columns, so they move together.\n- Pins I6 and J6.\n- Oscillator 3 FREQUENCY 3 (0.35 Hz, about three seconds a cycle), triangle LEVEL 6: more than an octave each way.\n- Listen for: the drone swooping up and down like a passing spaceship.',
        set: { 'osc3.freq': 3, 'osc3.tri': 6 }, cables: [['r.osc3tri', 'c.osc1'], ['r.osc3tri', 'c.osc2']] },
    ],
    context: {
      'osc3.tri': 'In this sound: how far the swoops go.',
      'osc3.freq': 'In this sound: how fast the swoops are.',
      'rev.mix': 'In this sound: how much the swoops are smeared.',
      'vcf.freq': 'In this sound: how bright the swoops are.',
    },
    tweaks: [
      { id: 'osc3.freq', try: 'Turn Oscillator 3 up to 5.5', hear: 'A fast warble instead of a slow swoop.' },
      { id: 'osc3.shape', try: 'Turn Oscillator 3 SHAPE to 10', hear: 'A slow fall then a sudden jump back: a falling siren.' },
    ],
  },
  {
    id: 'vcs3-eno-treatment', name: 'Chattering Treatment', ref: 'In the style of Roxy Music — "Ladytron"', artist: 'Brian Eno',
    tags: ['fx', 'experimental', '70s'], level: 3,
    blurb: 'Three oscillators modulating each other in a ring, so the pitch chatters and never quite repeats.',
    how: 'Oscillator 2 wobbles Oscillator 1 (I4), Oscillator 3 wobbles Oscillator 2 (J6), and Oscillator 1, at audio rate, shakes Oscillator 3 (K1). Each depends on the next, so the pattern drifts instead of looping, the kind of circular modulation the manual suggests for pseudo-random patterns. The reverb places it in a room.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 4]] },
    steps: [
      { title: 'Oscillator 1 into the reverb', module: 'osc',
        why: 'Oscillator 1’s sine into the reverb, and the reverb to both outputs.\n- Pins G1, B14 and C14.\n- Oscillator 1 FREQUENCY 6.5 (440 Hz), sine LEVEL 6.\n- Reverb MIX 5, LEVEL 8.\n- Listen for: a plain whistle in a spring room.',
        set: { 'osc1.freq': 6.5, 'osc1.sine': 6, 'rev.mix': 5, 'rev.level': 8 }, cables: [['r.osc1sine', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'Oscillator 2 wobbles it', module: 'mod',
        why: 'Oscillator 2’s triangle into Oscillator 1’s frequency (I4).\n- Oscillator 2 FREQUENCY 2.5 (7 Hz), triangle LEVEL 4: a wide, fast warble.\n- Listen for: a bird-like trill.',
        set: { 'osc2.freq': 2.5, 'osc2.tri': 4 }, cables: [['r.osc2tri', 'c.osc1']] },
      { title: 'Close the loop', module: 'lfo',
        why: 'Oscillator 3 changes Oscillator 2’s speed (J6), and Oscillator 1 shakes Oscillator 3 (K1).\n- Pins J6 and K1.\n- Oscillator 3 FREQUENCY 4 (1 Hz), triangle LEVEL 5.\n- Listen for: the trill speeding up and slowing down, chattering and squiggling in a pattern that keeps changing.',
        set: { 'osc3.freq': 4, 'osc3.tri': 5 }, cables: [['r.osc3tri', 'c.osc2'], ['r.osc1sine', 'c.osc3']] },
    ],
    context: {
      'osc2.tri': 'In this sound: how wide the warble on Oscillator 1 is.',
      'osc3.tri': 'In this sound: how much the warble speeds up and slows down.',
      'osc1.sine': 'In this sound: also how hard Oscillator 1 shakes Oscillator 3, because the row goes to both the reverb and column K.',
      'osc2.freq': 'In this sound: the basic speed of the warble.',
    },
    tweaks: [
      { id: 'osc2.tri', try: 'Turn Oscillator 2 triangle LEVEL to 7', hear: 'Wild leaps of pitch instead of a trill.' },
      { id: 'osc3.freq', try: 'Turn Oscillator 3 down to 2', hear: 'The chatter slows into long, lazy curves.' },
    ],
  },
  {
    id: 'vcs3-run-sequence', name: 'Running Sequence', ref: 'In the style of Pink Floyd — "On the Run"', artist: 'Pink Floyd',
    tags: ['seq', 'pluck', '70s'], level: 2,
    blurb: 'A fast, filtered pulse line where every note is a short, bright blip.',
    how: 'On the record the line came from the sequencer of a Synthi AKS, the VCS3’s briefcase sibling. Here the keyboard plays it: Oscillator 2’s pulse goes through the filter, and the trapezoid (N11) opens the filter for each note while the envelope shaper cuts it short.',
    phrase: { bpm: 165, loop: true, steps: [[0, 52, 0.22], [0.25, 55, 0.22], [0.5, 59, 0.22], [0.75, 55, 0.22], [1, 62, 0.22], [1.25, 59, 0.22], [1.5, 57, 0.22], [1.75, 59, 0.22]] },
    steps: [
      { title: 'A pulse wave from the keys', module: 'osc',
        why: 'Oscillator 2’s square into the filter, following the keyboard.\n- Pins H3 and J8.\n- Oscillator 2 FREQUENCY 6 (middle C on the keys), square LEVEL 6, SHAPE 3: a narrower pulse, more nasal than a square.\n- INPUT LEVEL CHANNEL 1 at 5.',
        set: { 'osc2.freq': 6, 'osc2.square': 6, 'osc2.shape': 3, 'in.ch1': 5 }, cables: [['r.osc2sq', 'c.vcf'], ['r.in1', 'c.osc2']] },
      { title: 'Short notes through the envelope', module: 'env',
        why: 'The filter into the envelope shaper (D10) and on to both outputs (B12, C12). The envelope waits for each key.\n- Filter FREQUENCY 5.5 (330 Hz), RESPONSE 5.5, LEVEL 8.\n- ATTACK 0, ON 0, DECAY 3.5 (60 ms), OFF 10.\n- SIGNAL LEVEL 8.\n- Listen for: short, dark blips.',
        set: { 'vcf.freq': 5.5, 'vcf.response': 5.5, 'vcf.level': 8, 'env.attack': 0, 'env.on': 0, 'env.decay': 3.5, 'env.off': 10, 'env.sigLevel': 8 },
        cables: [['r.vcf', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2']] },
      { title: 'The trapezoid opens the filter', module: 'filter',
        why: 'The trapezoid into the filter frequency (N11), so each note starts bright and closes as the envelope falls.\n- Pin N11.\n- TRAPEZOID LEVEL 3.5.\n- Listen for: each blip snapping open, the classic sequencer sound.',
        set: { 'env.trapLevel': 3.5 }, cables: [['r.trap', 'c.cutoff']] },
    ],
    context: {
      'env.decay': 'In this sound: the length of each blip.',
      'env.trapLevel': 'In this sound: how bright each note gets.',
      'vcf.response': 'In this sound: the squelch on each note.',
      'osc2.shape': 'In this sound: the width of the pulse. 5 is a hollow square; further from 5 is thinner.',
    },
    tweaks: [
      { id: 'vcf.response', try: 'Raise RESPONSE to 6.3', hear: 'Each note pings and whistles as the filter opens.' },
      { id: 'env.decay', try: 'Raise DECAY to 5', hear: 'Longer notes that run into each other.' },
    ],
  },
  {
    id: 'vcs3-oxygene-wind', name: 'Wind and Waves', ref: 'In the style of Jean-Michel Jarre — Oxygène', artist: 'Jean-Michel Jarre',
    tags: ['fx', 'noise', '70s'], level: 1,
    blurb: 'Noise through a whistling filter that rises and falls, deep in the spring reverb.',
    how: 'Noise into a filter turned up until it nearly oscillates, so it howls at its frequency. Oscillator 3 slowly sweeps that frequency up and down, which is the rise and fall of the wind, and the reverb gives it distance. The joystick’s vertical axis is also pinned to the filter, so you can push the gusts higher by hand.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 4]] },
    steps: [
      { title: 'Noise through a howling filter', module: 'filter',
        why: 'Noise into the filter.\n- Pin H7.\n- Noise LEVEL 8, COLOUR 4: slightly dark.\n- Filter FREQUENCY 6.5 (700 Hz), RESPONSE 6.3: just short of whistling on its own, so the noise howls.\n- Filter LEVEL 7.',
        set: { 'noise.level': 8, 'noise.colour': 4, 'vcf.freq': 6.5, 'vcf.response': 6.3, 'vcf.level': 7 }, cables: [['r.noise', 'c.vcf']] },
      { title: 'Into the reverb and out', module: 'fx',
        why: 'The filter into the reverb, and the reverb to both outputs.\n- Pins G10, B14 and C14.\n- Reverb MIX 6, LEVEL 9.\n- Listen for: a steady wind in a large space.',
        set: { 'rev.mix': 6, 'rev.level': 9 }, cables: [['r.vcf', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'Gusts from Oscillator 3', module: 'lfo',
        why: 'Oscillator 3 sweeps the filter (N6), and the joystick can push it further (N16).\n- Pins N6 and N16.\n- Oscillator 3 FREQUENCY 3 (0.35 Hz), triangle LEVEL 5.\n- Vertical RANGE 5.\n- Listen for: the wind rising and falling every few seconds. Pull the stick down for higher gusts.',
        set: { 'osc3.freq': 3, 'osc3.tri': 5, 'joy.rangeY': 5 }, cables: [['r.osc3tri', 'c.cutoff'], ['r.joyy', 'c.cutoff']] },
    ],
    context: {
      'vcf.response': 'In this sound: how much the wind howls. Too high and the filter whistles on its own.',
      'osc3.freq': 'In this sound: the speed of the gusts.',
      'noise.colour': 'In this sound: darker is a rumble, lighter is a hiss.',
      'rev.mix': 'In this sound: how far away the wind sounds.',
    },
    tweaks: [
      { id: 'joy.y', try: 'Pull the joystick down and let it back slowly', hear: 'You push the wind higher and let it fall by hand.' },
      { id: 'vcf.response', try: 'Lower RESPONSE to 3', hear: 'Soft surf instead of a howl.' },
    ],
  },
  {
    id: 'vcs3-staircase', name: 'Staircase Pattern', ref: 'Classic technique: summed square waves on one oscillator', artist: 'Classic technique',
    tags: ['seq', 'pattern', 'modulation'], level: 3,
    blurb: 'Two square waves at different speeds add up to a repeating four-note pattern, chopped by the envelope.',
    how: 'Pins in one column add together. Oscillator 2’s square (I3) jumps Oscillator 1 by a fifth, and Oscillator 3’s slower square (I5) jumps it by an octave, so between them the pitch steps round four notes. The levels of the two squares set the intervals. The repeating envelope chops it into blips, and the keyboard (I8) moves the whole pattern.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 2], [2, 55, 2]] },
    steps: [
      { title: 'Blips from the envelope', module: 'env',
        why: 'Oscillator 1’s sine through the repeating envelope to both outputs, following the keys.\n- Pins D1, B12, C12 and I8.\n- Oscillator 1 FREQUENCY 6, sine LEVEL 6.\n- ATTACK 0, ON 0, DECAY 3, OFF 1.5: a quick blip, about ten a second.\n- SIGNAL LEVEL 8. INPUT LEVEL CHANNEL 1 at 5.\n- Listen for: a fast stream of blips at one pitch.',
        set: { 'osc1.freq': 6, 'osc1.sine': 6, 'env.attack': 0, 'env.on': 0, 'env.decay': 3, 'env.off': 1.5, 'env.sigLevel': 8, 'in.ch1': 5 },
        cables: [['r.osc1sine', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2'], ['r.in1', 'c.osc1']] },
      { title: 'A fifth from Oscillator 2', module: 'mod',
        why: 'Oscillator 2’s square into Oscillator 1’s frequency (I3).\n- Oscillator 2 FREQUENCY 2 (4.4 Hz), square LEVEL 2.4: just enough voltage to jump a fifth.\n- Listen for: the blips trilling between two notes a fifth apart.',
        set: { 'osc2.freq': 2, 'osc2.square': 2.4 }, cables: [['r.osc2sq', 'c.osc1']] },
      { title: 'An octave from Oscillator 3', module: 'lfo',
        why: 'Oscillator 3’s square, slower, into the same column (I5). It adds to Oscillator 2’s jump.\n- Oscillator 3 FREQUENCY 4.5 (1.6 Hz), square LEVEL 3.2: an octave.\n- Listen for: the trill jumping up and down an octave, a four-note pattern.',
        set: { 'osc3.freq': 4.5, 'osc3.square': 3.2 }, cables: [['r.osc3sq', 'c.osc1']] },
    ],
    context: {
      'osc2.square': 'In this sound: the size of the small jump. 2.4 is about a fifth.',
      'osc3.square': 'In this sound: the size of the big jump. 3.2 is about an octave.',
      'osc2.freq': 'In this sound: the speed of the small jump.',
      'osc3.freq': 'In this sound: the speed of the big jump.',
    },
    tweaks: [
      { id: 'osc2.square', try: 'Set Oscillator 2 square LEVEL to 2', hear: 'The small jump shrinks to about a fourth.' },
      { id: 'osc3.shape', try: 'Turn Oscillator 3 SHAPE to 7', hear: 'The upper octave lasts longer than the lower one, so the pattern turns lopsided.' },
    ],
  },
  {
    id: 'vcs3-fm-bass', name: 'Growling FM Bass', ref: 'Classic technique: one oscillator shaking another’s pitch', artist: 'Classic technique',
    tags: ['bass', 'fm', 'modulation'], level: 2,
    blurb: 'A low oscillator whose pitch is shaken at audio rate by another, giving a metallic growl.',
    how: 'Oscillator 2’s triangle, at the same pitch as Oscillator 1, goes into Oscillator 1’s frequency column (I4). At audio rate that is frequency modulation: you hear new overtones rather than a wobble. Both oscillators follow the keys, so the growl stays the same on every note. The envelope shaper turns it into separate notes.',
    phrase: { bpm: 100, loop: true, steps: [[0, 36, 0.7], [1, 36, 0.4], [1.5, 39, 0.4], [2, 43, 0.7], [3, 41, 0.7]] },
    steps: [
      { title: 'A bass note through the envelope', module: 'osc',
        why: 'Oscillator 1’s ramp through the envelope shaper to both outputs, following the keys.\n- Pins D2, B12, C12 and I8.\n- Oscillator 1 FREQUENCY 6, ramp LEVEL 5: with the keyboard pinned the dial sets middle C, and the riff plays two octaves below it. INPUT LEVEL CHANNEL 1 at 5.\n- ATTACK 0, ON 0, DECAY 4.5 (0.15 s), OFF 10: the note holds while the key is down, then stops quickly.\n- SIGNAL LEVEL 7.',
        set: { 'osc1.freq': 6, 'osc1.ramp': 5, 'in.ch1': 5, 'env.attack': 0, 'env.on': 0, 'env.decay': 4.5, 'env.off': 10, 'env.sigLevel': 7 },
        cables: [['r.osc1ramp', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2'], ['r.in1', 'c.osc1']] },
      { title: 'Oscillator 2 shakes its pitch', module: 'mod',
        why: 'Oscillator 2’s triangle into Oscillator 1’s frequency (I4), with Oscillator 2 also following the keys (J8).\n- Oscillator 2 FREQUENCY 6, the same as Oscillator 1, triangle LEVEL 3.5.\n- Listen for: a harder, metallic growl on every note. Turn the triangle LEVEL up for more.',
        set: { 'osc2.freq': 6, 'osc2.tri': 3.5 }, cables: [['r.osc2tri', 'c.osc1'], ['r.in1', 'c.osc2']] },
    ],
    context: {
      'osc2.tri': 'In this sound: how much growl. Higher gives more overtones.',
      'osc2.freq': 'In this sound: the same as Oscillator 1, so the growl is harmonic. Move it and the tone turns clangy.',
      'env.decay': 'In this sound: how quickly each note stops after you let go.',
      'osc1.freq': 'In this sound: the tuning of the whole keyboard. Keep Oscillator 2 at the same setting for a harmonic growl.',
    },
    tweaks: [
      { id: 'osc2.freq', try: 'Move Oscillator 2 to 6.67', hear: 'An octave up: a brighter, more hollow growl.' },
      { id: 'osc2.tri', try: 'Turn Oscillator 2 triangle LEVEL to 6', hear: 'A harsh, buzzing metallic tone.' },
    ],
  },
  {
    id: 'vcs3-trap-pluck', name: 'Trapezoid Pluck', ref: 'Classic technique: the envelope’s own voltage sweeping the filter', artist: 'Classic technique',
    tags: ['pluck', 'filter', 'bass'], level: 2,
    blurb: 'A pulse bass whose filter snaps open on each key and closes as the note fades.',
    how: 'The trapezoid on row 11 is the envelope as a voltage. It goes negative while the envelope is up, and on the VCS3 a falling voltage raises the filter, so pinning it to column N opens the filter on each note. The same envelope also shapes the loudness through column D. Its resting voltage pushes the filter down, which is why the filter knob sits higher than you might expect.',
    phrase: { bpm: 110, loop: true, steps: [[0, 40, 0.4], [0.5, 40, 0.4], [1, 52, 0.4], [1.5, 40, 0.4], [2, 43, 0.4], [2.5, 45, 0.4], [3, 47, 0.8]] },
    steps: [
      { title: 'A pulse through the filter', module: 'osc',
        why: 'Oscillator 2’s pulse into the filter, following the keys.\n- Pins H3 and J8.\n- Oscillator 2 FREQUENCY 6 (middle C on the keys; the riff plays an octave and more below), square LEVEL 7, SHAPE 2: a fairly narrow pulse.\n- INPUT LEVEL CHANNEL 1 at 5.\n- Filter FREQUENCY 6.5, RESPONSE 5, LEVEL 8.',
        set: { 'osc2.freq': 6, 'osc2.square': 7, 'osc2.shape': 2, 'in.ch1': 5, 'vcf.freq': 6.5, 'vcf.response': 5, 'vcf.level': 8 },
        cables: [['r.osc2sq', 'c.vcf'], ['r.in1', 'c.osc2']] },
      { title: 'Shape the loudness', module: 'env',
        why: 'The filter through the envelope shaper to both outputs.\n- Pins D10, B12 and C12.\n- ATTACK 0, ON 0, DECAY 4.5, OFF 10: each key gives one short note.\n- SIGNAL LEVEL 8.\n- Listen for: short notes with a steady tone.',
        set: { 'env.attack': 0, 'env.on': 0, 'env.decay': 4.5, 'env.off': 10, 'env.sigLevel': 8 }, cables: [['r.vcf', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2']] },
      { title: 'The trapezoid sweeps the filter', module: 'filter',
        why: 'The trapezoid into the filter frequency (N11).\n- Pin N11.\n- TRAPEZOID LEVEL 4.5: each note opens the filter by about two octaves; between notes it sits about two octaves lower than the knob says.\n- Listen for: a pluck on every note, bright at the start and darkening as it fades.',
        set: { 'env.trapLevel': 4.5 }, cables: [['r.trap', 'c.cutoff']] },
    ],
    context: {
      'env.trapLevel': 'In this sound: the depth of the pluck.',
      'vcf.freq': 'In this sound: the centre of the sweep. The trapezoid moves it down at rest and up during each note.',
      'vcf.response': 'In this sound: the squelch of the pluck.',
      'env.decay': 'In this sound: how long the note and the sweep last.',
    },
    tweaks: [
      { id: 'vcf.response', try: 'Raise RESPONSE to 6', hear: 'A squelchy, acid-like pluck.' },
      { id: 'env.decay', try: 'Raise DECAY to 6', hear: 'Longer notes with a slower, wah-like close.' },
    ],
  },
  {
    id: 'vcs3-joystick-duo', name: 'Joystick Duet', ref: 'Classic technique: two oscillators bent by hand', artist: 'Classic technique',
    tags: ['drone', 'joystick', 'stereo'], level: 1,
    blurb: 'Two oscillators, one on each side, each bent by one axis of the joystick.',
    how: 'Oscillator 1’s sine goes to the left output and Oscillator 2’s triangle to the right. The joystick’s horizontal is pinned to Oscillator 1 (I15) and its vertical to Oscillator 2 (J16), so one hand plays two pitches at once. The RANGE knobs set how far each axis bends.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 4]] },
    steps: [
      { title: 'One oscillator on each side', module: 'osc',
        why: 'Oscillator 1’s sine to channel 1 (left), Oscillator 2’s triangle to channel 2 (right).\n- Pins B1 and C4.\n- Oscillator 1 FREQUENCY 6, sine LEVEL 6. Oscillator 2 FREQUENCY 6.4, triangle LEVEL 6: about a fifth above.\n- Listen for: two steady tones, one in each speaker.',
        set: { 'osc1.freq': 6, 'osc1.sine': 6, 'osc2.freq': 6.4, 'osc2.tri': 6 }, cables: [['r.osc1sine', 'c.out1'], ['r.osc2tri', 'c.out2']] },
      { title: 'The joystick bends them', module: 'mod',
        why: 'The joystick’s horizontal to Oscillator 1 (I15), its vertical to Oscillator 2 (J16).\n- RANGE 3 on both: several semitones each way.\n- Try: drag the stick. Left and right bend the left tone; up and down bend the right one. Up lowers the pitch, because the oscillators rise as their voltage falls.',
        set: { 'joy.rangeX': 3, 'joy.rangeY': 3 }, cables: [['r.joyx', 'c.osc1'], ['r.joyy', 'c.osc2']] },
    ],
    context: {
      'joy.rangeX': 'In this sound: how far the stick bends the left tone.',
      'joy.rangeY': 'In this sound: how far the stick bends the right tone.',
      'osc2.freq': 'In this sound: the interval between the two tones with the stick in the middle.',
    },
    tweaks: [
      { id: 'joy.x', try: 'Move the stick in a slow circle', hear: 'The two tones weave round each other.' },
      { id: 'joy.rangeX', try: 'Turn the horizontal RANGE to 10', hear: 'Several octaves of bend: a swooping siren.' },
    ],
  },
  {
    id: 'vcs3-ring-melody', name: 'Ring-Mod Bell Melody', ref: 'Classic technique: two oscillators that track the keys, ring-modulated', artist: 'Classic technique',
    tags: ['keys', 'ring mod', 'bells'], level: 2,
    blurb: 'A bell tone you can play in tune: two oscillators both follow the keys, so their ring-modulated overtones move with the melody.',
    how: 'A ring modulator gives only the sum and difference of its two inputs. If both oscillators follow the keyboard (I8 and J8), the ratio between them stays the same on every key, so the bell keeps its character up and down the keyboard. Oscillator 2 sits 3.5 times above Oscillator 1, which puts the sum and difference on the 5th and 9th harmonics of the note you play. The envelope shaper strikes each note and the spring reverb holds the tail on the right.',
    phrase: { bpm: 92, loop: true, steps: [[0, 64, 0.3], [1, 62, 0.3], [2, 60, 0.3], [3, 67, 0.5], [6, 64, 0.3], [7, 60, 0.3]] },
    steps: [
      { title: 'Two oscillators into the ring modulator', module: 'util',
        why: 'Oscillator 1’s sine into input A, Oscillator 2’s triangle into input B.\n- Pins E1 and F4.\n- Oscillator 1 FREQUENCY 6.67, sine LEVEL 6.\n- Oscillator 2 FREQUENCY 7.87, triangle LEVEL 6: 3.5 times higher than Oscillator 1.\n- Ring modulator LEVEL 7.\n- Listen for: nothing yet. Row 13 is not pinned to an output.',
        set: { 'osc1.freq': 6.67, 'osc1.sine': 6, 'osc2.freq': 7.87, 'osc2.tri': 6, 'ring.level': 7 }, cables: [['r.osc1sine', 'c.ringA'], ['r.osc2tri', 'c.ringB']] },
      { title: 'Both oscillators follow the keys', module: 'util',
        why: 'The keyboard voltage (row 8) into both frequency columns, so the pair moves together and the ratio between them holds.\n- Pins I8 and J8.\n- INPUT LEVEL CHANNEL 1 at 5: one semitone per key on both oscillators.\n- Listen for: still nothing. The ring modulator has not been sent anywhere.',
        set: { 'in.ch1': 5 }, cables: [['r.in1', 'c.osc1'], ['r.in1', 'c.osc2']] },
      { title: 'Strike each note', module: 'env',
        why: 'The ring modulator into the envelope shaper (D13), and the shaped signal to both outputs.\n- Pins D13, B12 and C12.\n- ATTACK 0, ON 0, DECAY 6.8 (about 1 s), OFF 10: one strike per key, ringing on after you let go.\n- SIGNAL LEVEL 8.\n- Listen for: a bell on every key, in tune with the melody.',
        set: { 'env.attack': 0, 'env.on': 0, 'env.decay': 6.8, 'env.off': 10, 'env.sigLevel': 8 }, cables: [['r.ring', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2']] },
      { title: 'Spring reverb on the right', module: 'fx',
        why: 'The shaped signal also feeds the reverb (G12), and the reverb joins channel 2 (C14), which is panned right.\n- Pins G12 and C14.\n- Reverb MIX 6, LEVEL 7.\n- Listen for: the dry strike on the left and a spring tail on the right.',
        set: { 'rev.mix': 6, 'rev.level': 7 }, cables: [['r.envsig', 'c.rev'], ['r.rev', 'c.out2']] },
    ],
    context: {
      'osc2.freq': 'In this sound: the ratio to Oscillator 1, which decides the bell. 7.87 is 3.5 times higher and stays in tune; other settings give clangier, out-of-tune bells.',
      'in.ch1': 'In this sound: the keyboard’s reach on both oscillators. Away from 5 the two still move together, but the melody comes out squeezed or stretched.',
      'env.decay': 'In this sound: how long each bell rings.',
      'ring.level': 'In this sound: the volume of the bell before the envelope shaper.',
      'rev.mix': 'In this sound: how much spring is on the right-hand side.',
    },
    tweaks: [
      { id: 'osc2.freq', try: 'Move Oscillator 2 down to 7.6', hear: 'The ratio is no longer simple, so the bell turns into a clanging, out-of-tune gong that still follows the melody.' },
      { id: 'osc1.shape', try: 'Turn Oscillator 1 SHAPE to 8', hear: 'The sine gains harmonics, so more overtones come out of the ring modulator: a harsher, more metallic bell.' },
    ],
  },
  {
    id: 'vcs3-saucer', name: 'Flying Saucer', ref: 'In the style of 1970s BBC Radiophonic Workshop sci-fi effects', artist: 'BBC Radiophonic Workshop',
    tags: ['fx', 'sci-fi', 'filter'], level: 2,
    blurb: 'The filter’s own sine tone, warbling fast, rising and sinking on a slow repeating envelope.',
    how: 'The filter makes the tone itself, with RESPONSE past 6 and nothing pinned into it. Oscillator 3, running at about seven cycles a second, shakes its frequency (N6) for the warble. The trapezoid is pinned to the same column (N11), so each slow cycle of the envelope lifts the pitch and lets it sink back as the sound fades. The envelope repeats on its own, so the craft comes and goes with no key held.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 8]] },
    steps: [
      { title: 'The filter as a sine oscillator', module: 'filter',
        why: 'Nothing goes into the filter: with RESPONSE 8 it whistles by itself.\n- Filter FREQUENCY 6.5 (700 Hz), RESPONSE 8, LEVEL 5.\n- Listen for: nothing yet. Row 10 is not pinned anywhere.',
        set: { 'vcf.freq': 6.5, 'vcf.response': 8, 'vcf.level': 5 } },
      { title: 'A slow repeating envelope', module: 'env',
        why: 'The filter into the envelope shaper (D10), then through the reverb (G12) to both outputs (B14 and C14).\n- Pins D10, G12, B14 and C14.\n- ATTACK 8 (0.3 s), ON 6 (0.9 s), DECAY 8 (2.7 s), OFF 5 (1.8 s): a slow rise, a hold, a long fade and a rest, round and round.\n- SIGNAL LEVEL 8. Reverb MIX 5, LEVEL 8.\n- Listen for: a pure tone fading in and out every few seconds, at one pitch.',
        set: { 'env.attack': 8, 'env.on': 6, 'env.decay': 8, 'env.off': 5, 'env.sigLevel': 8, 'rev.mix': 5, 'rev.level': 8 },
        cables: [['r.vcf', 'c.env'], ['r.envsig', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'Oscillator 3 makes it warble', module: 'lfo',
        why: 'Oscillator 3’s triangle into the filter frequency (N6). At this speed it is a wide, fast vibrato.\n- Pin N6.\n- Oscillator 3 FREQUENCY 5.9 (7 Hz), triangle LEVEL 4: almost an octave each way.\n- Listen for: the tone wobbling up and down several times a second.',
        set: { 'osc3.freq': 5.9, 'osc3.tri': 4 }, cables: [['r.osc3tri', 'c.cutoff']] },
      { title: 'The trapezoid lifts and drops it', module: 'env',
        why: 'The envelope’s own voltage (row 11) into the filter frequency too (N11). It falls while the envelope is up, and a falling voltage raises the filter, so the pitch climbs with each rise and sinks with each fade.\n- Pin N11.\n- TRAPEZOID LEVEL 3: about an octave each way.\n- Listen for: the warbling tone swooping up as it arrives and sinking away as it goes.',
        set: { 'env.trapLevel': 3 }, cables: [['r.trap', 'c.cutoff']] },
    ],
    context: {
      'vcf.response': 'In this sound: past 6.6 the filter makes the tone. Below that there is silence, because nothing is pinned into the filter.',
      'osc3.freq': 'In this sound: the speed of the warble.',
      'osc3.tri': 'In this sound: the width of the warble.',
      'env.trapLevel': 'In this sound: how far each arrival lifts the pitch.',
      'env.off': 'In this sound: the gap between arrivals. Past 6 the envelope waits for a key or the ATTACK button.',
    },
    tweaks: [
      { id: 'osc3.freq', try: 'Turn Oscillator 3 down to 4.5', hear: 'A slow, lazy wobble instead of a fast warble.' },
      { id: 'env.off', try: 'Turn OFF to 10, then click the ATTACK button on and off', hear: 'One arrival each time you press it: you fire the effect by hand.' },
      { id: 'osc3.shape', try: 'Turn Oscillator 3 SHAPE to 0', hear: 'The warble becomes a ramp, so the pitch keeps climbing and snapping back: a busier, more mechanical sound.' },
    ],
  },
  {
    id: 'vcs3-joystick-dive', name: 'Joystick Dive', ref: 'Classic technique: pitch and filter played on one stick', artist: 'Classic technique',
    tags: ['fx', 'joystick', 'performance'], level: 1,
    blurb: 'A buzzing two-oscillator drone you dive and climb with the joystick, one axis for pitch and the other for brightness.',
    how: 'The joystick gives two voltages at once. Here the vertical axis (row 16) goes to both oscillators’ frequency columns (I16, J16), so pushing the stick up dives the pitch and pulling it down climbs. The horizontal axis (row 15) goes to the filter frequency (N15), so the same hand opens and closes the tone. The spring reverb catches the end of each move.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 8]] },
    steps: [
      { title: 'Two oscillators through the filter', module: 'osc',
        why: 'Oscillator 1’s ramp and Oscillator 2’s square into the filter, nearly in tune so they beat.\n- Pins H2 and H3.\n- Oscillator 1 FREQUENCY 6, ramp LEVEL 6; Oscillator 2 FREQUENCY 6.03, square LEVEL 5.\n- Filter FREQUENCY 7 (1 kHz), RESPONSE 4, LEVEL 8.\n- Listen for: nothing yet. Row 10 goes out in the next step.',
        set: { 'osc1.freq': 6, 'osc1.ramp': 6, 'osc2.freq': 6.03, 'osc2.square': 5, 'vcf.freq': 7, 'vcf.response': 4, 'vcf.level': 8 },
        cables: [['r.osc1ramp', 'c.vcf'], ['r.osc2sq', 'c.vcf']] },
      { title: 'Through the reverb to both sides', module: 'fx',
        why: 'The filter into the reverb (G10), and the reverb to both outputs.\n- Pins G10, B14 and C14.\n- Reverb MIX 3, LEVEL 8: mostly dry, with a spring tail.\n- Listen for: a steady, slightly beating buzz.',
        set: { 'rev.mix': 3, 'rev.level': 8 }, cables: [['r.vcf', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'Up and down: the pitch', module: 'mod',
        why: 'The joystick’s vertical (row 16) into both oscillators’ frequency columns, so they move together and keep beating at the same rate.\n- Pins I16 and J16.\n- Vertical RANGE 6: up to about three octaves each way.\n- Push the stick slowly up for a long dive, then pull it down past the middle to climb.\n- Listen for: the whole drone sliding down and up with the stick.',
        set: { 'joy.rangeY': 6 }, cables: [['r.joyy', 'c.osc1'], ['r.joyy', 'c.osc2']] },
      { title: 'Left and right: the brightness', module: 'mod',
        why: 'The joystick’s horizontal (row 15) into the filter frequency (N15).\n- Pin N15.\n- Horizontal RANGE 3.\n- Move the stick right to close the filter and left to open it, while you dive.\n- Listen for: the dive darkening as you lean right, so it sounds further away as it falls.',
        set: { 'joy.rangeX': 3 }, cables: [['r.joyx', 'c.cutoff']] },
    ],
    context: {
      'joy.rangeY': 'In this sound: how far the dive goes. At 10 the stick covers the whole audible range.',
      'joy.rangeX': 'In this sound: how much the stick changes the brightness.',
      'osc2.freq': 'In this sound: a hair above Oscillator 1, so the two beat. Both follow the stick, so the beat stays as you dive.',
      'vcf.freq': 'In this sound: the brightness with the stick in the middle.',
    },
    tweaks: [
      { id: 'joy.y', try: 'Push the stick all the way up over two seconds, then let it spring back to the middle', hear: 'A falling dive that ends in a low growl, then jumps back up to the drone.' },
      { id: 'joy.x', try: 'Move the stick in small fast circles', hear: 'The pitch and the brightness wobble together, a hand-made vibrato and wah.' },
      { id: 'vcf.response', try: 'Raise RESPONSE to 6', hear: 'A ringing peak that whistles as you sweep left and right.' },
    ],
  },
  {
    id: 'vcs3-trap-rhythm', name: 'Self-Playing Rhythm', ref: 'Classic technique: a repeating envelope and free-running oscillators', artist: 'Classic technique',
    tags: ['perc', 'rhythm', 'envelope'], level: 3,
    blurb: 'A rhythm of filtered noise and low thuds that plays itself, with no keys, and keeps shifting.',
    how: 'With OFF below 6 the envelope shaper repeats on its own, so it is the clock. Its trapezoid opens the filter on each hit (N11). Oscillator 3, running at its own speed, switches the filter between bright and dull hits with its square (N5) and stretches and shortens each decay with its triangle (L6), which also moves the timing. The envelope and Oscillator 3 are not locked together, so the pattern slowly changes as they drift in and out of step.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 8]] },
    steps: [
      { title: 'Noise and a low square into the filter', module: 'filter',
        why: 'Noise and Oscillator 2’s square both into the filter.\n- Pins H7 and H3.\n- Noise LEVEL 6, COLOUR 6: a little brighter than white.\n- Oscillator 2 FREQUENCY 4.86 (80 Hz), square LEVEL 5: the thud.\n- Filter FREQUENCY 6 (480 Hz), RESPONSE 4, LEVEL 9.\n- Listen for: nothing yet. Row 10 goes to the envelope shaper next.',
        set: { 'noise.level': 6, 'noise.colour': 6, 'osc2.freq': 4.86, 'osc2.square': 5, 'vcf.freq': 6, 'vcf.response': 4, 'vcf.level': 9 },
        cables: [['r.noise', 'c.vcf'], ['r.osc2sq', 'c.vcf']] },
      { title: 'The envelope is the clock', module: 'env',
        why: 'The filter into the envelope shaper (D10) and the shaped signal to both outputs.\n- Pins D10, B12 and C12.\n- ATTACK 0, ON 0, DECAY 4.5 (0.14 s), OFF 2.2 (0.1 s): a short hit about four times a second.\n- SIGNAL LEVEL 8.\n- Listen for: an even run of dull hits, with no key pressed.',
        set: { 'env.attack': 0, 'env.on': 0, 'env.decay': 4.5, 'env.off': 2.2, 'env.sigLevel': 8 }, cables: [['r.vcf', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2']] },
      { title: 'The trapezoid opens the filter', module: 'env',
        why: 'The envelope’s own voltage into the filter frequency (N11): each hit starts bright and closes as it decays.\n- Pin N11.\n- TRAPEZOID LEVEL 4.\n- Listen for: crisp, snappy hits instead of dull ones.',
        set: { 'env.trapLevel': 4 }, cables: [['r.trap', 'c.cutoff']] },
      { title: 'Oscillator 3 makes the pattern', module: 'lfo',
        why: 'Oscillator 3’s square into the filter frequency (N5) and its triangle into the decay time (L6).\n- Pins N5 and L6.\n- Oscillator 3 FREQUENCY 4.45 (1.6 Hz), square LEVEL 4, triangle LEVEL 6.\n- The square gives alternate groups of bright, hissy hits and dark thuds; the triangle makes the hits longer and slower, then shorter and quicker.\n- Listen for: a lopsided pattern of ticks and thuds that never settles into a straight loop.',
        set: { 'osc3.freq': 4.45, 'osc3.square': 4, 'osc3.tri': 6 }, cables: [['r.osc3sq', 'c.cutoff'], ['r.osc3tri', 'c.decay']] },
    ],
    context: {
      'env.off': 'In this sound: the rest between hits, and so the tempo. Past 6 it stops and waits for a key.',
      'env.decay': 'In this sound: the length of each hit, before Oscillator 3 stretches it.',
      'osc3.freq': 'In this sound: how fast the pattern changes between bright and dark hits.',
      'osc3.tri': 'In this sound: how much the hit lengths, and so the timing, swing.',
      'env.trapLevel': 'In this sound: how much each hit snaps the filter open.',
    },
    tweaks: [
      { id: 'osc3.freq', try: 'Turn Oscillator 3 to 5', hear: 'The bright and dark groups get shorter, so the pattern turns busier.' },
      { id: 'env.off', try: 'Turn OFF down to 1.5', hear: 'A faster rhythm, nearly a roll.' },
      { id: 'vcf.response', try: 'Raise RESPONSE to 6', hear: 'Each hit pings at the filter frequency, like a tuned drum.' },
    ],
  },
  {
    id: 'vcs3-spring-filter', name: 'Spring Through the Filter', ref: 'Classic technique: the reverb in the middle of the patch', artist: 'Classic technique',
    tags: ['fx', 'reverb', 'filter'], level: 3,
    blurb: 'Short plucks thrown into the spring reverb, with the whole reverb then played through a ringing filter that Oscillator 3 sweeps.',
    how: 'On most synths the reverb is the last thing in the chain. On the VCS3 it is just another row and column, so its output can go anywhere, here into the filter (H14). With RESPONSE near the peak the filter rings at its own pitch every time the springs rattle, so each pluck leaves a whistling, pitched tail rather than a plain echo. Oscillator 3 moves the filter (N6), so the tails slide up and down.',
    phrase: { bpm: 70, loop: true, steps: [[0, 60, 0.15], [2, 67, 0.15], [3, 63, 0.15]] },
    steps: [
      { title: 'A pluck from the keys', module: 'env',
        why: 'Oscillator 2’s triangle through the envelope shaper, following the keys.\n- Pins D4 and J8.\n- Oscillator 2 FREQUENCY 6, triangle LEVEL 7. INPUT LEVEL CHANNEL 1 at 5.\n- ATTACK 0, ON 0, DECAY 3.5 (60 ms), OFF 10: a short blip per key.\n- SIGNAL LEVEL 7.\n- Listen for: nothing yet. Row 12 goes to the reverb next.',
        set: { 'osc2.freq': 6, 'osc2.tri': 7, 'in.ch1': 5, 'env.attack': 0, 'env.on': 0, 'env.decay': 3.5, 'env.off': 10, 'env.sigLevel': 7 },
        cables: [['r.osc2tri', 'c.env'], ['r.in1', 'c.osc2']] },
      { title: 'Into the springs, then the filter', module: 'fx',
        why: 'The pluck into the reverb (G12), the reverb into the filter (H14), and the filter to both outputs (B10, C10). The filter starts wide open, so for now it changes little.\n- Pins G12, H14, B10 and C10.\n- Reverb MIX 8, LEVEL 7: mostly spring.\n- Filter FREQUENCY 8 (2.2 kHz), RESPONSE 0, LEVEL 8.\n- Listen for: short blips with a long, twangy spring tail.',
        set: { 'rev.mix': 8, 'rev.level': 7, 'vcf.freq': 8, 'vcf.response': 0, 'vcf.level': 8 },
        cables: [['r.envsig', 'c.rev'], ['r.rev', 'c.vcf'], ['r.vcf', 'c.out1'], ['r.vcf', 'c.out2']] },
      { title: 'Make the filter ring', module: 'filter',
        why: 'Bring the filter down and turn RESPONSE up until it nearly oscillates. Now every rattle of the springs sets it ringing at its own pitch.\n- Filter FREQUENCY 6.5 (700 Hz), RESPONSE 6: right at the edge of oscillating.\n- Listen for: the spring tail turning into a pitched whistle that rings on after each pluck.',
        set: { 'vcf.freq': 6.5, 'vcf.response': 6 } },
      { title: 'Oscillator 3 moves the whistle', module: 'lfo',
        why: 'Oscillator 3’s slow triangle into the filter frequency (N6), so the pitch of the ringing tail drifts.\n- Pin N6.\n- Oscillator 3 FREQUENCY 3 (0.35 Hz), triangle LEVEL 4.\n- Listen for: the tails sliding up and down in pitch, each pluck landing on a different part of the sweep.',
        set: { 'osc3.freq': 3, 'osc3.tri': 4 }, cables: [['r.osc3tri', 'c.cutoff']] },
    ],
    context: {
      'vcf.response': 'In this sound: how much the filter rings on the spring tail. Lower gives a plain reverb; a little higher and the filter whistles all the time.',
      'rev.mix': 'In this sound: how much of the pluck reaches the filter as spring rather than dry. Towards 10 the plucks blur into the tails.',
      'vcf.freq': 'In this sound: the centre pitch of the whistling tail.',
      'osc3.tri': 'In this sound: how far the tails slide.',
      'rev.level': 'In this sound: how hard the reverb drives the filter, so also how loud the result is.',
    },
    tweaks: [
      { id: 'vcf.freq', try: 'Sweep Filter FREQUENCY between 5.5 and 7.5 while the tails ring', hear: 'You tune the ringing tail by hand.' },
      { id: 'vcf.response', try: 'Raise RESPONSE to 6.4', hear: 'The filter whistles all the time, and each pluck knocks the whistle about.' },
    ],
  },
  {
    id: 'vcs3-breaking-waves', name: 'Breaking Waves', ref: 'Classic technique: noise, a slow envelope and the stereo outputs', artist: 'Classic technique',
    tags: ['fx', 'noise', 'stereo'], level: 2,
    blurb: 'Dark noise rising and falling in slow waves that break on the left and wash away on the right.',
    how: 'Noise goes through the filter and a slow, self-repeating envelope. The trapezoid opens the filter as each wave rises (N11), so it breaks brighter and sinks back to a rumble. The dry wave goes to channel 1, panned left, and the reverb to channel 2, panned right, so each wave lands on one side and its wash spreads to the other. Oscillator 3, very slow, stretches the decay (L6), so no two waves are the same length.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 8]] },
    steps: [
      { title: 'Dark noise through the filter', module: 'filter',
        why: 'Noise into the filter, and the filter into the envelope shaper.\n- Pins H7 and D10.\n- Noise LEVEL 8, COLOUR 3.5: darker than white, more rumble.\n- Filter FREQUENCY 6 (480 Hz), RESPONSE 2, LEVEL 9.\n- Listen for: nothing yet. The envelope shaper’s output is not pinned.',
        set: { 'noise.level': 8, 'noise.colour': 3.5, 'vcf.freq': 6, 'vcf.response': 2, 'vcf.level': 9 }, cables: [['r.noise', 'c.vcf'], ['r.vcf', 'c.env']] },
      { title: 'Slow waves on the left', module: 'env',
        why: 'The shaped signal to channel 1 (B12), panned to the left.\n- Pin B12.\n- ATTACK 10 (1 s), ON 4 (0.4 s), DECAY 8.5 (4 s), OFF 4 (0.6 s): a slow surge, a short peak, a long draw-back and a pause.\n- SIGNAL LEVEL 9.\n- PAN CHANNEL 1 at 1.\n- Listen for: a wave of noise building and falling away on the left, every five or six seconds.',
        set: { 'env.attack': 10, 'env.on': 4, 'env.decay': 8.5, 'env.off': 4, 'env.sigLevel': 9, 'out1.pan': 1 }, cables: [['r.envsig', 'c.out1']] },
      { title: 'The trapezoid opens the filter', module: 'env',
        why: 'The envelope’s own voltage into the filter frequency (N11), so the noise brightens as each wave rises and darkens as it draws back.\n- Pin N11.\n- TRAPEZOID LEVEL 3.5.\n- Listen for: a hiss at the top of each wave and a low rumble as it pulls away.',
        set: { 'env.trapLevel': 3.5 }, cables: [['r.trap', 'c.cutoff']] },
      { title: 'The wash on the right', module: 'fx',
        why: 'The shaped signal into the reverb (G12), and the reverb to channel 2 (C14), panned right.\n- Pins G12 and C14.\n- Reverb MIX 9, LEVEL 7: almost all spring.\n- PAN CHANNEL 2 at 9.\n- Listen for: each wave breaking on the left and its spray spreading to the right.',
        set: { 'rev.mix': 9, 'rev.level': 7, 'out2.pan': 9 }, cables: [['r.envsig', 'c.rev'], ['r.rev', 'c.out2']] },
      { title: 'Every wave a different length', module: 'lfo',
        why: 'Oscillator 3, very slow, into the decay time (L6).\n- Pin L6.\n- Oscillator 3 FREQUENCY 1.5 (one cycle every 14 s or so), triangle LEVEL 6.\n- Listen for: some waves drawing back quickly, others lingering, so the timing never repeats exactly.',
        set: { 'osc3.freq': 1.5, 'osc3.tri': 6 }, cables: [['r.osc3tri', 'c.decay']] },
    ],
    context: {
      'noise.colour': 'In this sound: below 5 for a heavier sea. Turn it up for a lighter, hissier surf.',
      'env.attack': 'In this sound: how slowly each wave builds.',
      'env.decay': 'In this sound: how long each wave takes to draw back.',
      'env.trapLevel': 'In this sound: how much brighter the top of each wave is.',
      'out2.pan': 'In this sound: where the reverb wash sits. Move it to the left and the sea closes in to one side.',
      'osc3.tri': 'In this sound: how much the wave lengths vary.',
    },
    tweaks: [
      { id: 'env.off', try: 'Turn OFF to 10 and click the ATTACK button on and off', hear: 'One wave each time you press it.' },
      { id: 'vcf.response', try: 'Raise RESPONSE to 5.5', hear: 'The noise whistles at the top of each wave, more like wind than water.' },
    ],
  },
  {
    id: 'vcs3-bubbling', name: 'Bubbling Cross-Modulation', ref: 'In the style of early-1970s space rock', artist: 'Various',
    tags: ['fx', 'modulation', 'space rock'], level: 3,
    blurb: 'A ringing filter pinged by one oscillator and retuned by another, while the two oscillators modulate each other.',
    how: 'Oscillator 2’s square, at eight cycles a second, goes into the filter (H3); with RESPONSE near the peak each edge makes the filter ring, a bloop. Oscillator 1’s sine moves the filter frequency (N1), so each bloop has a different pitch. Then the two oscillators are pinned into each other’s frequency columns (I3 and J1): each speeds up and slows down the other, so the pattern bubbles instead of repeating. This kind of loop is easy on a pin matrix and impossible on a fixed-path synth.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 8]] },
    steps: [
      { title: 'A square pings the filter', module: 'filter',
        why: 'Oscillator 2’s square into the filter, and the filter to both outputs.\n- Pins H3, B10 and C10.\n- Oscillator 2 FREQUENCY 2.65 (8 Hz), square LEVEL 6.\n- Filter FREQUENCY 6 (480 Hz), RESPONSE 5.8, LEVEL 7: just short of oscillating, so each edge of the square rings.\n- Listen for: an even run of ringing blips at one pitch.',
        set: { 'osc2.freq': 2.65, 'osc2.square': 6, 'vcf.freq': 6, 'vcf.response': 5.8, 'vcf.level': 7 }, cables: [['r.osc2sq', 'c.vcf'], ['r.vcf', 'c.out1'], ['r.vcf', 'c.out2']] },
      { title: 'Oscillator 1 retunes each blip', module: 'mod',
        why: 'Oscillator 1’s sine into the filter frequency (N1).\n- Pin N1.\n- Oscillator 1 FREQUENCY 2.25 (5.3 Hz), sine LEVEL 4: almost an octave each way.\n- Listen for: the blips going up and down in pitch in a regular pattern.',
        set: { 'osc1.freq': 2.25, 'osc1.sine': 4 }, cables: [['r.osc1sine', 'c.cutoff']] },
      { title: 'The oscillators modulate each other', module: 'mod',
        why: 'Oscillator 2’s square into Oscillator 1’s frequency (I3) and Oscillator 1’s sine into Oscillator 2’s (J1). Each now changes the other’s speed.\n- Pins I3 and J1.\n- Listen for: the regular pattern breaking up into bubbling, uneven runs of blips.',
        cables: [['r.osc2sq', 'c.osc1'], ['r.osc1sine', 'c.osc2']] },
      { title: 'Into the spring', module: 'fx',
        why: 'The filter also feeds the reverb (G10), and the reverb joins both outputs.\n- Pins G10, B14 and C14.\n- Reverb MIX 6, LEVEL 6.\n- Listen for: the bubbles ringing on in the springs.',
        set: { 'rev.mix': 6, 'rev.level': 6 }, cables: [['r.vcf', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
    ],
    context: {
      'vcf.response': 'In this sound: how much each edge rings. Lower gives clicks; past 6.6 the filter whistles over everything.',
      'osc2.freq': 'In this sound: the basic rate of the blips.',
      'osc2.square': 'In this sound: how hard the blips ping the filter, and, through I3, how far Oscillator 2 throws Oscillator 1’s speed.',
      'osc1.sine': 'In this sound: how far the blips move in pitch, and how much Oscillator 1 speeds and slows Oscillator 2.',
      'osc1.freq': 'In this sound: how fast the pitch pattern moves.',
    },
    tweaks: [
      { id: 'osc2.freq', try: 'Turn Oscillator 2 up to 3.5', hear: 'Fast, boiling bubbles.' },
      { id: 'osc1.freq', try: 'Turn Oscillator 1 up to 5', hear: 'Oscillator 1 reaches audio rate: the blips turn rough and gritty.' },
      { id: 'vcf.freq', try: 'Lower Filter FREQUENCY to 5', hear: 'Deeper, liquid bloops.' },
    ],
  },
  {
    id: 'vcs3-stereo-throws', name: 'Left-to-Right Throws', ref: 'Classic technique: the trapezoid on an output amplifier', artist: 'Classic technique',
    tags: ['pluck', 'stereo', 'envelope'], level: 2,
    blurb: 'Plucked notes that land on the left and slide over to the right as they fade.',
    how: 'The same shaped signal goes to both outputs, one panned left and one right. The trapezoid, which goes negative while the envelope is up, is pinned to channel 2’s level (P11). So at the start of each note channel 2 is almost shut and the note is heard on the left; as the envelope falls, channel 2 opens and the tail moves across to the right. The envelope is moving the sound in space as well as in loudness.',
    phrase: { bpm: 72, loop: true, steps: [[0, 57, 0.25], [1.5, 64, 0.25], [3, 60, 0.25], [4, 55, 0.25], [5.5, 62, 0.25]] },
    steps: [
      { title: 'A pluck from the keys', module: 'osc',
        why: 'Oscillator 1’s ramp and Oscillator 2’s square into the filter, both following the keys.\n- Pins H2, H3, I8 and J8.\n- Oscillator 1 FREQUENCY 6, ramp LEVEL 5; Oscillator 2 FREQUENCY 6.67 (an octave up), square LEVEL 4. INPUT LEVEL CHANNEL 1 at 5.\n- Filter FREQUENCY 6.8, RESPONSE 3, LEVEL 8.\n- Listen for: nothing yet. Row 10 goes to the envelope shaper next.',
        set: { 'osc1.freq': 6, 'osc1.ramp': 5, 'osc2.freq': 6.67, 'osc2.square': 4, 'in.ch1': 5, 'vcf.freq': 6.8, 'vcf.response': 3, 'vcf.level': 8 },
        cables: [['r.osc1ramp', 'c.vcf'], ['r.osc2sq', 'c.vcf'], ['r.in1', 'c.osc1'], ['r.in1', 'c.osc2']] },
      { title: 'One note, both sides', module: 'env',
        why: 'The filter through the envelope shaper (D10) to both outputs (B12, C12).\n- ATTACK 0, ON 0, DECAY 7 (1.2 s), OFF 10: a strike and a long fade per key.\n- SIGNAL LEVEL 8.\n- OUTPUT LEVEL 1 at 7.5, OUTPUT LEVEL 2 at 7.5. PAN CHANNEL 1 at 0 (left), PAN CHANNEL 2 at 10 (right).\n- Listen for: plucked notes in the middle of the stereo picture.',
        set: { 'env.attack': 0, 'env.on': 0, 'env.decay': 7, 'env.off': 10, 'env.sigLevel': 8, 'out1.level': 7.5, 'out2.level': 7.5, 'out1.pan': 0, 'out2.pan': 10 },
        cables: [['r.vcf', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2']] },
      { title: 'The trapezoid moves channel 2', module: 'out',
        why: 'The trapezoid (row 11) into channel 2’s level (P11). It swings negative at the strike, closing the right side, and climbs back as the note fades, opening it.\n- Pin P11.\n- TRAPEZOID LEVEL 6.\n- OUTPUT LEVEL 2 at 7.5: with the trapezoid added it is nearly shut at the strike and fully open between notes.\n- Listen for: each note striking on the left and its tail sliding across to the right.',
        set: { 'env.trapLevel': 6 }, cables: [['r.trap', 'c.lvl2']] },
    ],
    context: {
      'env.trapLevel': 'In this sound: how far each note travels. At 0 the notes stay in the middle.',
      'env.decay': 'In this sound: how long the slide across takes.',
      'out2.level': 'In this sound: the starting point for channel 2. Lower and the right side stays quieter throughout.',
      'out1.pan': 'In this sound: where each note lands. Bring it to 5 and notes start in the middle before moving right.',
    },
    tweaks: [
      { id: 'env.off', try: 'Turn OFF down to 3', hear: 'The envelope repeats on its own, so the notes are thrown across again and again.' },
      { id: 'env.decay', try: 'Raise DECAY to 8', hear: 'A slower glide across, nearly three seconds a note.' },
    ],
  },
  {
    id: 'vcs3-filter-drone', name: 'Singing Filter Drone', ref: 'Classic technique: an oscillating filter with something going through it', artist: 'Classic technique',
    tags: ['drone', 'filter', 'sine'], level: 2,
    blurb: 'The filter whistling its own tone two octaves above a low ramp that runs through it, with the spring reverb breathing in and out.',
    how: 'With RESPONSE past 6 the filter is an oscillator, but it still passes what is pinned into it. Here a low ramp from Oscillator 1 goes through it (H2), so you hear the filtered ramp and the filter’s own sine over the top, two octaves higher, with the input pulling at the sine. Oscillator 2, at audio rate, shakes the filter frequency (N4) and roughens the sine. Oscillator 3 slowly moves the reverb MIX (M6), so the space around the drone grows and shrinks.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 8]] },
    steps: [
      { title: 'The filter sings', module: 'filter',
        why: 'No input yet: RESPONSE 7.5 makes the filter oscillate on its own, through the reverb to both outputs.\n- Pins G10, B14 and C14.\n- Filter FREQUENCY 5.2 (260 Hz, about middle C), RESPONSE 7.5, LEVEL 5.\n- Reverb MIX 5, LEVEL 7.\n- Listen for: a pure, steady sine.',
        set: { 'vcf.freq': 5.2, 'vcf.response': 7.5, 'vcf.level': 5, 'rev.mix': 5, 'rev.level': 7 }, cables: [['r.vcf', 'c.rev'], ['r.rev', 'c.out1'], ['r.rev', 'c.out2']] },
      { title: 'A low ramp through it', module: 'osc',
        why: 'Oscillator 1’s ramp into the filter (H2), two octaves below the filter’s tone.\n- Pin H2.\n- Oscillator 1 FREQUENCY 4.67 (65 Hz), ramp LEVEL 5.\n- Listen for: a dark buzz underneath, with the sine still singing on top and wavering slightly as the ramp pulls at it.',
        set: { 'osc1.freq': 4.67, 'osc1.ramp': 5 }, cables: [['r.osc1ramp', 'c.vcf']] },
      { title: 'Oscillator 2 roughens the sine', module: 'mod',
        why: 'Oscillator 2’s triangle, at the same low pitch as Oscillator 1, into the filter frequency (N4). At audio rate that adds overtones rather than a wobble.\n- Pin N4.\n- Oscillator 2 FREQUENCY 4.67, triangle LEVEL 3.\n- Listen for: the sine gaining a hoarse, vocal edge.',
        set: { 'osc2.freq': 4.67, 'osc2.tri': 3 }, cables: [['r.osc2tri', 'c.cutoff']] },
      { title: 'Oscillator 3 breathes the reverb', module: 'lfo',
        why: 'Oscillator 3’s slow triangle into the reverb MIX (M6).\n- Pin M6.\n- Oscillator 3 FREQUENCY 2.5 (one cycle every five seconds), triangle LEVEL 9.\n- Listen for: the drone moving closer and further away as the spring comes and goes.',
        set: { 'osc3.freq': 2.5, 'osc3.tri': 9 }, cables: [['r.osc3tri', 'c.revMix']] },
    ],
    context: {
      'vcf.response': 'In this sound: past 6.6 the filter sings its own tone. Below that you hear only the filtered ramp.',
      'vcf.freq': 'In this sound: the pitch of the sung tone. Keep it a whole number of octaves above Oscillator 1 for a steady drone.',
      'osc2.tri': 'In this sound: how rough the sine is. At 0 it is pure again.',
      'osc1.ramp': 'In this sound: how loud the low buzz is, and how hard it pulls at the filter’s tone.',
      'osc3.tri': 'In this sound: how far the reverb MIX swings.',
    },
    tweaks: [
      { id: 'vcf.freq', try: 'Move Filter FREQUENCY slowly between 5 and 5.4', hear: 'The sung tone beats against the ramp’s harmonics, then locks in where they line up.' },
      { id: 'osc2.freq', try: 'Move Oscillator 2 to 4.9', hear: 'Out of step with the drone, the roughness turns into a clanging, metallic edge.' },
    ],
  },
  {
    id: 'vcs3-toms', name: 'Electronic Toms', ref: 'Classic technique: the trapezoid bending pitch', artist: 'Classic technique',
    tags: ['perc', 'drums', 'envelope'], level: 2,
    blurb: 'Pitched drums from a sine wave: the trapezoid bends each hit downwards as it fades, and the keys tune them.',
    how: 'Oscillator 1’s sine and a little noise go through the envelope shaper, struck by each key. The trapezoid is pinned to Oscillator 1’s frequency (I11): it is at its lowest while the envelope is up, and a falling voltage raises the pitch, so each hit starts high and drops as it decays, like a struck drum skin. The keyboard (I8) tunes the drums, so the riff is a tom fill.',
    phrase: { bpm: 100, loop: true, steps: [[0, 60, 0.1], [0.5, 60, 0.1], [1, 55, 0.1], [1.5, 52, 0.1], [2, 60, 0.1], [2.25, 60, 0.1], [2.5, 55, 0.1], [3, 48, 0.1]] },
    steps: [
      { title: 'A sine struck by each key', module: 'env',
        why: 'Oscillator 1’s sine through the envelope shaper to both outputs, following the keys.\n- Pins D1, B12, C12 and I8.\n- Oscillator 1 FREQUENCY 5 (93 Hz on middle C), sine LEVEL 7. INPUT LEVEL CHANNEL 1 at 5.\n- ATTACK 0, ON 0, DECAY 5.5 (0.3 s), OFF 10. Each key is a short tap: while a key is held the envelope stays at the top.\n- SIGNAL LEVEL 8.\n- Listen for: low, dull beeps at the pitch of each key.',
        set: { 'osc1.freq': 5, 'osc1.sine': 7, 'in.ch1': 5, 'env.attack': 0, 'env.on': 0, 'env.decay': 5.5, 'env.off': 10, 'env.sigLevel': 8 },
        cables: [['r.osc1sine', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2'], ['r.in1', 'c.osc1']] },
      { title: 'The trapezoid bends the pitch', module: 'env',
        why: 'The trapezoid (row 11) into Oscillator 1’s frequency (I11).\n- Pin I11.\n- TRAPEZOID LEVEL 3: about eight semitones above the dial at the strike, falling to eight below as the hit dies.\n- Listen for: each beep turning into a tom, starting high and dropping.',
        set: { 'env.trapLevel': 3 }, cables: [['r.trap', 'c.osc1']] },
      { title: 'Noise for the stick', module: 'osc',
        why: 'A little noise into the envelope shaper too (D7), so each hit has a rattle on top.\n- Pin D7.\n- Noise LEVEL 2.5, COLOUR 7: thin and hissy.\n- Listen for: a crisper attack on each tom.',
        set: { 'noise.level': 2.5, 'noise.colour': 7 }, cables: [['r.noise', 'c.env']] },
    ],
    context: {
      'env.trapLevel': 'In this sound: how far each hit drops. Higher gives a laser-like zap; lower a plain thud.',
      'env.decay': 'In this sound: the length of each drum, and of its drop.',
      'osc1.freq': 'In this sound: the tuning of the whole kit.',
      'noise.level': 'In this sound: how much rattle sits on each hit.',
    },
    tweaks: [
      { id: 'env.trapLevel', try: 'Turn TRAPEZOID LEVEL to 6', hear: 'Each hit sweeps down over two octaves: a disco-style electronic drum zap.' },
      { id: 'noise.level', try: 'Turn Noise LEVEL to 7', hear: 'The rattle takes over: more snare than tom.' },
    ],
  },
  {
    id: 'vcs3-random-babble', name: 'Random Computer Babble', ref: 'Classic technique: filtered noise as a random voltage', artist: 'Classic technique',
    tags: ['fx', 'random', 'noise'], level: 3,
    blurb: 'Fast blips whose pitch lurches about at random, the film-computer sound, made without a sample and hold.',
    how: 'The VCS3 Mk 1 has no sample and hold. Noise through the filter turned almost to the bottom (H7), with RESPONSE near the peak, is the next best thing: only a narrow band of slow movement around 16 Hz gets through, a wobbling voltage whose size and timing change at random. Pinned to Oscillator 1’s frequency (I10), it gives each blip from the repeating envelope a different pitch and a different bend. The same voltage on the decay column (L10) makes the blips uneven in length and speed.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 8]] },
    steps: [
      { title: 'Fast blips from the envelope', module: 'env',
        why: 'Oscillator 1’s sine through the repeating envelope to both outputs.\n- Pins D1, B12 and C12.\n- Oscillator 1 FREQUENCY 7 (740 Hz), sine LEVEL 6.\n- ATTACK 0, ON 0, DECAY 3.5 (60 ms), OFF 1.8: about eight blips a second.\n- SIGNAL LEVEL 8.\n- Listen for: a stream of blips at one pitch.',
        set: { 'osc1.freq': 7, 'osc1.sine': 6, 'env.attack': 0, 'env.on': 0, 'env.decay': 3.5, 'env.off': 1.8, 'env.sigLevel': 8 },
        cables: [['r.osc1sine', 'c.env'], ['r.envsig', 'c.out1'], ['r.envsig', 'c.out2']] },
      { title: 'Noise filtered into a slow random voltage', module: 'filter',
        why: 'Noise into the filter (H7) with FREQUENCY almost at the bottom, so only its slowest movements get through. RESPONSE near the peak makes the filter ring on that band, which makes the voltage much bigger. The filter’s output is now a control voltage, not a sound.\n- Pin H7.\n- Noise LEVEL 10, COLOUR 0: the darkest noise has the most low movement in it.\n- Filter FREQUENCY 1.5 (16 Hz), RESPONSE 6, LEVEL 10.\n- Listen for: no change yet. Row 10 is not pinned.',
        set: { 'noise.level': 10, 'noise.colour': 0, 'vcf.freq': 1.5, 'vcf.response': 6, 'vcf.level': 10 }, cables: [['r.noise', 'c.vcf']] },
      { title: 'The random voltage plays the pitch', module: 'mod',
        why: 'The filtered noise (row 10) into Oscillator 1’s frequency (I10).\n- Pin I10.\n- Listen for: the blips jumping about to unrelated pitches, never repeating a phrase.',
        cables: [['r.vcf', 'c.osc1']] },
      { title: 'And the timing', module: 'env',
        why: 'The same voltage into the decay time (L10), so the length of each blip, and the gap to the next, wander too.\n- Pin L10.\n- Listen for: blips speeding up, hesitating and clustering, as if something were thinking.',
        cables: [['r.vcf', 'c.decay']] },
    ],
    context: {
      'vcf.freq': 'In this sound: how fast the random voltage moves. Higher and the pitch jitters within each blip; lower and it moves more slowly.',
      'vcf.response': 'In this sound: how big the random voltage is. Lower and the filter rings less, so the pitches stay closer together.',
      'vcf.level': 'In this sound: how wide the random pitches range.',
      'noise.colour': 'In this sound: at 0 the noise is darkest, which gives the filter the most to pass.',
      'env.off': 'In this sound: the basic rate of the blips.',
    },
    tweaks: [
      { id: 'vcf.freq', try: 'Turn Filter FREQUENCY up to 3', hear: 'The pitch now jitters inside each blip: a burbling, chattering sound.' },
      { id: 'vcf.level', try: 'Turn Filter LEVEL down to 7', hear: 'The pitches stay closer together, more like muttering than shouting.' },
    ],
  },
];
