// More sounds for the Roland Jupiter-6 library. Same Preset shape as the ones in ../jupiter-6.js (see CONTRACT.md → Preset).
const ENV = (e, a, d, s, r) => ({ [`${e}.attack`]: a, [`${e}.decay`]: d, [`${e}.sustain`]: s, [`${e}.release`]: r });

export default [
  {
    id: 'jp6-hpf-glass', name: 'High-Pass Glass Pad', ref: 'In the style of airy 80s soundtrack pads', artist: 'Classic technique',
    tags: ['pad', 'soundtrack', '80s'], level: 2,
    blurb: 'A thin, glassy pad with no low end, that drifts slowly brighter and darker.',
    how: 'The VCF is switched to high-pass, so it removes the lows and keeps the highs: the opposite of the usual filter. With some resonance at the cutoff the pad sounds glassy and airy. LFO-1 moves the cutoff very slowly so the chord keeps changing colour.',
    phrase: { bpm: 70, loop: true, steps: [[0, 64, 3.8], [0, 67, 3.8], [0, 71, 3.8], [0, 76, 3.8], [4, 62, 3.8], [4, 65, 3.8], [4, 69, 3.8], [4, 74, 3.8]] },
    steps: [
      { title: 'Two sawtooths an octave apart', module: 'osc', why: 'Bright sawtooths give the high-pass filter plenty of top to keep.\n- VCO-2 SAWTOOTH lit, RANGE 4’ (+12 st): VCO-2 an octave above VCO-1.\n- VCO-2 TUNE +1.2 (+12 cents): a little sharp, for slow beating.\n- MIX 5: both at full level. VOLUME 6.\n- Listen for: a bright, buzzy chord with a shimmer on top.',
        set: { 'vco2.saw': true, 'vco2.range': 48, 'vco2.tune': 1.2, 'mix.balance': 5, 'out.volume': 6 } },
      { title: 'Switch the filter to high-pass', module: 'filter', why: 'With HPF lit and LPF off, the filter keeps everything above the cutoff and cuts what is below it.\n- HPF lit, LPF off: 24 dB high-pass.\n- FREQ 5.5 (654 Hz): everything below this is thinned away, so the chord loses its body.\n- RES 4 (40 %): a peak right at the cutoff that makes it sound glassy.\n- KYBD 10 (120 %): the cutoff rises with the keys, so every note keeps the same thinness.\n- Listen for: a chord with no low end, airy and bright. Light LPF as well and it becomes band-pass.',
        set: { 'vcf.hpf': true, 'vcf.lpf': false, 'vcf.freq': 5.5, 'vcf.res': 4, 'vcf.kybd': 10 } },
      { title: 'A very slow drift', module: 'lfo', why: 'LFO-1 moves the cutoff up and down very slowly, so the colour of the pad keeps changing.\n- VCF LFO 3 (30 %): how far LFO-1 moves the cutoff.\n- LFO-1 RATE 2.5 (0.28 Hz): one sweep about every three and a half seconds.\n- Listen for: the chord getting thinner and fuller on its own.',
        set: { 'vcf.lfo': 3, 'lfo.rate': 2.5 } },
      { title: 'Slow in, slow out', module: 'amp', why: 'ENV-2 makes the pad fade in and out.\n- ENV-2 A 6 (600 ms), S 10, R 7 (1.5 s).\n- Listen for: chords that rise and overlap.',
        set: ENV('env2', 6, 6, 10, 7) },
    ],
    context: {
      'vcf.freq': 'In this sound: in high-pass, how much body is taken away. Up is thinner.',
      'vcf.res': 'In this sound: the glassy peak at the cutoff.',
      'vcf.hpf': 'In this sound: makes the filter keep the highs instead of the lows.',
    },
    tweaks: [
      { id: 'vcf.freq', try: 'Move between 3 and 7', hear: 'From a full pad to a whisper of fizz.' },
      { id: 'vcf.lpf', try: 'Light LPF as well', hear: 'Band-pass: a nasal, vocal pad.' },
    ],
  },
  {
    id: 'jp6-bpf-vowel', name: 'Band-Pass Vowel', ref: 'In the style of talking-filter synth pads', artist: 'Classic technique',
    tags: ['pad', 'synth-pop', '80s'], level: 2,
    blurb: 'A nasal, vocal pad whose “aah” slowly turns into “ooh” and back.',
    how: 'With both MODE buttons lit the filter is band-pass: it keeps only a band around the cutoff, which sounds like a vowel. High resonance makes the vowel stronger, and LFO-1 slides the band up and down so the vowel changes.',
    phrase: { bpm: 76, loop: true, steps: [[0, 52, 3.8], [0, 59, 3.8], [0, 64, 3.8], [4, 50, 3.8], [4, 57, 3.8], [4, 62, 3.8]] },
    steps: [
      { title: 'A sawtooth and a pulse', module: 'osc', why: 'Rich waves give the band-pass filter something to pick out.\n- VCO-2 PULSE lit, MIX 5, VCO-2 TUNE −0.8 (−8 cents).\n- PW 3 (36 %).\n- Listen for: a buzzy chord.',
        set: { 'vco2.pulse': true, 'mix.balance': 5, 'vco2.tune': -0.8, 'pwm.pw': 3 } },
      { title: 'Band-pass with resonance', module: 'filter', why: 'HPF and LPF lit together make the filter band-pass: lows and highs are cut and a band in the middle remains, like the formant of a voice.\n- HPF and LPF lit.\n- FREQ 5.5 (654 Hz): where the band sits. Lower is “ooh”, higher “eeh”.\n- RES 6 (60 %): a strong peak, so the vowel is clear.\n- Listen for: a nasal, talking chord.',
        set: { 'vcf.hpf': true, 'vcf.freq': 5.5, 'vcf.res': 6 } },
      { title: 'Move the vowel', module: 'lfo', why: 'LFO-1 slides the band up and down, so the vowel changes.\n- VCF LFO 4 (40 %), LFO-1 RATE 3 (0.42 Hz).\n- LFO-1 DELAY 5 (0.6 s): each new chord starts still, then the movement fades in.\n- ENV-2 A 4.5 (180 ms), R 6 (700 ms): a soft start and a fading tail.\n- Listen for: “aah-ooh-aah” across each held chord.',
        set: { 'vcf.lfo': 4, 'lfo.rate': 3, 'lfo.delay': 5, ...ENV('env2', 4.5, 5, 10, 6) } },
    ],
    context: {
      'vcf.freq': 'In this sound: which vowel you hear.',
      'vcf.res': 'In this sound: how strongly the vowel speaks.',
      'lfo.delay': 'In this sound: how long each chord holds still before the vowel moves.',
    },
    tweaks: [
      { id: 'vcf.res', try: 'Raise to 8', hear: 'A whistling, very vocal band.' },
      { id: 'lfo.rate', try: 'Raise to 5', hear: 'The vowel babbles twice a second.' },
    ],
  },
  {
    id: 'jp6-ep', name: 'Key-Follow Electric Piano', ref: 'In the style of early-80s synth electric pianos', artist: 'Classic technique',
    tags: ['keys', 'pop', '80s'], level: 2,
    blurb: 'A soft, bell-edged electric piano whose high notes die away sooner than the low ones.',
    how: 'Two triangles an octave apart give a mellow tone, and ENV-1 opens the filter briefly for a soft “tine” at the start. Both envelopes decay to silence, and KEY FOLLOW makes them shorter on high notes and longer on low ones, as on a real piano.',
    phrase: { bpm: 84, loop: true, steps: [[0, 48, 1.8], [0, 60, 1.8], [0, 64, 1.8], [0, 67, 1.8], [2, 72, 0.4], [2.5, 76, 0.4], [3, 79, 0.9]] },
    steps: [
      { title: 'Two triangles', module: 'osc', why: 'Triangle waves are soft and round, the body of an electric piano.\n- VCO-1 SAWTOOTH off, TRIANGLE lit.\n- VCO-2 TRIANGLE lit, RANGE 4’ (+12 st): an octave up for the bright tine.\n- MIX 3.5: VCO-2 at 70 %, under VCO-1.\n- Listen for: a pure, flute-like organ tone.',
        set: { 'vco1.saw': false, 'vco1.tri': true, 'vco2.tri': true, 'vco2.range': 48, 'mix.balance': 3.5 } },
      { title: 'A short bright tine', module: 'filter', why: 'ENV-1 opens the filter briefly at the start of each note for a soft strike.\n- FREQ 6 (956 Hz), VCF ENV 3.\n- ENV-1 A 0, D 6 (700 ms), S 0, R 5.\n- ENV-1 KEY FOLLOW 6 (72 %): the tine is shorter on high notes.\n- Listen for: a little brightness at the start of each note.',
        set: { 'vcf.freq': 6, 'vcf.env': 3, ...ENV('env1', 0, 6, 0, 5), 'env1.kf': 6 } },
      { title: 'A piano-like decay', module: 'amp', why: 'A piano note fades even if you hold the key, and low notes ring longer than high ones.\n- ENV-2 A 0, D 8 (3.4 s), S 0, R 5.5 (480 ms).\n- ENV-2 KEY FOLLOW 7 (84 %): high notes decay much sooner than low ones. At 0 every note would ring for the same time.\n- Listen for: the low chord rings while the high notes die quickly.',
        set: { ...ENV('env2', 0, 8, 0, 5.5), 'env2.kf': 7 } },
    ],
    context: {
      'env2.kf': 'In this sound: how much shorter the high notes are than the low ones.',
      'env2.decay': 'In this sound: how long a middle note rings.',
      'vcf.env': 'In this sound: the tine at the start of each note.',
    },
    tweaks: [
      { id: 'env2.kf', try: 'Set to 0, then 10', hear: 'All notes ring alike at 0; high notes become plinks at 10.' },
      { id: 'vcf.env', try: 'Raise to 6', hear: 'A harder, brighter strike.' },
    ],
  },
  {
    id: 'jp6-reverse-swell', name: 'Inverted Swell', ref: 'In the style of 80s ambient pads', artist: 'Classic technique',
    tags: ['pad', 'ambient', '80s'], level: 3,
    blurb: 'Chords that start bright, close as they hold, and open again as you let go.',
    how: 'ENV-1’s POLARITY is turned upside down, so as the envelope rises the filter closes instead of opening. The chord starts bright, darkens over a second or so, and brightens again in the release, which sounds like a tape played backwards.',
    phrase: { bpm: 66, loop: true, steps: [[0, 57, 3.6], [0, 60, 3.6], [0, 64, 3.6], [4, 55, 3.6], [4, 59, 3.6], [4, 62, 3.6]] },
    steps: [
      { title: 'Two detuned sawtooths', module: 'osc', why: 'A wide, bright chord to work with.\n- VCO-2 SAWTOOTH lit, MIX 5, VCO-2 TUNE −1 (−10 cents). VOLUME 6.\n- Listen for: a bright, wide chord.',
        set: { 'vco2.saw': true, 'mix.balance': 5, 'vco2.tune': -1, 'out.volume': 6 } },
      { title: 'Turn ENV-1 upside down', module: 'env', why: 'POLARITY inverted makes ENV-1 work backwards: it now pushes the filter down while it rises.\n- POLARITY: the lower button (inverted).\n- FREQ 8 (4.4 kHz): open to start with.\n- VCF ENV 4: how far the inverted envelope closes the filter.\n- Listen for: every chord now darkens right away.',
        set: { 'env1.polarity': 'inverted', 'vcf.freq': 8, 'vcf.env': 4 } },
      { title: 'Slow envelopes', module: 'env', why: 'Slow envelopes stretch the dip into a long swell.\n- ENV-1 A 7 (1.3 s), D 8, S 6, R 7 (1.5 s): the filter closes over more than a second and opens again over the release.\n- ENV-2 A 4 (120 ms), S 10, R 7.\n- Listen for: a chord that fades darker as it holds, then blooms bright as you let go.',
        set: { ...ENV('env1', 7, 8, 6, 7), ...ENV('env2', 4, 5, 10, 7) } },
    ],
    context: {
      'env1.polarity': 'In this sound: why the filter closes as the note holds.',
      'env1.attack': 'In this sound: how long the darkening takes.',
      'vcf.env': 'In this sound: how dark the chord gets.',
    },
    tweaks: [
      { id: 'env1.polarity', try: 'Switch back to normal', hear: 'An ordinary slow filter swell, dark to bright.' },
      { id: 'env1.release', try: 'Raise to 8.5', hear: 'A longer bloom after you let go.' },
    ],
  },
  {
    id: 'jp6-low-siren', name: 'Cross-Mod Siren', ref: 'In the style of 80s sci-fi sound effects', artist: 'Classic technique',
    tags: ['fx', 'soundtrack', '80s'], level: 3,
    blurb: 'A warbling, alarm-like tone with a metallic rasp that grows over each note.',
    how: 'VCO-2 is turned down into LOW, where it stops following the keys and runs at a few cycles a second. Used as the cross-mod source it becomes a second LFO that wobbles VCO-1’s pitch. ENV-1 then adds more and more cross mod as the note goes on.',
    phrase: { bpm: 80, loop: true, steps: [[0, 60, 3.5], [4, 55, 3.5]] },
    steps: [
      { title: 'VCO-2 into LOW', module: 'osc', why: 'At LOW, VCO-2 is a slow modulator that ignores the keyboard.\n- VCO-2 RANGE LOW 7.4 Hz: five steps from the left end.\n- VCO-2 TRIANGLE lit, MIX 0: VCO-2 is not heard directly, only used for cross mod.\n- Listen for: no change yet, just VCO-1’s saw.',
        set: { 'vco2.range': 5, 'vco2.tri': true, 'mix.balance': 0 } },
      { title: 'Cross mod as a siren', module: 'osc', why: 'CROSS MOD lets VCO-2 move VCO-1’s pitch. At a few cycles a second that is a wide warble.\n- CROSS MOD MANUAL 6 (60 %): about an octave of swing.\n- Listen for: a two-tone siren.',
        set: { 'vco1.xmod': 6 } },
      { title: 'Let ENV-1 widen it', module: 'env', why: 'CROSS MOD ENV-1 adds more as ENV-1 rises, so the siren starts gentle and grows wild.\n- CROSS MOD ENV-1 8 (80 %).\n- ENV-1 A 7.5 (2 s), D 8, S 10, R 5.\n- ENV-2 R 6 (700 ms).\n- FREQ 7 (2 kHz), RES 3 (30 %).\n- Listen for: the warble widening over two seconds.',
        set: { 'vco1.xmodEnv': 8, ...ENV('env1', 7.5, 8, 10, 5), 'env2.release': 6, 'vcf.freq': 7, 'vcf.res': 3 } },
    ],
    context: {
      'vco2.range': 'In this sound: the speed of the siren. Step it right for faster, until it reaches audio and turns to rasp.',
      'vco1.xmod': 'In this sound: how wide the siren swings.',
    },
    tweaks: [
      { id: 'vco2.range', try: 'Step it from 2 to 11', hear: 'From a slow wail to a fast, growling buzz.' },
      { id: 'vco1.xmodEnv', try: 'Set to 0', hear: 'A steady siren that does not grow.' },
    ],
  },
  {
    id: 'jp6-noise-snare', name: 'Noise Snare', ref: 'In the style of early drum-machine snares', artist: 'Classic technique',
    tags: ['perc', 'electro', '80s'], level: 2,
    blurb: 'A short snare hit: a pitched thump with a burst of noise on top.',
    how: 'VCO-1’s triangle is the drum’s body, given a quick pitch drop by ENV-1, and VCO-2’s NOISE is the snare rattle. ENV-2 has no sustain, so every hit is short however long the key is held.',
    phrase: { bpm: 100, loop: true, steps: [[0, 50, 0.25], [1, 50, 0.25], [1.75, 50, 0.2], [2.5, 50, 0.25], [3, 50, 0.25]] },
    steps: [
      { title: 'A body and a rattle', module: 'osc', why: 'A drum is a short tone plus noise.\n- VCO-1 SAWTOOTH off, TRIANGLE lit: the body.\n- VCO-2 NOISE lit, MIX 6.5: noise at full level, VCO-1 at 70 %.\n- Listen for: a tone with hiss on top.',
        set: { 'vco1.saw': false, 'vco1.tri': true, 'vco2.noise': true, 'mix.balance': 6.5 } },
      { title: 'A pitch drop on the body', module: 'mod', why: 'Real drums drop in pitch as they are hit.\n- VCO MOD VCO-2 off, ENV-1 3 (+5.4 st at the peak): only VCO-1 is moved.\n- ENV-1 A 0, D 3 (67 ms), S 0, R 3.\n- Listen for: a “dmm” instead of a steady tone.',
        set: { 'vcomod.vco2': false, 'vcomod.env': 3, ...ENV('env1', 0, 3, 0, 3) } },
      { title: 'Short hits', module: 'amp', why: 'No sustain makes every hit short.\n- ENV-2 A 0, D 4 (150 ms), S 0, R 3.5.\n- FREQ 7.5 (3 kHz), RES 2: takes the harshest top off the noise.\n- ENV-2 LEVEL 10 and VOLUME 9: a short hit needs more level to sit with other sounds.\n- Listen for: a snappy snare.',
        set: { ...ENV('env2', 0, 4, 0, 3.5), 'vcf.freq': 7.5, 'vcf.res': 2, 'vca.level': 10, 'out.volume': 9 } },
    ],
    context: {
      'env2.decay': 'In this sound: the length of each hit.',
      'mix.balance': 'In this sound: the balance of body and rattle.',
    },
    tweaks: [
      { id: 'mix.balance', try: 'Move between 5 and 9', hear: 'More tom at 5, nearly all rattle at 9.' },
      { id: 'env2.decay', try: 'Raise to 5', hear: 'A longer, roomier snare.' },
    ],
  },
  {
    id: 'jp6-clav', name: 'Funky Clav', ref: 'In the style of 80s synth-funk clavinet parts', artist: 'Classic technique',
    tags: ['pluck', 'funk', '80s'], level: 1,
    blurb: 'A short, nasal, plucked keyboard sound for funky chords.',
    how: 'A narrow pulse wave sounds thin and nasal, like a clavinet string. ENV-1 snaps the filter open and shut on every note, and ENV-2 has no sustain, so each note is a short pluck.',
    phrase: { bpm: 104, loop: true, steps: [[0, 60, 0.2], [0, 64, 0.2], [0.5, 60, 0.2], [0.5, 64, 0.2], [0.75, 62, 0.2], [0.75, 65, 0.2], [1.5, 60, 0.2], [1.5, 64, 0.2], [2.25, 67, 0.2], [2.5, 64, 0.2], [3, 62, 0.2], [3, 65, 0.2]] },
    steps: [
      { title: 'A narrow pulse', module: 'osc', why: 'A narrow pulse is thin and nasal.\n- VCO-1 SAWTOOTH off, PULSE lit, PW 6 (21 %).\n- Listen for: a reedy buzz.',
        set: { 'vco1.saw': false, 'vco1.pulse': true, 'pwm.pw': 6 } },
      { title: 'Snap the filter', module: 'filter', why: 'The pluck comes from the filter.\n- FREQ 4 (209 Hz), RES 3, VCF ENV 6, KYBD 7.\n- ENV-1 A 0, D 3.5 (100 ms), S 0, R 3.\n- Listen for: a “tik” on every note.',
        set: { 'vcf.freq': 4, 'vcf.res': 3, 'vcf.env': 6, 'vcf.kybd': 7, ...ENV('env1', 0, 3.5, 0, 3) } },
      { title: 'Short notes', module: 'amp', why: 'ENV-2 A 0, D 4.5 (220 ms), S 0, R 3: notes die away quickly however long they are held.\n- Listen for: tight, choppy chords.',
        set: ENV('env2', 0, 4.5, 0, 3) },
    ],
    context: {
      'pwm.pw': 'In this sound: how nasal the string is.',
      'env1.decay': 'In this sound: how long the snap lasts.',
    },
    tweaks: [
      { id: 'pwm.pw', try: 'Move between 3 and 8', hear: 'From woody to very thin and buzzy.' },
      { id: 'vcf.res', try: 'Raise to 6', hear: 'A rubbery, wah-like quack.' },
    ],
  },
  {
    id: 'jp6-organ', name: 'Square Organ', ref: 'In the style of combo organs', artist: 'Classic technique',
    tags: ['keys', 'pop', '60s'], level: 1,
    blurb: 'A bright, steady organ with a gentle tremolo.',
    how: 'Organs are steady tones made of a few pitches. Here VCO-1 mixes a triangle and a square, VCO-2 adds a square an octave up, the envelopes switch the sound on and off like a key, and LFO-1 adds tremolo through the VCA.',
    phrase: { bpm: 110, loop: true, steps: [[0, 60, 0.9], [0, 64, 0.9], [0, 67, 0.9], [1, 62, 0.9], [1, 65, 0.9], [1, 69, 0.9], [2, 64, 1.8], [2, 67, 1.8], [2, 71, 1.8]] },
    steps: [
      { title: 'Combine the waves', module: 'osc', why: 'The waveform buttons can be combined, like organ drawbars.\n- VCO-1 SAWTOOTH off, TRIANGLE and SQUARE lit.\n- VCO-2 PULSE lit, RANGE 4’ (+12 st): with PW at 0 the pulse is a square, an octave up.\n- MIX 5. VOLUME 6.\n- Listen for: a hollow, reedy organ.',
        set: { 'vco1.saw': false, 'vco1.tri': true, 'vco1.square': true, 'vco2.pulse': true, 'vco2.range': 48, 'mix.balance': 5, 'out.volume': 6 } },
      { title: 'On-off like an organ key', module: 'amp', why: 'ENV-2 A 0.5, S 10, R 2.5 (45 ms): full at once and gone as you let go.\n- FREQ 7 (2 kHz): a little softer on top.\n- Listen for: notes that start and stop cleanly.',
        set: { ...ENV('env2', 0.5, 5, 10, 2.5), 'vcf.freq': 7 } },
      { title: 'Tremolo', module: 'amp', why: 'VCA LFO lets LFO-1 move the volume.\n- VCA LFO 2.5, LFO-1 RATE 6 (4.4 Hz).\n- Listen for: a gentle pulsing.',
        set: { 'vca.lfo': 2.5, 'lfo.rate': 6 } },
    ],
    context: {
      'vca.lfo': 'In this sound: how deep the tremolo is.',
      'lfo.rate': 'In this sound: how fast the tremolo pulses.',
    },
    tweaks: [
      { id: 'vco1.square', try: 'Switch it off', hear: 'A softer, flute-like organ.' },
      { id: 'vca.lfo', try: 'Raise to 6', hear: 'A choppy, throbbing tremolo.' },
    ],
  },
  {
    id: 'jp6-vibrato-lead', name: 'Hand Vibrato Lead', ref: 'In the style of 80s synth solos', artist: 'Classic technique',
    tags: ['lead', 'rock', '80s'], level: 1,
    blurb: 'A singing mono lead with a vibrato that swells in on each note.',
    how: 'Two detuned sawtooths make a full lead tone. LFO-2, brought in with the LFO MOD button on the plate beside the keys, adds a vibrato that rises in after each note starts, the way a player adds vibrato by hand.',
    phrase: { bpm: 96, loop: true, steps: [[0, 69, 1.4], [1.5, 72, 0.45], [2, 74, 1.9], [4, 76, 0.9], [5, 74, 0.9], [6, 72, 1.8]] },
    steps: [
      { title: 'A full lead tone', module: 'osc', why: 'Two sawtooths, slightly apart, played one note at a time.\n- VCO-2 SAWTOOTH lit, MIX 5, VCO-2 TUNE +1 (+10 cents).\n- SOLO lit: one note at a time.\n- FREQ 6.5 (1.4 kHz), RES 2, KYBD 6.\n- Listen for: a warm, thick lead.',
        set: { 'vco2.saw': true, 'mix.balance': 5, 'vco2.tune': 1, 'voice.solo': true, 'vcf.freq': 6.5, 'vcf.res': 2, 'vcf.kybd': 6 } },
      { title: 'Bring in LFO-2', module: 'mod', why: 'LFO MOD switches on LFO-2, a sine kept for playing vibrato.\n- LFO MOD lit.\n- LFO-2 VCO 4 (±19 cents), RATE 5.5 (3.5 Hz).\n- RISE 6 (0.3 s): the vibrato waits and then swells in on each new note.\n- Listen for: long notes start straight and begin to sing.',
        set: { 'lfo2.on': true, 'lfo2.vco': 4, 'lfo2.rate': 5.5, 'lfo2.rise': 6 } },
      { title: 'A slide between notes', module: 'glide', why: 'PORTAMENTO lit, TIME 2 (0.06 s an octave): a quick slide.\n- ENV-2 A 1.5, S 10, R 4.5.\n- Listen for: a smooth, vocal line.',
        set: { 'glide.porta': true, 'glide.time': 2, ...ENV('env2', 1.5, 5, 10, 4.5) } },
    ],
    context: {
      'lfo2.vco': 'In this sound: how wide the vibrato is.',
      'lfo2.rise': 'In this sound: how long each note stays straight before the vibrato comes in.',
      'lfo2.on': 'In this sound: switches the vibrato on.',
    },
    tweaks: [
      { id: 'lfo2.rise', try: 'Move between 0 and 10', hear: 'Instant vibrato at 0, a slow swell at 10.' },
      { id: 'lfo2.vcf', try: 'Raise to 3', hear: 'The filter wobbles too: a growl.' },
    ],
  },
  {
    id: 'jp6-poly-glide', name: 'Poly Glide Pad', ref: 'In the style of 80s film-score pads', artist: 'Classic technique',
    tags: ['pad', 'soundtrack', '80s'], level: 2,
    blurb: 'Warm chords whose notes slide into each other as the chords change.',
    how: 'Portamento works on every voice at once, so when one chord moves to the next each voice slides from its old note to its new one. Soft saws, a closed filter and slow envelopes make it a pad.',
    phrase: { bpm: 70, loop: true, steps: [[0, 55, 1.9], [0, 59, 1.9], [0, 62, 1.9], [2, 57, 1.9], [2, 60, 1.9], [2, 64, 1.9], [4, 53, 1.9], [4, 57, 1.9], [4, 60, 1.9], [6, 55, 1.9], [6, 59, 1.9], [6, 62, 1.9]] },
    steps: [
      { title: 'Soft sawtooths', module: 'osc', why: 'VCO-2 SAWTOOTH lit, MIX 5, VCO-2 TUNE −0.6.\n- FREQ 5 (447 Hz), KYBD 6.\n- VOLUME 6.\n- Listen for: a warm, dark chord.',
        set: { 'vco2.saw': true, 'mix.balance': 5, 'vco2.tune': -0.6, 'vcf.freq': 5, 'vcf.kybd': 6, 'out.volume': 6 } },
      { title: 'Polyphonic portamento', module: 'glide', why: 'Every voice slides from its last note.\n- PORTAMENTO lit, TIME 4 (0.26 s an octave).\n- POLY-2 lit: on the hardware POLY-2 keeps a key on the same voice, which suits glide.\n- Listen for: chords that bend into each other.',
        set: { 'glide.porta': true, 'glide.time': 4, 'voice.assign': 'poly2' } },
      { title: 'Pad envelopes', module: 'amp', why: 'ENV-2 A 4 (120 ms), S 10, R 6 (700 ms).\n- Listen for: smooth, legato changes.',
        set: ENV('env2', 4, 5, 10, 6) },
    ],
    context: {
      'glide.time': 'In this sound: how long each slide takes.',
      'glide.porta': 'In this sound: switches the slides on.',
    },
    tweaks: [
      { id: 'glide.time', try: 'Raise to 7', hear: 'Slow, woozy slides.' },
      { id: 'voice.detune', try: 'Light UNISON and set DETUNE to 4', hear: 'Fewer notes, each doubled and wider.' },
    ],
  },
  {
    id: 'jp6-flute', name: 'Breathy Flute', ref: 'In the style of synth flute lines', artist: 'Classic technique',
    tags: ['wind', 'pop', '80s'], level: 1,
    blurb: 'A soft triangle flute with breath noise and a delayed vibrato.',
    how: 'A triangle is close to a flute’s pure tone. VCO-2’s noise adds breath, a gentle attack lets each note blow in, and LFO-1’s DELAY makes the vibrato wait until the note has settled.',
    phrase: { bpm: 88, loop: true, steps: [[0, 72, 0.9], [1, 74, 0.45], [1.5, 76, 1.4], [3, 79, 0.9], [4, 76, 1.9], [6, 74, 1.9]] },
    steps: [
      { title: 'Triangle and breath', module: 'osc', why: 'VCO-1 SAWTOOTH off, TRIANGLE lit.\n- VCO-2 NOISE lit, MIX 3: noise at 60 %, under the tone.\n- FREQ 6 (956 Hz), RES 1: the filter softens the noise.\n- Listen for: a breathy whistle.',
        set: { 'vco1.saw': false, 'vco1.tri': true, 'vco2.noise': true, 'mix.balance': 3, 'vcf.freq': 6, 'vcf.res': 1 } },
      { title: 'Blow in', module: 'amp', why: 'ENV-2 A 3.5 (77 ms), S 9, R 4: each note blows in rather than clicking on.\n- Listen for: soft starts.',
        set: ENV('env2', 3.5, 5, 9, 4) },
      { title: 'Delayed vibrato', module: 'lfo', why: 'VCO MOD LFO 1 (±0.4 st): a light vibrato on both VCOs.\n- LFO-1 RATE 6.2 (5.1 Hz).\n- LFO-1 DELAY 6 (0.9 s): the vibrato waits nearly a second after each new note.\n- Listen for: long notes start straight, then waver.',
        set: { 'vcomod.lfo': 1, 'lfo.rate': 6.2, 'lfo.delay': 6 } },
    ],
    context: {
      'lfo.delay': 'In this sound: how long each note stays straight.',
      'mix.balance': 'In this sound: how breathy the flute is.',
    },
    tweaks: [
      { id: 'mix.balance', try: 'Move between 1 and 5', hear: 'From a pure whistle to a very breathy pan pipe.' },
      { id: 'vcomod.lfo', try: 'Raise to 2', hear: 'A wide, wobbly vibrato.' },
    ],
  },
  {
    id: 'jp6-random-drone', name: 'Random-Step Drone', ref: 'In the style of 70s and 80s electronic drones', artist: 'Classic technique',
    tags: ['drone', 'ambient', '80s'], level: 3,
    blurb: 'A low, held drone whose resonant filter jumps to a new random setting every beat.',
    how: 'LFO-1 set to RANDOM steps to a new random value each cycle; sent to a resonant filter it picks a new colour on every step, a sample-and-hold sound. The drone itself is two low, detuned VCOs.',
    phrase: { bpm: 60, loop: true, steps: [[0, 36, 7.8], [0, 43, 7.8]] },
    steps: [
      { title: 'A low drone', module: 'osc', why: 'VCO-2 SAWTOOTH lit, MIX 5, VCO-2 TUNE +1.5 (+15 cents).\n- VCO-1 and VCO-2 RANGE 16’.\n- Listen for: a slow beating drone.',
        set: { 'vco2.saw': true, 'mix.balance': 5, 'vco2.tune': 1.5, 'vco1.range': 12, 'vco2.range': 24 } },
      { title: 'A resonant filter', module: 'filter', why: 'FREQ 4.5 (306 Hz), RES 7 (70 %): a strong, singing peak.\n- Listen for: a whistle riding on the drone.',
        set: { 'vcf.freq': 4.5, 'vcf.res': 7 } },
      { title: 'Random steps', module: 'lfo', why: 'LFO-1 RANDOM picks a new value each cycle.\n- WAVEFORM RANDOM, RATE 5.5 (3 steps a second).\n- VCF LFO 5: how far each step can move the cutoff.\n- ENV-2 A 5, S 10, R 7.\n- Listen for: the whistle jumping about.',
        set: { 'lfo.wave': 'rnd', 'lfo.rate': 5.5, 'vcf.lfo': 5, ...ENV('env2', 5, 5, 10, 7) } },
    ],
    context: {
      'lfo.rate': 'In this sound: how often the filter jumps.',
      'vcf.res': 'In this sound: how much each jump sings.',
    },
    tweaks: [
      { id: 'lfo.rate', try: 'Move between 3 and 8', hear: 'Lazy jumps to a fast bubbling.' },
      { id: 'lfo.wave', try: 'Choose the triangle', hear: 'A smooth sweep instead of steps.' },
    ],
  },
];
