// More sounds for the Roland Jupiter-8 library. Same Preset shape as the ones in ../jupiter-8.js (see CONTRACT.md → Preset).
const ENV = (e, a, d, s, r) => ({ [`${e}.attack`]: a, [`${e}.decay`]: d, [`${e}.sustain`]: s, [`${e}.release`]: r });

export default [
  {
    id: 'jp8-pop-stab', name: 'Synth-Pop Stab', ref: 'In the style of Howard Jones — "What Is Love?"', artist: 'Howard Jones',
    tags: ['keys', 'synth-pop', '80s'], level: 1,
    blurb: 'Short, bright chord stabs with a glassy edge, made for off-beat rhythm parts.',
    how: 'A sawtooth on VCO-1 and a pulse on VCO-2 an octave up give a bright, hollow chord. ENV-2 has no sustain, so every chord is a short stab however long the keys are held, and ENV-1 snaps the filter open at the front of each one.',
    phrase: { bpm: 108, loop: true, steps: [[0.5, 64, 0.3], [0.5, 67, 0.3], [0.5, 71, 0.3], [1.5, 64, 0.3], [1.5, 67, 0.3], [1.5, 71, 0.3], [2.5, 62, 0.3], [2.5, 66, 0.3], [2.5, 69, 0.3], [3.25, 62, 0.3], [3.25, 66, 0.3], [3.25, 69, 0.3]] },
    steps: [
      { title: 'Saw and an octave pulse', module: 'osc', why: 'A sawtooth gives body, and a pulse an octave above gives a glassy top.\n- VCO-2 RANGE +12 (4’), WAVEFORM pulse.\n- PULSE WIDTH MOD 4 at MANUAL: a little narrower than square, reedier.\n- SOURCE MIX 4: VCO-1 a little ahead of VCO-2.\n- Listen for: a bright, hollow chord. Turn SOURCE MIX right to hear the octave come forward.',
        set: { 'vco2.range': 24, 'vco2.wave': 'pulse', 'pwm.amount': 4, 'mix.balance': 4 } },
      { title: 'A snapping filter', module: 'filter', why: 'The filter rests fairly dark and ENV-1 snaps it open for a moment at the start of each chord.\n- CUT OFF FREQ 5 (about 660 Hz), RES 2.\n- ENV MOD 5 from ENV-1: A 0, D 3.5 (100 ms), S 2, R 3.\n- Listen for: a bright “tick” at the front of each chord.',
        set: { 'vcf.cutoff': 5, 'vcf.res': 2, 'vcf.env': 5, ...ENV('env1', 0, 3.5, 2, 3) } },
      { title: 'Make it a stab', module: 'amp', why: 'With no sustain the chord dies away on its own, so held chords still come out as stabs.\n- ENV-2 A 0, D 4.5 (220 ms), S 0, R 3.5 (100 ms).\n- VCA LEVEL 10: stabs this short need a little more level.\n- Listen for: tight chords that leave room between them. Raise D for a longer, ringing chord.',
        set: { ...ENV('env2', 0, 4.5, 0, 3.5), 'vca.level': 10 } },
    ],
    context: {
      'env2.decay': 'In this sound: the length of each stab.',
      'vcf.env': 'In this sound: how bright the front of each stab is.',
    },
    tweaks: [
      { id: 'env2.decay', try: 'Move between 3.5 and 6', hear: 'From a clipped tick to a ringing chord.' },
      { id: 'mix.balance', try: 'Turn to 8', hear: 'The glassy octave takes over.' },
    ],
  },
  {
    id: 'jp8-glass-pad', name: 'Airy Glass Pad', ref: 'Classic high-passed pad', artist: 'Classic technique',
    tags: ['pad', 'ambient', '80s'], level: 2,
    blurb: 'A thin, shining pad with a slow vibrato that grows in on held notes.',
    how: 'The high-pass filter removes the body of the sound, leaving a light, glassy shimmer. The LFO is set to a slow vibrato, and DELAY TIME makes it fade in only after each chord has been held for a moment, as a player would.',
    phrase: { bpm: 66, loop: true, steps: [[0, 64, 3.8], [0, 67, 3.8], [0, 71, 3.8], [0, 76, 3.8], [4, 62, 3.8], [4, 65, 3.8], [4, 69, 3.8], [4, 74, 3.8]] },
    steps: [
      { title: 'Two detuned sawtooths, an octave apart', module: 'osc', why: 'Two saws an octave apart and slightly detuned give a wide, bright source.\n- VCO-2 RANGE +12, FINE TUNE +1.2.\n- Listen for: a bright, moving chord.',
        set: { 'vco2.range': 24, 'vco2.fine': 1.2 } },
      { title: 'Take the body away', module: 'filter', why: 'The high-pass filter cuts the low end, leaving only the air on top.\n- HPF CUT OFF FREQ 6 (about 430 Hz): the chord loses its weight.\n- VCF CUT OFF FREQ 7 at −12 dB: the top is softened a little.\n- Listen for: move the HPF slider between 0 and 7 and hear the chord go from full to thin and glassy.',
        set: { 'hpf.cutoff': 6, 'vcf.cutoff': 7, 'vcf.slope': '12' } },
      { title: 'A vibrato that grows in', module: 'lfo', why: 'The LFO adds a slow vibrato, and DELAY TIME holds it back for the first part of each chord.\n- VCO MOD LFO 0.7 (about a quarter of a semitone), both VCOs.\n- LFO RATE 6 (2.8 Hz): a slow, singing wobble.\n- DELAY TIME 5 (1.4 s): plain at first, then the vibrato fades in.\n- Listen for: each chord starting still and beginning to sway after a second.',
        set: { 'vcomod.lfo': 0.7, 'lfo.rate': 6, 'lfo.delay': 5 } },
      { title: 'Slow swell and fade', module: 'amp', why: 'Slow envelopes keep the pad soft.\n- ENV-2 A 6 (350 ms), S 10, R 7.5 (1.9 s).\n- Listen for: chords overlapping as they fade.',
        set: ENV('env2', 6, 5, 10, 7.5) },
    ],
    context: {
      'hpf.cutoff': 'In this sound: how thin and airy the pad is.',
      'lfo.delay': 'In this sound: how long each chord holds still before the vibrato comes in.',
    },
    tweaks: [
      { id: 'lfo.delay', try: 'Set to 0, then 8', hear: 'Vibrato from the start at 0; at 8 only on long chords.' },
      { id: 'hpf.cutoff', try: 'Lower to 2', hear: 'The body comes back and the pad gets warmer.' },
    ],
  },
  {
    id: 'jp8-reverse-swell', name: 'Inverted Swell', ref: 'Classic inverted-envelope pad', artist: 'Classic technique',
    tags: ['pad', 'ambient', '80s'], level: 2,
    blurb: 'Chords that start bright, close as they are held and open again as you let go.',
    how: 'ENV-1’s POLARITY switch turns the envelope upside down, so instead of opening the filter it closes it. With slow envelope times the chord starts bright, darkens as ENV-1 rises, and brightens again during the release.',
    phrase: { bpm: 70, loop: true, steps: [[0, 57, 3.6], [0, 60, 3.6], [0, 64, 3.6], [4, 55, 3.6], [4, 59, 3.6], [4, 62, 3.6]] },
    steps: [
      { title: 'A wide, open chord', module: 'osc', why: 'Two detuned saws and an open filter give a bright chord for the envelope to work on.\n- FINE TUNE −1 (−10 cents).\n- CUT OFF FREQ 7.5 (about 3.6 kHz), RES 3.\n- Listen for: a bright, slightly beating chord.',
        set: { 'vco2.fine': -1, 'vcf.cutoff': 7.5, 'vcf.res': 3 } },
      { title: 'Turn ENV-1 upside down', module: 'env', why: 'POLARITY inverted makes ENV-1 close the filter as it rises, instead of opening it.\n- POLARITY inverted.\n- ENV MOD 6 from ENV-1: how far it closes.\n- ENV-1 A 7.5 (1 s), D 7, S 6, R 7.5: slow, so the darkening is a gradual swell.\n- Listen for: each chord dimming over a second, then opening again after you let go.',
        set: { 'env1.polarity': 'inverted', 'vcf.env': 6, ...ENV('env1', 7.5, 7, 6, 7.5) } },
      { title: 'Let it ring on', module: 'amp', why: 'A long release lets you hear the filter opening again after the keys are up.\n- ENV-2 A 3, S 10, R 8 (2.6 s).\n- Listen for: the bright bloom in the tail of every chord.',
        set: ENV('env2', 3, 5, 10, 8) },
    ],
    context: {
      'env1.polarity': 'In this sound: why the filter closes on each chord instead of opening.',
      'env1.attack': 'In this sound: how slowly each chord darkens.',
    },
    tweaks: [
      { id: 'env1.polarity', try: 'Switch back to normal', hear: 'The chords now open as they are held: an ordinary slow sweep.' },
      { id: 'env1.attack', try: 'Set to 4', hear: 'The chord ducks dark almost at once.' },
    ],
  },
  {
    id: 'jp8-wind', name: 'Night Wind', ref: 'Classic noise wind effect', artist: 'Classic technique',
    tags: ['fx', 'soundtrack', '80s'], level: 1,
    blurb: 'Gusting wind made from noise, a resonant filter and a slow, wandering LFO.',
    how: 'VCO-2 is switched to NOISE and the mix turned all the way over to it. A resonant filter picks a band out of the noise, and the LFO on RANDOM moves the cutoff about slowly, so the wind rises and falls.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 7.8]] },
    steps: [
      { title: 'Noise instead of a tone', module: 'osc', why: 'VCO-2’s NOISE setting turns it into a noise source.\n- VCO-2 WAVEFORM noise, SOURCE MIX 10: only noise reaches the filter.\n- Listen for: a steady hiss on any key.',
        set: { 'vco2.wave': 'noise', 'mix.balance': 10 } },
      { title: 'A whistling band', module: 'filter', why: 'High resonance makes the filter ring at its cutoff, so the noise whistles like wind.\n- CUT OFF FREQ 5.5 (about 930 Hz), RES 8, −24 dB.\n- Listen for: a hollow, whistling hiss.',
        set: { 'vcf.cutoff': 5.5, 'vcf.res': 8 } },
      { title: 'Gusts from the LFO', module: 'lfo', why: 'The LFO moves the cutoff, and RANDOM makes each gust different.\n- LFO WAVE FORM random, RATE 2.5 (0.27 Hz): a new gust every few seconds.\n- VCF LFO MOD 6: how far the gusts move the filter.\n- Listen for: the whistle sliding up and down at random.',
        set: { 'lfo.wave': 'random', 'lfo.rate': 2.5, 'vcf.lfo': 6 } },
      { title: 'Fade in and out', module: 'amp', why: 'Slow envelopes keep the wind from starting and stopping abruptly.\n- ENV-2 A 7.5 (1 s), S 10, R 8.\n- VCA LEVEL 10 and VOLUME 9: a narrow band of noise is quiet, so both are turned up.\n- Listen for: the wind rising in and dying away.',
        set: { ...ENV('env2', 7.5, 5, 10, 8), 'vca.level': 10, 'out.volume': 9 } },
    ],
    context: {
      'vcf.res': 'In this sound: how much the wind whistles.',
      'lfo.rate': 'In this sound: how often the gusts change.',
    },
    tweaks: [
      { id: 'vcf.res', try: 'Lower to 3', hear: 'A softer rush, like surf rather than wind.' },
      { id: 'lfo.wave', try: 'Set to sine', hear: 'Even, regular waves instead of gusts.' },
    ],
  },
  {
    id: 'jp8-bubbles', name: 'Random Bubbles', ref: 'Classic sample-and-hold filter', artist: 'Classic technique',
    tags: ['fx', 'electronic', '80s'], level: 2,
    blurb: 'A burbling stream of random filter steps on a held note.',
    how: 'The LFO’s RANDOM shape jumps to a new value every cycle. Sent to a resonant filter at a fast rate, those jumps become a stream of bubbles, the classic sample-and-hold sound.',
    phrase: { bpm: 100, loop: true, steps: [[0, 48, 3.8], [4, 51, 3.8]] },
    steps: [
      { title: 'A resonant, closed filter', module: 'filter', why: 'High resonance makes every cutoff jump ring.\n- CUT OFF FREQ 4 (about 340 Hz), RES 7.\n- Listen for: a dark note with a ringing edge.',
        set: { 'vcf.cutoff': 4, 'vcf.res': 7 } },
      { title: 'Random steps on the cutoff', module: 'lfo', why: 'The RANDOM shape picks a new level every cycle; at this rate that is a new bubble about eight times a second.\n- LFO WAVE FORM random, RATE 7.5 (7.5 Hz).\n- VCF LFO MOD 7: wide jumps.\n- Listen for: a stream of bubbling, pitched blips.',
        set: { 'lfo.wave': 'random', 'lfo.rate': 7.5, 'vcf.lfo': 7 } },
      { title: 'Track the keyboard', module: 'filter', why: 'With key follow, the bubbles move with the note you play.\n- KEY FOLLOW 8 (96 %).\n- Listen for: the bubbles shifting up when the second note plays.',
        set: { 'vcf.kbd': 8 } },
    ],
    context: {
      'lfo.rate': 'In this sound: how fast the bubbles come.',
      'vcf.lfo': 'In this sound: how wide each jump is.',
    },
    tweaks: [
      { id: 'lfo.rate', try: 'Move between 5 and 9', hear: 'From slow drips to a fizzing stream.' },
      { id: 'vcf.res', try: 'Raise to 9', hear: 'Each step rings like a struck tube.' },
    ],
  },
  {
    id: 'jp8-pluck-keys', name: 'Plucked Keys', ref: 'Classic key-follow pluck', artist: 'Classic technique',
    tags: ['pluck', 'pop', '80s'], level: 2,
    blurb: 'A soft, plucked keyboard sound whose high notes are short and low notes ring.',
    how: 'Both envelopes decay to nothing, so every note is a pluck. KEY FOLLOW on both makes the envelopes faster on high notes, as on a harp or a piano, and the filter’s KEY FOLLOW keeps the high notes bright.',
    phrase: { bpm: 96, loop: true, steps: [[0, 48, 0.9], [0.5, 55, 0.9], [1, 60, 0.9], [1.5, 64, 0.9], [2, 67, 0.9], [2.5, 72, 0.9], [3, 76, 0.9], [3.5, 79, 0.9]] },
    steps: [
      { title: 'A soft square', module: 'osc', why: 'A square on VCO-1 and a pure sine an octave up give a woody tone.\n- VCO-1 WAVEFORM square, VCO-2 WAVEFORM sine, RANGE +12: a pure octave on top.\n- Listen for: a hollow, organ-like tone.',
        set: { 'vco1.wave': 'square', 'vco2.wave': 'sine', 'vco2.range': 24 } },
      { title: 'Pluck the filter', module: 'filter', why: 'ENV-1 opens the filter at each note and lets it fall.\n- CUT OFF FREQ 3.5, ENV MOD 6 from ENV-1, A 0, D 5 (320 ms), S 0, R 4.\n- KEY FOLLOW 8: high notes keep their brightness.\n- Listen for: each note starting bright and mellowing.',
        set: { 'vcf.cutoff': 3.5, 'vcf.env': 6, 'vcf.kbd': 8, ...ENV('env1', 0, 5, 0, 4) } },
      { title: 'Notes that die away', module: 'amp', why: 'No sustain on ENV-2 makes each note a pluck.\n- ENV-2 A 0, D 7 (1.3 s), S 0, R 5.\n- Listen for: notes fading on their own.',
        set: ENV('env2', 0, 7, 0, 5) },
      { title: 'Faster at the top', module: 'env', why: 'KEY FOLLOW on both envelopes shortens them as you go up.\n- ENV-1 KEY FOLLOW ON, ENV-2 KEY FOLLOW ON.\n- Listen for: the low notes ringing much longer than the high ones in the rising run.',
        set: { 'env1.kf': true, 'env2.kf': true } },
    ],
    context: {
      'env2.kf': 'In this sound: why high notes are short and low ones ring.',
      'env2.decay': 'In this sound: how long the notes ring around middle C.',
    },
    tweaks: [
      { id: 'env2.kf', try: 'Switch OFF', hear: 'Every note now rings for the same time, top or bottom.' },
      { id: 'vcf.env', try: 'Raise to 8', hear: 'A sharper, brighter pluck.' },
    ],
  },
  {
    id: 'jp8-warble-organ', name: 'Warble Organ', ref: 'Classic cross-mod vibrato', artist: 'Classic technique',
    tags: ['keys', 'rock', '70s'], level: 3,
    blurb: 'A reedy organ tone with a fast, rich warble from VCO-2 used as a second LFO.',
    how: 'LOW FREQ turns VCO-2 into a slow oscillator that no longer follows the keys. Through CROSS MOD it wobbles VCO-1’s pitch, a vibrato that runs separately from the main LFO. The mix is turned fully to VCO-1, so VCO-2 is never heard directly.',
    phrase: { bpm: 90, loop: true, steps: [[0, 60, 1.9], [0, 64, 1.9], [0, 67, 1.9], [2, 62, 1.9], [2, 65, 1.9], [2, 69, 1.9]] },
    steps: [
      { title: 'A reedy VCO-1 alone', module: 'osc', why: 'VCO-1 on a pulse wave is the organ tone; VCO-2 is taken out of the mix.\n- VCO-1 WAVEFORM pulse, PULSE WIDTH MOD 3 at MANUAL.\n- SOURCE MIX 0.\n- Listen for: a plain, reedy chord.',
        set: { 'vco1.wave': 'pulse', 'pwm.amount': 3, 'mix.balance': 0 } },
      { title: 'VCO-2 as a modulator', module: 'osc', why: 'LOW FREQ drops VCO-2 to a few cycles a second, and CROSS MOD lets it move VCO-1.\n- VCO-2 NORMAL/LOW FREQ at LOW FREQ, WAVEFORM sine, RANGE 22 (about 3.6 Hz).\n- CROSS MOD 2.5: a gentle wobble. More turns it into a siren.\n- Listen for: a fast, even vibrato on every note.',
        set: { 'vco2.lowFreq': true, 'vco2.wave': 'sine', 'vco2.range': 22, 'vco1.xmod': 2.5 } },
      { title: 'Organ envelopes', module: 'amp', why: 'An organ is on or off.\n- ENV-2 A 0.5, S 10, R 2.5. CUT OFF FREQ 7.\n- Listen for: clean starts and stops.',
        set: { ...ENV('env2', 0.5, 4, 10, 2.5), 'vcf.cutoff': 7 } },
    ],
    context: {
      'vco1.xmod': 'In this sound: the depth of the warble.',
      'vco2.range': 'In this sound: in LOW FREQ this sets the warble speed.',
    },
    tweaks: [
      { id: 'vco2.range', try: 'Turn it down to 10, then up to 34', hear: 'A slow wobble, then a fast flutter.' },
      { id: 'vco1.xmod', try: 'Raise to 6', hear: 'A wide, sci-fi siren.' },
    ],
  },
  {
    id: 'jp8-singing-lead', name: 'Singing Lead', ref: 'Classic portamento solo lead', artist: 'Classic technique',
    tags: ['lead', 'rock', '80s'], level: 2,
    blurb: 'A smooth, gliding solo lead with vibrato you bring in by hand.',
    how: 'SOLO turns the Jupiter into a mono synth and PORTAMENTO slides between notes. The LFO MODULATION button brings in the performance LFO, a vibrato that rises in over RISE TIME, the way a singer leans into a long note.',
    phrase: { bpm: 84, loop: true, steps: [[0, 67, 1.4], [1.5, 69, 0.45], [2, 71, 1.9], [4, 74, 0.9], [5, 72, 0.9], [6, 71, 1.9]] },
    steps: [
      { title: 'One voice, sliding', module: 'mode', why: 'A lead plays one note at a time.\n- ASSIGN MODE SOLO.\n- PORTAMENTO 3.5 (370 ms), switch ON.\n- Listen for: each note sliding into the next.',
        set: { 'assign.mode': 'solo', 'glide.time': 3.5, 'glide.mode': 'on' } },
      { title: 'A warm saw tone', module: 'filter', why: 'Two saws a fifth apart, softened by the filter, give a singing tone.\n- VCO-2 RANGE +7, SOURCE MIX 3.\n- CUT OFF FREQ 6 (about 1.3 kHz), RES 3, KEY FOLLOW 6.\n- Listen for: a full, slightly vocal lead.',
        set: { 'vco2.range': 19, 'mix.balance': 3, 'vcf.cutoff': 6, 'vcf.res': 3, 'vcf.kbd': 6 } },
      { title: 'Vibrato that rises', module: 'mod', why: 'The performance LFO is a second, sine LFO for playing vibrato.\n- LFO MODULATION on, VCO MOD switch ON.\n- LFO MOD VCO 4: a moderate vibrato.\n- RISE TIME 6 (about 0.9 s): it fades in after each new note.\n- Listen for: long notes blooming into vibrato. Turn the button off to compare.',
        set: { 'plfo.on': true, 'plfo.vco': true, 'plfo.vcoDepth': 4, 'plfo.rise': 6 } },
    ],
    context: {
      'plfo.rise': 'In this sound: how long a note holds still before the vibrato comes in.',
      'glide.time': 'In this sound: the slide between notes.',
    },
    tweaks: [
      { id: 'plfo.vcoDepth', try: 'Raise to 8', hear: 'A wide, operatic vibrato.' },
      { id: 'glide.time', try: 'Set to 6', hear: 'Slow, swooping slides between notes.' },
    ],
  },
  {
    id: 'jp8-tremolo-keys', name: 'Tremolo Keys', ref: 'Classic electric-piano tremolo', artist: 'Classic technique',
    tags: ['keys', 'soul', '70s'], level: 1,
    blurb: 'A mellow electric-piano-like chord with a gentle tremolo.',
    how: 'A triangle and a sine, filtered soft, give a round keyboard tone. The VCA’s LFO MOD switch dips the volume with the LFO in four steps, which is the tremolo; key follow on ENV-2 makes high notes fade sooner.',
    phrase: { bpm: 80, loop: true, steps: [[0, 52, 1.9], [0, 59, 1.9], [0, 64, 1.9], [2, 50, 1.9], [2, 57, 1.9], [2, 62, 1.9]] },
    steps: [
      { title: 'Soft waves', module: 'osc', why: 'Triangle and sine have few harmonics: a mellow, rounded tone.\n- VCO-1 WAVEFORM triangle, VCO-2 WAVEFORM sine, RANGE +12.\n- CUT OFF FREQ 6.5.\n- Listen for: a soft, bell-like chord.',
        set: { 'vco1.wave': 'tri', 'vco2.wave': 'sine', 'vco2.range': 24, 'vcf.cutoff': 6.5 } },
      { title: 'A piano-like fade', module: 'amp', why: 'Notes fade slowly while held, faster at the top.\n- ENV-2 A 0.5, D 8 (2.6 s), S 3, R 5. KEY FOLLOW ON.\n- Listen for: chords fading to a quiet tail.',
        set: { ...ENV('env2', 0.5, 8, 3, 5), 'env2.kf': true } },
      { title: 'Tremolo', module: 'amp', why: 'The LFO dips the volume up and down.\n- VCA LFO MOD at 2.\n- LFO RATE 6 (2.8 Hz), sine.\n- Listen for: a gentle, regular pulsing. Step 3 is deeper; 0 is off.',
        set: { 'vca.lfo': 2, 'lfo.rate': 6 } },
    ],
    context: {
      'vca.lfo': 'In this sound: how deep the tremolo is.',
      'lfo.rate': 'In this sound: the tremolo speed.',
    },
    tweaks: [
      { id: 'vca.lfo', try: 'Set to 3 with LFO WAVE FORM on square', hear: 'A choppy, on-off tremolo.' },
      { id: 'lfo.rate', try: 'Move between 5 and 7', hear: 'From a slow sway to a fast shimmer.' },
    ],
  },
  {
    id: 'jp8-pwm-bass', name: 'Swept Pulse Bass', ref: 'Classic envelope PWM bass', artist: 'Classic technique',
    tags: ['bass', 'electronic', '80s'], level: 2,
    blurb: 'A punchy bass whose pulse width snaps narrow and opens on every note.',
    how: 'PULSE WIDTH MOD set to ENV-1 makes the pulse width sweep once per note, from thin and nasal back to square. Together with a short filter envelope it gives each bass note a quick, vocal “yow”.',
    phrase: { bpm: 118, loop: true, steps: [[0, 33, 0.4], [0.75, 33, 0.2], [1, 45, 0.4], [1.5, 33, 0.4], [2, 36, 0.4], [2.75, 36, 0.2], [3, 38, 0.4], [3.5, 40, 0.4]] },
    steps: [
      { title: 'Pulses in SOLO', module: 'osc', why: 'Both oscillators on pulse, one voice.\n- VCO-1 and VCO-2 WAVEFORM pulse, VCO-1 RANGE 16’.\n- ASSIGN MODE SOLO.\n- Listen for: a hollow, heavy bass.',
        set: { 'vco1.wave': 'pulse', 'vco2.wave': 'pulse', 'vco1.range': '16', 'assign.mode': 'solo' } },
      { title: 'Sweep the width with ENV-1', module: 'mod', why: 'At ENV-1, the PULSE WIDTH MOD slider sets how narrow the pulse goes at the peak of the envelope.\n- PULSE WIDTH MOD switch ENV-1, slider 7.\n- ENV-1 A 0, D 4.5 (220 ms), S 0, R 3.\n- Listen for: a vocal “yow” at the front of each note.',
        set: { 'pwm.mode': 'env1', 'pwm.amount': 7, ...ENV('env1', 0, 4.5, 0, 3) } },
      { title: 'Filter and loudness', module: 'filter', why: 'ENV-1 also opens the filter a little.\n- CUT OFF FREQ 4, ENV MOD 4, RES 2.\n- ENV-2 A 0, D 5, S 8, R 2.5.\n- Listen for: a tight, punchy line.',
        set: { 'vcf.cutoff': 4, 'vcf.env': 4, 'vcf.res': 2, ...ENV('env2', 0, 5, 8, 2.5) } },
    ],
    context: {
      'pwm.amount': 'In this sound: how far each note’s pulse narrows.',
      'env1.decay': 'In this sound: how long the width sweep and the filter snap last.',
    },
    tweaks: [
      { id: 'pwm.amount', try: 'Move between 3 and 9', hear: 'From a slight edge to a nasal quack.' },
      { id: 'env1.polarity', try: 'Switch to inverted', hear: 'The width starts narrow and opens out, and the filter closes on each note.' },
    ],
  },
  {
    id: 'jp8-random-arp', name: 'Random Arpeggio', ref: 'Classic random arpeggio', artist: 'Classic technique',
    tags: ['seq', 'electronic', '80s'], level: 1,
    blurb: 'A chord scattered at random over three octaves, in short bright blips.',
    how: 'The arpeggio’s RANDOM mode plays the held notes in a different order every time, across three octaves. Short envelopes turn each note into a blip, and a resonant filter gives it a little ping.',
    phrase: { bpm: 110, loop: true, steps: [[0, 60, 7.8], [0, 63, 7.8], [0, 67, 7.8], [0, 70, 7.8]] },
    steps: [
      { title: 'Random over three octaves', module: 'mode', why: 'RANDOM picks a held note at random on each step.\n- MODE RANDOM, RANGE 3, RATE 7 (about 8 notes a second).\n- Listen for: a scattered, changing pattern.',
        set: { 'arp.mode': 'random', 'arp.range': 3, 'arp.rate': 7 } },
      { title: 'Short blips', module: 'filter', why: 'A resonant filter plucked by ENV-1, and a short ENV-2.\n- CUT OFF FREQ 4.5, RES 5, ENV MOD 6, ENV-1 A 0, D 3.5, S 0, R 3.\n- ENV-2 A 0, D 4, S 0, R 3. VCA LEVEL 10: short blips need the extra level.\n- Listen for: bright, pinging blips.',
        set: { 'vcf.cutoff': 4.5, 'vcf.res': 5, 'vcf.env': 6, ...ENV('env1', 0, 3.5, 0, 3), ...ENV('env2', 0, 4, 0, 3), 'vca.level': 10 } },
      { title: 'Latch it', module: 'mode', why: 'HOLD keeps the arpeggio going after you let go.\n- HOLD UPPER on.\n- Listen for: the pattern carrying on with no keys held. Play a new chord to replace it.',
        set: { 'kbd.holdUpper': true } },
    ],
    context: {
      'arp.range': 'In this sound: how wide the notes are scattered.',
      'vcf.res': 'In this sound: the ping on each blip.',
    },
    tweaks: [
      { id: 'arp.mode', try: 'Press U&D', hear: 'An orderly up-and-down run instead of a scatter.' },
      { id: 'arp.rate', try: 'Raise to 9', hear: 'A fast, glittering spray of notes.' },
    ],
  },
  {
    id: 'jp8-sweep-pad', name: 'Slow Sweep Pad', ref: 'Classic LFO filter sweep', artist: 'Classic technique',
    tags: ['pad', 'ambient', '80s'], level: 1,
    blurb: 'A warm pad whose brightness rolls slowly up and down.',
    how: 'Two detuned saws through a resonant filter, swept very slowly by the LFO, so the chord brightens and darkens over several seconds. Slow envelopes keep it soft.',
    phrase: { bpm: 60, loop: true, steps: [[0, 50, 7.8], [0, 57, 7.8], [0, 62, 7.8], [0, 65, 7.8]] },
    steps: [
      { title: 'Detuned saws, a resonant filter', module: 'filter', why: 'A dark, resonant starting point for the sweep.\n- FINE TUNE +1.5.\n- CUT OFF FREQ 4.5 (about 470 Hz), RES 5.\n- Listen for: a warm chord with a slight hum at the cutoff.',
        set: { 'vco2.fine': 1.5, 'vcf.cutoff': 4.5, 'vcf.res': 5 } },
      { title: 'A slow sweep', module: 'lfo', why: 'The LFO sweeps the cutoff once every few seconds.\n- LFO RATE 2 (0.19 Hz): about one sweep every five seconds.\n- VCF LFO MOD 5.\n- Listen for: the chord slowly brightening and darkening.',
        set: { 'lfo.rate': 2, 'vcf.lfo': 5 } },
      { title: 'Soft envelopes', module: 'amp', why: 'A slow attack and long release.\n- ENV-2 A 7 (700 ms), S 10, R 7.5.\n- Listen for: a smooth swell in and out.',
        set: ENV('env2', 7, 5, 10, 7.5) },
    ],
    context: {
      'vcf.lfo': 'In this sound: how far the sweep moves.',
      'lfo.rate': 'In this sound: how slow the sweep is.',
    },
    tweaks: [
      { id: 'vcf.res', try: 'Raise to 8', hear: 'The sweep turns vocal and whistling.' },
      { id: 'vcf.slope', try: 'Switch to −12 dB/OCT', hear: 'Brighter and buzzier throughout the sweep.' },
    ],
  },
  {
    id: 'jp8-clang', name: 'Metal Clang', ref: 'Classic cross-mod percussion', artist: 'Classic technique',
    tags: ['perc', 'industrial', '80s'], level: 3,
    blurb: 'A hard, clanging metallic hit that drops in pitch as it dies.',
    how: 'Heavy CROSS MOD from an inharmonic VCO-2 makes a dense, metallic spectrum. ENV-1 drops both oscillators’ pitch quickly at the start of each hit, and a short ENV-2 with no sustain makes it percussive.',
    phrase: { bpm: 100, loop: true, steps: [[0, 48, 0.3], [1, 48, 0.3], [1.75, 55, 0.3], [2.5, 48, 0.3], [3, 43, 0.3]] },
    steps: [
      { title: 'Heavy cross modulation', module: 'osc', why: 'A lot of cross mod from VCO-2 tuned to an odd interval.\n- VCO-2 WAVEFORM sine, RANGE +11 (a major seventh up).\n- CROSS MOD 7.\n- SOURCE MIX 3.\n- Listen for: a harsh, metallic tone.',
        set: { 'vco2.wave': 'sine', 'vco2.range': 23, 'vco1.xmod': 7, 'mix.balance': 3 } },
      { title: 'A pitch drop', module: 'mod', why: 'ENV-1 pushes the pitch up for an instant at the start of each hit.\n- VCO MOD ENV 5 (both VCOs).\n- ENV-1 A 0, D 3 (70 ms), S 0, R 3.\n- Listen for: a sharp “tink” falling into the clang.',
        set: { 'vcomod.env': 5, ...ENV('env1', 0, 3, 0, 3) } },
      { title: 'Percussive shape', module: 'amp', why: 'No sustain: each hit dies away.\n- ENV-2 A 0, D 6 (700 ms), S 0, R 5.\n- Listen for: hits ringing briefly, like struck metal.',
        set: ENV('env2', 0, 6, 0, 5) },
    ],
    context: {
      'vco1.xmod': 'In this sound: how harsh the metal is.',
      'vcomod.env': 'In this sound: the depth of the pitch drop.',
    },
    tweaks: [
      { id: 'vco2.range', try: 'Step it a semitone at a time', hear: 'Each step is a different piece of metal.' },
      { id: 'env2.decay', try: 'Lower to 4', hear: 'A short, dry clank.' },
    ],
  },
  {
    id: 'jp8-brass-swell', name: 'Swelling Brass', ref: 'Classic slow brass swell', artist: 'Classic technique',
    tags: ['brass', 'soundtrack', '80s'], level: 2,
    blurb: 'A brass section that swells up slowly and opens out on held chords.',
    how: 'Like a brass stab, but with a slow ENV-1 attack: the filter opens over most of a second as each chord is held, the way a brass section swells. Delayed vibrato from the LFO adds life to long chords.',
    phrase: { bpm: 72, loop: true, steps: [[0, 55, 3.6], [0, 59, 3.6], [0, 62, 3.6], [4, 57, 3.6], [4, 60, 3.6], [4, 64, 3.6]] },
    steps: [
      { title: 'Brass oscillators', module: 'osc', why: 'Two detuned saws.\n- FINE TUNE +0.8. SLOPE −12 dB.\n- Listen for: a bright, buzzy chord.',
        set: { 'vco2.fine': 0.8, 'vcf.slope': '12' } },
      { title: 'A slow filter swell', module: 'filter', why: 'ENV-1 opens the filter slowly.\n- CUT OFF FREQ 3.5, ENV MOD 6.\n- ENV-1 A 7 (700 ms), D 6, S 6, R 6.\n- ENV-2 A 4 (70 ms), S 10, R 5.\n- Listen for: each chord opening up as it is held.',
        set: { 'vcf.cutoff': 3.5, 'vcf.env': 6, ...ENV('env1', 7, 6, 6, 6), ...ENV('env2', 4, 5, 10, 5) } },
      { title: 'Delayed vibrato', module: 'lfo', why: 'A little vibrato, held back until the chord is established.\n- VCO MOD LFO 0.6 (about a sixth of a semitone), LFO RATE 6, DELAY TIME 5 (1.4 s).\n- Listen for: the long chords starting to shimmer after a second.',
        set: { 'vcomod.lfo': 0.6, 'lfo.rate': 6, 'lfo.delay': 5 } },
    ],
    context: {
      'env1.attack': 'In this sound: how slowly the brass opens.',
      'vcf.env': 'In this sound: how bright the swell gets.',
    },
    tweaks: [
      { id: 'env1.attack', try: 'Set between 5 and 8', hear: 'From a quick swell to a slow, cinematic crescendo.' },
      { id: 'vcf.res', try: 'Raise to 4', hear: 'A more nasal, buzzy brass.' },
    ],
  },
];
