// More Model 15 sounds. Shape: see CONTRACT.md → Preset.
export default [
  {
    id: 'm15-glide-lead', name: 'Glide Lead', ref: 'In the style of a 70s Moog solo lead', artist: 'Classic technique',
    tags: ['lead', 'moog', 'vibrato'], level: 1,
    blurb: 'A warm, singing lead that slides between notes with a gentle vibrato.',
    how: 'Two sawtooths a hair apart give a full, slightly moving tone. The ladder filter is half open, with a small push from the envelope at the start of each note. GLIDE slides between notes, and the LFO adds vibrato through PITCH MOD, with MODULATION as its master depth.',
    phrase: { bpm: 96, loop: true, steps: [[0, 67, 0.9], [1, 70, 0.4], [1.5, 72, 1.4], [3, 75, 0.4], [3.5, 72, 0.4], [4, 70, 1.8], [6, 67, 1.8]] },
    steps: [
      { title: 'Two sawtooths, slightly apart', module: 'osc', why: 'Two sawtooths at the same octave, a little out of tune with each other, beat slowly. That gives the lead its width and movement.\n- Oscillator 1 and 2 sawtooth, both OCTAVE 8’.\n- FREQUENCY +0.12: Oscillator 2 a fraction sharp. Too little to sound out of tune, enough to beat.\n- Mixer 1 and 2 at 7.\n- Listen for: a full, gently swirling tone on a held note.',
        set: { 'osc1.wave': 'saw', 'osc1.oct': '8', 'osc2.wave': 'saw', 'osc2.oct': '8', 'osc2.freq': 0.12, 'mix.1': 7, 'mix.2': 7 } },
      { title: 'A half-open filter with a push', module: 'filter', why: 'The filter rounds off the top of the sawtooths, and the envelope opens it a little at the start of each note so the notes speak.\n- CUTOFF 5.5 (about 890 Hz), RESONANCE 2.5.\n- ENV AMT +2.5 (+2.7 octaves).\n- ATTACK 0, DECAY 5 (about 280 ms), SUSTAIN 6, RELEASE 4 (80 ms): a quick push that settles to a held tone.\n- KEY TRACKING 1:2: higher notes stay bright enough.\n- Listen for: each note starting a little brighter, then settling.',
        set: { 'vcf.cutoff': 5.5, 'vcf.res': 2.5, 'vcf.env': 2.5, 'env.attack': 0, 'env.decay': 5, 'env.sustain': 6, 'env.release': 4, 'vcf.kbd': 'half' } },
      { title: 'Glide and vibrato', module: 'lfo', why: 'GLIDE makes each note slide from the last, and the LFO adds a gentle vibrato.\n- GLIDE 4 (about 100 ms): a quick slide, the classic lead portamento.\n- LFO RATE 4.2 (about 4 Hz), WAVEFORM sine: a natural vibrato speed and shape.\n- PITCH MOD 2: how far the LFO can move the pitch.\n- MODULATION 4: the master depth. Together they give about a third of a semitone.\n- Reverb MIX 3: a short spring tail.\n- Listen for: notes sliding into each other and a slight waver on the long ones.',
        set: { glide: 4, 'lfo.rate': 4.2, 'lfo.wave': 'sine', 'lfo.pitch': 2, 'mod.amount': 4, 'rev.mix': 3 } },
    ],
    context: {
      glide: 'In this sound: how long each note takes to slide into the next.',
      'mod.amount': 'In this sound: the depth of the vibrato. At 0 the lead goes still.',
      'osc2.freq': 'In this sound: the slow beating between the oscillators.',
    },
    tweaks: [
      { id: 'mod.amount', try: 'Raise to 7', hear: 'A wide, theatrical vibrato.' },
      { id: 'glide', try: 'Raise to 6', hear: 'Long, swooping slides.' },
      { id: 'vcf.res', try: 'Raise to 6', hear: 'A more vocal, nasal lead.' },
    ],
  },
  {
    id: 'm15-sub-bass', name: 'Sub Bass', ref: 'The sub-oscillator under a square bass', artist: 'Classic technique',
    tags: ['bass', 'sub', 'deep'], level: 1,
    blurb: 'A deep, round bass with a square an octave below holding up the floor.',
    how: 'OSC 2’s waveform switch, turned into its SUB positions, puts the sub-oscillator on mixer channel 3: a square an octave below Oscillator 2. With a sawtooth on top and the filter kept low, the sub gives the bass a weight you feel more than hear.',
    phrase: { bpm: 100, loop: true, steps: [[0, 31, 0.9], [1, 31, 0.4], [1.5, 34, 0.4], [2, 36, 0.9], [3, 38, 0.4], [3.5, 34, 0.4]] },
    steps: [
      { title: 'A sawtooth and a square', module: 'osc', why: 'A sawtooth gives the bass its edge and a square under it its body.\n- Oscillator 1 OCTAVE 16’, WAVEFORM sawtooth, mixer 1 at 5.\n- Oscillator 2 OCTAVE 16’, WAVEFORM square under the SUB bracket, mixer 2 at 4: the square, with the sub-oscillator switched on.\n- Listen for: a full, buzzy bass. The sub is not in yet: mixer 3 is still at 0.',
        set: { 'osc1.oct': '16', 'osc1.wave': 'saw', 'mix.1': 5, 'osc2.oct': '16', 'osc2.wave': 'sq+sub', 'mix.2': 4 } },
      { title: 'Bring in the sub', module: 'mixer', why: 'Mixer channel 3 now carries the sub-oscillator instead of white noise, because OSC 2’s switch is under its SUB bracket.\n- Mixer 3 at 7: a square an octave below Oscillator 2, so 32’ here.\n- Listen for: the bass getting much deeper and heavier. On small speakers you may hear it more as weight than as a note. Turn OSC 2’s switch back to the plain square and channel 3 turns to hiss.',
        set: { 'mix.3': 7 } },
      { title: 'Keep the filter low', module: 'filter', why: 'A low cutoff with a short push from the envelope keeps the bass round, with just enough attack to be heard.\n- CUTOFF 3 (about 160 Hz), RESONANCE 1.\n- ENV AMT +2.5 (+2.7 octaves), ATTACK 0, DECAY 4.5 (about 170 ms), SUSTAIN 4, RELEASE 2.\n- Reverb MIX 0: a bass stays dry.\n- Listen for: a short thump at the start of each note, then a deep, steady tone.',
        set: { 'vcf.cutoff': 3, 'vcf.res': 1, 'vcf.env': 2.5, 'env.attack': 0, 'env.decay': 4.5, 'env.sustain': 4, 'env.release': 2, 'rev.mix': 0 } },
    ],
    context: {
      'mix.3': 'In this sound: the level of the sub-oscillator, the deepest part of the bass.',
      'osc2.wave': 'In this sound: under the SUB bracket, which is what puts the sub on channel 3.',
      'vcf.cutoff': 'In this sound: kept low so the bass stays round.',
    },
    tweaks: [
      { id: 'mix.3', try: 'Turn down to 0 and back up', hear: 'How much of the weight the sub carries.' },
      { id: 'vcf.env', try: 'Raise to 4', hear: 'A harder, brighter attack on each note.' },
      { id: 'osc1.wave', try: 'Switch to narrow pulse', hear: 'A thinner, more nasal top over the same deep floor.' },
    ],
  },
  {
    id: 'm15-filter-whistle', name: 'Filter Whistle', ref: 'The self-oscillating ladder filter played as an oscillator', artist: 'Classic technique',
    tags: ['lead', 'filter', 'sine'], level: 2,
    blurb: 'A pure, whistling tone with no oscillators at all: the filter ringing on its own.',
    how: 'With RESONANCE at full, the ladder filter rings at its cutoff even with nothing coming in, so it makes a near-sine tone of its own. KEY TRACKING 1:1 moves the cutoff with the keys so it plays in tune, and the LFO through FILTER MOD gives it a vibrato.',
    phrase: { bpm: 70, loop: true, steps: [[0, 72, 1.8], [2, 76, 0.9], [3, 79, 0.9], [4, 77, 1.8], [6, 74, 1.8]] },
    steps: [
      { title: 'Silence the mixer', module: 'mixer', why: 'All three mixer channels down, so nothing reaches the filter. The sound will come from the filter itself.\n- Mixer 1, 2 and 3 at 0.\n- Listen for: nothing yet.',
        set: { 'mix.1': 0, 'mix.2': 0, 'mix.3': 0 } },
      { title: 'Make the filter ring', module: 'filter', why: 'At full resonance the ladder filter feeds back on itself and rings at its cutoff: a pure, whistling tone.\n- RESONANCE 10: full. The filter now makes a sound with no input.\n- KEY TRACKING 1:1: the cutoff moves with the keys, one octave per octave, so the whistle plays the notes.\n- CUTOFF 3.7 (about 260 Hz, middle C): sets where the whistle sits; here it is close to in tune with the keys.\n- ENV AMT 0: the envelope leaves the pitch alone.\n- Listen for: a clean, flute-like tone following the keys.',
        set: { 'vcf.res': 10, 'vcf.kbd': 'full', 'vcf.cutoff': 3.7, 'vcf.env': 0 } },
      { title: 'Shape it and add vibrato', module: 'lfo', why: 'A soft start, a slide and a slight vibrato make the whistle sing. The vibrato goes through the filter, because that is what is making the pitch.\n- ATTACK 3 (30 ms), SUSTAIN 10, RELEASE 5 (0.2 s): a soft start and a short tail.\n- GLIDE 3: the whistle slides between notes.\n- LFO RATE 4.5 (about 6 Hz), FILTER MOD 0.5, MODULATION 3: a slight wobble of the cutoff, heard as vibrato.\n- Reverb MIX 4.\n- Listen for: a theremin-like line.',
        set: { 'env.attack': 3, 'env.sustain': 10, 'env.release': 5, glide: 3, 'lfo.rate': 4.5, 'lfo.filter': 0.5, 'mod.amount': 3, 'rev.mix': 4 } },
    ],
    context: {
      'vcf.res': 'In this sound: at full, which is what makes the filter whistle. Below about 9 it goes quiet.',
      'vcf.cutoff': 'In this sound: the tuning of the whistle.',
      'vcf.kbd': 'In this sound: 1:1, so the whistle plays the keys in tune.',
    },
    tweaks: [
      { id: 'vcf.kbd', try: 'Set to 1:2', hear: 'The whistle moves half as far: a squashed scale.' },
      { id: 'mix.1', try: 'Raise to 2', hear: 'Oscillator 1 under the whistle, coloured by the ringing filter.' },
      { id: 'vcf.cutoff', try: 'Turn slowly', hear: 'The whole line moves up or down in pitch.' },
    ],
  },
  {
    id: 'm15-fm-bell', name: 'Cross-Mod Bell', ref: 'Oscillator 1 patched into OSC 2 FM', artist: 'Classic technique',
    tags: ['keys', 'fm', 'patched'], level: 3,
    blurb: 'A metallic, bell-like tone that rings and fades.',
    how: 'A cable from OSC 1 to OSC 2 FM makes Oscillator 1 bend Oscillator 2’s pitch hundreds of times a second. The ear hears that as new, clashing overtones rather than a wobble: a bell or gong. A plucked envelope with no sustain lets each note ring out.',
    phrase: { bpm: 80, loop: true, steps: [[0, 72, 0.5], [1, 79, 0.5], [2, 76, 0.5], [3, 84, 1.5]] },
    steps: [
      { title: 'Oscillator 2 alone', module: 'osc', why: 'Only Oscillator 2 is heard; Oscillator 1 will be used as the modulator, out of the mix.\n- Mixer 1 at 0, mixer 2 at 8.\n- Oscillator 2 WAVEFORM triangle, OCTAVE 8’: a soft tone for the modulation to roughen.\n- Oscillator 1 WAVEFORM triangle, OCTAVE 4’: still running, an octave up, though not in the mix.\n- Listen for: a soft, plain tone.',
        set: { 'mix.1': 0, 'mix.2': 8, 'osc2.wave': 'tri', 'osc2.oct': '8', 'osc1.wave': 'tri', 'osc1.oct': '4' } },
      { title: 'Patch Oscillator 1 into OSC 2 FM', module: 'mod', why: 'A cable from OSC 1 to OSC 2 FM. Oscillator 1 now moves Oscillator 2’s pitch at audio speed, which creates new overtones.\n- Cable OSC 1 → OSC 2 FM.\n- FREQUENCY +3: Oscillator 2 is no longer a simple ratio of Oscillator 1, so the new overtones clash like a bell rather than blending like an organ.\n- Listen for: a metallic, clangy tone. Move FREQUENCY and it changes from bell to gong to glass.',
        set: { 'osc2.freq': 3 }, cables: [['j.osc1_out', 'j.osc2_fm']] },
      { title: 'Let it ring', module: 'env', why: 'A bell has a hard strike and a long fade with no sustain.\n- ATTACK 0, DECAY 6 (about 0.75 s), SUSTAIN 0, RELEASE 6 (0.5 s).\n- CUTOFF 7.5 (about 3.6 kHz), ENV AMT +1.5: the filter mostly open, a little brighter at the strike.\n- Reverb MIX 4: the spring gives the bell a room.\n- Listen for: each note struck and fading away, metallic in the tail.',
        set: { 'env.attack': 0, 'env.decay': 6, 'env.sustain': 0, 'env.release': 6, 'vcf.cutoff': 7.5, 'vcf.env': 1.5, 'rev.mix': 4 } },
    ],
    context: {
      'osc2.freq': 'In this sound: the ratio between the oscillators, which decides how clangy the bell is.',
      'osc1.oct': 'In this sound: the modulator’s range. Lower is rougher, higher is glassier.',
      'env.decay': 'In this sound: how long each strike rings.',
    },
    tweaks: [
      { id: 'osc2.freq', try: 'Try 0, +3 and +5.5', hear: 'At 0 an organ-like tone; off the simple ratios, bells and gongs.' },
      { id: 'osc1.wave', try: 'Switch to sawtooth', hear: 'A harsher, noisier clang.' },
      { id: 'osc1.oct', try: 'Set to 16’', hear: 'A growling, rough modulation instead of a bell.' },
    ],
  },
  {
    id: 'm15-wind', name: 'Wind', ref: 'White noise through a resonant filter swept by the LFO', artist: 'Classic technique',
    tags: ['fx', 'noise', 'ambient'], level: 1,
    blurb: 'Gusts of wind rising and falling.',
    how: 'White noise on mixer channel 3 goes through the ladder filter with a fair amount of resonance, which gives the hiss a whistling centre. A slow LFO sweeps the cutoff up and down, so the wind rises and falls on its own.',
    phrase: { bpm: 60, loop: true, steps: [[0, 48, 7.8]] },
    steps: [
      { title: 'Noise only', module: 'mixer', why: 'Mixer channel 3 carries white noise while OSC 2’s waveform switch is on one of its four plain positions.\n- Mixer 1 and 2 at 0: no oscillators.\n- Mixer 3 at 9: noise, loud.\n- Listen for: a plain hiss.',
        set: { 'mix.1': 0, 'mix.2': 0, 'mix.3': 9, 'osc2.wave': 'saw' } },
      { title: 'A resonant filter', module: 'filter', why: 'Resonance makes the filter boost a band of the noise, so it whistles like wind.\n- CUTOFF 4.5 (about 450 Hz), RESONANCE 7.\n- ENV AMT 0: the envelope leaves the filter alone.\n- Listen for: a hollow, whistling hiss.',
        set: { 'vcf.cutoff': 4.5, 'vcf.res': 7, 'vcf.env': 0 } },
      { title: 'Slow gusts', module: 'lfo', why: 'A slow LFO sweeps the cutoff up and down: the gusts.\n- LFO RATE 1.5 (about one cycle every 3 seconds), WAVEFORM sine.\n- FILTER MOD 6, MODULATION 8: wide sweeps.\n- ATTACK 6 (about 0.45 s), SUSTAIN 10, RELEASE 7 (about 1.3 s): the wind fades in and out with the key.\n- Reverb MIX 5.\n- Listen for: wind rising and falling on its own while the key is held.',
        set: { 'lfo.rate': 1.5, 'lfo.wave': 'sine', 'lfo.filter': 6, 'mod.amount': 8, 'env.attack': 6, 'env.sustain': 10, 'env.release': 7, 'rev.mix': 5 } },
    ],
    context: {
      'vcf.res': 'In this sound: the whistle in the wind.',
      'lfo.rate': 'In this sound: how often the gusts come.',
      'lfo.filter': 'In this sound: how far each gust sweeps.',
    },
    tweaks: [
      { id: 'lfo.wave', try: 'Switch to square', hear: 'Wind that jumps between two pitches, like a siren.' },
      { id: 'vcf.res', try: 'Raise to 9', hear: 'A howling, tonal wind.' },
      { id: 'lfo.rate', try: 'Raise to 3', hear: 'Faster, choppier gusts.' },
    ],
  },
  {
    id: 'm15-inverted-swell', name: 'Opening Swell', ref: 'ENV INV patched into CUTOFF', artist: 'Classic technique',
    tags: ['pad', 'patched', 'swell'], level: 2,
    blurb: 'Each note starts muffled and slowly opens up.',
    how: 'The ENV INV output is the envelope upside down. Patched into CUTOFF, it pulls the filter down at the start of each note and lets it rise as the envelope decays, so the note brightens over a second or so. VCA MODE RELEASE keeps the loudness steady while that happens.',
    phrase: { bpm: 72, loop: true, steps: [[0, 57, 1.8], [2, 60, 1.8], [4, 64, 3.6]] },
    steps: [
      { title: 'Two sawtooths', module: 'osc', why: 'Two sawtooths, slightly apart, give the filter plenty of brightness to reveal.\n- Oscillator 1 and 2 sawtooth, OCTAVE 8’, FREQUENCY +0.1.\n- Mixer 1 and 2 at 6.\n- Listen for: a bright, full tone.',
        set: { 'osc1.wave': 'saw', 'osc1.oct': '8', 'osc2.wave': 'saw', 'osc2.oct': '8', 'osc2.freq': 0.1, 'mix.1': 6, 'mix.2': 6 } },
      { title: 'The envelope, upside down, into CUTOFF', module: 'mod', why: 'ENV INV falls when the envelope rises. Patched into CUTOFF, it closes the filter at the start of each note and lets it open as the envelope dies away.\n- Cable ENV INV → CUTOFF.\n- CUTOFF 7 (about 2.5 kHz): where the filter ends up once the envelope has gone.\n- ENV AMT 0: the envelope’s own path to the filter is off, so only the cable moves it.\n- ATTACK 0, DECAY 6.5 (about 1.2 s), SUSTAIN 0: a fast drop, then a slow opening.\n- Listen for: each note starting dark and brightening.',
        set: { 'vcf.cutoff': 7, 'vcf.env': 0, 'env.attack': 0, 'env.decay': 6.5, 'env.sustain': 0 }, cables: [['j.env_inv', 'j.cutoff']] },
      { title: 'Steady loudness', module: 'amp', why: 'With VCA MODE on ENV, the same envelope would also fade the note out as it opens. RELEASE mode holds full level while the key is down instead.\n- VCA MODE RELEASE, RELEASE 5 (0.2 s).\n- Reverb MIX 3.5.\n- Listen for: steady notes that open up, like a slow wah in reverse.',
        set: { 'vca.mode': 'release', 'env.release': 5, 'rev.mix': 3.5 } },
    ],
    context: {
      'env.decay': 'In this sound: how long each note takes to open up.',
      'vca.mode': 'In this sound: RELEASE, so loudness stays steady while the filter opens. On ENV the notes fade as they brighten.',
      'vcf.cutoff': 'In this sound: how bright each note ends up.',
    },
    tweaks: [
      { id: 'env.decay', try: 'Set to 4', hear: 'A quick “wow” on each note instead of a slow opening.' },
      { id: 'vcf.res', try: 'Raise to 6', hear: 'A vocal, sweeping resonance as it opens.' },
      { id: 'vca.mode', try: 'Switch to ENV', hear: 'Each note fades away as it brightens.' },
    ],
  },
  {
    id: 'm15-thin-pluck', name: 'Thin Pluck', ref: 'The HI PASS filter patched after the VCA', artist: 'Classic technique',
    tags: ['pluck', 'patched', 'high-pass'], level: 3,
    blurb: 'A light, glassy pluck with the low end filtered away.',
    how: 'The separate high-pass filter is out of the sound until patched. A cable from VCA output to HI PASS input and another from HI PASS output to REVERB input put it between the VCA and the reverb, so it trims the low end off the pluck before the spring.',
    phrase: { bpm: 116, loop: true, steps: [[0, 72, 0.2], [0.5, 79, 0.2], [1, 76, 0.2], [1.5, 84, 0.2], [2, 72, 0.2], [2.5, 79, 0.2], [3, 77, 0.2], [3.5, 74, 0.2]] },
    steps: [
      { title: 'A plucked tone', module: 'env', why: 'A sawtooth and a square, with a short envelope and no sustain, give a quick pluck.\n- Oscillator 1 sawtooth and Oscillator 2 square at 8’, mixer 1 at 8, mixer 2 at 7: loud, because the high-pass filter will take a lot away.\n- ATTACK 0, DECAY 4 (about 100 ms), SUSTAIN 0, RELEASE 3.\n- CUTOFF 5 (about 630 Hz), ENV AMT +3 (+3.4 octaves), RESONANCE 3.\n- Listen for: short, bright plucks with a full low end.',
        set: { 'osc1.wave': 'saw', 'osc1.oct': '8', 'osc2.wave': 'sq', 'osc2.oct': '8', 'mix.1': 8, 'mix.2': 7, 'env.attack': 0, 'env.decay': 4, 'env.sustain': 0, 'env.release': 3, 'vcf.cutoff': 5, 'vcf.env': 3, 'vcf.res': 3 } },
      { title: 'Patch the high-pass filter in', module: 'util', why: 'Two cables put the HI PASS filter between the VCA and the reverb.\n- Cable VCA → HI PASS (input): the VCA’s output into the high-pass filter.\n- Cable HI PASS (output) → REVERB (input): the filtered pluck into the reverb, in place of the plain VCA output.\n- HI PASS FILTER 5 (about 400 Hz): the low end is cut away.\n- Listen for: the pluck losing its body and turning light and glassy. Turn HI PASS FILTER to 0 and the body comes back.',
        set: { 'hpf.cutoff': 5 }, cables: [['j.vca_out', 'j.hp_in'], ['j.hp_out', 'j.rev_in']] },
      { title: 'Into the spring', module: 'fx', why: 'The reverb now gets only the thin, filtered pluck, so its tail is bright and clean rather than boomy.\n- Reverb MIX 5.\n- VOLUME 9: a little more level to make up for what the high-pass filter removed.\n- Listen for: a light, sparkling line with a splashy tail.',
        set: { 'rev.mix': 5, 'out.volume': 9 } },
    ],
    context: {
      'hpf.cutoff': 'In this sound: how much of the low end is cut away.',
      'rev.mix': 'In this sound: how much spring the thin pluck gets.',
      'env.decay': 'In this sound: the length of each pluck.',
    },
    tweaks: [
      { id: 'hpf.cutoff', try: 'Sweep from 2 to 8', hear: 'From a full pluck to a tiny, tinny click.' },
      { id: 'vcf.res', try: 'Raise to 7', hear: 'A ringing, wet pluck.' },
      { id: 'osc1.oct', try: 'Set to 4’', hear: 'A higher, more delicate line.' },
    ],
  },
];
