// Behringer System 15 — the rest of the sound library (same shape as the presets in src/synths/system-15.js).
import { KEYS, LINK2, TRIGS, VOICE } from '@/synths/moog900/cables.js';

export default [
  {
    id: 's15-percussive-lead', name: 'Percussive Lead', ref: 'From the Behringer System 15 guide', artist: 'Behringer',
    tags: ['seq', 'lead', 'guide'], level: 2,
    blurb: 'A triangle and a detuned sawtooth with a hard front and a filter that keeps moving: made for fast melodic lines.',
    how: 'The guide’s percussive lead. The first 911 gives the amplifier an instant attack and a short fall to a low sustain, so each note has a hard front. The second 911 opens the filter slowly and lets it go over seconds, and the slow 921 adds a gentle sweep on top, so a repeated pattern never sounds quite the same twice.',
    phrase: { bpm: 120, loop: true, steps: [[0, 48, 0.4], [0.5, 55, 0.4], [1, 60, 0.4], [1.5, 63, 0.4], [2, 60, 0.4], [2.5, 55, 0.4], [3, 58, 0.4], [3.5, 60, 0.4]] },
    steps: [
      { title: 'Triangle and sawtooth', module: 'osc',
        why: 'Two linked 921Bs: the first’s TRIANGLE and the second’s SAWTOOTH into the mixer, then the usual filter and amplifier.\n- Cables: the keyboard to the 921A and both 921Bs; TRIANGLE (1) to CP3A-M INPUT 1, SAWTOOTH (2) to INPUT 2; CP3A-M to 904A to 902 (1) to OUTPUT.\n- 921B (2) FREQUENCY +0.08: slightly detuned.\n- CP3A-M GAIN 1 at 7, GAIN 2 at 5, MASTER 8.\n- 904A FIXED CONTROL VOLTAGE −1, REGENERATION 3.',
        set: { 'm921b_2.frequency': 0.08, 'cp3am_1.gain1': 7, 'cp3am_1.gain2': 5, 'cp3am_1.master': 8, 'm904a.fixed_cv': -1, 'm904a.regeneration': 3 },
        cables: [...KEYS, ...LINK2, ['j.m921b_1.triangle', 'j.cp3am_1.in1'], ['j.m921b_2.sawtooth', 'j.cp3am_1.in2'], ...VOICE] },
      { title: 'A hard front', module: 'env',
        why: 'The first 911 on the amplifier: no attack, a short fall to a low sustain.\n- Cables: CM1A TRIG through CP35 MULTIPLE A to both 911s; 911 (1) OUT to 902 (1) CONTROL INPUT 1.\n- 911 (1): T1 0, T2 5.4 (200 ms), E SUS 4, T3 5.4.\n- Listen for: notes that start with a click of energy and drop back.',
        set: { 'm911_1.t1': 0, 'm911_1.t2': 5.4, 'm911_1.esus': 4, 'm911_1.t3': 5.4 },
        cables: [...TRIGS, ['j.m911_1.out', 'j.m902_1.cv_1']] },
      { title: 'Slow filter movement', module: 'filter',
        why: 'The second 911 opens the filter over about a second and lets it go over four; the 921, as a slow LFO, sways it as well, through CP35 attenuator 1.\n- 911 (2): T1 7.3, T2 3.8, E SUS 9, T3 8.9.\n- 921 COARSE RNG on SUB, FREQUENCY −1. CP35 ATTENUATOR 1 at 1.5.\n- Cables: 911 (2) OUT to 904A CONTROL INPUT 2; 921 SINE to CP35 IN 1, CP35 OUT 1 to 904A CONTROL INPUT 1.\n- Listen for: the line gets brighter the longer you keep playing, and breathes slowly.',
        set: { 'm911_2.t1': 7.3, 'm911_2.t2': 3.8, 'm911_2.esus': 9, 'm911_2.t3': 8.9, 'm921.coarse': 'sub', 'm921.frequency': -1, 'cp35.att1': 1.5 },
        cables: [['j.m911_2.out', 'j.m904a.cv_2'], ['j.m921.sine', 'j.cp35.att_in1'], ['j.cp35.att_out1', 'j.m904a.cv_1']] },
    ],
    context: {
      'm911_1.esus': 'In this sound: how much of each note is left after the hard front.',
      'm911_2.t1': 'In this sound: how slowly the filter opens, so a run of notes brightens as it goes.',
      'cp35.att1': 'In this sound: how far the 921 sways the filter.',
      'm904a.regeneration': 'In this sound: a little resonance for bite.',
    },
    tweaks: [
      { id: 'm911_1.esus', try: 'Turn E SUS on the first 911 down to 0', hear: 'Every note becomes a short pluck.' },
      { id: 'm911_2.t1', try: 'Turn T1 on the second 911 down to 3', hear: 'The filter snaps open on each note instead of building up.' },
    ],
  },
  {
    id: 's15-ladder-bass', name: 'Ladder Bass', ref: 'The classic modular bass', artist: 'Behringer',
    tags: ['bass', 'basics'], level: 1,
    blurb: 'Two oscillators an octave apart through the ladder filter, with a snappy filter envelope and key tracking.',
    how: 'A sawtooth at 8’ and a rectangular wave an octave below at 16’ give a deep, solid base. The 904A is closed well down and the second 911 snaps it open on each note, which gives the round “thump”. The CM1A’s second CV goes to the filter too, so high notes are as bright as low ones. The 902 is set to EXP, which makes the loudness envelope snappier.',
    phrase: { bpm: 110, loop: true, steps: [[0, 36, 0.45], [0.5, 36, 0.45], [1, 43, 0.45], [1.5, 36, 0.45], [2, 46, 0.45], [2.5, 36, 0.45], [3, 41, 0.45], [3.5, 43, 0.45]] },
    steps: [
      { title: 'Two oscillators an octave apart', module: 'osc',
        why: 'The first 921B’s SAWTOOTH at 8’ and the second’s RECTANGULAR an octave down at 16’, both from the keyboard.\n- 921B (1) RANGE 8’, 921B (2) RANGE 16’.\n- CP3A-M GAIN 1 at 7, GAIN 2 at 5, MASTER 8.\n- Cables: the keyboard to both 921Bs; SAWTOOTH (1) to INPUT 1, RECTANGULAR (2) to INPUT 2; CP3A-M to 904A to 902 (1) to OUTPUT.',
        set: { 'm921b_1.range': "8'", 'm921b_2.range': "16'", 'cp3am_1.gain1': 7, 'cp3am_1.gain2': 5, 'cp3am_1.master': 8 },
        cables: [...KEYS, ...LINK2, ['j.m921b_1.sawtooth', 'j.cp3am_1.in1'], ['j.m921b_2.rectangular', 'j.cp3am_1.in2'], ...VOICE] },
      { title: 'Snappy envelopes', module: 'env',
        why: 'Both 911s with no attack. The first opens the 902 (on EXP), the second snaps the closed filter open.\n- 902 (1) CONTROL MODE EXP.\n- 911 (1): T1 0, T2 6, E SUS 9, T3 3.5 (on EXP the sustain needs to be high to be heard). 911 (2): T1 0, T2 5, E SUS 2, T3 3.5.\n- 904A FIXED CONTROL VOLTAGE 0, REGENERATION 3.\n- Cables: the triggers to both 911s; 911 (1) to 902 (1) CONTROL INPUT 1; 911 (2) to 904A CONTROL INPUT 1.\n- Listen for: a round, punchy bass with a “thump” on each note.',
        set: { 'm902_1.mode': 'exp', 'm911_1.t1': 0, 'm911_1.t2': 6, 'm911_1.esus': 9, 'm911_1.t3': 3.5, 'm911_2.t1': 0, 'm911_2.t2': 5, 'm911_2.esus': 2, 'm911_2.t3': 3.5, 'm904a.fixed_cv': 0, 'm904a.regeneration': 3 },
        cables: [...TRIGS, ['j.m911_1.out', 'j.m902_1.cv_1'], ['j.m911_2.out', 'j.m904a.cv_1']] },
      { title: 'The filter follows the keys', module: 'filter',
        why: 'The CM1A’s second CV goes to the filter as well, at 1 V per octave, so it opens by an octave for every octave you play.\n- Cable: CM1A CV 2 to 904A CONTROL INPUT 2.\n- Listen for: the high notes of the riff stay as bright as the low ones.',
        set: {}, cables: [['j.cm1a.cv_2', 'j.m904a.cv_2']] },
    ],
    context: {
      'm904a.fixed_cv': 'In this sound: how dark the bass is under the thump.',
      'm911_2.t2': 'In this sound: the length of the thump.',
      'm902_1.mode': 'In this sound: EXP makes the loudness drop away faster after the start.',
      'm904a.regeneration': 'In this sound: a little resonance gives the thump its “wow”.',
    },
    tweaks: [
      { id: 'm904a.regeneration', try: 'Turn REGENERATION up to 7', hear: 'A squelchy, rubbery bass.' },
      { id: 'm911_2.t2', try: 'Turn T2 on the second 911 up to 6.5', hear: 'A longer, slower “wow” on each note.' },
    ],
  },
  {
    id: 's15-sync-sweep', name: 'Sync Sweep', ref: 'Hard sync on a modular', artist: 'Behringer',
    tags: ['lead', 'sync'], level: 3,
    blurb: 'One 921B hard-synced to the other, with an envelope sweeping its pitch: the tearing sync lead.',
    how: 'The second 921B is set to STRONG sync and fed the first one’s sawtooth, so it restarts on every cycle of the first and keeps that pitch. Raising its own frequency then changes only its tone, adding a vocal, tearing edge. The second 911, turned down through a CP35 attenuator, pushes its pitch up at the start of each note, so every note sweeps.',
    phrase: { bpm: 96, loop: true, steps: [[0, 60, 1.5], [1.5, 63, 0.5], [2, 67, 1], [3, 65, 1], [4, 63, 2], [6, 60, 2]] },
    steps: [
      { title: 'Lock one oscillator to the other', module: 'osc',
        why: 'Both 921Bs follow the keyboard. The first’s SAWTOOTH goes to the second’s SYNC IN, and only the second is heard.\n- 921B (2) SYNC STRONG, FREQUENCY +5.\n- Cables: the keyboard to both 921Bs; SAWTOOTH (1) to 921B (2) SYNC IN; SAWTOOTH (2) to CP3A-M INPUT 1; then the usual filter, amplifier and envelope on the 902.\n- CP3A-M GAIN 1 at 7, MASTER 8. 904A FIXED CONTROL VOLTAGE 3.\n- 911 (1): T1 1, T2 6, E SUS 8, T3 5.\n- Listen for: a bright, nasal tone at the first oscillator’s pitch.',
        set: { 'm921b_2.sync': 'strong', 'm921b_2.frequency': 5, 'cp3am_1.gain1': 7, 'cp3am_1.master': 8, 'm904a.fixed_cv': 3, 'm911_1.t1': 1, 'm911_1.t2': 6, 'm911_1.esus': 8, 'm911_1.t3': 5 },
        cables: [...KEYS, ...LINK2, ['j.m921b_1.sawtooth', 'j.m921b_2.sync'], ['j.m921b_2.sawtooth', 'j.cp3am_1.in1'], ...VOICE, ...TRIGS, ['j.m911_1.out', 'j.m902_1.cv_1']] },
      { title: 'An envelope sweeps the synced pitch', module: 'env',
        why: 'The second 911 goes through CP35 attenuator 1 to the second 921B’s DC MOD. Each note starts with its pitch high and falls back, so the tone sweeps.\n- 911 (2): T1 0, T2 6.5, E SUS 2, T3 5.\n- CP35 ATTENUATOR 1 at 3: up to about 1.8 V, nearly two octaves.\n- Cables: 911 (2) OUT to CP35 IN 1, CP35 OUT 1 to 921B (2) DC MOD.\n- Listen for: a tearing “yow” at the start of every note.',
        set: { 'm911_2.t1': 0, 'm911_2.t2': 6.5, 'm911_2.esus': 2, 'm911_2.t3': 5, 'cp35.att1': 3 },
        cables: [['j.m911_2.out', 'j.cp35.att_in1'], ['j.cp35.att_out1', 'j.m921b_2.dc_mod']] },
    ],
    context: {
      'm921b_2.frequency': 'In this sound: the tone of the synced oscillator, not its pitch. Sweep it and listen to the harmonics move.',
      'm921b_2.sync': 'In this sound: STRONG locks it. Try OFF to hear the two oscillators drift apart.',
      'cp35.att1': 'In this sound: how far the envelope sweeps the synced pitch.',
      'm911_2.t2': 'In this sound: how long the sweep takes.',
    },
    tweaks: [
      { id: 'm921b_2.sync', try: 'Switch SYNC on the second 921B to OFF', hear: 'The sweep becomes an ordinary pitch bend at the start of each note.' },
      { id: 'cp35.att1', try: 'Turn ATTENUATOR 1 up to 6', hear: 'A much wider, screaming sweep.' },
    ],
  },
  {
    id: 's15-formant', name: 'Talking Filter Bank', ref: 'The 914 Fixed Filter Bank', artist: 'Behringer',
    tags: ['keys', 'formant'], level: 2,
    blurb: 'Two oscillators through the 914 with its bands set into an “ah” vowel, so every note sounds sung.',
    how: 'The 914 does not follow the note: its fourteen bands sit at fixed frequencies. That is what a voice does too: the shape of the mouth makes fixed peaks (formants) whatever note is sung. Here the bands round 700 Hz and 1 kHz are up, with a smaller peak near 2.8 kHz and the rest down, which is roughly the vowel “ah”. Play up and down and listen to the vowel stay put while the pitch moves.',
    phrase: { bpm: 84, loop: true, steps: [[0, 48, 1.8], [2, 52, 1.8], [4, 55, 1.8], [6, 53, 1.8]] },
    steps: [
      { title: 'Into the filter bank, all bands open', module: 'filter',
        why: 'A RECTANGULAR and a SAWTOOTH mixed and sent through the 914 instead of the 904A, then the 902 and its envelope.\n- Cables: the keyboard to both 921Bs; RECTANGULAR (1) and SAWTOOTH (2) to the mixer; CP3A-M OUTPUT + to 914 INPUT 1; 914 OUTPUT 1 to 902 (1) SIG IN +; 902 (1) to OUTPUT; CM1A TRIG to 911 (1); 911 (1) to 902 (1).\n- CP3A-M GAIN 1 and 2 at 5, MASTER 7. 921B (2) FREQUENCY +0.1.\n- 911 (1): T1 4, T2 7, E SUS 8, T3 6.\n- Every 914 knob at 10: the bank is flat, so the sound is plain.',
        set: { 'cp3am_1.gain1': 5, 'cp3am_1.gain2': 5, 'cp3am_1.master': 7, 'm921b_2.frequency': 0.1, 'm911_1.t1': 4, 'm911_1.t2': 7, 'm911_1.esus': 8, 'm911_1.t3': 6 },
        cables: [...KEYS, ...LINK2, ['j.m921b_1.rectangular', 'j.cp3am_1.in1'], ['j.m921b_2.sawtooth', 'j.cp3am_1.in2'], ['j.cp3am_1.out_pos_1', 'j.m914.in_1'], ['j.m914.out_1', 'j.m902_1.sig_in_pos'], ['j.m902_1.out_pos', 'j.out.l'], ['j.cm1a.trig_upper', 'j.m911_1.strig'], ['j.m911_1.out', 'j.m902_1.cv_1']] },
      { title: 'Shape an “ah”', module: 'filter',
        why: 'Peaks round 700 Hz and 1 kHz, a smaller one near 2.8 kHz, and the rest turned down.\n- LOW PASS 3, 125 2, 175 2, 250 3, 350 5, 500 8, 700 10, 1000 10, 1400 6, 2000 3, 2800 7, 4000 3, 5600 1, HIGH PASS 0.\n- Listen for: an open vowel that stays the same as the notes move.',
        set: { 'm914.band_low_pass': 3, 'm914.band_125': 2, 'm914.band_175': 2, 'm914.band_250': 3, 'm914.band_350': 5, 'm914.band_500': 8, 'm914.band_700': 10, 'm914.band_1000': 10, 'm914.band_1400': 6, 'm914.band_2000': 3, 'm914.band_2800': 7, 'm914.band_4000': 3, 'm914.band_5600': 1, 'm914.band_high_pass': 0 },
        cables: [] },
    ],
    context: {
      'm914.band_700': 'In this sound: the first vowel peak.',
      'm914.band_1000': 'In this sound: the first vowel peak, with 700 Hz.',
      'm914.band_2800': 'In this sound: the second, higher vowel peak.',
      'm914.band_350': 'In this sound: turn this up and 700 down and the vowel closes towards “oh”.',
    },
    tweaks: [
      { id: 'm914.band_350', try: 'Turn 350 up to 10 and 1000 down to 3', hear: 'The vowel darkens towards “oh”.' },
      { id: 'm914.band_2000', try: 'Turn 2000 up to 10 and 700 down to 4', hear: 'A brighter, thinner vowel, nearer “eh”.' },
    ],
  },
  {
    id: 's15-ghost-wind', name: 'Ghost Wind', ref: 'Resonant noise', artist: 'Behringer',
    tags: ['fx', 'noise'], level: 2,
    blurb: 'Pink noise through a ringing filter that the keyboard tunes, so the wind whistles your notes.',
    how: 'Noise has every frequency in it, so a resonant filter picks out a pitch from it: a whistle in the wind. With REGENERATION high the 904A rings at its cutoff, and the keyboard CV on a control input moves the cutoff an octave per octave, so the whistle plays your notes. The slow 921 sways it, and a 911 with long times swells it in and out.',
    phrase: { bpm: 60, loop: true, steps: [[0, 60, 3], [4, 67, 3]] },
    steps: [
      { title: 'Noise through the filter', module: 'filter',
        why: 'Pink noise into the 904A with high REGENERATION, then the 902 under a slow envelope.\n- Cables: 923 PINK NOISE 1 to 904A SIG IN, 904A to 902 (1) to OUTPUT; CM1A TRIG to 911 (1), 911 (1) to 902 (1).\n- 904A FIXED CONTROL VOLTAGE 0, REGENERATION 8.5.\n- 911 (1): T1 7.5, T2 7, E SUS 9, T3 8.5.\n- Listen for: a breathy whistle that swells in and fades.',
        set: { 'm904a.fixed_cv': 0, 'm904a.regeneration': 8.5, 'm911_1.t1': 7.5, 'm911_1.t2': 7, 'm911_1.esus': 9, 'm911_1.t3': 8.5 },
        cables: [['j.m923.pink_1', 'j.m904a.sig_in'], ['j.m904a.sig_out', 'j.m902_1.sig_in_pos'], ['j.m902_1.out_pos', 'j.out.l'], ['j.cm1a.trig_upper', 'j.m911_1.strig'], ['j.m911_1.out', 'j.m902_1.cv_1']] },
      { title: 'The keys tune the whistle', module: 'mod',
        why: 'The CM1A CV goes straight to the filter’s cutoff, at 1 V per octave.\n- Cable: CM1A CV 1 to 904A CONTROL INPUT 1.\n- Listen for: the whistle now follows the notes.',
        set: {}, cables: [['j.cm1a.cv_1', 'j.m904a.cv_1']] },
      { title: 'A slow sway', module: 'lfo',
        why: 'The 921 on SUB, turned down through CP35 attenuator 1, wobbles the cutoff a little.\n- 921 COARSE RNG on SUB, FREQUENCY −2. CP35 ATTENUATOR 1 at 0.4.\n- Cables: 921 SINE to CP35 IN 1, CP35 OUT 1 to 904A CONTROL INPUT 2.\n- Listen for: the whistle wavers like wind in a gap.',
        set: { 'm921.coarse': 'sub', 'm921.frequency': -2, 'cp35.att1': 0.4 },
        cables: [['j.m921.sine', 'j.cp35.att_in1'], ['j.cp35.att_out1', 'j.m904a.cv_2']] },
    ],
    context: {
      'm904a.regeneration': 'In this sound: how pitched the wind is. Lower is more hiss; higher is more whistle.',
      'm911_1.t1': 'In this sound: how slowly each gust swells in.',
      'cp35.att1': 'In this sound: how far the whistle wavers.',
    },
    tweaks: [
      { id: 'm904a.regeneration', try: 'Turn REGENERATION down to 6', hear: 'More rushing noise, less note.' },
      { id: 'cp35.att1', try: 'Turn ATTENUATOR 1 up to 2', hear: 'A howling, swooping wind.' },
    ],
  },
  {
    id: 's15-brass', name: 'Modular Brass', ref: 'In the style of Wendy Carlos — "Switched-On Bach"', artist: 'Wendy Carlos',
    tags: ['brass', 'classical'], level: 2,
    blurb: 'Two detuned sawtooths with a filter that opens a little slower than the loudness: a bright, brassy swell.',
    how: 'Brass gets brighter as it gets louder. Here the second 911 opens the 904A over about 140 ms while the first opens the amplifier a little faster, so each note starts soft and blooms. The keyboard also moves the filter, so the tone is even across the range. The two sawtooths are a few cents apart for body.',
    phrase: { bpm: 100, loop: true, steps: [[0, 55, 0.9], [1, 60, 0.9], [2, 62, 0.45], [2.5, 64, 0.45], [3, 62, 0.9], [4, 60, 1.9], [6, 59, 0.9], [7, 60, 0.9]] },
    steps: [
      { title: 'Two detuned sawtooths', module: 'osc',
        why: 'Both 921B SAWTOOTH outputs mixed, the second a few cents sharp, through the usual voice.\n- 921B (2) FREQUENCY +0.12.\n- CP3A-M GAIN 1 and 2 at 6, MASTER 8.\n- Cables: the keyboard to both 921Bs; both SAWTOOTHs to the mixer; CP3A-M to 904A to 902 (1) to OUTPUT.',
        set: { 'm921b_2.frequency': 0.12, 'cp3am_1.gain1': 6, 'cp3am_1.gain2': 6, 'cp3am_1.master': 8 },
        cables: [...KEYS, ...LINK2, ['j.m921b_1.sawtooth', 'j.cp3am_1.in1'], ['j.m921b_2.sawtooth', 'j.cp3am_1.in2'], ...VOICE] },
      { title: 'Loudness, then brightness', module: 'env',
        why: 'The first 911 opens the amplifier; the second opens the filter a little later and further.\n- 911 (1): T1 3.5, T2 6, E SUS 8, T3 5.\n- 911 (2): T1 5, T2 6.5, E SUS 5, T3 5.\n- 904A FIXED CONTROL VOLTAGE −2, REGENERATION 1.\n- Cables: triggers to both 911s; 911 (1) to 902 (1); 911 (2) to 904A CONTROL INPUT 1.\n- Listen for: each note swells in and brightens: “bwah”.',
        set: { 'm911_1.t1': 3.5, 'm911_1.t2': 6, 'm911_1.esus': 8, 'm911_1.t3': 5, 'm911_2.t1': 5, 'm911_2.t2': 6.5, 'm911_2.esus': 5, 'm911_2.t3': 5, 'm904a.fixed_cv': -2, 'm904a.regeneration': 1 },
        cables: [...TRIGS, ['j.m911_1.out', 'j.m902_1.cv_1'], ['j.m911_2.out', 'j.m904a.cv_1']] },
      { title: 'Even tone across the keys', module: 'filter',
        why: 'CM1A CV 2 to the filter, so it tracks the notes.\n- Cable: CM1A CV 2 to 904A CONTROL INPUT 2.',
        set: {}, cables: [['j.cm1a.cv_2', 'j.m904a.cv_2']] },
    ],
    context: {
      'm911_2.t1': 'In this sound: how slowly the brightness blooms. Longer is softer and more like a horn section.',
      'm911_2.esus': 'In this sound: how bright a held note stays.',
      'm921b_2.frequency': 'In this sound: the detune that gives the section its body.',
    },
    tweaks: [
      { id: 'm911_2.t1', try: 'Turn T1 on the second 911 up to 6.5', hear: 'A slow, swelling French-horn attack.' },
      { id: 'm904a.fixed_cv', try: 'Turn the 904A FIXED CONTROL VOLTAGE up to 0', hear: 'A brighter, brassier trumpet tone.' },
    ],
  },
  {
    id: 's15-clangy-bell', name: 'Clangy Bell', ref: 'Audio-rate FM between two oscillators', artist: 'Behringer',
    tags: ['keys', 'fm', 'bell'], level: 3,
    blurb: 'The 921 at audio rate shaking a 921B’s pitch through AC MOD: metallic, bell-like overtones that ring away.',
    how: 'Frequency modulation at audio rate does not sound like vibrato: it adds new overtones. When the two oscillators are at an odd ratio the overtones do not line up with the harmonic series, and the result is a bell or a gong. Both oscillators follow the keyboard (the 921 from CM1A CV 2), so the ratio, and with it the bell’s character, stays the same in every key. A 902 on EXP with a long T2 makes the strike and ring.',
    phrase: { bpm: 70, loop: true, steps: [[0, 60, 0.5], [1, 67, 0.5], [2, 64, 0.5], [3, 72, 2]] },
    steps: [
      { title: 'A pure sine, struck', module: 'osc',
        why: 'The first 921B’s SINE straight into the 902, with a percussive envelope.\n- Cables: the keyboard to the 921A and 921B (1); SINE (1) to 902 (1) SIG IN +; 902 (1) to OUTPUT; CM1A TRIG to 911 (1); 911 (1) to 902 (1).\n- 902 (1) CONTROL MODE EXP.\n- 911 (1): T1 0, T2 8, E SUS 0, T3 7.5.\n- Listen for: a soft, struck sine, like a tuning fork.',
        set: { 'm902_1.mode': 'exp', 'm911_1.t1': 0, 'm911_1.t2': 8, 'm911_1.esus': 0, 'm911_1.t3': 7.5 },
        cables: [...KEYS, ['j.m921b_1.sine', 'j.m902_1.sig_in_pos'], ['j.m902_1.out_pos', 'j.out.l'], ['j.cm1a.trig_upper', 'j.m911_1.strig'], ['j.m911_1.out', 'j.m902_1.cv_1']] },
      { title: 'The 921 at an odd ratio', module: 'mod',
        why: 'The 921 in its audio range, following the keys and tuned 7.9 semitones above the 921B at 4’, goes through CP35 attenuator 1 into the 921B’s AC MOD.\n- 921 COARSE RNG on AUDIO, RANGE 4’, SCALE ±12 SEMI, FREQUENCY 3.95 (7.9 semitones).\n- CP35 ATTENUATOR 1 at 4.\n- Cables: CM1A CV 2 to 921 FREQUENCY CONTROL INPUT 1; 921 SINE to CP35 IN 1; CP35 OUT 1 to 921B (1) AC MOD.\n- Listen for: a clangy, metallic bell.',
        set: { 'm921.coarse': 'audio', 'm921.range': "4'", 'm921.scale': 'semitone', 'm921.frequency': 3.95, 'cp35.att1': 4 },
        cables: [['j.cm1a.cv_2', 'j.m921.freq_cv_1'], ['j.m921.sine', 'j.cp35.att_in1'], ['j.cp35.att_out1', 'j.m921b_1.ac_mod']] },
    ],
    context: {
      'cp35.att1': 'In this sound: the FM depth. More gives more, harsher overtones.',
      'm921.frequency': 'In this sound: the ratio between the two oscillators. Whole octaves sound like harmonic tones; odd settings like bells.',
      'm911_1.t2': 'In this sound: how long the bell rings.',
    },
    tweaks: [
      { id: 'm921.frequency', try: 'Set the 921 FREQUENCY to 6 (an octave)', hear: 'A harmonic, electric-piano-like tone instead of a bell.' },
      { id: 'cp35.att1', try: 'Turn ATTENUATOR 1 up to 8', hear: 'A crashing, gong-like clang.' },
    ],
  },
  {
    id: 's15-upside-down', name: 'Upside-Down Trigger', ref: 'S-triggers and V-triggers', artist: 'Behringer',
    tags: ['fx', 'basics', 'triggers'], level: 2,
    blurb: 'A lesson in Moog triggers: what a V-trigger does to a 911, and the two ways to put it right.',
    how: 'Moog envelopes are fired by an S-trigger: a line pulled down to 0 V while a key is held. Most other gear sends a V-trigger: +5 V while the key is held. Patch a V-trigger into a 911 and it reads “key held” when nothing is played, and “let go” when you press a key, so the sound plays backwards. The CM1A can send either kind (TRIG MODE), and the 961 converts one into the other.',
    phrase: { bpm: 80, loop: true, steps: [[0, 60, 1], [2, 64, 1], [4, 67, 1], [6, 64, 1]] },
    steps: [
      { title: 'A V-trigger into an S-trigger input', module: 'env',
        why: 'The usual voice, but with the CM1A set to send V-triggers.\n- CM1A TRIG MODE on V-TRIG.\n- Cables: the keyboard to the 921A and 921B (1); SAWTOOTH (1) to 904A SIG IN; 904A to 902 (1) to OUTPUT; CM1A TRIG (upper) to 911 (1) S-TRIG IN; 911 (1) to 902 (1).\n- 904A FIXED CONTROL VOLTAGE 2. 911 (1): T1 3, T2 6, E SUS 8, T3 6.\n- Listen for: sound between the notes, and silence fading in while each key is held. It is upside down.',
        set: { 'cm1a.trig_mode': 'v_trig', 'm904a.fixed_cv': 2, 'm911_1.t1': 3, 'm911_1.t2': 6, 'm911_1.esus': 8, 'm911_1.t3': 6 },
        cables: [...KEYS, ['j.m921b_1.sawtooth', 'j.m904a.sig_in'], ['j.m904a.sig_out', 'j.m902_1.sig_in_pos'], ['j.m902_1.out_pos', 'j.out.l'], ['j.cm1a.trig_upper', 'j.m911_1.strig'], ['j.m911_1.out', 'j.m902_1.cv_1']] },
      { title: 'Fix one: switch the CM1A to S-TRIG', module: 'env',
        why: 'The CM1A sends the kind of trigger the 911 expects.\n- CM1A TRIG MODE on S-TRIG.\n- Listen for: ordinary notes again.',
        set: { 'cm1a.trig_mode': 's_trig' }, cables: [] },
      { title: 'Fix two: the 961 converts', module: 'util',
        why: 'With TRIG MODE on BOTH the upper TRIG is an S-trigger and the lower a V-trigger. The lower one goes through the 961 (V-TRIG IN A to S-TRIG OUT) to fire the second 911, which sweeps the filter.\n- CM1A TRIG MODE on BOTH.\n- Cables: CM1A TRIG (lower) to 961 V-TRIG IN A (left) 1; 961 S-TRIG OUT (left) to 911 (2) S-TRIG IN; 911 (2) OUT to 904A CONTROL INPUT 1.\n- 904A FIXED CONTROL VOLTAGE −1. 911 (2): T1 2, T2 5.5, E SUS 3, T3 5.\n- Listen for: both envelopes the right way up: notes with a filter sweep.',
        set: { 'cm1a.trig_mode': 'both', 'm904a.fixed_cv': -1, 'm911_2.t1': 2, 'm911_2.t2': 5.5, 'm911_2.esus': 3, 'm911_2.t3': 5 },
        cables: [['j.cm1a.trig_lower', 'j.m961.vtrig_a_l_1'], ['j.m961.strig_out_l', 'j.m911_2.strig'], ['j.m911_2.out', 'j.m904a.cv_1']] },
    ],
    context: {
      'cm1a.trig_mode': 'In this sound: the whole lesson. V-TRIG plays it upside down; S-TRIG and BOTH play it the right way up.',
      'm911_1.t1': 'In this sound: with the trigger upside down you hear this as the fade-in after each key is let go.',
    },
    tweaks: [
      { id: 'cm1a.trig_mode', try: 'Switch TRIG MODE back to V-TRIG', hear: 'Both envelopes run backwards again: the first through the upper jack, the second through the 961, which now converts the wrong way round.' },
    ],
  },
  {
    id: 's15-singing-filter', name: 'Singing Filter', ref: 'The 904A as an oscillator', artist: 'Behringer',
    tags: ['lead', 'filter'], level: 3,
    blurb: 'No oscillator at all: the 904A rings on its own as a sine wave, played from the keyboard.',
    how: 'At full REGENERATION the 904A whistles at its cutoff frequency with nothing at its input. Its cutoff responds at 1 V per octave, the same as the oscillators, so the CM1A CV on a control input plays it in tune. A 911 on a 902 makes notes, and the 921, turned well down, adds a vibrato. It is a pure, flute-like tone.',
    phrase: { bpm: 76, loop: true, steps: [[0, 72, 1.5], [1.5, 74, 0.5], [2, 76, 2], [4, 79, 1], [5, 76, 1], [6, 74, 2]] },
    steps: [
      { title: 'The filter rings', module: 'filter',
        why: 'REGENERATION all the way up, the keyboard on the cutoff, and the 904A’s output through a 902 under an envelope.\n- 904A REGENERATION 10, FIXED CONTROL VOLTAGE 0.\n- Cables: CM1A CV 1 to 904A CONTROL INPUT 1; 904A SIG OUT to 902 (1) SIG IN +; 902 (1) to OUTPUT; CM1A TRIG to 911 (1); 911 (1) to 902 (1).\n- 911 (1): T1 3.5, T2 6, E SUS 9, T3 6.\n- Listen for: a pure whistle that plays the notes. If it is out of tune, nudge FIXED CONTROL VOLTAGE.',
        set: { 'm904a.regeneration': 10, 'm904a.fixed_cv': 0, 'm911_1.t1': 3.5, 'm911_1.t2': 6, 'm911_1.esus': 9, 'm911_1.t3': 6 },
        cables: [['j.cm1a.cv_1', 'j.m904a.cv_1'], ['j.m904a.sig_out', 'j.m902_1.sig_in_pos'], ['j.m902_1.out_pos', 'j.out.l'], ['j.cm1a.trig_upper', 'j.m911_1.strig'], ['j.m911_1.out', 'j.m902_1.cv_1']] },
      { title: 'A touch of vibrato', module: 'lfo',
        why: 'The 921’s AUX OUT, turned low, to another control input.\n- 921 COARSE RNG on SUB, FREQUENCY +1, AUX OUT WAVEFORM sine, AUX OUT LEVEL 2.\n- Cable: 921 AUX OUT 1 to 904A CONTROL INPUT 2.\n- Listen for: a gentle, flute-like wobble.',
        set: { 'm921.coarse': 'sub', 'm921.frequency': 1, 'm921.aux_wave': 'sine', 'm921.aux_level': 2 },
        cables: [['j.m921.aux_1', 'j.m904a.cv_2']] },
    ],
    context: {
      'm904a.regeneration': 'In this sound: at 10 the filter is the oscillator. Below about 9 it stops ringing and you hear nothing.',
      'm904a.fixed_cv': 'In this sound: the tuning. Each volt is an octave.',
      'm921.aux_level': 'In this sound: the vibrato depth.',
    },
    tweaks: [
      { id: 'm904a.range', try: 'Switch FREQUENCY RANGE to 3', hear: 'Everything jumps up two octaves: a piccolo.' },
      { id: 'm921.aux_level', try: 'Turn AUX OUT LEVEL up to 4', hear: 'A wide, warbling siren.' },
    ],
  },
];
