// More sounds for the tb-303 library. Same Preset shape as the ones in ../tb-303.js (see CONTRACT.md → Preset).
import { acidPhrase } from '@/lib/maps.js';

export default [
  {
    id: 'tb-jack-house', name: 'Jacking House Line', ref: 'In the style of Armando — "Land of Confusion"', artist: 'Armando',
    tags: ['bass', 'acid', 'house', '80s'], level: 1,
    blurb: 'A raw Chicago acid house line where held notes open and close slowly under heavy resonance.',
    how: 'A sawtooth goes through the filter with RESONANCE near the top and ENV MOD high, so every note is a wide sweep. DECAY is set longer than usual, and the riff ties some notes over two steps, so you hear the filter closing all the way down. ENV MOD also pulls the resting cutoff down a little, which keeps the gaps between sweeps dark.',
    phrase: acidPhrase(120, 'C2 - C2 C3a . C2 A#1 C2 D#2 - C2 C2a . C2s G1 C2'),
    steps: [
      { title: 'Sawtooth, filter low', module: 'osc', why: 'Start from the plain acid voice: one sawtooth and a filter that is mostly closed.\n- WAVEFORM sawtooth: every harmonic, so the filter has plenty to work on.\n- CUT OFF FREQ 3 (about 450 Hz): dark between notes.\n- Listen for: a dull, thudding line. The tied notes on the first and ninth steps last twice as long as the rest.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3, 'filter.res': 3, 'filter.envMod': 2, 'env.decay': 3 } },
      { title: 'Big sweep, slow close', module: 'filter', why: 'High RESONANCE and ENV MOD make each note a wide "yow", and a longer DECAY slows the close so you can follow it.\n- RESONANCE 9: a strong peak that rides the sweep.\n- ENV MOD 7: each note opens the filter a long way. It also lowers the resting cutoff a little, so the line is darker between notes.\n- DECAY 5 (about 630 ms): the filter is still closing when the next note starts.\n- Listen for: the tied notes. They open bright and you can hear them close right down before the next note.',
        set: { 'filter.res': 9, 'filter.envMod': 7, 'env.decay': 5 } },
      { title: 'Moderate accents', module: 'env', why: 'With ENV MOD this high, every note is already loud and bright, so ACCENT is set in the middle.\n- ACCENT 5: the two accented steps stand out without taking over.\n- Listen for: the jump to the upper C on step 4 is louder and snaps shut quickly. Accented notes close the filter in 0.2 s whatever DECAY says.',
        set: { 'amp.accent': 5 } },
    ],
    context: {
      'filter.envMod': 'Set high, so every note sweeps. It also pulls the resting cutoff down a little; turn it to 2 and the line is brighter between notes but flat.',
      'env.decay': 'Long enough to hear each sweep close. Below 3 the notes become short blips; above 7 they run into each other.',
      'filter.res': 'Near the top for the squelch. Below about 6 the sweeps lose their vocal sound.',
      'filter.cutoff': 'The resting point. Raise it slowly over a few bars to build the track.',
      'amp.accent': 'Middle setting, because the ordinary notes are already loud.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Turn slowly from 3 to 6 over several bars', hear: 'The line opens from a thud into a bright, buzzing squelch.' },
      { id: 'env.decay', try: 'Drop to 1', hear: 'The tied notes no longer sweep; they click open and stay dark.' },
    ],
  },
  {
    id: 'tb-rising-acid', name: 'Rising Acid', ref: 'In the style of Josh Wink — "Higher State of Consciousness"', artist: 'Josh Wink',
    tags: ['bass', 'acid', 'techno', '90s'], level: 3,
    blurb: 'A fast, unbroken run of sixteenth notes at full resonance, built to be opened up slowly by hand.',
    how: 'Every step plays, so the filter is struck sixteen times a bar and the line rolls without gaps. RESONANCE is right up and ACCENT high, and the accents come in pairs: the accent sweep charges up over a run of accents, so the second of each pair goes higher than the first. The cutoff starts low because the idea is to turn it up as the track builds.',
    phrase: acidPhrase(134, 'C2 C2 C3 C2 C2a C2a C3 C2 C2 C3 C2 D#2s F2 C2 C2a C3a C2 C2 C3 C2 C2a C2a C3 C2 G1 C2 C3 C2 A#1s C2 C2a C3a'),
    steps: [
      { title: 'Sawtooth, tight and low', module: 'osc', why: 'A sawtooth with the filter low and a short DECAY, so each of the sixteen notes in a bar stays separate.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 2.5 (about 380 Hz), ENV MOD 3, DECAY 2 (about 320 ms).\n- Listen for: a fast, muffled rolling pulse with octave jumps.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 2.5, 'filter.envMod': 3, 'env.decay': 2 } },
      { title: 'Resonance right up', module: 'filter', why: 'At full RESONANCE the filter peak is as strong as it goes, so even small filter movement squeals.\n- RESONANCE 10.\n- Listen for: the line turns from a pulse into a chattering whistle on every note.',
        set: { 'filter.res': 10 } },
      { title: 'Accents that build', module: 'env', why: 'The size of the accent sweep is ACCENT × (0.6 + 2.6 × RESONANCE/10) octaves, so at these settings it is nearly three octaves. Accents also charge up over a run: two accents in a row push the filter further than one.\n- ACCENT 9.\n- Listen for: the accented pairs. The second note of each pair shrieks higher than the first.',
        set: { 'amp.accent': 9 } },
      { title: 'Open it by hand', module: 'filter', why: 'Records like this are performed on CUT OFF FREQ, opening the filter over many bars. Set a middle point to hear where it is heading.\n- CUT OFF FREQ 4 (about 650 Hz).\n- Listen for: the whole line gets brighter and harder. Keep turning towards 7 and it starts to scream.',
        set: { 'filter.cutoff': 4 } },
    ],
    context: {
      'filter.cutoff': 'The performance control here. Start low and turn it up over a minute or more; that slow climb is the build.',
      'filter.res': 'At full, so every note whistles and the accent sweep is as large as it gets.',
      'amp.accent': 'High, and the accents come in pairs so the sweep charges up. Turn it to 3 and the pairs sound like the other notes.',
      'env.decay': 'Short, so sixteen notes a bar stay separate. Turn it up and they blur into one long squelch.',
      'filter.envMod': 'Kept low so the accents stand out against the ordinary notes.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Sweep from 2 to 7 over about 30 seconds', hear: 'The line climbs from a muffled pulse to a piercing scream.' },
      { id: 'filter.res', try: 'Drop to 5', hear: 'The whistle goes and the accent pairs shrink, because the accent sweep depends on RESONANCE.' },
      { id: 'env.decay', try: 'Raise to 6', hear: 'The notes smear together into one rolling squelch.' },
    ],
  },
  {
    id: 'tb-dotted-phase', name: 'Dotted Phase', ref: 'In the style of Emmanuel Top — "Acid Phase"', artist: 'Emmanuel Top',
    tags: ['bass', 'acid', 'techno', '90s'], level: 2,
    blurb: 'An acid techno line whose accents fall every three steps, so they drift against the four-to-the-floor beat.',
    how: 'The accents land on steps 1, 4, 7, 10 and 13: groups of three sixteenths played against a beat of four. The pattern of bright notes shifts against the beat while the bar still repeats every sixteen steps. A short DECAY and low ENV MOD keep the ordinary notes dark, so the accents carry the rhythm.',
    phrase: acidPhrase(134, 'C2a C2 C3 C2a C2 C3 D#2a C2 C3s C2a C2 C3 C2a C2s G2 C2'),
    steps: [
      { title: 'Short, dark notes', module: 'filter', why: 'The ordinary notes are kept dark and short so they sit in the background.\n- WAVEFORM sawtooth, CUT OFF FREQ 3.\n- ENV MOD 2.5, DECAY 2 (about 320 ms).\n- Listen for: an even sixteenth-note pulse with little to mark out the groups.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3, 'filter.envMod': 2.5, 'env.decay': 2 } },
      { title: 'Resonance', module: 'filter', why: 'RESONANCE gives the notes their acid edge and makes the accent sweep larger.\n- RESONANCE 8.\n- Listen for: a little squelch on each note.',
        set: { 'filter.res': 8 } },
      { title: 'Accents in threes', module: 'env', why: 'With ACCENT turned up, the accents every three steps become the rhythm you hear first.\n- ACCENT 8.\n- Listen for: count four beats while the riff plays. The bright notes land on the beat, then just after it, then before it, and so on round the bar.',
        set: { 'amp.accent': 8 } },
    ],
    context: {
      'amp.accent': 'Carries the three-step rhythm. At 0 the line is an even pulse and the cross-rhythm disappears.',
      'filter.envMod': 'Low, so only the accents open the filter much.',
      'env.decay': 'Short, so each accent is a clear hit.',
      'filter.res': 'Sets the squelch and how far each accent sweeps.',
    },
    tweaks: [
      { id: 'amp.accent', try: 'Turn from 8 to 0 and back', hear: 'The three-step rhythm comes and goes while the notes stay the same.' },
      { id: 'filter.envMod', try: 'Raise to 7', hear: 'Every note opens, so the accents no longer stand out and the cross-rhythm blurs.' },
    ],
  },
  {
    id: 'tb-funk-stab', name: 'Funk Stab Line', ref: 'In the style of Daft Punk — "Da Funk"', artist: 'Daft Punk',
    tags: ['bass', 'house', 'funk', '90s'], level: 2,
    blurb: 'A slower, funky line with gaps, off-beat notes and a held note that bends into the next.',
    how: 'The rests matter as much as the notes: they leave space for the beat, and the off-beat notes give the swing. Resonance is moderate, so the notes have a rubbery bite without a full acid squeal. A slide into a tied note at the end of the second bar bends the pitch down without restarting the envelopes.',
    phrase: acidPhrase(111, 'G1 . G1 G2a . G1 A#1 . C2s D2 . G1 . F1a G1 . G1 . G1 G2a . G1 A#1 . D2a . C2 A#1s G1 - . F1'),
    steps: [
      { title: 'Sawtooth, middle filter', module: 'osc', why: 'A sawtooth with the filter half open, so the notes are bright enough to carry a melody.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 4 (about 650 Hz).\n- Listen for: the shape of the riff, with its gaps and off-beat notes.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 4 } },
      { title: 'Rubbery, not squealing', module: 'filter', why: 'Moderate RESONANCE and ENV MOD give each note a bite at the front without the full acid sound.\n- RESONANCE 6, ENV MOD 5.\n- DECAY 3 (about 400 ms): short enough to keep the gaps clean.\n- Listen for: a "dow" at the start of each note.',
        set: { 'filter.res': 6, 'filter.envMod': 5, 'env.decay': 3 } },
      { title: 'Accents on the jumps', module: 'env', why: 'The octave jumps, the low F and one D are accented, so they hit hardest.\n- ACCENT 7.\n- Listen for: the jump up to the high G on step 4 is louder and brighter. Near the end of the second bar, A sharp slides into G, which is held over two steps.',
        set: { 'amp.accent': 7 } },
    ],
    context: {
      'filter.res': 'Moderate, for bite without squeal. Above 8 it turns into an acid line.',
      'filter.envMod': 'Gives each note its "dow". At 0 the notes are flat.',
      'env.decay': 'Short, so the rests stay clear.',
      'amp.accent': 'Makes the octave jumps hit hard.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Raise to 9', hear: 'The line starts to squelch and sounds more like acid house than funk.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A hollower, softer line, closer to a plain synth bass.' },
      { id: 'env.decay', try: 'Raise to 7', hear: 'Notes ring into the gaps and the groove loses its snap.' },
    ],
  },
  {
    id: 'tb-hollow-square', name: 'Hollow Square Line', ref: 'In the style of late-1980s UK acid house', artist: 'Various',
    tags: ['bass', 'acid', 'house', '80s'], level: 1,
    blurb: 'An acid line on the square wave, rounder and more hollow than the sawtooth, tuned down to A.',
    how: 'The square wave has only odd harmonics, so with the same resonance it squelches with a hollow, woody tone instead of a buzz. The riff is written in C, and TUNING moves the whole instrument down three semitones so it plays in A. Everything else is the usual acid set-up of resonance, envelope and accents.',
    phrase: acidPhrase(124, 'C2 . C3 C2a . C2 D#2s F2 . C2 C2 G2a . F2s D#2 C2'),
    steps: [
      { title: 'Square wave', module: 'osc', why: 'The WAVEFORM switch on the back edge picks the square wave.\n- WAVEFORM square.\n- Listen for: a hollow tone. Switch to sawtooth and back to compare.',
        set: { 'osc.wave': 'sq' } },
      { title: 'Tune down to A', module: 'osc', why: 'TUNING shifts every note by the same amount, so a riff written in C can be moved to match a track in another key.\n- TUNING −3: three semitones down, from C to A.\n- Listen for: the whole riff drops in pitch with its shape unchanged.',
        set: { 'osc.tuning': -3 } },
      { title: 'Acid filter settings', module: 'filter', why: 'The usual acid filter: low cutoff, high resonance, and a medium envelope.\n- CUT OFF FREQ 4, RESONANCE 8, ENV MOD 5.\n- DECAY 4 (about 500 ms).\n- Listen for: a squelch on each note, softer and rounder than on the sawtooth.',
        set: { 'filter.cutoff': 4, 'filter.res': 8, 'filter.envMod': 5, 'env.decay': 4 } },
      { title: 'Accents', module: 'env', why: 'The accents on steps 4 and 12 mark the bar.\n- ACCENT 6.\n- Listen for: those two notes are louder and close quickly.',
        set: { 'amp.accent': 6 } },
    ],
    context: {
      'osc.wave': 'The square wave is what makes this line hollow. The sawtooth is brighter and buzzier.',
      'osc.tuning': 'Moves the riff from C to A. Each whole number is one semitone.',
      'filter.res': 'High, for the squelch. On the square wave it sounds rounder than on the sawtooth.',
      'filter.cutoff': 'The square has less top end, so the cutoff sits a little higher than for a sawtooth line.',
    },
    tweaks: [
      { id: 'osc.tuning', try: 'Set to 0, then to +2', hear: 'The riff plays in C, then in D.' },
      { id: 'filter.cutoff', try: 'Turn up to 7', hear: 'The hollow, reedy character of the square wave comes through clearly.' },
    ],
  },
  {
    id: 'tb-raga-line', name: 'Raga Line', ref: 'In the style of Charanjit Singh — "Ten Ragas to a Disco Beat"', artist: 'Charanjit Singh',
    tags: ['lead', 'acid', 'disco', '80s'], level: 2,
    blurb: 'A melody an octave above the usual bass range, using a raga-like scale with a flattened second and sixth.',
    how: 'The notes come from a scale with D flat and A flat in place of D and A, which gives the line its Indian sound. Played an octave higher than a bass line, the TB-303 becomes a lead. A moderate cutoff and resonance keep the melody clear, and slides give it a sung quality.',
    phrase: acidPhrase(125, 'C3 C3 C4a C3 B3s C4 G3 C3 E3 F3a G3 C3 G#3s G3 F3 E3 C3 C3 C4a C3 B3s C4 G3 C3 C#3 C3a E3 F3 G3s G#3 G3 C3a'),
    steps: [
      { title: 'Sawtooth in the lead range', module: 'osc', why: 'The riff sits an octave above the other sounds, up to middle C. Higher notes need a higher cutoff, or the filter dulls them.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 5 (about 900 Hz).\n- Listen for: a melody rather than a bass line.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 5 } },
      { title: 'Clear, singing filter', module: 'filter', why: 'Enough resonance to give the notes a voice, but not so much that the melody turns into squelch.\n- RESONANCE 6, ENV MOD 4.\n- DECAY 4 (about 500 ms).\n- Listen for: each note has a soft "wah" and the pitches stay easy to follow.',
        set: { 'filter.res': 6, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'Accents', module: 'env', why: 'The accents mark the top of each phrase.\n- ACCENT 6.\n- Listen for: the upper C on step 3 rings out, and on steps 5 and 6 B slides up into C.',
        set: { 'amp.accent': 6 } },
    ],
    context: {
      'filter.cutoff': 'Higher than for a bass line, so the upper notes are not muffled.',
      'filter.res': 'Moderate, so the melody stays clear. Above 8 it turns into squelch.',
      'filter.envMod': 'A soft opening on each note.',
      'amp.accent': 'How much the accented top notes of each phrase stand out.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Raise to 9', hear: 'The melody squeals and becomes an acid lead.' },
      { id: 'osc.tuning', try: 'Set to −5', hear: 'The whole melody moves down a fourth, to G.' },
    ],
  },
  {
    id: 'tb-dub-drift', name: 'Dub Drift', ref: 'In the style of slow dub and ambient acid', artist: 'Various',
    tags: ['bass', 'acid', 'dub', 'ambient'], level: 2,
    blurb: 'A slow line of long, tied notes that open and close at walking pace.',
    how: 'At 92 BPM with ties holding each note for three steps, there is time to hear the whole filter sweep. DECAY is near the top, about 1.6 seconds, so the filter closes slowly through each note. The volume envelope has no panel control and cuts off when a note ends, so the ties are what make the notes long.',
    phrase: acidPhrase(92, 'C2 - - . . . G1s C2 - - . . D#2 - . . C2 - - . . . A#1s C2 - - . F2a - D#2s C2 .'),
    steps: [
      { title: 'Dark sawtooth', module: 'osc', why: 'A sawtooth with the filter low, so the notes are deep and round at rest.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 2.5 (about 380 Hz).\n- Listen for: long, dark notes with plenty of space between them.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 2.5 } },
      { title: 'Long decay', module: 'env', why: 'DECAY sets how long the filter takes to close. Near the top it lasts longer than the notes themselves.\n- DECAY 9 (about 1.6 s).\n- ENV MOD 6: a wide opening on each note.\n- Listen for: each note starts bright and dims slowly while it is held.',
        set: { 'env.decay': 9, 'filter.envMod': 6 } },
      { title: 'Resonance', module: 'filter', why: 'RESONANCE turns the slow close into a slow "wow".\n- RESONANCE 8.\n- Listen for: a vowel-like sweep through each held note. The slid notes bend up into C without starting the sweep again.',
        set: { 'filter.res': 8 } },
      { title: 'Soft accents', module: 'env', why: 'Accented steps close the filter in 0.2 s whatever DECAY says, which would cut across the slow sweeps. ACCENT is kept low.\n- ACCENT 3.\n- Listen for: the accented F near the end is only a little louder and closes faster than the other notes.',
        set: { 'amp.accent': 3 } },
    ],
    context: {
      'env.decay': 'Near the top, so the filter closes slowly through each held note. Below 5 the notes go dark almost at once.',
      'filter.envMod': 'How far each note opens before the slow close.',
      'filter.res': 'Makes the slow close a vowel-like "wow".',
      'amp.accent': 'Low, because accents shorten the filter close to 0.2 s and break up the slow sweeps.',
    },
    tweaks: [
      { id: 'env.decay', try: 'Move between 4 and 10', hear: 'From short dark notes to long sweeps that are still closing when the next note comes.' },
      { id: 'filter.cutoff', try: 'Raise to 5', hear: 'The notes stay bright all the way through and the space between them fills up.' },
    ],
  },
  {
    id: 'tb-blip', name: 'Accent Blips', ref: 'In the style of early electro', artist: 'Various',
    tags: ['pluck', 'electro', '80s'], level: 2,
    blurb: 'Short, high blips with every note accented, used as a percussive part rather than a bass.',
    how: 'The notes are short and high, with the filter closed and ENV MOD near the top, so each one is a quick bright click that dies away. Lighting the ACCENT button accents every note, which makes the filter close in 0.2 s and adds the accent sweep to each one. The result works like a tuned percussion part.',
    phrase: acidPhrase(120, 'C3 . . C4 . . G3 . . C3 . D#4 . . A#3 .', 0.3),
    steps: [
      { title: 'Closed filter, big envelope', module: 'filter', why: 'With the filter almost closed and ENV MOD high, each note is a short burst of brightness on a dark background.\n- WAVEFORM sawtooth, CUT OFF FREQ 1.5.\n- ENV MOD 9: a large opening. It also lowers the resting cutoff, so between blips there is almost nothing.\n- DECAY 0 (about 200 ms): the shortest close.\n- Listen for: short, high clicks spaced across the bar.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 1.5, 'filter.envMod': 9, 'env.decay': 0 } },
      { title: 'Some resonance', module: 'filter', why: 'RESONANCE gives each blip a pitched ring as the filter closes.\n- RESONANCE 6.\n- Listen for: a "pew" on each note instead of a plain click.',
        set: { 'filter.res': 6 } },
      { title: 'Accent every note', module: 'env', why: 'Lit, the ACCENT button accents every note played, whatever the riff says. With the ACCENT knob up, each blip is louder and gets the accent sweep.\n- ACCENT button on.\n- ACCENT 7.\n- Listen for: the blips are sharper and louder. Turn the ACCENT button off to hear the plain version.',
        set: { 'seq.accent': true, 'amp.accent': 7 } },
    ],
    context: {
      'filter.envMod': 'Near the top, so each note is a quick bright burst from a closed filter.',
      'env.decay': 'At 0 for the shortest blip. Raise it and the blips turn into plucks.',
      'seq.accent': 'Lit, so every note is accented: louder, with a 0.2 s filter close and the accent sweep.',
      'amp.accent': 'How much the ACCENT button adds to each blip.',
      'filter.res': 'Gives the blips their pitched "pew".',
    },
    tweaks: [
      { id: 'seq.accent', try: 'Switch off', hear: 'The blips are quieter and less sharp, because they are no longer accented.' },
      { id: 'filter.res', try: 'Raise to 10', hear: 'Each blip rings with a high whistle.' },
      { id: 'env.decay', try: 'Raise to 5', hear: 'The blips become longer plucks with a "wah".' },
    ],
  },
  {
    id: 'tb-slow-chord-arp', name: 'Slow Broken Chord', ref: 'In the style of ambient electronica', artist: 'Various',
    tags: ['seq', 'ambient', 'arpeggio'], level: 1,
    blurb: 'A slow arpeggio that climbs up through an A minor chord and back down, then does the same over F.',
    how: 'Each note of the chord is tied over two steps, so the line moves in eighth notes at a relaxed 84 BPM. RESONANCE is low and DECAY long, so the filter only brightens each note a little and closes slowly, which keeps the sound soft. Two slides join the top of each chord to the next note down without restarting the envelopes.',
    phrase: acidPhrase(84, 'A2 - C3 - E3 - A3 - C4s A3 - - E3 - C3s B2 F2 - A2 - C3 - F3 - A3s C4 - - A3 - F3 -'),
    steps: [
      { title: 'Sawtooth, filter half closed', module: 'osc', why: 'A sawtooth through a filter set fairly low, so the arpeggio is warm rather than buzzy.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 4 (about 650 Hz).\n- Listen for: the broken chord going up and down. The notes are evenly spaced eighth notes.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 4, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'Low resonance, small sweep', module: 'filter', why: 'Without much resonance the filter shapes the tone and does not squelch.\n- RESONANCE 2: almost no peak.\n- ENV MOD 3: each note gets only a little brighter at the start.\n- Listen for: soft, even notes with no "yow".',
        set: { 'filter.res': 2, 'filter.envMod': 3 } },
      { title: 'Long decay, quiet accents', module: 'env', why: 'A long DECAY lets the filter close slowly through each tied note. The riff has no accents, so ACCENT is turned down in case you light the ACCENT button.\n- DECAY 8 (about 1.3 s).\n- ACCENT 2.\n- Listen for: the long C at the top of each chord. It dims slowly as it is held, then slides down to the next note.',
        set: { 'env.decay': 8, 'amp.accent': 2 } },
    ],
    context: {
      'env.decay': 'Long, so each note fades in brightness gently. Below 4 the notes become short plucks.',
      'filter.res': 'Kept low so the arpeggio stays soft. Above about 6 it starts to squelch.',
      'filter.envMod': 'Small, so each note brightens only a little at the start.',
      'filter.cutoff': 'Sets how warm the whole line is. Above 6 it gets thin and buzzy.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Turn slowly between 3 and 6', hear: 'The arpeggio moves from muffled to bright without changing its rhythm.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A hollower, rounder arpeggio, closer to a soft organ.' },
    ],
  },
  {
    id: 'tb-pad-pulse', name: 'Pulse Under a Pad', ref: 'In the style of ambient and downtempo pulse bass lines', artist: 'Various',
    tags: ['bass', 'ambient', 'downtempo'], level: 1,
    blurb: 'A soft square-wave bass playing steady eighth notes, meant to sit under a slow pad.',
    how: 'The square wave and a low filter with almost no resonance give a round, quiet note. Each note is the same length and the same strength, so the line works as a steady pulse rather than a tune. The pitch moves only once, from D to A and back, so a pad played over it has room to change chords.',
    phrase: acidPhrase(100, 'D2 . D2 . D2 . D2 . D2 . D2 . F2 . E2 . A1 . A1 . A1 . A1 . A1 . A1 . C2 . E2 .', 1.6),
    steps: [
      { title: 'Square wave', module: 'osc', why: 'The square wave has only odd harmonics, so it is hollow and round.\n- WAVEFORM square.\n- Listen for: a steady pulse of eighth notes, D for one bar and A for the next.',
        set: { 'osc.wave': 'sq' } },
      { title: 'Low, gentle filter', module: 'filter', why: 'The filter is low with little resonance and a small sweep, so each note has a soft start and no squelch.\n- CUT OFF FREQ 3 (about 450 Hz).\n- RESONANCE 1.\n- ENV MOD 2.\n- Listen for: a round, muted pulse that does not draw attention.',
        set: { 'filter.cutoff': 3, 'filter.res': 1, 'filter.envMod': 2 } },
      { title: 'Medium decay, no accent', module: 'env', why: 'DECAY is set so the filter is still closing as each note ends, which smooths the start of every note. ACCENT is off so every note is the same.\n- DECAY 5 (about 630 ms).\n- ACCENT 0.\n- Listen for: no note stands out from the others.',
        set: { 'env.decay': 5, 'amp.accent': 0 } },
    ],
    context: {
      'osc.wave': 'The square is what keeps the pulse round. The sawtooth is brighter and fights with a pad.',
      'filter.cutoff': 'Low, so the pulse sits under other parts. Raise it if the pulse gets lost in a mix.',
      'filter.res': 'Almost off, so the notes do not squelch.',
      'filter.envMod': 'Small, for a soft start to each note.',
      'env.decay': 'Middle setting. Shorter gives a clipped pulse; longer gives a smoother one.',
      'amp.accent': 'Off, so every note is the same strength.',
    },
    tweaks: [
      { id: 'filter.envMod', try: 'Raise to 6', hear: 'Each note starts with a clear thump and the pulse becomes more rhythmic.' },
      { id: 'osc.tuning', try: 'Set to 2', hear: 'The whole line moves up a tone, from D to E, to fit a different key.' },
    ],
  },
  {
    id: 'tb-chill-glide', name: 'Chill-Out Glide', ref: 'In the style of early-1990s ambient house', artist: 'Various',
    tags: ['lead', 'ambient', 'chill-out', '90s'], level: 2,
    blurb: 'A slow melody in the middle register where most notes glide into the next.',
    how: 'The notes overlap, so the TB-303 slides between them and does not restart its envelopes. A long DECAY and some resonance make the filter close slowly through each phrase, and with the volume envelope also running on, a slid phrase gets gradually softer. The square wave and a moderate cutoff keep the tone smooth.',
    phrase: { bpm: 96, loop: true, steps: [[0, 57, 1.55], [1.5, 60, 0.6], [2, 64, 1.55], [3.5, 62, 0.45], [4, 60, 1.55], [5.5, 57, 0.6], [6, 55, 0.95], [7, 57, 0.9]] },
    steps: [
      { title: 'Square wave, middle register', module: 'osc', why: 'The melody sits an octave or so above a bass line, so it is played as a lead. The square wave is softer than the sawtooth up here.\n- WAVEFORM square.\n- CUT OFF FREQ 4.5 (about 770 Hz).\n- Listen for: a slow tune of A, C, E, D, then C, A, G, A.',
        set: { 'osc.wave': 'sq', 'filter.cutoff': 4.5, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'Long decay, light sweep', module: 'env', why: 'With a long DECAY the filter is still closing when the next note slides in, so a phrase of slid notes is one slow fade.\n- DECAY 9 (about 1.6 s).\n- ENV MOD 3: a small opening at the start of each phrase.\n- Listen for: each phrase starts a little brighter and dims as it glides on.',
        set: { 'env.decay': 9, 'filter.envMod': 3 } },
      { title: 'Some resonance', module: 'filter', why: 'A middle amount of RESONANCE gives the slow close a slight vowel sound without turning it into a squelch.\n- RESONANCE 5.\n- ACCENT 0: there are no accents in the riff.\n- Listen for: the glides. The pitch bends over about 70 ms from one note to the next.',
        set: { 'filter.res': 5, 'amp.accent': 0 } },
    ],
    context: {
      'env.decay': 'Near the top, so the filter closes slowly across each phrase of slid notes.',
      'filter.res': 'Middle setting, for a slight vowel sound. Above 8 the line starts to whistle.',
      'filter.cutoff': 'Moderate, so the melody is clear but not buzzy.',
      'osc.wave': 'The square is softer for a melody in this register.',
      'filter.envMod': 'Small, so the start of each phrase is only a little brighter.',
    },
    tweaks: [
      { id: 'osc.wave', try: 'Switch to sawtooth', hear: 'The melody becomes brighter and more nasal.' },
      { id: 'filter.res', try: 'Raise to 8', hear: 'The glides get a vocal "ow" as the filter peak moves with them.' },
      { id: 'env.decay', try: 'Drop to 3', hear: 'Each phrase goes dark soon after it starts.' },
    ],
  },
  {
    id: 'tb-minor-arp', name: 'Soft Minor Arpeggio', ref: 'In the style of downtempo and trip-hop sequences', artist: 'Various',
    tags: ['seq', 'ambient', 'downtempo', 'arpeggio'], level: 2,
    blurb: 'A sixteenth-note arpeggio through four chords in D minor at 94 BPM, kept soft with a low filter.',
    how: 'The sequencer steps through each chord up and back down, two beats per chord: D minor, B flat, C and A. The filter is low and the resonance moderate, so the notes are rounded with a slight squelch. Light accents on the first note of each chord mark the changes.',
    phrase: acidPhrase(94, 'D2a F2 A2 D3 A2 F2 D2 F2 A#1a D2 F2 A#2 F2 D2 A#1 D2 C2a E2 G2 C3 G2 E2 C2 E2 A1a C#2 E2 A2 E2 C#2 A1 C#2', 0.7),
    steps: [
      { title: 'Sawtooth, filter low', module: 'osc', why: 'A sawtooth gives every note a clear pitch, and a low cutoff takes the edge off.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 3.5 (about 540 Hz).\n- Listen for: a steady stream of sixteenth notes moving through four chords.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3.5, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'A little resonance', module: 'filter', why: 'Moderate RESONANCE gives each note a slight rounded "w" at the start, which makes a fast arpeggio easier to follow.\n- RESONANCE 4.\n- ENV MOD 3.5.\n- DECAY 3 (about 400 ms): short enough that each note stays separate.\n- Listen for: soft, separate notes with a small squelch.',
        set: { 'filter.res': 4, 'filter.envMod': 3.5, 'env.decay': 3 } },
      { title: 'Light accents', module: 'env', why: 'The first note of each chord is accented. A low ACCENT makes it just a little louder and brighter.\n- ACCENT 3.\n- Listen for: the chord changes every two beats. Turn ACCENT up to 8 and those notes start to bark.',
        set: { 'amp.accent': 3 } },
    ],
    context: {
      'filter.cutoff': 'Low, so the arpeggio stays soft. Raise it for a brighter, more insistent sequence.',
      'filter.res': 'Moderate, for a small squelch on each note.',
      'env.decay': 'Short, so sixteen notes a bar stay separate. Above 6 they blur together.',
      'amp.accent': 'Low, so the chord changes are marked without jumping out.',
    },
    tweaks: [
      { id: 'env.decay', try: 'Raise to 7', hear: 'The notes run into each other and the chords sound more like a wash.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A hollower, quieter sequence.' },
    ],
  },
  {
    id: 'tb-a3-shuffle', name: 'Country Shuffle Bass', ref: 'In the style of Alabama 3 — "Ain’t Goin’ to Goa"', artist: 'Alabama 3',
    tags: ['bass', 'blues', 'country', 'acid'], level: 2,
    blurb: 'A walking country-blues bass line with a shuffle feel, played through a lightly squelching filter.',
    how: 'Alabama 3 put acid house grooves under country and blues songs. This line walks through a I–IV–V change in A, with each beat split into a long note and a short one placed on the last third of the beat, which gives the shuffle. The square wave keeps it close to a bass guitar, and moderate RESONANCE adds a little acid squelch.',
    phrase: { bpm: 104, loop: true, steps: [
      [0, 33, 0.55, 1], [0.67, 37, 0.28], [1, 40, 0.55], [1.67, 42, 0.28], [2, 43, 0.55], [2.67, 42, 0.28], [3, 40, 0.55], [3.67, 37, 0.28],
      [4, 38, 0.55, 1], [4.67, 42, 0.28], [5, 45, 0.55], [5.67, 47, 0.28],
      [6, 40, 0.55, 1], [6.67, 44, 0.28], [7, 47, 0.55], [7.67, 44, 0.28],
    ] },
    steps: [
      { title: 'Square wave, round tone', module: 'osc', why: 'The square wave is hollow and round, closer to a plucked bass than the sawtooth.\n- WAVEFORM square.\n- CUT OFF FREQ 3.5 (about 540 Hz).\n- Listen for: the walk up and down through the A chord, then D, then E.',
        set: { 'osc.wave': 'sq', 'filter.cutoff': 3.5, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'Short, punchy notes', module: 'env', why: 'A short DECAY closes the filter quickly, so the long and short notes of the shuffle stay distinct.\n- DECAY 3 (about 400 ms).\n- ENV MOD 4.\n- Listen for: the long-short swing on every beat.',
        set: { 'env.decay': 3 } },
      { title: 'A touch of acid', module: 'filter', why: 'RESONANCE in the middle of its range adds a slight squelch to each note without hiding the walking line.\n- RESONANCE 5.\n- ACCENT 5: the first note of each chord is accented.\n- Listen for: the chord changes. The accented A, D and E bark a little.',
        set: { 'filter.res': 5, 'amp.accent': 5 } },
    ],
    context: {
      'osc.wave': 'The square keeps it close to a bass guitar. The sawtooth makes it sound more like acid house.',
      'env.decay': 'Short, so the shuffle stays clear.',
      'filter.res': 'Middle setting, for a little squelch. Raise it to push the line further towards acid.',
      'amp.accent': 'Marks the first note of each chord.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Raise to 8', hear: 'The walking line turns into an acid line while keeping its shuffle.' },
      { id: 'osc.wave', try: 'Switch to sawtooth', hear: 'Brighter and buzzier, less like a bass guitar.' },
    ],
  },
  {
    id: 'tb-a3-gospel', name: 'Gospel Octave Bass', ref: 'In the style of Alabama 3', artist: 'Alabama 3',
    tags: ['bass', 'gospel', 'acid', 'house'], level: 2,
    blurb: 'A gospel-style bass line that jumps between octaves and slides between chords, over a steady 4/4.',
    how: 'Alabama 3 mixed gospel and blues with acid house. This line moves from C to F, then down through B flat and A to G, using the chord changes of a gospel song. Octave jumps slide back down, and short slides walk up into the next chord. A sawtooth with moderate RESONANCE gives the slides a slight acid edge.',
    phrase: acidPhrase(118, 'C2a . C3s C2 . C2 E2 F2a . F2 F3s F2 . A2 A#2s B2 C3a . C2 . A#1 . A1s A#1 G1a . G2s G1 . A1 B1s C2'),
    steps: [
      { title: 'Sawtooth, filter low', module: 'osc', why: 'A sawtooth through a low filter gives a full, dark bass.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 3.5 (about 540 Hz).\n- Listen for: the octave jumps on C and F, and the walk up from A to C at the end of the first bar.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3.5, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'Resonance for the slides', module: 'filter', why: 'With more RESONANCE the slides carry a vowel sound from one pitch to the next.\n- RESONANCE 6.\n- ENV MOD 4.\n- Listen for: each octave jump slides back down with a "yow".',
        set: { 'filter.res': 6 } },
      { title: 'Accents on the chords', module: 'env', why: 'Each new chord starts on an accented note. Accents are louder and their filter closes in 0.2 s, so they mark the changes.\n- ACCENT 6.\n- DECAY 4 (about 500 ms).\n- Listen for: the accented C, F and G hitting harder than the walking notes between them.',
        set: { 'amp.accent': 6, 'env.decay': 4 } },
    ],
    context: {
      'filter.res': 'Gives the slides their vowel sound. Below 4 the slides are plain glides.',
      'amp.accent': 'Marks each chord change.',
      'filter.cutoff': 'Low, to keep the bass full and dark under a vocal.',
      'env.decay': 'Middle setting, so the slid notes stay bright as they glide.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Raise to 5', hear: 'The line gets brighter and more like an acid riff than a bass part.' },
      { id: 'env.decay', try: 'Raise to 7', hear: 'The slides stay open longer and the line gets wetter.' },
    ],
  },
  {
    id: 'tb-a3-slow-blues', name: 'Slow Blues Bend', ref: 'In the style of Alabama 3', artist: 'Alabama 3',
    tags: ['bass', 'blues', 'acid'], level: 3,
    blurb: 'A slow blues line in E where slides bend between the minor third and the fourth, like a bent guitar string.',
    how: 'The line sits on E and keeps sliding between G and A, the minor third and the fourth of the blues scale. Because slid notes do not restart the envelopes, each slide sounds like one note being bent. A long DECAY and high RESONANCE make the filter close slowly through each bend.',
    phrase: acidPhrase(78, 'E2 - - . G2s A2 - - G2s E2 - . D2 - E2 . E2 - - . G2s A2s A#2s A2 - G2s E2 - . B1 D2s E2'),
    steps: [
      { title: 'Sawtooth, filter low', module: 'osc', why: 'A sawtooth with a low cutoff gives a dark, heavy note.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 3 (about 450 Hz).\n- Listen for: a slow line on E that keeps reaching up to A and falling back.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'Long decay', module: 'env', why: 'A long DECAY lets the filter close slowly, so you can hear it moving through each bend.\n- DECAY 7 (about 1 s).\n- Listen for: the held notes dimming as they go.',
        set: { 'env.decay': 7 } },
      { title: 'Resonance for the bend', module: 'filter', why: 'High RESONANCE gives the filter a strong peak, which makes the slides sound like a voice or a bent string.\n- RESONANCE 7.\n- ENV MOD 4.\n- Listen for: the second bar, where G slides up to A, then to B flat and back. Turn RESONANCE down to 3 and the bends go plain.',
        set: { 'filter.res': 7 } },
      { title: 'Light accents', module: 'env', why: 'There are no accents in the riff, and accents would close the filter in 0.2 s and cut across the slow bends. ACCENT is kept low for playing.\n- ACCENT 3.',
        set: { 'amp.accent': 3 } },
    ],
    context: {
      'env.decay': 'Long, so the filter closes slowly through each bend.',
      'filter.res': 'High, so the slides sound like bent notes.',
      'filter.cutoff': 'Low, for a dark, heavy tone.',
      'amp.accent': 'Low, because accents shorten the filter close and break up the bends.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Move between 3 and 9', hear: 'From a plain glide to a vocal "wah" on each bend.' },
      { id: 'osc.tuning', try: 'Set to −2', hear: 'The line drops a tone, from E to D.' },
    ],
  },
  {
    id: 'tb-a3-blues-acid', name: 'Blues-Scale Squelch', ref: 'In the style of Alabama 3 — "Woke Up This Morning"', artist: 'Alabama 3',
    tags: ['bass', 'acid', 'blues'], level: 2,
    blurb: 'A squelching acid riff on the A blues scale, meant to sit under slide guitar and harmonica.',
    how: 'The riff uses only the notes of the A blues scale: A, C, D, E flat, E and G. That puts it in the same key as a blues guitar or harmonica part, while the TB-303 filter turns it into acid house. High RESONANCE and strong accents give the squelch; slides join D to E flat to E, the blues run.',
    phrase: acidPhrase(124, 'A1 A1 C2a A1 D2s D#2 E2 A1 A1 G1 A1a C2 . D2s D#2 E2a A1 A1 C2 A1 D2 D#2s E2 G2a A1 . A1 G1s A1 C2 E2a D2'),
    steps: [
      { title: 'Sawtooth, filter low', module: 'osc', why: 'The usual acid start: one sawtooth and a mostly closed filter.\n- WAVEFORM sawtooth.\n- CUT OFF FREQ 3 (about 450 Hz).\n- Listen for: a busy line on A, climbing through D, E flat and E.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4 } },
      { title: 'Squelch', module: 'filter', why: 'High RESONANCE and a large ENV MOD make each note sweep with a strong peak.\n- RESONANCE 8.\n- ENV MOD 5.\n- DECAY 3.5 (about 450 ms): short enough to keep the line tight.\n- Listen for: the D, E flat, E run. It slides as one rising squelch.',
        set: { 'filter.res': 8, 'filter.envMod': 5, 'env.decay': 3.5 } },
      { title: 'Strong accents', module: 'env', why: 'Accents on the C, E and G give the riff its shape. With RESONANCE high, the accent sweep is large.\n- ACCENT 7.\n- Listen for: the accented notes shrieking above the rest.',
        set: { 'amp.accent': 7 } },
    ],
    context: {
      'filter.res': 'High for the squelch, and it sets how far each accent opens the filter.',
      'filter.envMod': 'Each note opens a long way. Turn it down to leave room for a guitar.',
      'amp.accent': 'Gives the riff its shape.',
      'env.decay': 'Short, so the line stays tight under other instruments.',
      'filter.cutoff': 'Low. Raise it slowly to bring the line forward in the mix.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Sweep from 2 to 6 while the riff plays', hear: 'The line opens from a dark rumble into a bright squelch.' },
      { id: 'filter.envMod', try: 'Drop to 2', hear: 'A darker, quieter line that leaves more space for a guitar or harmonica.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A rounder line, closer to a blues bass.' },
    ],
  },
];
