// More sounds for the td-3 library. Same Preset shape as the ones in ../td-3.js (see CONTRACT.md → Preset).
import { acidPhrase } from '@/lib/maps.js';

export default [
  {
    id: 'td-rolling-sixteenths', name: 'Rolling Sixteenths', ref: 'In the style of Hardfloor — "Acperience 1"', artist: 'Hardfloor',
    tags: ['bass', 'acid', 'trance', '90s'], level: 1,
    blurb: 'A fast line that plays on every sixteenth, rolling round one low note with jumps, accents and slides on top.',
    how: 'Every step of the pattern has a note, so the filter is restarted sixteen times a bar and the line never stops moving. A short DECAY keeps the notes apart at this speed, and the accents and slides carry the groove. A little distortion thickens the line without hiding the squelch.',
    phrase: acidPhrase(136, 'A1 A1 A2a A1 A1 E2 A1 G2s A2 A1 A1a C3 A1 A1 G2 A1 A1 A1 A2a A1 C2s D2 A1 A1a E2 A1 G2 A1 A2a A1 D2s E2', 0.5),
    steps: [
      { title: 'A tight acid voice', module: 'filter', why: 'At 136 BPM each sixteenth lasts about 110 ms, so the filter has to close quickly or the notes run together.\n- WAVEFORM sawtooth, CUTOFF 3.5, RESONANCE 7.5.\n- ENVELOPE 5, DECAY 2 (about 320 ms): a sharp blip on each note that is mostly gone before the next.\n- Listen for: a busy, chattering line where every step is a separate squelch.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3.5, 'filter.res': 7.5, 'filter.envMod': 5, 'env.decay': 2, 'amp.accent': 5 } },
      { title: 'Accents carry the groove', module: 'env', why: 'With a note on every step, the accents and the jumps up an octave are what give the line its shape.\n- ACCENT 7: accented steps play louder and get an extra sweep of the filter. Where two accents come close together the sweep builds up.\n- Listen for: the octave jumps that are accented snap out of the line. Turn ACCENT to 2 and the line turns into an even run of notes.',
        set: { 'amp.accent': 7 } },
      { title: 'A little grit', module: 'fx', why: 'Light distortion thickens the line but leaves the filter movement clear.\n- OFF/ON to ON.\n- DISTORTION 2: only the loudest peaks are clipped.\n- TONE 6: slightly bright, so the squelch keeps its edge.\n- LEVEL 6: about the same loudness as with the distortion off.\n- Listen for: switch the distortion off and on. On, the line sounds fuller and a little rougher, but the squelch is unchanged.',
        set: { 'dist.on': true, 'dist.drive': 2, 'dist.tone': 6, 'dist.level': 6 } },
    ],
    context: {
      'env.decay': 'Kept short because every step has a note. Turn it past 5 and the notes blur into one long wobble.',
      'filter.cutoff': 'Turn this slowly over a minute or so while the riff runs. That slow opening is how long acid tracks build.',
      'filter.res': 'Raise it towards 9 for a wetter squelch on every step.',
      'amp.accent': 'Sets how far the accented steps stand out from the steady run of notes.',
      'dist.drive': 'Kept low so it adds weight without blurring the notes.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Sweep slowly from 2 to 7 while the riff plays', hear: 'The line opens from a muffled ticking into a bright, chattering squelch.' },
      { id: 'env.decay', try: 'Raise to 6', hear: 'The notes smear into each other and the line starts to wobble instead of tick.' },
      { id: 'filter.envMod', try: 'Drop to 2', hear: 'The line goes darker and the accents become the only bright notes.' },
    ],
  },
  {
    id: 'td-acid-techno', name: 'Hard Acid Techno', ref: 'In the style of Chris Liberator and 1990s London acid techno', artist: 'Chris Liberator',
    tags: ['bass', 'acid', 'techno', '90s'], level: 2,
    blurb: 'A hard, fast, heavily distorted line with bright, screaming accents.',
    how: 'The resonance is high and the distortion is driven nearly flat out, so every note comes out at much the same loudness and the resonant peak turns into a scream. A bright TONE setting keeps the top end harsh. Because heavy distortion is much louder than the clean sound, LEVEL is turned well down to match.',
    phrase: acidPhrase(145, 'C2a C2 C2 C3 C2 C2a D#2 C2 C2s C3 C2 C2a G2 C2 C2s F2'),
    steps: [
      { title: 'A squelchy, fast voice', module: 'filter', why: 'Start from a clean acid voice set for a fast tempo.\n- WAVEFORM sawtooth, CUTOFF 4, RESONANCE 8.5.\n- ENVELOPE 6, DECAY 3: a strong sweep on each note that closes before the next one.\n- ACCENT 8: big jumps on the accented steps.\n- Listen for: a sharp, squelchy line, still clean.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 4, 'filter.res': 8.5, 'filter.envMod': 6, 'env.decay': 3, 'amp.accent': 8 } },
      { title: 'Drive the distortion hard', module: 'fx', why: 'Heavy distortion clips the wave flat, so the quiet ends of the notes come up nearly as loud as the starts.\n- OFF/ON to ON.\n- DISTORTION 9: driven almost as far as it goes.\n- Listen for: the line suddenly much louder, thicker and harsher, with the squelch screaming at the top of each note.',
        set: { 'dist.on': true, 'dist.drive': 9 } },
      { title: 'Bright tone, lower level', module: 'fx', why: 'TONE and LEVEL finish the distortion.\n- TONE 7: bright, so the scream cuts through a loud kick drum.\n- LEVEL 3.5: heavy distortion is much louder than the clean sound, so the output is pulled right down to match.\n- Listen for: switch the distortion off and on. The loudness should stay close; only the character changes.',
        set: { 'dist.tone': 7, 'dist.level': 3.5 } },
    ],
    context: {
      'dist.drive': 'Near the top, so every note is squashed to the same level. Turn it down to 4 and the gaps between loud and quiet notes come back.',
      'dist.tone': 'Bright here for a harsh top end. Turn it left for a thicker, less painful sound.',
      'dist.level': 'Low because heavy drive is loud. Raise it only with VOLUME turned down.',
      'filter.res': 'High, so the distortion has a resonant peak to scream with.',
      'amp.accent': 'High, so the accented steps sweep the filter far up even through the distortion.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Sweep from 2 to 8 and back while the riff plays', hear: 'From a distorted rumble to a full scream and back down.' },
      { id: 'dist.tone', try: 'Turn down to 2', hear: 'The scream goes dark and thick, more like a fuzz bass.' },
      { id: 'filter.res', try: 'Push to 10', hear: 'The accents start to whistle on their own on top of the distortion.' },
    ],
  },
  {
    id: 'td-rave-fuzz', name: 'Rave Fuzz Bass', ref: 'In the style of early 1990s UK rave bass (Altern-8)', artist: 'Altern-8',
    tags: ['bass', 'rave', 'hardcore', '90s'], level: 2,
    blurb: 'A low, dark, heavily fuzzed bass with long held notes that slide down and back up.',
    how: 'A sawtooth with a mostly closed filter is pushed into heavy distortion with TONE turned well down. The clipping fills in the sound, and the dark tone takes off the harsh top so what is left is a thick, round fuzz. Ties hold some notes for several steps and slides join them, so the bass groans between pitches instead of stepping.',
    phrase: acidPhrase(128, 'E1a - - E1 . E1 G1s A1 - . E1a - D2 . B1s A1'),
    steps: [
      { title: 'A dark, held bass', module: 'filter', why: 'The filter is kept low and the envelope slow, so the notes are round and long.\n- WAVEFORM sawtooth, CUTOFF 2.5, RESONANCE 5.\n- ENVELOPE 5, DECAY 6 (about 800 ms): each note opens the filter part way and closes slowly.\n- Listen for: a low, plain bass. The tied notes hold for several steps.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 2.5, 'filter.res': 5, 'filter.envMod': 5, 'env.decay': 6, 'amp.accent': 5 } },
      { title: 'Full drive, dark tone', module: 'fx', why: 'This is the fuzz. With DISTORTION at the top the wave is clipped almost square, and TONE takes away the fizz that clipping adds.\n- OFF/ON to ON.\n- DISTORTION 10: flat out.\n- TONE 2: dark, so the fuzz is thick rather than harsh.\n- LEVEL 4: lower than usual, because full drive is loud.\n- Listen for: the bass grows much fatter and the end of each held note no longer fades away.',
        set: { 'dist.on': true, 'dist.drive': 10, 'dist.tone': 2, 'dist.level': 4 } },
      { title: 'Compare the tone', module: 'fx', why: 'The same drive sounds very different with TONE turned up, so this step leaves it dark but shows the range.\n- TONE stays at 2.\n- Listen for: turn TONE to 8 while the riff plays. The fuzz turns into a buzzing rasp, much closer to a distorted acid line. Bring it back to 2 for the rave bass.',
        set: {} },
    ],
    context: {
      'dist.tone': 'The main control here. Dark gives a round fuzz bass; bright gives a buzzing rasp.',
      'dist.drive': 'Flat out, so the wave is clipped almost to a square and every held note stays loud.',
      'dist.level': 'Low to stop the fuzz being much louder than the clean sound.',
      'filter.cutoff': 'Kept low so the fuzz has little top end to start with.',
      'env.decay': 'Long, so each held note stays open for a while before it closes.',
    },
    tweaks: [
      { id: 'dist.tone', try: 'Sweep from 2 to 8 while the riff plays', hear: 'From a thick, round fuzz to a harsh, buzzing rasp.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A hollower fuzz with more of a hum in it.' },
      { id: 'filter.res', try: 'Raise to 8', hear: 'A growling squelch appears inside the fuzz on each note.' },
    ],
  },
  {
    id: 'td-electro-funk', name: 'Electro Funk Bass', ref: 'In the style of 1980s electro-funk bass lines', artist: 'Various',
    tags: ['bass', 'electro', 'funk', '80s'], level: 1,
    blurb: 'A short, punchy, clean bass with syncopated notes, octave jumps and a few slides.',
    how: 'The notes are short and land off the beat, so the gaps matter as much as the notes. A short DECAY and moderate resonance give each note a quick "bow" at the start instead of a long squelch. There is no distortion, so the bass stays clean and tight.',
    phrase: acidPhrase(108, 'G1a . G1 G2s F2 . D2 . G1a . . A#1 . C2s D2 F1 G1a . G1 G2s F2 . D2 C2 . A#1 G1a . F1 . G1s A#1', 0.45),
    steps: [
      { title: 'Short notes, low filter', module: 'filter', why: 'A funk bass needs notes that stop cleanly, so the envelope is short.\n- WAVEFORM sawtooth, CUTOFF 3, RESONANCE 4.\n- ENVELOPE 5, DECAY 1.5 (about 280 ms): a quick bright start that is gone almost at once.\n- Listen for: a punchy, plucked bass. The rests between notes stay clear.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3, 'filter.res': 4, 'filter.envMod': 5, 'env.decay': 1.5, 'amp.accent': 4 } },
      { title: 'Accents on the downbeats', module: 'env', why: 'The accents in this riff fall on the low note at the start of each half bar.\n- ACCENT 6: louder, with a short extra flick of the filter.\n- Listen for: the low G thumping at the front of each phrase. With RESONANCE at 4 the accent sweep is small, so the accents punch rather than shriek.',
        set: { 'amp.accent': 6 } },
      { title: 'Slides into the octave', module: 'glide', why: 'Slid steps glide into the next note over about 70 ms without starting the envelopes again.\n- No knob for this: the slides are written into the riff.\n- Listen for: the low G sliding up to the high G, and C sliding into D. The second note has no attack of its own, so it sounds bent into place.',
        set: {} },
    ],
    context: {
      'env.decay': 'Short, so the notes stop and the rests stay clean. Above 4 the line loses its punch.',
      'filter.res': 'Moderate. High enough to give each note a little "bow", low enough not to squelch.',
      'filter.cutoff': 'Sets how bright the bass is between notes. Raise it for a buzzier, more electro tone.',
      'amp.accent': 'Gives the downbeats their thump.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Raise to 8', hear: 'The bass turns into an acid line with the same funk rhythm.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A rounder, rubbery tone that sits further back.' },
      { id: 'env.decay', try: 'Raise to 5', hear: 'Each note wows open and closed, and the line gets looser.' },
    ],
  },
  {
    id: 'td-square-line', name: 'Square Acid Line', ref: 'In the style of Fatboy Slim — "Everybody Needs a 303"', artist: 'Fatboy Slim',
    tags: ['bass', 'acid', 'big beat', '90s'], level: 1,
    blurb: 'An acid line on the square wave: hollower and more rubbery than the sawtooth, with a little grit.',
    how: 'The square wave has only odd harmonics, so with the same filter settings it sounds hollower and less buzzy than the sawtooth. The resonance still gives the squelch, but it sounds more like a rubbery "boing". A touch of dark distortion fills out the thinner wave.',
    phrase: acidPhrase(125, 'D2 D2a . D2 F2s G2 . D2 C3a . D2 A#1s C2 . D2a D3'),
    steps: [
      { title: 'Square wave', module: 'osc', why: 'Switch the oscillator from sawtooth to square.\n- WAVEFORM square: hollow, like a clarinet next to the sawtooth’s brass.\n- Listen for: play the riff and flip WAVEFORM back and forth. The sawtooth is buzzier; the square is rounder and a little quieter.',
        set: { 'osc.wave': 'sq', 'filter.cutoff': 4, 'filter.res': 3, 'filter.envMod': 4, 'env.decay': 4, 'amp.accent': 5 } },
      { title: 'Squelch on the square', module: 'filter', why: 'The filter works the same way on either wave.\n- RESONANCE 7.5: a strong peak that rides on the filter sweep.\n- ENVELOPE 5, DECAY 4 (about 500 ms): each note opens and closes in a steady "boing".\n- ACCENT 7: the accented steps jump out.\n- Listen for: a rubbery, hollow squelch. The accents still shriek, because the accent sweep depends on RESONANCE, not the wave.',
        set: { 'filter.res': 7.5, 'filter.envMod': 5, 'amp.accent': 7 } },
      { title: 'Light, dark grit', module: 'fx', why: 'A little distortion fills out the square wave.\n- OFF/ON to ON.\n- DISTORTION 3: light clipping on the peaks.\n- TONE 3: dark, so the grit adds weight but not fizz.\n- LEVEL 6: about level with the distortion off.\n- Listen for: switch the distortion off and on. On, the line sounds a little thicker and warmer.',
        set: { 'dist.on': true, 'dist.drive': 3, 'dist.tone': 3, 'dist.level': 6 } },
    ],
    context: {
      'osc.wave': 'The square is what makes this line hollow. Switch to sawtooth for the brighter, classic acid buzz.',
      'filter.res': 'The squelch. With the square it sounds more like a rubbery "boing".',
      'env.decay': 'Middle setting, so each note opens and closes once before the next.',
      'dist.tone': 'Dark, so the grit thickens the line without making it fizz.',
    },
    tweaks: [
      { id: 'osc.wave', try: 'Switch to sawtooth and back', hear: 'The sawtooth is brighter and buzzier; the square is hollow and rounder.' },
      { id: 'filter.cutoff', try: 'Sweep from 2 to 7 while the riff plays', hear: 'The line opens from a dull thud into a hollow, honking squelch.' },
      { id: 'dist.drive', try: 'Raise to 7', hear: 'The square clips into a buzzing fuzz and loses most of its hollowness.' },
    ],
  },
  {
    id: 'td-high-lead', name: 'Distorted High Lead', ref: 'In the style of Daft Punk — "Da Funk"', artist: 'Daft Punk',
    tags: ['lead', 'acid', 'house', '90s'], level: 2,
    blurb: 'A riff an octave and more above the usual bass range, distorted to a bright, singing edge.',
    how: 'The notes sit around the octave below middle C and up to it, where the TD-3 works as a lead. The filter is set higher and the resonance lower than for a bass, because up here the squelch gets piercing. Moderate distortion with a bright TONE gives the notes a hard, singing edge, and ties and slides make the riff legato.',
    phrase: acidPhrase(112, 'G3a - F3s G3 . D3 . F3 G3a - A#3s C4 - A#3 G3 F3 G3a - F3s G3 . D3 . C3 D3a - F3s G3 - - . .'),
    steps: [
      { title: 'A brighter filter for a high riff', module: 'filter', why: 'High notes need the filter further open, or the cutoff sits below the note and it goes dull.\n- WAVEFORM sawtooth, CUTOFF 5.5, RESONANCE 6.\n- ENVELOPE 4, DECAY 5 (about 630 ms): a gentle opening on each note.\n- Listen for: a clear, buzzy lead line. The tied notes hold and the slid notes bend into place.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 5.5, 'filter.res': 6, 'filter.envMod': 4, 'env.decay': 5, 'amp.accent': 5 } },
      { title: 'Medium drive', module: 'fx', why: 'Distortion turns the lead from a synth tone into something closer to an overdriven guitar.\n- OFF/ON to ON.\n- DISTORTION 5: enough to clip each note hard but keep the pitches clear.\n- Listen for: the notes get thicker and the held notes stay loud to the end.',
        set: { 'dist.on': true, 'dist.drive': 5 } },
      { title: 'Bright tone, matched level', module: 'fx', why: 'TONE and LEVEL finish the lead.\n- TONE 7: bright, so the lead cuts through a mix.\n- LEVEL 4.5: brings the louder distorted signal back down.\n- Listen for: a hard, singing edge on every note. Turn TONE down to 3 and the lead goes muffled and far away.',
        set: { 'dist.tone': 7, 'dist.level': 4.5 } },
    ],
    context: {
      'filter.cutoff': 'Set higher than for a bass so the high notes are not muffled.',
      'filter.res': 'Lower than a bass line, because in this register a strong peak gets piercing.',
      'dist.drive': 'Medium. Higher and the pitches start to blur into the fuzz.',
      'dist.tone': 'Bright, for the singing edge. Darker settings push the lead into the background.',
      'osc.tune': 'Use this to move the whole riff up or down, for example −12 to hear it as a bass.',
    },
    tweaks: [
      { id: 'osc.tune', try: 'Set to −12', hear: 'The same riff becomes a distorted bass line an octave down.' },
      { id: 'filter.res', try: 'Raise to 9', hear: 'The notes squeal at the start, which gets painful up here.' },
      { id: 'dist.on', try: 'Switch the distortion off', hear: 'A thinner, plainer lead with more of the filter movement showing.' },
    ],
  },
  {
    id: 'td-dub-acid', name: 'Slow Dub Acid', ref: 'In the style of slow, dub-influenced acid', artist: 'Various',
    tags: ['bass', 'acid', 'dub', 'downtempo'], level: 2,
    blurb: 'A slow, sparse line where each note opens the filter and closes it over more than a second.',
    how: 'DECAY is turned near the top, so after each note the filter takes well over a second to close and the note wows slowly. The tempo is low and the riff has long gaps, which leaves room for each sweep. ENVELOPE is high to make the sweep wide, and the cutoff starts low so it begins from dark. Accented notes ignore DECAY and close in 0.2 s, so they come out short and sharp against the slow ones.',
    phrase: acidPhrase(100, 'C2a - - . . . G1 . C2 - D#2s F2 - - . . C2a - - . . . G1 . A#1 - C2s D#2 - - . G1'),
    steps: [
      { title: 'A long decay', module: 'env', why: 'DECAY sets how long the filter takes to close after each note starts.\n- WAVEFORM sawtooth, CUTOFF 2.5, RESONANCE 7, ENVELOPE 4.\n- DECAY 9 (about 1.7 s): the filter is still closing long after the next note has started.\n- Listen for: each note opening and closing slowly in one long "wow".',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 2.5, 'filter.res': 7, 'filter.envMod': 4, 'env.decay': 9, 'amp.accent': 3 } },
      { title: 'A wider sweep', module: 'filter', why: 'ENVELOPE sets how far each note pushes the filter open. It also pulls the resting point down a little, so turning it up makes the gaps darker as well.\n- ENVELOPE 7.\n- RESONANCE 8: a stronger peak to follow the slow sweep.\n- Listen for: each "wow" is wider and the low end between notes gets darker.',
        set: { 'filter.envMod': 7, 'filter.res': 8 } },
      { title: 'Short accents against long notes', module: 'env', why: 'Accented notes close their filter in 0.2 s whatever DECAY says.\n- ACCENT 5: the accented C at the start of each bar is louder and short.\n- Listen for: the accented first note snaps shut, then the unaccented notes after it wow slowly. Turn ACCENT to 0 and the first note wows like the rest but quieter.',
        set: { 'amp.accent': 5 } },
    ],
    context: {
      'env.decay': 'Near the top so each note closes slowly. This is what makes it dub rather than acid house.',
      'filter.envMod': 'High for a wide sweep. It also darkens the resting cutoff a little.',
      'filter.cutoff': 'Low, so each sweep starts from a dark, round bass.',
      'amp.accent': 'Accented notes close fast no matter what DECAY says, so they stand out against the slow ones.',
    },
    tweaks: [
      { id: 'env.decay', try: 'Sweep from 9 down to 3 while the riff plays', hear: 'The slow wows tighten into short, plucky notes.' },
      { id: 'filter.res', try: 'Raise to 9.5', hear: 'The slow sweeps start to sing and whistle as they close.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A hollower, rounder wow that sits lower in the mix.' },
    ],
  },
  {
    id: 'td-res-zaps', name: 'Resonance Zaps', ref: 'In the style of the zaps and whistles in early acid house', artist: 'Various',
    tags: ['fx', 'acid', 'house', '80s'], level: 3,
    blurb: 'RESONANCE at the top, so the filter whistles on its own and each note fires a falling laser zap.',
    how: 'With RESONANCE at 10 the filter rings at its cutoff by itself, a whistle that follows the cutoff rather than the notes. A high ENVELOPE and short DECAY throw the cutoff up on each note and drop it fast, so the whistle falls in pitch: a zap. Accented steps add their own sweep, which is biggest at high resonance and builds up over accents close together.',
    phrase: acidPhrase(124, 'C2a . . C2 . C2a . . C2 . . C2a . C2 C2a .'),
    steps: [
      { title: 'Resonance to the top', module: 'filter', why: 'Near 10 the filter starts to whistle at the cutoff on its own.\n- WAVEFORM sawtooth, CUTOFF 5, ENVELOPE 3, DECAY 3.\n- RESONANCE 10.\n- Listen for: a thin whistle riding on each note, with the bass thinned out underneath. Turn CUTOFF and the whistle changes pitch.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 5, 'filter.res': 10, 'filter.envMod': 3, 'env.decay': 3, 'amp.accent': 4 } },
      { title: 'Throw it up and drop it', module: 'env', why: 'A big envelope with a short decay sweeps the whistle down fast.\n- ENVELOPE 9: each note throws the cutoff, and the whistle with it, far up.\n- DECAY 1 (about 250 ms): it falls back quickly.\n- Listen for: every note is now a falling "pew" zap.',
        set: { 'filter.envMod': 9, 'env.decay': 1 } },
      { title: 'Accents build bigger zaps', module: 'env', why: 'At RESONANCE 10 the accent sweep is at its largest, and back-to-back accents stack up.\n- ACCENT 7.\n- Listen for: the accented steps zap higher and louder than the others, and the two accents near the end of the bar go highest.',
        set: { 'amp.accent': 7 } },
    ],
    context: {
      'filter.res': 'At 10 the filter whistles on its own. Below about 8.5 the zaps turn back into an ordinary squelch.',
      'filter.envMod': 'How high each zap starts. Lower values give smaller "blips".',
      'env.decay': 'How fast the zap falls. Longer gives a slow, falling whistle.',
      'filter.cutoff': 'Sets where the whistle comes to rest between zaps.',
      'amp.accent': 'With resonance this high, the accents give the biggest zaps.',
    },
    tweaks: [
      { id: 'env.decay', try: 'Raise to 6', hear: 'The zaps slow into falling whistles that overlap the next note.' },
      { id: 'filter.cutoff', try: 'Sweep from 2 to 8 while the riff plays', hear: 'The whistle between zaps rises and falls with the knob.' },
      { id: 'filter.res', try: 'Drop to 7', hear: 'The zaps lose their pitch and become a plain acid squelch.' },
    ],
  },
  {
    id: 'td-slow-chord-arp', name: 'Slow Chord Arpeggio', ref: 'In the style of slow acid arpeggios in ambient electronica', artist: 'Various',
    tags: ['seq', 'ambient', 'chill', 'downtempo'], level: 1,
    blurb: 'A slow arpeggio that walks up and down two chords, each note opening the filter gently and closing it slowly.',
    how: 'The notes climb through A minor 7 and back down, then do the same over F major 7. RESONANCE is kept low so there is no squelch, only a soft opening on each note. DECAY near the top lets each note close slowly, so the filter is still moving when the next one starts.',
    phrase: acidPhrase(80, 'A2 - C3 - E3 - G3 - A3 - G3 - E3 - C3 - F2 - A2 - C3 - E3 - F3 - E3 - C3 - A2 -', 0.9),
    steps: [
      { title: 'A soft, open filter', module: 'filter', why: 'For an ambient arpeggio the filter should round the notes off, not squelch.\n- WAVEFORM sawtooth, CUTOFF 4, RESONANCE 2.\n- ENVELOPE 3: a small opening on each note.\n- Listen for: a mellow, slightly buzzy arpeggio with no squelch.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 4, 'filter.res': 2, 'filter.envMod': 3, 'env.decay': 4, 'amp.accent': 0 } },
      { title: 'A long decay', module: 'env', why: 'DECAY sets how slowly the filter closes after each note.\n- DECAY 8 (about 1.5 s): each note brightens and then fades back over more than a second.\n- Listen for: the notes run into each other in a slow, rolling swell instead of separate plucks.',
        set: { 'env.decay': 8 } },
      { title: 'No accents', module: 'env', why: 'Accented steps would close the filter in 0.2 s and jump out of the line, which breaks up a calm arpeggio.\n- ACCENT 0, and no accents are written into the riff.\n- Listen for: every note at the same level, so the arpeggio moves evenly.',
        set: {} },
    ],
    context: {
      'filter.res': 'Low, so the notes are rounded off without a squelch. Raise it past 5 and the arpeggio starts to sound like acid.',
      'env.decay': 'Long, so each note fades back slowly and the notes blend into each other.',
      'filter.cutoff': 'Sets how bright the arpeggio is overall. Around 4 it sits in the background.',
      'filter.envMod': 'Small, for a gentle lift on each note rather than a sweep.',
      'amp.accent': 'At 0 because no step is accented and the line should stay even.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Turn slowly from 2.5 to 6 over half a minute', hear: 'The arpeggio comes forward from a muffled hum into a clear, bright line.' },
      { id: 'osc.tune', try: 'Set to −12', hear: 'The same arpeggio an octave down, darker and closer to a slow bass part.' },
      { id: 'filter.res', try: 'Raise to 6', hear: 'Each note gains a soft "wow" as the filter moves.' },
    ],
  },
  {
    id: 'td-tape-square-arp', name: 'Tape-Warm Square Arpeggio', ref: 'In the style of lo-fi and chillout electronica', artist: 'Various',
    tags: ['seq', 'ambient', 'lo-fi', 'chill'], level: 2,
    blurb: 'A rounded square-wave arpeggio with a little dark distortion, so it sounds slightly saturated, as if played back from tape.',
    how: 'The square wave is hollow and soft compared with the sawtooth. Light distortion with TONE turned well down rounds off the peaks of each note and adds weight without adding fizz, the way an overdriven tape machine does. Two slides in each bar make the arpeggio bend between notes rather than step.',
    phrase: acidPhrase(90, 'D3 A3 F3 A3 C4 A3 F3s G3 D3 A3 F3 A3 E3s F3 C3 A2 A#2 F3 D3 F3 A3 F3 D3s E3 A#2 F3 D3 F3 C3s D3 A2 C3', 0.7),
    steps: [
      { title: 'Square wave, mellow filter', module: 'osc', why: 'Start with the hollow wave and a filter that only rounds it off.\n- WAVEFORM square.\n- CUTOFF 4.5, RESONANCE 3, ENVELOPE 3, DECAY 6 (about 900 ms).\n- Listen for: a soft, woody arpeggio. The slid notes bend into place without a new attack.',
        set: { 'osc.wave': 'sq', 'filter.cutoff': 4.5, 'filter.res': 3, 'filter.envMod': 3, 'env.decay': 6, 'amp.accent': 0 } },
      { title: 'Dark, light distortion', module: 'fx', why: 'A small amount of clipping with the top end turned down gives the saturation.\n- OFF/ON to ON.\n- DISTORTION 3: only the start of each note is clipped.\n- TONE 2: dark, so the clipping adds warmth, not buzz.\n- LEVEL 6: close to the loudness with the distortion off.\n- Listen for: switch the distortion off and on. On, the notes are thicker and slightly blurred at the start.',
        set: { 'dist.on': true, 'dist.drive': 3, 'dist.tone': 2, 'dist.level': 6 } },
      { title: 'Even out the line', module: 'filter', why: 'A touch more resonance gives each note a slight hump without turning it into acid.\n- RESONANCE 4.5.\n- Listen for: a faint vowel sound on each note, still soft. Above 6 it starts to squelch.',
        set: { 'filter.res': 4.5 } },
    ],
    context: {
      'osc.wave': 'The square is what makes it hollow and soft. The sawtooth is brighter and sounds more like a sequencer line.',
      'dist.tone': 'Turned well down so the distortion warms the sound instead of making it buzz.',
      'dist.drive': 'Low. Above about 5 the arpeggio starts to sound like fuzz rather than tape.',
      'dist.level': 'Set so switching the distortion on does not make it louder.',
      'env.decay': 'Fairly long, so the notes fade into each other.',
      'filter.res': 'Kept low to medium for a soft vowel on each note, not a squelch.',
    },
    tweaks: [
      { id: 'dist.tone', try: 'Turn up to 7', hear: 'The warmth turns into a thin, buzzing edge.' },
      { id: 'dist.drive', try: 'Raise to 6', hear: 'The notes get thicker and flatter, more like a fuzz box than tape.' },
      { id: 'osc.wave', try: 'Switch to sawtooth', hear: 'A brighter, buzzier arpeggio that sits further forward.' },
    ],
  },
  {
    id: 'td-trip-hop-squelch', name: 'Trip-Hop Squelch', ref: 'In the style of 1990s trip-hop and downtempo', artist: 'Various',
    tags: ['bass', 'acid', 'trip-hop', 'downtempo'], level: 2,
    blurb: 'A slow, sparse, squelchy bass at 88 BPM, with long gaps for a heavy drum break to fill.',
    how: 'At a slow tempo the gaps between notes are long, so each squelch is heard on its own. High RESONANCE and a medium DECAY make every note a slow "wow" that lasts about half a beat. Light distortion with a dark TONE thickens the low end, which suits the dusty sound of downtempo records.',
    phrase: acidPhrase(88, 'E1a - . E1 . . G1s A1 . . E2a . D2 . B1s G1 E1 - . . E1 . G1 . A1a - . C2s D2 . B1 .'),
    steps: [
      { title: 'A slow squelch', module: 'filter', why: 'At 88 BPM each note has time to open and close the filter fully.\n- WAVEFORM sawtooth, CUTOFF 2.5, RESONANCE 8.\n- ENVELOPE 6, DECAY 5 (about 630 ms).\n- Listen for: each note is a slow, wet squelch with silence after it.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 2.5, 'filter.res': 8, 'filter.envMod': 6, 'env.decay': 5, 'amp.accent': 4 } },
      { title: 'Accents on the low notes', module: 'env', why: 'The accents fall on the low E and the A, so they mark out the bar.\n- ACCENT 6.\n- Listen for: the accented notes are louder and shorter, with a sharp upward flick of the filter. The other notes wow more slowly.',
        set: { 'amp.accent': 6 } },
      { title: 'Dusty weight', module: 'fx', why: 'A little dark distortion fills out the bottom end.\n- OFF/ON to ON.\n- DISTORTION 2, TONE 3, LEVEL 6.\n- Listen for: the line sounds fuller and slightly rough, but the squelch is still clear.',
        set: { 'dist.on': true, 'dist.drive': 2, 'dist.tone': 3, 'dist.level': 6 } },
    ],
    context: {
      'filter.res': 'High for the squelch. At this tempo the squelch is the main sound, so it can go higher than in a fast line.',
      'env.decay': 'Medium. Shorter and the notes go plucky; longer and they blur together.',
      'filter.cutoff': 'Low, so the gaps sound dark and each note opens out of the dark.',
      'amp.accent': 'Marks the low notes that hold the bar together.',
      'dist.tone': 'Dark, so the distortion adds weight rather than hiss.',
    },
    tweaks: [
      { id: 'filter.cutoff', try: 'Sweep from 1.5 to 5 while the riff plays', hear: 'The line opens from a muffled thud into a full, wet squelch.' },
      { id: 'env.decay', try: 'Raise to 8', hear: 'Each note wows slowly and the line gets lazier.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A rounder, hollow squelch that sits lower behind the drums.' },
    ],
  },
  {
    id: 'td-res-bells', name: 'Resonant Bell Arpeggio', ref: 'In the style of slow 1990s ambient techno', artist: 'Various',
    tags: ['seq', 'ambient', 'techno', '90s'], level: 3,
    blurb: 'A slow, sparse arpeggio where the filter rings like a bell on top of each note.',
    how: 'With RESONANCE near the top the filter rings at its cutoff whenever it is moved quickly. A strong ENVELOPE throws the cutoff up at the start of each note, so every note begins with a bright, ringing tone that falls away as the filter closes. The square wave and a long DECAY keep the note under the ring soft, so the result sounds struck, like a bell or a glass.',
    phrase: acidPhrase(76, 'C3 - . E3 - . G3 - . B3 - . . G3 . . C3 - . A2 - . E3 - . G3 - . . E3 . .', 0.8),
    steps: [
      { title: 'Square wave, high resonance', module: 'filter', why: 'The filter is set close to ringing on its own.\n- WAVEFORM square, CUTOFF 3.5.\n- RESONANCE 9.5: a strong, narrow peak.\n- ENVELOPE 3, DECAY 4.\n- Listen for: each note has a thin whistle riding on it.',
        set: { 'osc.wave': 'sq', 'filter.cutoff': 3.5, 'filter.res': 9.5, 'filter.envMod': 3, 'env.decay': 4, 'amp.accent': 0 } },
      { title: 'Strike each note', module: 'env', why: 'A larger envelope moves the cutoff, and the ringing peak with it, a long way on each note.\n- ENVELOPE 6.\n- DECAY 7 (about 1.2 s): the ring falls slowly back down.\n- Listen for: a bright "ting" at the start of every note that slides down and fades, like a struck bell.',
        set: { 'filter.envMod': 6, 'env.decay': 7 } },
      { title: 'Find the bell pitch', module: 'filter', why: 'The ring follows the cutoff, not the notes, so CUTOFF picks where it sits.\n- CUTOFF 4.\n- Listen for: the ring now lands above most notes. Move CUTOFF a little either side while the riff plays and keep it where the ring sounds clearest.',
        set: { 'filter.cutoff': 4 } },
    ],
    context: {
      'filter.res': 'Near the top so the filter rings. Below about 8 the bell becomes an ordinary filter sweep.',
      'filter.envMod': 'How high each strike throws the ring before it falls.',
      'env.decay': 'How long the ring takes to fall back. Long for a slow bell.',
      'filter.cutoff': 'Where the ring settles. It does not follow the keys, so small moves change the colour of every note.',
      'osc.wave': 'The square keeps the note under the ring soft.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Push to 10', hear: 'The ring gets louder and longer, and starts to whistle between notes.' },
      { id: 'env.decay', try: 'Drop to 3', hear: 'Short, bright pings instead of slow bells.' },
      { id: 'osc.wave', try: 'Switch to sawtooth', hear: 'More buzz under the ring, so it sounds less like a bell and more like a synth.' },
    ],
  },
  {
    id: 'td-country-two-step', name: 'Country Two-Step Acid', ref: 'In the style of Alabama 3 — "Ain’t Goin’ to Goa"', artist: 'Alabama 3',
    tags: ['bass', 'acid', 'country', '90s'], level: 1,
    blurb: 'A country two-step bass that rocks between root and fifth, played as an acid line with accented downbeats.',
    how: 'Country bass alternates the root of the chord with the fifth below or above it, one on each beat. Here that pattern runs on the TD-3 with a squelchy filter, so the line is a country bass and an acid line at once. A walk-up of two slid notes links the G bar to the C bar and back, as a country bass player would.',
    phrase: acidPhrase(118, 'G1a . . G1 D2 . . . G1a . . G1 D2 . B1s C2 C2a . . C2 G2 . . . C2a . . C2 G1 . A1s B1'),
    steps: [
      { title: 'A tight country bass', module: 'filter', why: 'Start with short, round notes so the root–fifth rhythm is clear.\n- WAVEFORM sawtooth, CUTOFF 3.5, RESONANCE 4.\n- ENVELOPE 4, DECAY 2.5 (about 380 ms).\n- Listen for: a bouncing bass, low note on the beat, higher note on the next.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3.5, 'filter.res': 4, 'filter.envMod': 4, 'env.decay': 2.5, 'amp.accent': 4 } },
      { title: 'Add the squelch', module: 'filter', why: 'Raising the resonance turns the country bass into an acid line without changing the notes.\n- RESONANCE 7.\n- Listen for: each note now has a squelch on it, and the walk-ups bend into the next chord.',
        set: { 'filter.res': 7 } },
      { title: 'Accent the downbeats', module: 'env', why: 'The accents sit on the root at the start of each half bar, where a country bass player would dig in.\n- ACCENT 7.\n- Listen for: the root notes snap out with a sharp filter flick, and the fifths sit back between them.',
        set: { 'amp.accent': 7 } },
    ],
    context: {
      'filter.res': 'This is what makes the country bass sound acid. Turn it down to 3 and it goes back to a plain bass.',
      'env.decay': 'Short, so the two-step bounce stays tight.',
      'amp.accent': 'Gives the roots their weight against the fifths.',
      'filter.cutoff': 'Medium. Higher and the line gets buzzy and pushes in front of the guitars.',
      'filter.envMod': 'Medium, so each note squelches without the line getting shrill.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Turn between 3 and 8 while the riff plays', hear: 'The line moves between a plain country bass and an acid line.' },
      { id: 'dist.on', try: 'Switch the distortion on with DISTORTION 3 and LEVEL 6', hear: 'A rougher, more rock-and-roll bass.' },
      { id: 'env.decay', try: 'Raise to 6', hear: 'The notes wow and the two-step gets looser and lazier.' },
    ],
  },
  {
    id: 'td-dirty-blues', name: 'Dirty Blues Shuffle', ref: 'In the style of Alabama 3 — "Woke Up This Morning"', artist: 'Alabama 3',
    tags: ['bass', 'acid', 'blues', '90s'], level: 2,
    blurb: 'A distorted blues riff on the minor pentatonic, played with a shuffle and sliding up into the root.',
    how: 'The riff uses the E minor pentatonic with the flattened fifth, the blue note, sliding up a semitone. The off-beat notes are played late, in a shuffle, which gives it a swing instead of the straight sixteenths of most acid. Heavy distortion with a mid TONE makes the TD-3 sound like an overdriven bass amp, and the slides from D up into E pull each bar back to the root.',
    phrase: { bpm: 92, loop: true, steps: [
      [0, 40, 0.5, 1], [0.667, 40, 0.28], [1, 43, 0.28], [1.667, 45, 0.28], [2, 46, 0.72], [2.667, 47, 0.28], [3, 38, 0.72], [3.667, 40, 0.28],
      [4, 40, 0.5, 1], [4.667, 40, 0.28], [5, 43, 0.28], [5.667, 45, 0.28, 1], [6, 43, 0.28], [6.667, 40, 0.28], [7, 38, 0.72], [7.667, 40, 0.28],
    ] },
    steps: [
      { title: 'A growling bass', module: 'filter', why: 'Start from a low, squelchy voice.\n- WAVEFORM sawtooth, CUTOFF 3, RESONANCE 6.5.\n- ENVELOPE 5, DECAY 3 (about 440 ms).\n- ACCENT 6.\n- Listen for: the shuffle: each pair of notes is long-short, not even. The B flat slides up into B, and D slides up into E.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3, 'filter.res': 6.5, 'filter.envMod': 5, 'env.decay': 3, 'amp.accent': 6 } },
      { title: 'Drive it like an amp', module: 'fx', why: 'Strong distortion gives the riff the edge of a blues bass played through a cranked amplifier.\n- OFF/ON to ON.\n- DISTORTION 7.\n- TONE 4: a little darker than centre, so it growls rather than fizzes.\n- Listen for: the notes get thicker and stay loud to the end, and the slides sound like a finger dragged up the string.',
        set: { 'dist.on': true, 'dist.drive': 7, 'dist.tone': 4 } },
      { title: 'Match the level', module: 'fx', why: 'This much drive is loud, so the output comes down.\n- LEVEL 4.\n- Listen for: switch the distortion off and on. The loudness should stay close, and only the dirt changes.',
        set: { 'dist.level': 4 } },
    ],
    context: {
      'dist.drive': 'High, for the overdriven amp sound. Below 4 it is a clean acid bass with a shuffle.',
      'dist.tone': 'Slightly dark, so the riff growls. Turn it up for a rasping, garage-rock edge.',
      'dist.level': 'Low because heavy drive is loud.',
      'filter.res': 'Medium-high: enough squelch to be acid under the dirt, not so much that it whistles.',
      'env.decay': 'Short enough that the shuffle stays crisp.',
      'amp.accent': 'Puts weight on the root at the start of each bar.',
    },
    tweaks: [
      { id: 'dist.tone', try: 'Sweep from 2 to 8 while the riff plays', hear: 'From a dark, woolly growl to a hard, rasping edge.' },
      { id: 'filter.cutoff', try: 'Raise to 5', hear: 'The riff gets brighter and closer to a fuzz guitar.' },
      { id: 'osc.tune', try: 'Set to −5', hear: 'The riff moves down to B, lower and heavier.' },
    ],
  },
  {
    id: 'td-gospel-call', name: 'Gospel Call and Response', ref: 'In the style of Alabama 3 — "Power in the Blood"', artist: 'Alabama 3',
    tags: ['bass', 'acid', 'gospel', '00s'], level: 2,
    blurb: 'A bass line that calls on the F chord and answers on B flat, with octave pick-ups leading into each half.',
    how: 'The first half bar states a phrase on F, the second answers it on B flat, as a choir and preacher trade lines in gospel. Each half ends with a jump up an octave, the pick-up a gospel bass player uses to lead the band into the next chord. The TD-3 plays it with a moderate squelch and a little grit, so the line is warm but still clearly acid.',
    phrase: acidPhrase(104, 'F1a . . F1 A1 . C2 . F2a - . . . . F1 F2 A#1a . . A#1 D2 . F2 . A#2a - . . C2 . C1 C2'),
    steps: [
      { title: 'A warm bass voice', module: 'filter', why: 'Start with a rounded, medium-bright voice.\n- WAVEFORM sawtooth, CUTOFF 3.5, RESONANCE 5.\n- ENVELOPE 4, DECAY 4 (about 500 ms).\n- Listen for: the call on F and the answer on B flat. Each one rises through the chord to a held high note.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 3.5, 'filter.res': 5, 'filter.envMod': 4, 'env.decay': 4, 'amp.accent': 4 } },
      { title: 'Accent the call and the answer', module: 'env', why: 'The accents fall on the first note of each phrase and on its held top note.\n- ACCENT 6.\n- RESONANCE 6.5: the accent sweep grows with RESONANCE, so this makes the accents speak more.\n- Listen for: the held high F and high B flat jump out with a squelch, the way a lead singer’s line stands out over the choir.',
        set: { 'amp.accent': 6, 'filter.res': 6.5 } },
      { title: 'A little grit', module: 'fx', why: 'Light distortion gives the line some body.\n- OFF/ON to ON.\n- DISTORTION 2, TONE 5, LEVEL 6.\n- Listen for: the octave pick-ups get a slightly harder edge, which helps them push into the next chord.',
        set: { 'dist.on': true, 'dist.drive': 2, 'dist.tone': 5, 'dist.level': 6 } },
    ],
    context: {
      'amp.accent': 'Picks out the start and the held top of each phrase, so the call and answer are clear.',
      'filter.res': 'Medium, for a squelch on the accents without turning the whole line into acid.',
      'env.decay': 'Medium, so the held top notes open and close once.',
      'filter.cutoff': 'Medium-low for a warm line. Raise it to make the octave pick-ups ring out.',
      'dist.drive': 'Light. More and the line loses the warmth gospel bass needs.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Raise to 8.5', hear: 'The held high notes squeal, and the line turns into acid house with a gospel bass part.' },
      { id: 'osc.wave', try: 'Switch to square', hear: 'A rounder, organ-like bass.' },
      { id: 'env.decay', try: 'Drop to 2', hear: 'Shorter, punchier notes; the call and answer sound more clipped.' },
    ],
  },
  {
    id: 'td-swamp-burn', name: 'Swamp Slow Burn', ref: 'In the style of Alabama 3’s slow swamp-blues grooves', artist: 'Alabama 3',
    tags: ['bass', 'acid', 'blues', 'downtempo'], level: 3,
    blurb: 'A slow, heavy, distorted groove where RESONANCE starts low and is opened by hand over a minute or so.',
    how: 'The groove is slow and leaves long gaps, like swamp blues. The distortion is on from the start with a dark TONE, so the line is thick and dirty but has little squelch. Turning RESONANCE up slowly while it plays brings the acid in bit by bit, the way an acid track builds, but over a blues riff.',
    phrase: acidPhrase(76, 'A1a - - . . A1 C2s D2 - . . E1 . G1 . A1 A1a - - . . A1 C2s D#2s E2 - . D2 . C2 . G1'),
    steps: [
      { title: 'A heavy, dark groove', module: 'filter', why: 'Start almost without resonance, so the line is a plain, low groove.\n- WAVEFORM sawtooth, CUTOFF 2.5, RESONANCE 2.\n- ENVELOPE 5, DECAY 6 (about 800 ms).\n- ACCENT 5.\n- Listen for: a slow, dark blues bass with the slides from C up to D, and in the second bar C through D sharp to E.',
        set: { 'osc.wave': 'saw', 'filter.cutoff': 2.5, 'filter.res': 2, 'filter.envMod': 5, 'env.decay': 6, 'amp.accent': 5 } },
      { title: 'Dirty and dark', module: 'fx', why: 'The distortion makes the groove thick and swampy.\n- OFF/ON to ON.\n- DISTORTION 6, TONE 3: heavy but dark.\n- LEVEL 4.5: brings the louder signal back down.\n- Listen for: the held A at the start of each bar now holds its loudness, and the line sounds like a fuzzed bass guitar.',
        set: { 'dist.on': true, 'dist.drive': 6, 'dist.tone': 3, 'dist.level': 4.5 } },
      { title: 'Open the resonance slowly', module: 'filter', why: 'This is the slow burn. Turn RESONANCE up by hand while the riff plays, taking a minute or so to get there.\n- RESONANCE from 2 up to 7.5.\n- Listen for: a squelch creeping into each note, then the accented A starting to shriek through the distortion. Stop at 7.5; past 9 it whistles.',
        set: { 'filter.res': 7.5 } },
    ],
    context: {
      'filter.res': 'The control to perform with. Start low and raise it slowly over the length of the track.',
      'dist.drive': 'Heavy, so the slow notes stay thick and loud.',
      'dist.tone': 'Dark, so the groove is muddy and low rather than harsh.',
      'dist.level': 'Lowered to match the extra loudness of the distortion.',
      'env.decay': 'Long, so each slow note opens and closes in one wide movement.',
      'filter.cutoff': 'Low, so the build comes from RESONANCE and not from brightness.',
    },
    tweaks: [
      { id: 'filter.res', try: 'Turn from 2 to 8 over about a minute', hear: 'The groove changes from a plain swamp-blues bass into an acid line.' },
      { id: 'dist.tone', try: 'Raise to 7', hear: 'The mud clears and the line gets a hard, rasping top.' },
      { id: 'filter.cutoff', try: 'Raise to 4.5 once RESONANCE is up', hear: 'The squelch gets brighter and moves to the front.' },
    ],
  },
];
