// The DeepMind 12D's effects engine: 35 algorithms, each with up to 12 parameters, loaded into four slots.
// Transcribed from behringer-deepmind.fx.json (manual chapter 9, "Effects Reference Guide"), with its parse errors
// mended by hand:
//  * FLANGER: the table ran rows into each other; the twelve rows are rebuilt from the text that was merged
//    (SPD WDL WDR DLL DLR MIX LC HC PHS FLC FHC FD).
//  * STEREO DELAY: rows 1 and 2 (MIX, TIM) were merged. Its MODE options are ST / X / M / P-P; the table only spells
//    out P-P, the other three are the X32 stereo delay's, whose table this is.
//  * HALL, ROOM and CHAMBER: units and ranges were shifted by one column for SIZE, DIF, LFX, SPR, SHP and MOD.
//  * VINTAGE ROOM: the descriptions of ER LEVEL and ER DELAY were swapped.
//  * ROTARY: five junk rows from the next chapter dropped. MOD FILTER: FRQ's description was ENV's.
//  * DECIMATOR DELAY: its table starts at parameter 2 (a stray PARAMETERS row took the place of row 1). Every other
//    delay has a MIX and this one has none, so row 1 is taken to be MIX.
//  * STEREO CHORUS PHASE is in degrees (0–180) like every other PHASE; the table printed 0–100.
// The manual lists option names but never says what the algorithms do; the DSP (src/audio/dm-fx.js) is this app's
// approximation of each one, built from the parameter list and the hardware it is named after.
//
// A parameter: [ref, display label, full name, min, max, default, unit, extra]. `unit` drives the readout; extra:
// { log: true } for an exponential drag, { options: [...] } for a choice, { help } to replace the generic help.

const FACTORS = ['1/4', '3/8', '1/2', '2/3', '1', '4/3', '3/2', '2', '3'];
const OFF_ON = ['OFF', 'ON'];

// Help shared by parameters with the same job in many algorithms.
const H = {
  pre: 'Time between the dry sound and the start of the reverb. A short gap keeps the front of each note clear of the wash.',
  decay: 'How long the reverb takes to die away.',
  size: 'How big the imaginary space is. Bigger spaces space their echoes further apart and build up more slowly.',
  damp: 'How fast the treble dies away inside the tail. Lower settings give a darker tail, like a room with soft furnishings.',
  diff: 'How quickly the first echoes blur into a smooth wash. Low settings leave separate, grainy echoes at the start.',
  mix: 'Balance between the dry sound and the effect. At 0 % you hear only the dry sound, at 100 % only the effect.',
  lc: 'Takes the bass out of the effect so it does not muddy the low end. The dry sound keeps its bass.',
  hc: 'Takes the treble out of the effect, so it sits darker and further back than the dry sound.',
  bass: 'How long the bass rings compared with the rest of the tail. Above 1 the low end rings on longer, below 1 it dies away sooner.',
  spread: 'How wide the effect spreads between the left and right outputs.',
  shape: 'How the reverb builds up. Low settings put the weight on the early echoes; high settings give a slower swell.',
  spin: 'Slow random movement inside the tail. It stops the tail ringing on fixed pitches and makes it sound lusher.',
  time: 'The main delay time: how long until the first echo.',
  factor: 'This echo’s time as a fraction or multiple of the main TIME, so the echoes fall in rhythm with each other.',
  fbk: 'How much of each echo is fed back in to make the next one. More feedback gives more repeats.',
  fhc: 'Takes treble out of each repeat, so the echoes get darker as they fade, like tape or an analogue delay.',
  flc: 'Takes bass out of each repeat, so the echoes get thinner as they fade.',
  speed: 'How fast the modulation moves.',
  depth: 'How far the modulation moves.',
  phase: 'Offsets the modulation between the left and right outputs. At 0° both sides move together; at 180° they move in opposite directions, which sounds widest.',
  bal: 'Balance between the two effects in this algorithm. Fully negative is only the first, fully positive only the second.',
  pan: 'Where this part sits between the left and right outputs.',
  attack: 'How fast the level follower reacts when the sound gets louder.',
  hold: 'How long the level follower holds before it starts to fall back.',
  release: 'How fast the level follower falls back once the sound gets quieter.',
  hisvf: 'Frequency of a treble shelf at the reverb’s input.',
  hisvg: 'How much the treble shelf at the reverb’s input cuts. Cutting treble going in gives a darker, softer reverb.',
};

const P = (ref, label, name, min, max, def, unit, extra = {}) => ({ ref, label, name, min, max, def, unit, ...extra });
const O = (ref, label, name, options, def, help) => ({ ref, label, name, options, def, help });

export const FX_ALGOS = [
  // ── Reverbs ────────────────────────────────────────────────────────────
  { id: 'tc-deepvrb', short: 'TC-DeepVRB', name: 'TC Deep Reverb', kind: 'reverb', after: 'TC Electronic Hall of Fame',
    params: [
      O('PST', 'PRESET', 'Preset', ['Ambience', 'Church', 'Gate', 'Hall', 'Lo Fi', 'Modulated', 'Plate', 'Room', 'Spring', 'Tile', 'Default'], 'Hall',
        'Which kind of space this reverb is. Each preset is a complete reverb of its own; DECAY, TONE and PREDELAY adjust it.'),
      P('DCY', 'DECAY', 'Decay', 0.1, 6, 2, 's', { log: true, help: `${H.decay} The range depends on the preset: a Room or Ambience decays sooner than a Church at the same setting.` }),
      P('TON', 'TONE', 'Tone', -50, 50, 0, '%', { help: 'Tilts the reverb’s colour: positive settings brighten it, negative settings darken it.' }),
      P('PDY', 'PREDELAY', 'PreDelay', 0, 200, 20, 'ms', { help: H.pre }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
    ] },
  { id: 'ambverb', short: 'AmbVerb', name: 'Ambient Reverb', kind: 'reverb', after: 'Lexicon 480L',
    params: [
      P('PD', 'PREDELAY', 'PreDelay', 0, 200, 10, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.2, 7.3, 1.2, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 2, 100, 40, '', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 6000, 'Hz', { log: true, help: H.damp }),
      P('DIF', 'DIFFUSION', 'Diffusion', 1, 30, 20, '', { help: H.diff }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 10000, 'Hz', { log: true, help: H.hc }),
      P('MOD', 'MOD', 'Mod', 0, 100, 30, '%', { help: 'How much the tail moves in pitch as it decays. A little makes it lusher; a lot sounds like a slow chorus.' }),
      P('TGN', 'TAIL GAIN', 'TailGain', 0, 100, 60, '%', { help: 'Level of the tail against the first reflections. Low settings give a short sense of space without a long wash.' }),
    ] },
  { id: 'roomrev', short: 'RoomRev', name: 'Room Reverb', kind: 'reverb', after: 'Lexicon 480L',
    params: [
      P('PRE', 'PREDELAY', 'PreDelay', 0, 200, 10, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.3, 28.9, 1, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 4, 76, 16, 'm', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 7000, 'Hz', { log: true, help: H.damp }),
      P('DIF', 'DIFFUSION', 'Diffusion', 0, 100, 60, '%', { help: H.diff }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 10000, 'Hz', { log: true, help: H.hc }),
      P('LFX', 'BASS MULT', 'BassMult', 0.2, 4, 1, 'x', { log: true, help: H.bass }),
      P('SPR', 'SPREAD', 'Spread', 0, 50, 25, '', { help: H.spread }),
      P('SHP', 'SHAPE', 'Shape', 0, 250, 100, '', { help: H.shape }),
      P('SPI', 'SPIN', 'Spin', 0, 100, 30, '%', { help: H.spin }),
    ] },
  { id: 'vintagerev', short: 'VintageRev', name: 'Vintage Room Reverb', kind: 'reverb', after: 'EMT 250',
    params: [
      P('PRE', 'PREDELAY', 'PreDelay', 0, 200, 20, 'ms', { help: H.pre }),
      P('SIZ', 'SIZE', 'Size', 1, 100, 50, '%', { help: `${H.size} It also sets how long DECAY can go.` }),
      P('DCY', 'DECAY', 'Decay', 0.1, 20.7, 1.8, 's', { log: true, help: H.decay }),
      P('LFX', 'LO MULT', 'Lo Mult', 0.1, 10, 1, 'x', { log: true, help: H.bass }),
      P('HFX', 'HI MULT', 'Hi Mult', 0.1, 10, 0.8, 'x', { log: true, help: 'How long the treble rings compared with the rest of the tail. Below 1 the tail darkens as it fades.' }),
      P('DEN', 'DENSITY', 'Density', 0, 100, 50, '%', { help: 'How closely packed the echoes are. Low settings sound grainy and fluttery, high settings smooth.' }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 50, 'Hz', { log: true, help: H.lc }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 12000, 'Hz', { log: true, help: H.hc }),
      P('ERL', 'ER LEVEL', 'ER Level', 0, 100, 40, '%', { help: 'Level of the early reflections: the first few distinct echoes off the walls, before the tail.' }),
      P('ERD', 'ER DELAY', 'ER Delay', 0, 200, 10, 'ms', { help: 'How long after the dry sound the early reflections arrive.' }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      O('FRZ', 'FREEZE', 'Freeze', OFF_ON, 'OFF', 'Holds the reverb tail as it is, for ever, and stops new sound going in. Play a chord, switch FREEZE on, and play over the frozen pad.'),
    ] },
  { id: 'hallrev', short: 'HallRev', name: 'Hall Reverb', kind: 'reverb', after: 'Lexicon 480L',
    params: [
      P('PD', 'PREDELAY', 'PreDelay', 0, 200, 25, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.2, 4.9, 2.2, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 2, 200, 60, '', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 6000, 'Hz', { log: true, help: H.damp }),
      P('DIF', 'DIFFUSION', 'Diffusion', 1, 30, 20, '', { help: H.diff }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 12000, 'Hz', { log: true, help: H.hc }),
      P('LFX', 'BASS MULT', 'BassMult', 0.5, 2, 1.1, 'x', { log: true, help: H.bass }),
      P('SPR', 'SPREAD', 'Spread', 0, 50, 30, '', { help: H.spread }),
      P('SHP', 'SHAPE', 'Shape', 0, 250, 120, '', { help: H.shape }),
      P('MOD', 'MOD SPEED', 'ModSpeed', 0, 100, 30, '', { help: 'Speed of the slow movement inside the tail. It keeps long tails from ringing on fixed pitches.' }),
    ] },
  { id: 'chamberrev', short: 'ChamberRev', name: 'Chamber Reverb', kind: 'reverb', after: 'Lexicon 480L',
    params: [
      P('PRE', 'PREDELAY', 'PreDelay', 0, 200, 15, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.3, 28.9, 1.4, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 4, 76, 24, 'm', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 8000, 'Hz', { log: true, help: H.damp }),
      P('DIF', 'DIFFUSION', 'Diffusion', 0, 100, 70, '%', { help: H.diff }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 60, 'Hz', { log: true, help: H.lc }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 12000, 'Hz', { log: true, help: H.hc }),
      P('LFX', 'BASS MULT', 'BassMult', 0.2, 4, 1, 'x', { log: true, help: H.bass }),
      P('SPR', 'SPREAD', 'Spread', 0, 50, 25, '', { help: H.spread }),
      P('SHP', 'SHAPE', 'Shape', 0, 250, 80, '', { help: H.shape }),
      P('SPI', 'SPIN', 'Spin', 0, 100, 20, '%', { help: H.spin }),
    ] },
  { id: 'platerev', short: 'PlateRev', name: 'Plate Reverb', kind: 'reverb', after: 'Lexicon PCM-70',
    params: [
      P('PD', 'PREDELAY', 'PreDelay', 0, 200, 5, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.5, 10, 2, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 2, 200, 40, '', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 9000, 'Hz', { log: true, help: H.damp }),
      P('DIF', 'DIFFUSION', 'Diffusion', 1, 30, 25, '', { help: H.diff }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 100, 'Hz', { log: true, help: H.lc }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 14000, 'Hz', { log: true, help: H.hc }),
      P('LFX', 'BASS MULT', 'BassMult', 0.5, 2, 1, 'x', { log: true, help: H.bass }),
      P('XOV', 'XOVER', 'Xover', 10, 500, 200, 'Hz', { log: true, help: 'The frequency below which BASS MULT applies.' }),
      P('MOD', 'MOD DEPTH', 'ModDepth', 1, 50, 15, '', { help: 'How far the tail moves in pitch. A little stops it ringing; a lot gives a chorused shimmer.' }),
      P('MDS', 'MOD SPEED', 'ModSpeed', 0, 100, 30, '', { help: 'How fast the tail moves in pitch.' }),
    ] },
  { id: 'richpltrev', short: 'RichPltRev', name: 'Rich Plate Reverb', kind: 'reverb', after: 'Lexicon 480L',
    params: [
      P('PD', 'PREDELAY', 'PreDelay', 0, 200, 5, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.3, 28.9, 2.5, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 4, 39, 20, 'm', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 10000, 'Hz', { log: true, help: H.damp }),
      P('DIF', 'DIFFUSION', 'Diffusion', 0, 100, 70, '%', { help: H.diff }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 100, 'Hz', { log: true, help: H.lc }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 15000, 'Hz', { log: true, help: H.hc }),
      P('LFX', 'BASS MULT', 'BassMult', 0.2, 4, 1, 'x', { log: true, help: H.bass }),
      P('SPR', 'SPREAD', 'Spread', 0, 50, 30, '', { help: H.spread }),
      P('ATK', 'ATTACK', 'Attack', 0, 100, 30, '', { help: 'How the reverb builds up: low settings hit at once, high settings swell in.' }),
      P('SPN', 'SPIN', 'Spin', 0, 100, 30, '%', { help: H.spin }),
    ] },
  { id: 'gatedrev', short: 'GatedRev', name: 'Gated Reverb', kind: 'reverb', after: 'Lexicon 300 / 480L',
    params: [
      P('PD', 'PREDELAY', 'PreDelay', 0, 200, 0, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 140, 1000, 300, 'ms', { help: 'How long the burst of reverb lasts before it is cut off. This is the "gate" time, not a fade.' }),
      P('ATK', 'ATTACK', 'Attack', 0, 30, 5, '', { help: 'How the burst starts: at 0 it hits at full level, higher settings ramp it up.' }),
      P('DEN', 'DENSITY', 'Density', 1, 50, 30, '', { help: 'How many echoes make up the burst. Low settings sound like a flutter, high settings a solid wall.' }),
      P('SPR', 'SPREAD', 'Spread', 0, 100, 50, '', { help: H.spread }),
      P('MIX', 'MIX', 'Mix', 0, 100, 40, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('HIF', 'HI SV FREQ', 'HiSvFreq', 200, 20000, 6000, 'Hz', { log: true, help: H.hisvf }),
      P('HIG', 'HI SV GAIN', 'HiSvGain', -30, 0, -6, 'dB', { help: H.hisvg }),
      P('DIF', 'DIFFUSION', 'Diffusion', 0, 100, 70, '%', { help: H.diff }),
    ] },
  { id: 'reverse', short: 'Reverse', name: 'Reverse Reverb', kind: 'reverb', after: 'Lexicon 300 / 480L',
    params: [
      P('PD', 'PREDELAY', 'PreDelay', 0, 200, 0, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 140, 1000, 500, 'ms', { help: 'How long the backwards swell lasts, from its quiet start to the moment it stops.' }),
      P('RIS', 'RISE', 'Rise', 0, 50, 25, '', { help: 'How the swell grows. Low settings rise evenly; high settings stay quiet and then surge at the end.' }),
      P('DIF', 'DIFFUSION', 'Diffusion', 1, 30, 20, '', { help: H.diff }),
      P('SPR', 'SPREAD', 'Spread', 0, 100, 50, '', { help: H.spread }),
      P('MIX', 'MIX', 'Mix', 0, 100, 40, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('HIF', 'HI SV FREQ', 'HiSvFreq', 200, 20000, 6000, 'Hz', { log: true, help: H.hisvf }),
      P('HIG', 'HI SV GAIN', 'HiSvGain', -30, 0, -3, 'dB', { help: H.hisvg }),
    ] },
  { id: 'chorusverb', short: 'ChorusVerb', name: 'Chorus & Reverb', kind: 'reverb', after: 'Lexicon PCM-70',
    params: [
      P('SPD', 'SPEED', 'Speed', 0, 4, 0.6, 'Hz', { help: `${H.speed} This is the chorus.` }),
      P('DEP', 'DEPTH', 'Depth', 0, 100, 40, '%', { help: `${H.depth} More depth gives a wider pitch wobble.` }),
      P('DLY', 'DELAY', 'Delay', 0.5, 50, 12, 'ms', { help: 'The chorus’s base delay. Short delays sound tight, long ones more like a doubled part.' }),
      P('PHS', 'PHASE', 'Phase', 0, 180, 90, 'deg', { help: H.phase }),
      P('WAV', 'WAVE', 'Wave', 0, 100, 0, '%', { help: 'Shape of the chorus movement, from a smooth sine at 0 % to a triangle at 100 %.' }),
      P('BAL', 'BALANCE', 'Balance', -100, 100, 0, '', { help: 'Balance between the chorus and the reverb in the effect. Negative favours the chorus, positive the reverb.' }),
      P('PRE', 'PREDELAY', 'PreDelay', 0, 200, 20, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.1, 5, 1.8, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 2, 200, 50, '', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 7000, 'Hz', { log: true, help: H.damp }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
    ] },
  { id: 'delayverb', short: 'DelayVerb', name: 'Delay & Reverb', kind: 'reverb', after: 'Lexicon PCM-70',
    params: [
      P('TIM', 'TIME', 'Time', 1, 1500, 375, 'ms', { help: 'Delay time of the left echo.' }),
      O('PAT', 'PATTERN', 'Pattern', ['1/4', '1/3', '3/8', '1/2', '2/3', '3/4', '1', '1/4X', '1/3X', '3/8X', '1/2X', '2/3X', '3/4X', '1X'], '3/4',
        'The right echo’s time as a fraction of TIME, so the two sides fall in a rhythm. The X patterns swap the echoes from side to side.'),
      P('FHC', 'FEED HC', 'FeedHC', 200, 20000, 6000, 'Hz', { log: true, help: H.fhc }),
      P('FBK', 'FEEDBACK', 'Feedback', 0, 100, 30, '%', { help: H.fbk }),
      P('XFD', 'X-FEED', 'X-Feed', 0, 100, 40, '%', { help: 'How much of the echoes goes into the reverb as well, so the repeats sit in the same space.' }),
      P('BAL', 'BALANCE', 'Balance', -100, 100, 0, '', { help: 'Balance between the delay and the reverb in the effect. Negative favours the delay, positive the reverb.' }),
      P('PRE', 'PREDELAY', 'PreDelay', 0, 200, 20, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.1, 5, 1.5, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 2, 200, 40, '', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 7000, 'Hz', { log: true, help: H.damp }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
    ] },
  { id: 'flangeverb', short: 'FlangeVerb', name: 'Flanger & Reverb', kind: 'reverb', after: 'Lexicon PCM-70',
    params: [
      P('SPD', 'SPEED', 'Speed', 0, 4, 0.3, 'Hz', { help: `${H.speed} This is the flanger’s sweep.` }),
      P('DEP', 'DEPTH', 'Depth', 0, 100, 50, '%', { help: `${H.depth} More depth sweeps the flanger over a wider range.` }),
      P('DLY', 'DELAY', 'Delay', 0.5, 20, 3, 'ms', { help: 'The flanger’s base delay. It sets where the sweep sits: short delays give a high, metallic whoosh.' }),
      P('PHS', 'PHASE', 'Phase', 0, 180, 90, 'deg', { help: H.phase }),
      P('FBK', 'FEED', 'Feed', -90, 90, 40, '%', { help: 'Feedback round the flanger. More feedback gives a sharper, more resonant jet sound; negative feedback a hollower one.' }),
      P('BAL', 'BALANCE', 'Balance', -100, 100, 0, '', { help: 'Balance between the flanger and the reverb in the effect. Negative favours the flanger, positive the reverb.' }),
      P('PRE', 'PREDELAY', 'PreDelay', 0, 200, 20, 'ms', { help: H.pre }),
      P('DCY', 'DECAY', 'Decay', 0.1, 5, 1.5, 's', { log: true, help: H.decay }),
      P('SIZ', 'SIZE', 'Size', 2, 200, 40, '', { help: H.size }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 7000, 'Hz', { log: true, help: H.damp }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 80, 'Hz', { log: true, help: H.lc }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
    ] },
  // ── EQ, dynamics and drive ────────────────────────────────────────────
  { id: 'midaseq', short: 'MidasEQ', name: 'Midas Equaliser', kind: 'processing', after: 'Midas Pro X',
    params: [
      P('LSG', 'LO SHELF G', 'LoShelfGain', -12, 12, 0, 'dB', { help: 'Boosts or cuts everything below the low shelf frequency.' }),
      P('LSF', 'LO SHELF F', 'LoShelfFreq', 30, 20000, 100, 'Hz', { log: true, help: 'Where the low shelf starts.' }),
      P('LMG', 'LO MID G', 'LoMidGain', -12, 12, 0, 'dB', { help: 'Boosts or cuts a band in the low mids.' }),
      P('LMF', 'LO MID F', 'LoMidFreq', 30, 20000, 400, 'Hz', { log: true, help: 'Centre of the low-mid band.' }),
      P('LMQ', 'LO MID Q', 'LoMidQ', 0.3, 5, 1, '', { log: true, help: 'Width of the low-mid band: low Q is broad and gentle, high Q narrow and pointed.' }),
      P('HMG', 'HI MID G', 'HiMidGain', -12, 12, 0, 'dB', { help: 'Boosts or cuts a band in the upper mids.' }),
      P('HMF', 'HI MID F', 'HiMidFreq', 30, 20000, 2500, 'Hz', { log: true, help: 'Centre of the high-mid band.' }),
      P('HMQ', 'HI MID Q', 'HiMidQ', 0.3, 5, 1, '', { log: true, help: 'Width of the high-mid band.' }),
      P('HSG', 'HI SHELF G', 'HiShelfGain', -12, 12, 0, 'dB', { help: 'Boosts or cuts everything above the high shelf frequency.' }),
      P('HSF', 'HI SHELF F', 'HiShelfFreq', 30, 20000, 8000, 'Hz', { log: true, help: 'Where the high shelf starts.' }),
      O('EQ', 'EQ', 'EQ', OFF_ON, 'ON', 'Switches the equaliser in or out, so you can compare. The manual’s description of this row repeats HI SHELF F; here it is the in/out switch.'),
    ] },
  { id: 'enhancer', short: 'Enhancer', name: 'Enhancing EQ', kind: 'processing', after: 'SPL Vitalizer',
    params: [
      P('OGN', 'OUT GAIN', 'OutGain', -12, 12, 0, 'dB', { help: 'Output level, to make up for the level the enhancement adds.' }),
      P('SPR', 'SPREAD', 'Spread', 0, 100, 0, '%', { help: 'Widens whatever stereo there already is. On its own the synth is mono, so this needs a stereo effect before it.' }),
      P('BGN', 'BASS GAIN', 'BassGain', 0, 100, 0, '%', { help: 'Adds weight and a little harmonic growl in the bass band.' }),
      P('BFR', 'BASS FREQ', 'BassFreq', 1, 50, 20, '', { help: 'Where the bass band sits: low settings reach down to the sub-bass, high ones lift the upper bass.' }),
      P('MGN', 'MID GAIN', 'MidGain', 0, 100, 0, '%', { help: 'Adds harmonics in the mid band, which makes a part more forward and easier to hear in a mix.' }),
      P('MIQ', 'MID Q', 'MidQ', 1, 50, 20, '', { help: 'Where the mid band sits: low settings favour the lower mids, high settings the presence range.' }),
      P('HIG', 'HI GAIN', 'HiGain', 0, 100, 0, '%', { help: 'Adds sparkle: generated harmonics above the high frequency, which brighten without the harshness of a plain treble boost.' }),
      P('HIF', 'HI FREQ', 'HiFreq', 1, 50, 20, '', { help: 'Where the added sparkle starts.' }),
      O('SOL', 'SOLO', 'Solo', OFF_ON, 'OFF', 'Plays only what the enhancer adds, without the original, so you can hear exactly what it is doing.'),
    ] },
  { id: 'faircomp', short: 'FairComp', name: 'Compressor', kind: 'processing', after: 'Fairchild 670',
    params: [
      O('MOD', 'MODE', 'Mode', ['L/R', 'LINK', 'M/S'], 'LINK', 'L/R compresses each side on its own. LINK compresses both sides together from the louder one, using the L/M controls. M/S compresses the middle and the sides of the stereo image separately.'),
      P('INL', 'IN GAIN L', 'InGain L/M', -20, 0, 0, 'dB', { help: 'Level into the left (or middle) channel. More level means more compression.' }),
      P('THL', 'THRESH L', 'ThreshL/M', 0, 10, 5, '', { help: 'Threshold for the left (or middle) channel. Higher settings compress more of the sound.' }),
      O('TML', 'TIME L', 'TimeL/M', ['1', '2', '3', '4', '5', '6'], '2', 'The Fairchild’s six time constants for the left (or middle) channel: 1 is fastest, 4 slowest, and 5 and 6 recover at a speed that follows the music.'),
      P('DCL', 'DC BIAS L', 'DCBiasL/M', 0, 100, 50, '%', { help: 'Ratio and knee for the left (or middle) channel: low settings compress gently, high settings clamp hard.' }),
      P('OGL', 'OUT GAIN L', 'OutGainL/M', -18, 6, 0, 'dB', { help: 'Output level of the left (or middle) channel, to make up for what the compression takes off.' }),
      P('BAL', 'BIAS BAL', 'Bias Bal', -100, 100, 0, '%', { help: 'Unbalances the valve stage, which adds harmonics and accents the attack of each note.' }),
      P('INR', 'IN GAIN R', 'InGain R/S', -20, 0, 0, 'dB', { help: 'Level into the right (or side) channel. Used in L/R and M/S modes.' }),
      P('THR', 'THRESH R', 'ThreshR/S', 0, 10, 5, '', { help: 'Threshold for the right (or side) channel. Used in L/R and M/S modes.' }),
      O('TMR', 'TIME R', 'TimeR/S', ['1', '2', '3', '4', '5', '6'], '2', 'Time constant for the right (or side) channel. Used in L/R and M/S modes.'),
      P('DCR', 'DC BIAS R', 'DCBiasR/S', 0, 100, 50, '%', { help: 'Ratio and knee for the right (or side) channel. Used in L/R and M/S modes.' }),
      P('OGR', 'OUT GAIN R', 'OutGainR/S', -18, 6, 0, 'dB', { help: 'Output level of the right (or side) channel. Used in L/R and M/S modes.' }),
    ] },
  { id: 'mulbnddist', short: 'MulBndDist', name: 'Multiband Distortion', kind: 'processing', after: 'Midas Pro X',
    params: [
      P('IPG', 'INPUT GAIN', 'InputGain', -24, 24, 0, 'dB', { help: 'Level into the distortion. More gain means more distortion in every band.' }),
      O('DST', 'DIST TYPE', 'Dist Types', ['VAL', 'SAT', 'TUB', 'PFV', 'PFS', 'PFT'], 'TUB', 'The character of the distortion: VAL (valve), SAT (saturation) or TUB (tube). The PF versions add a filter after the distortion that takes off the fizz.'),
      P('LBL', 'LOW LEVEL', 'Low Level', -12, 12, 0, 'dB', { help: 'Level of the low band, below XOVER 1.' }),
      P('LDR', 'LOW DRIVE', 'Low Drive', 0, 100, 30, '%', { help: 'How hard the low band is distorted.' }),
      P('XV1', 'XOVER 1', 'Xover Freq 1', 30, 9000, 250, 'Hz', { log: true, help: 'Where the low band ends and the mid band begins.' }),
      P('MBL', 'MID LEVEL', 'Mid Level', -12, 12, 0, 'dB', { help: 'Level of the mid band, between the two crossovers.' }),
      P('MDR', 'MID DRIVE', 'Mid Drive', 0, 100, 40, '%', { help: 'How hard the mid band is distorted.' }),
      P('XV2', 'XOVER 2', 'Xover Freq 2', 30, 9000, 2500, 'Hz', { log: true, help: 'Where the mid band ends and the high band begins.' }),
      P('HBL', 'HIGH LEVEL', 'High Level', -12, 12, 0, 'dB', { help: 'Level of the high band, above XOVER 2.' }),
      P('HDR', 'HIGH DRIVE', 'High Drive', 0, 100, 30, '%', { help: 'How hard the high band is distorted.' }),
      O('CAB', 'CABINET', 'Cabinet', ['OFF', 'VTw', 'VBs', 'A10', 'Mid', 'BFC', 'B60', 'V30', 'S78', 'Oax', 'A12', 'Rck'], 'OFF', 'A loudspeaker cabinet after the distortion, which takes off the harsh top as a guitar speaker does. Each type has its own tone; the manual’s table of them is not transcribed, so the tones here are estimates.'),
      P('OPG', 'OUTPUT GAIN', 'OutputGain', -12, 12, -6, 'dB', { help: 'Output level after the distortion.' }),
    ] },
  { id: 'rackamp', short: 'RackAmp', name: 'Rack Amplifier', kind: 'processing', after: 'Tech 21 SansAmp',
    params: [
      P('PRE', 'PREAMP', 'PreAmp', 0, 10, 4, '', { help: 'Gain into the amp: low settings stay nearly clean, high settings break up.' }),
      P('BUZ', 'BUZZ', 'Buzz', 0, 10, 5, '', { help: 'How much the bass breaks up. Up gives a woolly, farty low end; down keeps the bass clean.' }),
      P('PNC', 'PUNCH', 'Punch', 0, 10, 5, '', { help: 'How much the midrange distorts, which sets how hard the sound pushes forward.' }),
      P('CRN', 'CRUNCH', 'Crunch', 0, 10, 5, '', { help: 'How much the treble distorts: low is smooth, high is cutting and edgy.' }),
      P('DRV', 'DRIVE', 'Drive', 0, 10, 3, '', { help: 'Power-amp distortion, as when a valve amp is turned right up.' }),
      P('LVL', 'LEVEL', 'Level', 0, 10, 5, '', { help: 'Output level.' }),
      P('LOW', 'LOW', 'Low', 0, 10, 5, '', { help: 'Bass tone control after the distortion. 5 is flat.' }),
      P('HI', 'HIGH', 'High', 0, 10, 5, '', { help: 'Treble tone control after the distortion. 5 is flat.' }),
      O('CAB', 'CABINET', 'Cabinet', OFF_ON, 'ON', 'Adds a loudspeaker cabinet, which rounds off the harsh top of the distortion.'),
    ] },
  { id: 'edisonex1', short: 'EdisonEX1', name: 'Stereo Imaging', kind: 'processing', after: 'Edison EX-1',
    params: [
      O('ON', 'ON', 'On', OFF_ON, 'ON', 'Switches the imager in or out.'),
      O('IMD', 'IN MODE', 'InMode', ['ST', 'MS'], 'ST', 'ST takes a normal left/right input; MS treats the input as middle and side.'),
      O('OMD', 'OUT MODE', 'OutMode', ['ST', 'MS'], 'ST', 'ST gives a normal left/right output; MS sends the middle to the left output and the side to the right.'),
      P('STS', 'ST SPREAD', 'StSpread', -50, 50, 0, '', { help: 'Widens (positive) or narrows (negative) the stereo image. It can only work on stereo that is already there, from an effect before it.' }),
      P('LMF', 'LMF SPREAD', 'LMFSpread', -50, 50, 0, '', { help: 'Widens or narrows only the low and mid frequencies, so the bass can stay central while the top is wide.' }),
      P('BAL', 'BALANCE', 'Balance', -50, 50, 0, '', { help: 'Balance between the mono (middle) and the stereo (side) content.' }),
      P('CNT', 'CNTR DIST', 'CntrDist', -50, 50, 0, '', { help: 'Moves the mono content to the left or right.' }),
      P('GN', 'GAIN', 'Gain', -12, 12, 0, 'dB', { help: 'Output level.' }),
    ] },
  { id: 'auto-pan', short: 'Auto-Pan', name: 'Auto Panner / Tremolo', kind: 'processing', after: 'Behringer X32',
    params: [
      P('SPD', 'SPEED', 'Speed', 0, 5, 2, 'Hz', { help: 'How fast the level (or the position) moves.' }),
      P('PHS', 'PHASE', 'Phase', 0, 180, 180, 'deg', { help: 'At 180° the two sides move in opposite directions and the sound pans from side to side. At 0° both move together, which is a tremolo.' }),
      P('WAV', 'WAVE', 'Wave', -50, 50, 0, '', { help: 'Shape of the movement, from a smooth triangle (−50) to a hard on-off square (+50).' }),
      P('DEP', 'DEPTH', 'Depth', 0, 100, 60, '%', { help: 'How far the level moves. At 100 % it dips to silence.' }),
      P('ESP', 'ENV SPEED', 'EnvSpd', 0, 100, 0, '%', { help: 'Makes louder playing speed the movement up.' }),
      P('EDP', 'ENV DEPTH', 'EnvDepth', 0, 100, 0, '%', { help: 'Makes louder playing deepen the movement.' }),
      P('ATK', 'ATTACK', 'Attack', 10, 1000, 20, 'ms', { log: true, help: H.attack }),
      P('HLD', 'HOLD', 'Hold', 1, 2000, 50, 'ms', { log: true, help: H.hold }),
      P('REL', 'RELEASE', 'Release', 10, 1000, 200, 'ms', { log: true, help: H.release }),
    ] },
  { id: 'noisegate', short: 'NoiseGate', name: 'Noise Gate', kind: 'processing', after: 'Midas Pro X',
    params: [
      P('THR', 'THRESHOLD', 'Threshold', -50, 0, -40, 'dB', { help: 'The level the sound must reach for the gate to open. Below it the sound is turned down.' }),
      P('RNG', 'RANGE', 'Range', -100, 0, -60, 'dB', { help: 'How far the gate turns the sound down when it is closed. −100 dB is silence; −10 dB only a dip.' }),
      P('ATT', 'ATTACK', 'Attack', 0, 20, 1, 'ms', { help: 'How fast the gate opens once the sound is over the threshold.' }),
      P('REL', 'RELEASE', 'Release', 2, 2000, 150, 'ms', { log: true, help: 'How fast the gate closes once the sound falls below the threshold.' }),
      P('HLD', 'HOLD', 'Hold', 2, 2000, 20, 'ms', { log: true, help: 'How long the gate stays open after the sound falls below the threshold, before it starts to close.' }),
      P('PUN', 'PUNCH', 'Punch', -6, 6, 0, '', { help: 'Accents (positive) or softens (negative) the moment the gate opens.' }),
      O('MOD', 'MODE', 'Mode', ['GAT', 'TRN', 'DUC'], 'GAT', 'GAT is a normal gate. TRN (transient gate) opens only on the sharp start of a note. DUC (ducker) works the other way round: loud sound turns itself down.'),
      O('PWR', 'POWER', 'Power', OFF_ON, 'ON', 'Switches the gate in or out.'),
    ] },
  // ── Delays ─────────────────────────────────────────────────────────────
  { id: 'delay', short: 'Delay', name: 'Stereo Delay', kind: 'delay', after: 'Behringer X32',
    params: [
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('TIM', 'TIME', 'Time', 1, 1500, 375, 'ms', { help: H.time }),
      O('MOD', 'MODE', 'Mode', ['ST', 'X', 'M', 'P-P'], 'ST', 'ST: each side echoes itself. X: each side’s repeats feed the other side. M: both sides are fed the same mono signal. P-P (ping-pong): the echoes bounce from left to right; FEED R does nothing in this mode.'),
      O('FCL', 'FACTOR L', 'FactorL', FACTORS, '1', 'The left echo’s time as a fraction or multiple of TIME.'),
      O('FCR', 'FACTOR R', 'FactorR', FACTORS, '2/3', 'The right echo’s time as a fraction or multiple of TIME.'),
      P('OFS', 'OFFSET', 'Offset', -100, 100, 0, 'ms', { help: 'Adds a small time difference between the left and right echoes, which widens them.' }),
      P('LC', 'LO CUT', 'LC', 10, 500, 100, 'Hz', { log: true, help: 'Takes bass out of what goes into the delay, so the echoes do not muddy the low end.' }),
      P('HC', 'HI CUT', 'HC', 200, 20000, 8000, 'Hz', { log: true, help: 'Takes treble out of what goes into the delay, so the echoes sit behind the dry sound.' }),
      P('FLC', 'FEED LC', 'FeedLC', 10, 500, 50, 'Hz', { log: true, help: H.flc }),
      P('FBL', 'FEED L', 'FeedL', 0, 100, 35, '%', { help: `${H.fbk} This is the left side.` }),
      P('FBR', 'FEED R', 'FeedR', 0, 100, 35, '%', { help: `${H.fbk} This is the right side.` }),
      P('FHC', 'FEED HC', 'FeedHC', 200, 20000, 5000, 'Hz', { log: true, help: H.fhc }),
    ] },
  { id: '3tapdelay', short: '3TapDelay', name: '3-Tap Delay', kind: 'delay', after: 'Behringer X32',
    params: [
      P('TIM', 'TIME', 'Time', 1, 1500, 400, 'ms', { help: `${H.time} It is also the first of the three echoes.` }),
      P('GNT', 'GAIN T', 'GainT', 0, 100, 80, '%', { help: 'Level of the first echo.' }),
      P('PNT', 'PAN T', 'PanT', -100, 100, 0, '%', { help: `${H.pan} This is the first echo.` }),
      P('FBK', 'FEEDBACK', 'Feedback', 0, 100, 30, '%', { help: H.fbk }),
      O('FCA', 'FACTOR A', 'FactorA', FACTORS, '2/3', 'Time of the second echo, as a fraction or multiple of TIME.'),
      P('GNA', 'GAIN A', 'GainA', 0, 100, 60, '%', { help: 'Level of the second echo.' }),
      P('PNA', 'PAN A', 'PanA', -100, 100, -70, '%', { help: `${H.pan} This is the second echo.` }),
      O('FCB', 'FACTOR B', 'FactorB', FACTORS, '3/2', 'Time of the third echo, as a fraction or multiple of TIME.'),
      P('GNB', 'GAIN B', 'GainB', 0, 100, 50, '%', { help: 'Level of the third echo.' }),
      P('PNB', 'PAN B', 'PanB', -100, 100, 70, '%', { help: `${H.pan} This is the third echo.` }),
      O('XFD', 'X-FEED', 'X-Feed', OFF_ON, 'OFF', 'ON crosses the feedback over, so each round of repeats swaps sides.'),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
    ] },
  { id: '4tapdelay', short: '4TapDelay', name: '4-Tap Delay', kind: 'delay', after: 'Behringer X32',
    params: [
      P('TIM', 'TIME', 'Time', 1, 1500, 300, 'ms', { help: `${H.time} It is also the first of the four echoes.` }),
      P('GN', 'GAIN', 'Gain', 0, 100, 80, '%', { help: 'Level of the first echo.' }),
      P('FBK', 'FEEDBACK', 'Feedback', 0, 100, 30, '%', { help: H.fbk }),
      P('SPR', 'SPREAD', 'Spread', 0, 6, 3, '', { help: 'How far the four echoes are spread between left and right.' }),
      O('FCA', 'FACTOR A', 'FactorA', FACTORS, '1/2', 'Time of the second echo, as a fraction or multiple of TIME.'),
      P('GNA', 'GAIN A', 'GainA', 0, 100, 60, '%', { help: 'Level of the second echo.' }),
      O('FCB', 'FACTOR B', 'FactorB', FACTORS, '3/2', 'Time of the third echo, as a fraction or multiple of TIME.'),
      P('GNB', 'GAIN B', 'GainB', 0, 100, 50, '%', { help: 'Level of the third echo.' }),
      O('FCC', 'FACTOR C', 'FactorC', FACTORS, '2', 'Time of the fourth echo, as a fraction or multiple of TIME.'),
      P('GNC', 'GAIN C', 'GainC', 0, 100, 40, '%', { help: 'Level of the fourth echo.' }),
      O('XFD', 'X-FEED', 'X-Feed', OFF_ON, 'OFF', 'ON crosses the feedback over, so each round of repeats swaps sides.'),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
    ] },
  { id: 't-raydelay', short: 'T-RayDelay', name: 'Tel-Ray Delay', kind: 'delay', after: 'Tel-Ray oil-can delay',
    params: [
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
      P('DLY', 'DELAY', 'Delay', 0, 100, 40, '%', { help: 'The delay time, from a short slap to about half a second.' }),
      P('SUS', 'SUSTAIN', 'Sustain', 0, 100, 40, '%', { help: 'How long the echoes go on. Near 100 % they build up on themselves and keep growing, as on the real unit.' }),
      P('WOB', 'WOBBLE', 'Wobble', 0, 100, 40, '%', { help: 'The unsteady, warbling pitch of an old oil-can delay.' }),
      P('TON', 'TONE', 'Tone', 0, 100, 50, '%', { help: 'Brightness of the echoes: low is dark and murky, high is clearer.' }),
    ] },
  { id: 'decimdelay', short: 'DecimDelay', name: 'Decimator Delay', kind: 'delay', after: 'a lo-fi delay',
    params: [
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: `${H.mix} The manual’s table for this algorithm has lost its first row; MIX is assumed.` }),
      P('TIM', 'TIME', 'Time', 1, 1500, 300, 'ms', { help: H.time }),
      P('DSM', 'DOWNSAMPLE', 'Downsample', 0, 100, 30, '%', { help: 'Lowers the sample rate, which adds a gritty, metallic aliasing like an early sampler.' }),
      O('FCL', 'FACTOR L', 'FactorL', FACTORS, '1', 'The left echo’s time as a fraction or multiple of TIME.'),
      O('FCR', 'FACTOR R', 'FactorR', FACTORS, '2/3', 'The right echo’s time as a fraction or multiple of TIME.'),
      P('BRC', 'BIT-REDUCE', 'Bit-Reduce', 1, 24, 12, 'bit', { help: 'Fewer bits add a gritty, crackling noise that follows the sound. 24 is clean.' }),
      P('FC', 'CUTOFF', 'Cutoff', 30, 20000, 4000, 'Hz', { log: true, help: 'Cutoff of the filter on the echoes.' }),
      P('RES', 'RESONANCE', 'Resonance', 0, 100, 20, '%', { help: 'Resonance of the filter on the echoes.' }),
      O('FLT', 'TYPE', 'Type', ['LP', 'HP', 'BP', 'NOT'], 'LP', 'The filter on the echoes: low-pass, high-pass, band-pass or notch.'),
      P('FBL', 'FEED L', 'FeedL', 0, 100, 30, '%', { help: `${H.fbk} This is the left side.` }),
      P('FBR', 'FEED R', 'FeedR', 0, 100, 30, '%', { help: `${H.fbk} This is the right side.` }),
      O('DMT', 'DECIMATE', 'Decimate', ['PRE', 'POST'], 'POST', 'PRE crushes the whole sound, dry part included; POST crushes only the echoes.'),
    ] },
  { id: 'moddlyrev', short: 'ModDlyRev', name: 'Modulation, Delay & Reverb', kind: 'delay', after: 'Lexicon PCM-70',
    params: [
      P('TIM', 'TIME', 'Time', 1, 1500, 400, 'ms', { help: H.time }),
      O('FAC', 'FACTOR', 'Factor', ['1', '1/2', '2/3', '3/2'], '1', 'The right echo’s time as a fraction or multiple of TIME.'),
      P('FBK', 'FEEDBACK', 'Feedback', 0, 100, 30, '%', { help: H.fbk }),
      P('FHC', 'FEED HC', 'FeedHC', 200, 20000, 6000, 'Hz', { log: true, help: H.fhc }),
      P('DEP', 'DEPTH', 'Depth', 0, 100, 30, '%', { help: 'How far the echoes wobble in pitch, like a chorus on the repeats.' }),
      P('SPD', 'SPEED', 'Speed', 0, 10, 0.8, 'Hz', { help: 'How fast the echoes wobble.' }),
      O('MOD', 'MODE', 'Mode', ['SER', 'PAR'], 'SER', 'SER feeds the echoes into the reverb; PAR runs the delay and the reverb side by side.'),
      O('RTY', 'RTYPE', 'Rtype', ['AMB', 'CLUB', 'HALL'], 'HALL', 'The reverb’s space: AMB (ambience, short), CLUB (a small room) or HALL.'),
      P('DCY', 'DECAY', 'Decay', 1, 10, 4, '', { help: H.decay }),
      P('DMP', 'DAMPING', 'Damping', 1000, 20000, 7000, 'Hz', { log: true, help: H.damp }),
      P('BAL', 'BALANCE', 'Balance', -100, 100, 0, '', { help: 'Balance between the delay and the reverb. Negative favours the delay, positive the reverb.' }),
      P('MIX', 'MIX', 'Mix', 0, 100, 30, '%', { help: H.mix }),
    ] },
  // ── Modulation and pitch ─────────────────────────────────────────────
  { id: 'chorus', short: 'Chorus', name: 'Stereo Chorus', kind: 'creative', after: 'Behringer X32',
    params: [
      P('SPD', 'SPEED', 'Speed', 0, 5, 0.5, 'Hz', { help: `${H.speed} Slow is a gentle shimmer, fast a warble.` }),
      P('WDL', 'WIDTH L', 'WidthL', 0, 100, 40, '%', { help: 'How far the left side’s delay moves, and so how much its pitch wobbles.' }),
      P('WDR', 'WIDTH R', 'WidthR', 0, 100, 40, '%', { help: 'How far the right side’s delay moves.' }),
      P('DLL', 'DELAY L', 'DelayL', 0.5, 50, 12, 'ms', { help: 'Base delay of the left side. Different delays on the two sides give a wider chorus.' }),
      P('DLR', 'DELAY R', 'DelayR', 0.5, 50, 18, 'ms', { help: 'Base delay of the right side.' }),
      P('MIX', 'MIX', 'Mix', 0, 100, 40, '%', { help: H.mix }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 50, 'Hz', { log: true, help: 'Takes bass out of the chorused sound, so the low end stays solid and in tune.' }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 16000, 'Hz', { log: true, help: 'Takes treble out of the chorused sound, for a darker, more analogue chorus.' }),
      P('PHS', 'PHASE', 'Phase', 0, 180, 90, 'deg', { help: H.phase }),
      P('WAV', 'WAVE', 'Wave', 0, 100, 50, '%', { help: 'Shape of the movement, from the cleaner triangle of a digital chorus (0 %) to the smoother sine of an analogue one (100 %).' }),
      P('SPR', 'SPREAD', 'Spread', 0, 100, 50, '%', { help: 'How much of each side is mixed into the other. Less spread is wider.' }),
    ] },
  { id: 'chorus-d', short: 'Chorus-D', name: 'Dimensional Chorus', kind: 'creative', after: 'Roland Dimension D',
    params: [
      O('ON', 'ON', 'On', OFF_ON, 'ON', 'Switches the chorus in or out.'),
      O('MOD', 'MODE', 'Mode', ['MONO', 'STEREO'], 'STEREO', 'STEREO spreads the chorus across the two outputs; MONO gives the same on both.'),
      P('MIX', 'MIX', 'Mix', 0, 100, 50, '%', { help: H.mix }),
      O('SW1', 'SW1', 'Sw1', OFF_ON, 'OFF', 'Button 1: the subtlest setting. The buttons can be combined, as on the original.'),
      O('SW2', 'SW2', 'Sw2', OFF_ON, 'ON', 'Button 2: a little more.'),
      O('SW3', 'SW3', 'Sw3', OFF_ON, 'OFF', 'Button 3: stronger.'),
      O('SW4', 'SW4', 'Sw4', OFF_ON, 'OFF', 'Button 4: the strongest and fastest.'),
    ] },
  { id: 'flanger', short: 'Flanger', name: 'Stereo Flanger', kind: 'creative', after: 'Behringer X32',
    params: [
      P('SPD', 'SPEED', 'Speed', 0.05, 5, 0.3, 'Hz', { log: true, help: `${H.speed} Slow gives a jet-plane sweep, fast a metallic warble.` }),
      P('WDL', 'WIDTH L', 'WidthL', 0, 100, 60, '%', { help: 'How far the left side sweeps.' }),
      P('WDR', 'WIDTH R', 'WidthR', 0, 100, 60, '%', { help: 'How far the right side sweeps.' }),
      P('DLL', 'DELAY L', 'DelayL', 0.5, 20, 2, 'ms', { help: 'Base delay of the left side: where its sweep sits.' }),
      P('DLR', 'DELAY R', 'DelayR', 0.5, 20, 3, 'ms', { help: 'Base delay of the right side.' }),
      P('MIX', 'MIX', 'Mix', 0, 100, 50, '%', { help: `${H.mix} The flanging is strongest at 50 %.` }),
      P('LC', 'LO CUT', 'LoCut', 10, 500, 20, 'Hz', { log: true, help: 'Takes bass out of the flanged sound.' }),
      P('HC', 'HI CUT', 'Hi Cut', 200, 20000, 15000, 'Hz', { log: true, help: 'Takes treble out of the flanged sound.' }),
      P('PHS', 'PHASE', 'Phase', 0, 180, 90, 'deg', { help: H.phase }),
      P('FLC', 'FEED LC', 'FeedLC', 10, 500, 50, 'Hz', { log: true, help: 'Takes bass out of the feedback, so the resonance stays in the upper range.' }),
      P('FHC', 'FEED HC', 'FeedHC', 200, 20000, 10000, 'Hz', { log: true, help: 'Takes treble out of the feedback, for a softer resonance.' }),
      P('FD', 'FEED', 'Feed', -90, 90, 50, '%', { help: 'Feedback: more gives a sharper, more resonant sweep; negative feedback a hollower one.' }),
    ] },
  { id: 'phaser', short: 'Phaser', name: 'Stereo Phaser', kind: 'creative', after: 'Behringer X32',
    params: [
      P('SPD', 'SPEED', 'Speed', 0, 5, 0.4, 'Hz', { help: `${H.speed} This is the sweep.` }),
      P('DEP', 'DEPTH', 'Depth', 0, 100, 60, '%', { help: 'How far the notches sweep up and down.' }),
      P('RES', 'RESO', 'Reso', 0, 100, 40, '%', { help: 'Feedback round the phaser, which sharpens the notches into a whistling, vocal sweep.' }),
      P('BAS', 'BASE FREQ', 'Base Freq', 20, 15000, 300, 'Hz', { log: true, help: 'The bottom of the sweep.' }),
      P('STG', 'STAGES', 'Stages', 2, 12, 6, '', { step: 1, help: 'How many filter stages. More stages give more notches and a stronger, busier phasing.' }),
      P('MIX', 'MIX', 'Mix', 0, 100, 50, '%', { help: `${H.mix} Phasing is strongest at 50 %.` }),
      P('WAV', 'WAVE', 'Wave', -50, 50, 0, '', { help: 'Symmetry of the sweep: at 0 it rises and falls at the same speed, otherwise one way is quicker.' }),
      P('PHS', 'PHASE', 'Phase', 0, 180, 0, 'deg', { help: H.phase }),
      P('ENV', 'ENV MOD', 'EnvMod', -100, 100, 0, '%', { help: 'Makes the sweep follow how loud you play, up (positive) or down (negative).' }),
      P('ATK', 'ATTACK', 'Attack', 10, 1000, 20, 'ms', { log: true, help: H.attack }),
      P('HLD', 'HOLD', 'Hold', 1, 2000, 50, 'ms', { log: true, help: H.hold }),
      P('REL', 'RELEASE', 'Release', 10, 1000, 200, 'ms', { log: true, help: H.release }),
    ] },
  { id: 'moodfilter', short: 'MoodFilter', name: 'Mood Filter', kind: 'creative', after: 'a Moog-type filter',
    params: [
      P('SPD', 'SPEED', 'Speed', 0, 20, 1, 'Hz', { help: 'How fast the filter’s own LFO sweeps it.' }),
      P('DEP', 'DEPTH', 'Depth', 0, 100, 40, '%', { help: 'How far the LFO sweeps the filter.' }),
      P('RES', 'RESONANCE', 'Resonance', 0, 100, 50, '%', { help: 'Resonance: a peak at the cutoff that makes sweeps sound vocal.' }),
      P('FRQ', 'BASE FREQ', 'Base Freq', 20, 15000, 500, 'Hz', { log: true, help: 'The cutoff the sweeps start from.' }),
      O('TYP', 'TYPE', 'Type', ['LP', 'HP', 'BP', 'NOT'], 'LP', 'Filter type: low-pass, high-pass, band-pass or notch.'),
      P('MIX', 'MIX', 'Mix', 0, 100, 100, '%', { help: H.mix }),
      O('WAV', 'WAVE', 'Wave', ['TRI', 'SIN', 'SAW+', 'SAW-', 'RMP', 'SQU', 'RND'], 'TRI', 'Shape of the LFO: triangle, sine, rising saw, falling saw, ramp, square or random steps.'),
      P('ENV', 'ENV MOD', 'EnvMod', -100, 100, 0, '%', { help: 'Makes the cutoff follow how loud the sound is, up (positive) or down (negative): an auto-wah.' }),
      P('ATK', 'ATTACK', 'Attack', 10, 250, 20, 'ms', { log: true, help: 'How fast the filter follows the sound getting louder.' }),
      P('REL', 'RELEASE', 'Release', 10, 500, 150, 'ms', { log: true, help: 'How fast the filter falls back as the sound gets quieter.' }),
      P('DRV', 'DRIVE', 'Drive', 0, 100, 20, '%', { help: 'Level into the filter. Pushed hard it overdrives.' }),
      P('4P', '4-POLE', '4-Pole', 0, 100, 100, '%', { help: 'Slope of the filter, from 2-pole (gentler) at 0 % to 4-pole (steeper) at 100 %.' }),
    ] },
  { id: 'dual-pitch', short: 'DualPitch', name: 'Dual Pitch Shifter', kind: 'creative', after: 'Eventide',
    params: [
      P('SM1', 'SEMI 1', 'Semi1', -12, 12, 0, 'st', { step: 1, help: 'Pitch of the first shifted voice, in semitones.' }),
      P('CN1', 'CENT 1', 'Cent1', -50, 50, -8, 'ct', { help: 'Fine pitch of the first voice. A few cents either side of the dry sound thickens it like a double-tracked part.' }),
      P('DL1', 'DELAY 1', 'Delay1', 1, 500, 20, 'ms', { log: true, help: 'How late the first voice comes in after the dry sound.' }),
      P('GN1', 'GAIN 1', 'Gain1', 0, 100, 70, '%', { help: 'Level of the first voice.' }),
      P('PN1', 'PAN 1', 'Pan1', -100, 100, -60, '%', { help: `${H.pan} This is the first voice.` }),
      P('MIX', 'MIX', 'Mix', 0, 100, 40, '%', { help: H.mix }),
      P('SM2', 'SEMI 2', 'Semi2', -12, 12, 0, 'st', { step: 1, help: 'Pitch of the second shifted voice, in semitones.' }),
      P('CN2', 'CENT 2', 'Cent2', -50, 50, 8, 'ct', { help: 'Fine pitch of the second voice.' }),
      P('DL2', 'DELAY 2', 'Delay2', 1, 500, 30, 'ms', { log: true, help: 'How late the second voice comes in.' }),
      P('GN2', 'GAIN 2', 'Gain2', 0, 100, 70, '%', { help: 'Level of the second voice.' }),
      P('PN2', 'PAN 2', 'Pan2', -100, 100, 60, '%', { help: `${H.pan} This is the second voice.` }),
      P('HIC', 'HI CUT', 'HiCut', 200, 20000, 12000, 'Hz', { log: true, help: 'Takes treble off the shifted voices, which hides the graininess of large shifts.' }),
    ] },
  { id: 'vintage-pitch', short: 'VintgPitch', name: 'Vintage Pitch Shifter', kind: 'creative', after: 'Eventide',
    params: [
      P('SM1', 'SEMI 1', 'Semi1', -12, 12, 0, 'st', { step: 1, help: 'Pitch of the first shifted voice, in semitones.' }),
      P('CN1', 'CENT 1', 'Cent1', -50, 50, -6, 'ct', { help: 'Fine pitch of the first voice.' }),
      P('DL1', 'DELAY 1', 'Delay1', 1, 500, 25, 'ms', { log: true, help: 'How late the first voice comes in after the dry sound.' }),
      P('FB1', 'FEEDBACK 1', 'Feedback1', 0, 100, 20, '%', { help: 'Feeds the first voice back into itself, so each repeat is shifted again: rising or falling spirals of echoes.' }),
      P('PN1', 'PAN 1', 'Pan1', -100, 100, -60, '%', { help: `${H.pan} This is the first voice.` }),
      P('MIX', 'MIX', 'Mix', 0, 100, 40, '%', { help: H.mix }),
      P('SM2', 'SEMI 2', 'Semi2', -12, 12, 0, 'st', { step: 1, help: 'Pitch of the second shifted voice, in semitones.' }),
      P('CN2', 'CENT 2', 'Cent2', -50, 50, 6, 'ct', { help: 'Fine pitch of the second voice.' }),
      P('DL2', 'DELAY 2', 'Delay2', 1, 500, 35, 'ms', { log: true, help: 'How late the second voice comes in.' }),
      P('FB2', 'FEEDBACK 2', 'Feedback2', 0, 100, 20, '%', { help: 'Feeds the second voice back into itself.' }),
      P('PN2', 'PAN 2', 'Pan2', -100, 100, 60, '%', { help: `${H.pan} This is the second voice.` }),
      P('HIC', 'HI CUT', 'HiCut', 2000, 20000, 10000, 'Hz', { log: true, help: 'Takes treble off the shifted voices.' }),
    ] },
  { id: 'rotaryspkr', short: 'RotarySpkr', name: 'Rotary Speaker', kind: 'creative', after: 'Leslie',
    params: [
      P('LOS', 'LO SPEED', 'LoSpeed', 0.1, 4, 0.7, 'Hz', { help: 'How fast the speaker spins on the slow setting (chorale).' }),
      P('HIS', 'HI SPEED', 'HiSpeed', 2, 9.9, 6.5, 'Hz', { help: 'How fast it spins on the fast setting (tremolo).' }),
      P('ACC', 'ACCEL', 'Accel', 0, 100, 50, '%', { help: 'How quickly it speeds up and slows down when SPEED is switched. Slow acceleration gives the classic organ swell.' }),
      P('DIS', 'DISTANCE', 'Distance', 0, 100, 40, '%', { help: 'How far the virtual microphones are from the speaker. Further away sounds smoother and less throbbing.' }),
      P('BAL', 'BALANCE', 'Balance', -100, 100, 0, '', { help: 'Balance between the bass drum rotor (negative) and the treble horn (positive).' }),
      P('MIX', 'MIX', 'Mix', 0, 100, 100, '%', { help: H.mix }),
      O('MOT', 'MOTOR', 'Motor', ['RUN', 'STOP'], 'RUN', 'STOP switches the motor off: the rotors coast to a halt and the sound stops moving.'),
      O('SPD', 'SPEED', 'Speed', ['SLOW', 'FAST'], 'SLOW', 'Switches between the slow and the fast rotor speed. Switch it while you play to hear the rotors speed up.'),
    ] },
];

export const FX_ROUTINGS = [
  { v: 1, label: 'M-1 1>2>3>4', name: 'SERIAL 1-2-3-4', help: 'All four slots in a row: each effect processes the output of the one before it.' },
  { v: 2, label: 'M-2 (1+2)>3>4', name: 'PARALLEL 1/2 SERIAL 3-4', help: 'Slots 1 and 2 side by side, then 3 and 4 in a row after them.' },
  { v: 3, label: 'M-3 (1+2)>(3+4)', name: 'PARALLEL 1/2 PARALLEL 3/4', help: 'Two pairs: 1 and 2 side by side, feeding 3 and 4 side by side.' },
  { v: 4, label: 'M-4 1+2+3+4', name: 'PARALLEL 1/2/3/4', help: 'All four slots side by side, each fed the dry sound.' },
  { v: 5, label: 'M-5 (1+2+3)>4', name: 'PARALLEL 1/2/3 SERIAL 4', help: 'Slots 1, 2 and 3 side by side, all feeding slot 4.' },
  { v: 6, label: 'M-6 1>2>(3+4)', name: 'SERIAL 1-2 PARALLEL 3/4', help: 'Slot 1 then slot 2, feeding 3 and 4 side by side.' },
  { v: 7, label: 'M-7 1>(2+3+4)', name: 'SERIAL 1 PARALLEL 2/3/4', help: 'Slot 1 first, then 2, 3 and 4 side by side.' },
  { v: 8, label: 'M-8 (1>2>3)+4', name: 'PARALLEL (SERIAL 1-2-3)/4', help: 'Slots 1, 2 and 3 in a row, with slot 4 on its own beside them.' },
  { v: 9, label: 'M-9 3>4 FB:1>2', name: 'SERIAL 3-4 FEEDBACK4(1-2)', help: 'Slots 3 and 4 in a row; the output of 4 is fed back to the input of 3 through slots 1 and 2. A pitch shifter in 1 and a delay in 4 give echoes that climb in pitch.' },
  { v: 10, label: 'M-10 4 FB:1>2>3', name: 'SERIAL 4 FEEDBACK4(1-2-3)', help: 'Slot 4 alone, with its output fed back to its input through slots 1, 2 and 3.' },
];

export const FX_MODES = [
  { v: 'insert', label: 'INSERT', help: 'The whole sound goes through the effects, and each effect’s MIX sets how much of it is processed.' },
  { v: 'send', label: 'SEND', help: 'The dry sound goes straight out and the effects are added alongside it, fully wet; each effect’s MIX is ignored.' },
  { v: 'bypass', label: 'BYPASS', help: 'The effects are switched out and only the dry sound is heard.' },
];
