// Real instruments: the synths named on records, and the originals the app's panels are modelled on.
// `app` lists the app synths that model this instrument; a record made on it then shows in their "Heard on" list
// without being listed there by hand. `people` are ids in makers.js – the designers and the founders behind it. Shape: see CONTRACT.md → Databank.
export default [
  { id: 'moog-modular', name: 'Moog modular', maker: 'R. A. Moog Co.', year: '1964', kind: 'modular', people: ['robert-moog', 'herb-deutsch'], app: ['system-15', 'system-35', 'system-55'],
    text: 'Cabinets of separate modules joined by patch cords: voltage-controlled oscillators, the ladder filter, envelope generators and a step sequencer. The instrument behind Switched-On Bach and most early synthesizer records.' },
  { id: 'moog-minimoog', name: 'Minimoog Model D', maker: 'Moog Music', year: '1970', kind: 'mono', people: ['robert-moog', 'bill-hemsath', 'jim-scott'], app: ['model-d'],
    text: 'Three oscillators, the ladder filter and two envelopes wired together in a portable case with a keyboard, pitch and mod wheels. It made the synthesizer a stage instrument and set the layout most monosynths still follow.' },
  { id: 'moog-grandmother', name: 'Moog Grandmother', maker: 'Moog Music', year: '2018', kind: 'semi-modular', app: ['model-15', 'grandmother'],
    text: 'A semi-modular with a 32-note keyboard and a colour-coded panel: two oscillators, a ladder filter with a separate high-pass, one envelope, an LFO, a spring reverb and an arpeggiator and sequencer, playable with no cables. The Behringer Model 15 copies its layout.' },
  { id: 'moog-minimoog-voyager', name: 'Minimoog Voyager', maker: 'Moog Music', year: '2002', kind: 'mono', people: ['robert-moog'],
    text: 'Robert Moog’s update of the Minimoog, with patch memory, a touch surface and MIDI, and the last instrument he designed.' },
  { id: 'moog-source', name: 'Moog Source', maker: 'Moog Music', year: '1981', kind: 'mono',
    text: 'A two-oscillator monosynth with patch memory and a membrane panel worked by one data knob, in place of a knob for every setting.' },
  { id: 'moog-memorymoog', name: 'Memorymoog', maker: 'Moog Music', year: '1982', kind: 'poly',
    text: 'Moog’s six-voice polysynth, three oscillators per voice, with patch memory. Large, powerful and known for being unreliable.' },
  { id: 'arp-2600', name: 'ARP 2600', maker: 'ARP Instruments', year: '1971', kind: 'semi-modular', people: ['alan-r-pearlman', 'dennis-colin', 'david-friend'], app: ['b2600'],
    text: 'A semi-modular built for teaching: every module is wired to the next behind the panel, and patch cords override the wiring. Its printed signal flow made it the classroom synthesizer of the 1970s.' },
  { id: 'arp-odyssey', name: 'ARP Odyssey', maker: 'ARP Instruments', year: '1972', kind: 'mono', people: ['alan-r-pearlman', 'david-friend'],
    text: 'A smaller, keyboard-only cousin of the 2600 with two oscillators, sync, ring modulation and sliders for every setting. ARP’s answer to the Minimoog.' },
  { id: 'buchla-music-easel', name: 'Buchla Music Easel', maker: 'Buchla & Associates', year: '1973', kind: 'semi-modular', people: ['don-buchla'], app: ['buchla-easel'],
    text: 'A complex oscillator, wavefolding and two lowpass gates, played from a touch-plate keyboard, in one portable case. The West Coast approach in a single instrument.' },
  { id: 'ems-vcs3', name: 'EMS VCS3', maker: 'Electronic Music Studios', year: '1969', kind: 'semi-modular', people: ['david-cockerell', 'peter-zinovieff', 'tristram-cary'], app: ['ems-vcs3'],
    text: 'A small studio in a wooden cabinet, patched with pins in a matrix rather than cords, with a joystick and no keyboard. Britain’s first widely sold synthesizer.' },
  { id: 'ems-synthi-aks', name: 'EMS Synthi AKS', maker: 'Electronic Music Studios', year: '1972', kind: 'semi-modular', people: ['david-cockerell', 'peter-zinovieff'],
    text: 'The VCS3’s circuits in a briefcase, with a flat touch keyboard and a digital sequencer in the lid.' },
  { id: 'edp-wasp', name: 'EDP Wasp', maker: 'Electronic Dream Plant', year: '1978', kind: 'mono', people: ['chris-huggett', 'adrian-wagner'], app: ['wasp-deluxe'],
    text: 'A cheap, loud monosynth with a flat touch keyboard, digital oscillators and a CMOS filter, in a yellow and black plastic case with its own speaker.' },
  { id: 'korg-ms-20', name: 'Korg MS-20', maker: 'Korg', year: '1978', kind: 'semi-modular', people: ['fumio-mieda'], app: ['k2'],
    text: 'A monosynth with a patch panel and a high-pass and low-pass filter in series, both able to scream, plus an external signal processor for running a guitar or voice through it.' },
  { id: 'oberheim-sem', name: 'Oberheim SEM', maker: 'Oberheim Electronics', year: '1974', kind: 'module', people: ['tom-oberheim'],
    text: 'The Synthesizer Expander Module: two oscillators and a 12 dB state-variable filter that blends from low- through notch to high-pass, sold to add voices to other synths.' },
  { id: 'oberheim-two-voice', name: 'Oberheim Two Voice', maker: 'Oberheim Electronics', year: '1975', kind: 'poly', people: ['tom-oberheim'], app: ['2-xm'],
    text: 'Two SEMs in one case with a keyboard and a small sequencer, each playable on its own: one of the first instruments to play two notes at once.' },
  { id: 'oberheim-ob-xa', name: 'Oberheim OB-Xa', maker: 'Oberheim Electronics', year: '1980', kind: 'poly', people: ['tom-oberheim'], app: ['ub-xa-d'],
    text: 'An eight-voice polysynth with patch memory and a split or layered keyboard, known for its thick brass and the riff on Van Halen’s “Jump”.' },
  { id: 'octave-cat', name: 'Octave CAT', maker: 'Octave Electronics', year: '1976', kind: 'mono', people: ['carmine-bonanno'], app: ['cat'],
    text: 'A two-oscillator monosynth from New York, sold as a cheaper rival to the ARP Odyssey and close to it in design.' },
  { id: 'rsf-kobol', name: 'RSF Kobol', maker: 'RSF', year: '1978', kind: 'mono', people: ['ruben-fernandez', 'serge-fernandez'],
    text: 'A French monosynth with patch memory, rare at the time on a monophonic instrument.' },
  { id: 'rsf-kobol-expander', name: 'RSF Kobol Expander', maker: 'RSF', year: '1979', kind: 'module', people: ['ruben-fernandez', 'serge-fernandez'], app: ['kobol'],
    text: 'The Kobol’s voice in a keyboardless desktop case with patch points, sold as an expander for other synths.' },
  { id: 'roland-sh-2', name: 'Roland SH-2', maker: 'Roland', year: '1979', kind: 'mono', people: ['ikutaro-kakehashi'],
    text: 'A two-oscillator Roland monosynth with a sub-oscillator, often used for bass.' },
  { id: 'yamaha-cs-80', name: 'Yamaha CS-80', maker: 'Yamaha', year: '1977', kind: 'poly',
    text: 'An eight-voice polysynth of two layered voices per note, with a ribbon controller and a keyboard that responds to velocity and to pressure on each key. Heard on Vangelis’s Blade Runner score.' },
  { id: 'roland-jupiter-4', name: 'Roland Jupiter-4', maker: 'Roland', year: '1978', kind: 'poly', people: ['ikutaro-kakehashi'], app: ['jupiter-4'],
    text: 'Roland’s first self-contained polysynth: four voices, a microprocessor that shares keys among them, an arpeggiator and patch memory.' },
  { id: 'roland-jupiter-8', name: 'Roland Jupiter-8', maker: 'Roland', year: '1981', kind: 'poly', people: ['ikutaro-kakehashi'], app: ['jupiter-8'],
    text: 'Roland’s flagship: eight voices of two oscillators each, cross modulation and sync, a 12/24 dB filter, split and dual keyboard modes and 64 memories.' },
  { id: 'roland-sh-101', name: 'Roland SH-101', maker: 'Roland', year: '1982', kind: 'mono', people: ['ikutaro-kakehashi'],
    text: 'A light one-oscillator monosynth with a sub-oscillator, a sequencer and an optional strap-on handgrip. Cheap on the second-hand market by the late 80s, it became a dance-music staple.' },
  { id: 'roland-tb-303', name: 'Roland TB-303', maker: 'Roland', year: '1981', kind: 'sequencer', people: ['tadao-kikumoto', 'ikutaro-kakehashi'], app: ['tb-303', 'td-3'],
    text: 'A bass-line machine meant to accompany guitarists: one oscillator, a resonant filter, accent and slide, programmed step by step. It failed in the shops, then became the sound of acid house.' },
  { id: 'roland-juno-60', name: 'Roland Juno-60', maker: 'Roland', year: '1982', kind: 'poly', people: ['ikutaro-kakehashi'],
    text: 'Six voices of one digitally controlled oscillator each, with a sub-oscillator, a resonant filter, an arpeggiator and the stereo chorus that gives it its sound.' },
  { id: 'roland-jupiter-6', name: 'Roland Jupiter-6', maker: 'Roland', year: '1983', kind: 'poly', people: ['ikutaro-kakehashi'], app: ['jupiter-6'],
    text: 'A cheaper six-voice follow-up to the Jupiter-8, with a multimode filter and one of the first MIDI interfaces.' },
  { id: 'roland-juno-106', name: 'Roland Juno-106', maker: 'Roland', year: '1984', kind: 'poly', people: ['ikutaro-kakehashi'],
    text: 'The Juno-60’s voice with patch memory, MIDI and a pitch/mod lever, and the same chorus.' },
  { id: 'roland-alpha-juno', name: 'Roland Alpha Juno', maker: 'Roland', year: '1985', kind: 'poly', people: ['ikutaro-kakehashi'],
    text: 'A six-voice Juno programmed from one alpha dial and a menu. Its “What the” preset became the “hoover” sound of early-90s rave.' },
  { id: 'sequential-prophet-5', name: 'Sequential Circuits Prophet-5', maker: 'Sequential Circuits', year: '1978', kind: 'poly', people: ['dave-smith', 'john-bowen'],
    text: 'Five voices of two oscillators each, and the first synthesizer that stored every setting of a sound in memory. It made the polysynth practical in the studio and on stage.' },
  { id: 'sequential-pro-one', name: 'Sequential Circuits Pro-One', maker: 'Sequential Circuits', year: '1981', kind: 'mono', people: ['dave-smith'], app: ['pro-1'],
    text: 'One voice of the Prophet-5 in a small, cheap keyboard, with a sequencer, an arpeggiator and the Prophet’s modulation routing.' },
  { id: 'sequential-prophet-600', name: 'Sequential Circuits Prophet-600', maker: 'Sequential Circuits', year: '1982', kind: 'poly', people: ['dave-smith'], app: ['pro-800'],
    text: 'A six-voice, cheaper Prophet, and one end of the first public MIDI connection, to a Roland Jupiter-6 at the 1983 NAMM show.' },
  { id: 'yamaha-dx7', name: 'Yamaha DX7', maker: 'Yamaha', year: '1983', kind: 'poly', people: ['john-chowning'],
    text: 'A digital FM synthesizer: six sine-wave operators modulating each other, in place of oscillators and filters. The best-selling synthesizer of the 1980s, heard on electric-piano and bell sounds everywhere.' },
  { id: 'yamaha-tx81z', name: 'Yamaha TX81Z', maker: 'Yamaha', year: '1987', kind: 'module', people: ['john-chowning'],
    text: 'A cheap rack FM module with four operators and waveforms beyond the sine. Its “Lately Bass” preset is all over house music.' },
  { id: 'behringer-deepmind-12', name: 'Behringer DeepMind 12', maker: 'Behringer', year: '2016', kind: 'poly', people: ['uli-behringer'], app: ['deepmind-12d'],
    text: 'Behringer’s first original analogue polysynth: twelve voices in the Juno tradition, with a modulation matrix and built-in effects.' },
  { id: 'behringer-neutron', name: 'Behringer Neutron', maker: 'Behringer', year: '2018', kind: 'semi-modular', people: ['uli-behringer'], app: ['neutron'],
    text: 'An original semi-modular built round two 3340 oscillator chips, with a patch bay and an overdrive and delay.' },
  { id: 'behringer-poly-d', name: 'Behringer Poly D', maker: 'Behringer', year: '2019', kind: 'paraphonic', people: ['uli-behringer'], app: ['poly-d'],
    text: 'A Minimoog-style synth with a fourth oscillator, four-note paraphony, a sequencer and a chorus.' },
  { id: 'rca-theremin', name: 'RCA Theremin', maker: 'RCA', year: '1929', kind: 'mono', people: ['leon-theremin'],
    text: 'Leon Theremin’s instrument of 1920, made under licence by RCA from 1929: one antenna sets the pitch and a loop sets the volume, and the player never touches it. The gliding, wavering tone of 1950s science-fiction films.' },
  { id: 'theremin-rhythmicon', name: 'Rhythmicon', maker: 'Leon Theremin', year: '1931', kind: 'sequencer', people: ['leon-theremin'],
    text: 'A keyboard machine built for Henry Cowell that plays repeating pulses at rhythms in whole-number ratios, each key a different rate and pitch. Often called the first drum machine.' },
  { id: 'ondes-martenot', name: 'Ondes Martenot', maker: 'Maurice Martenot', year: '1928', kind: 'mono', people: ['maurice-martenot'],
    text: 'A monophonic vacuum-tube instrument played from a keyboard or by sliding a ring along a wire, with a pressure key for loudness and a choice of loudspeakers. Written for by Messiaen and Honegger.' },
  { id: 'trautonium', name: 'Trautonium', maker: 'Rundfunkversuchsstelle, Berlin', year: '1930', kind: 'mono', people: ['friedrich-trautwein', 'oskar-sala'],
    text: 'A monophonic instrument played by pressing a wire onto a metal rail, so any pitch along it can be played. Telefunken sold about 200 as the Volkstrautonium from 1933 to 1935.' },
  { id: 'mixtur-trautonium', name: 'Mixtur-Trautonium', maker: 'Oskar Sala', year: '1952', kind: 'poly', people: ['oskar-sala'],
    text: 'Oskar Sala’s two-manual development of the Trautonium, whose oscillators add subharmonics below each note. It made the bird sounds in Hitchcock’s The Birds.' },
  { id: 'hammond-novachord', name: 'Hammond Novachord', maker: 'Hammond', year: '1939', kind: 'poly', people: ['laurens-hammond'],
    text: 'A fully polyphonic electronic keyboard with filters and selectable envelope shapes, shown at the 1939 New York World’s Fair. About a thousand were made before 1942, and it was heard on film scores of the 1940s.' },
  { id: 'electronic-sackbut', name: 'Electronic Sackbut', maker: 'Hugh Le Caine', year: '1945', kind: 'mono', people: ['hugh-le-caine'],
    text: 'A monophonic keyboard instrument whose keys sense pressure and sideways movement, with left-hand controls for timbre. Four versions were built and none was sold.' },
  { id: 'rca-mark-ii', name: 'RCA Mark II Sound Synthesizer', maker: 'RCA', year: '1957', kind: 'sequencer', people: ['harry-olson', 'herbert-belar'],
    text: 'A room-sized vacuum-tube synthesizer at the Columbia-Princeton Electronic Music Center, programmed with punched paper rolls in place of being played. Milton Babbitt’s Philomel was made on it.' },
  { id: 'ans-synthesizer', name: 'ANS synthesizer', maker: 'Yevgeny Murzin', year: '1958', kind: 'poly', people: ['yevgeny-murzin'],
    text: 'A photoelectronic instrument from Moscow: marks scratched on a coated glass plate are read by light as up to 720 pure tones. Heard on Eduard Artemyev’s score for Tarkovsky’s Solaris.' },
  { id: 'oramics-machine', name: 'Oramics machine', maker: 'Oramics Studios', year: '1966', kind: 'sequencer', people: ['daphne-oram'],
    text: 'Daphne Oram’s machine for drawn sound: shapes drawn on strips of 35mm film, read by photocells, set the pitch, loudness and waveform of each note. Now in the Science Museum, London.' },
  { id: 'paia-gnome', name: 'PAiA Gnome', maker: 'PAiA Electronics', year: '1974', kind: 'mono', people: ['john-simonton'],
    text: 'A small battery-powered synthesizer sold as a kit for $48.95 in 1974 and mostly used for sound effects.' },
  { id: 'emu-modular', name: 'E-mu Modular System', maker: 'E-mu Systems', year: '1972', kind: 'modular', people: ['dave-rossum', 'scott-wedge'],
    text: 'E-mu’s large modular synthesizer, sold to studios and universities, later controlled by its own digitally scanned polyphonic keyboard.' },
  { id: 'serge-modular', name: 'Serge Modular', maker: 'Serge Modular Music Systems', year: '1974', kind: 'modular', people: ['serge-tcherepnin'],
    text: 'A West Coast-style modular, sold in part as kits, with banana-plug patching and modules that each do several jobs depending on how they are patched.' },
  { id: 'freeman-string-symphonizer', name: 'Freeman String Symphonizer', maker: 'Lowrey', year: '1974', kind: 'poly', people: ['ken-freeman'],
    text: 'Ken Freeman’s string synthesizer, made by Lowrey: an organ-style divide-down keyboard whose tone is thickened by delayed, wavering copies of itself to sound like a string section.' },
  { id: 'fairlight-cmi', name: 'Fairlight CMI', maker: 'Fairlight', year: '1979', kind: 'poly', people: ['peter-vogel', 'kim-ryrie', 'tony-furse'],
    text: 'A computer music system with a keyboard, screen and light pen, and the first sampler on sale. The Series II added the Page R sequencer in 1982. Heard across early-80s pop from Peter Gabriel to Kate Bush.' },
  { id: 'ned-synclavier', name: 'Synclavier', maker: 'New England Digital', year: '1977', kind: 'poly', people: ['sydney-alonso', 'cameron-jones'],
    text: 'A digital synthesizer built round its makers’ own computer, with FM and additive synthesis, later sampling and recording to hard disk. The Synclavier II followed in 1980, and full systems cost over $200,000.' },
  { id: 'emu-emulator', name: 'E-mu Emulator', maker: 'E-mu Systems', year: '1981', kind: 'poly', people: ['dave-rossum', 'scott-wedge'],
    text: 'A sampling keyboard sold for $7,900, a fraction of the price of a Fairlight, with sounds loaded from floppy disk.' },
  { id: 'ppg-wave-2', name: 'PPG Wave 2', maker: 'PPG', year: '1981', kind: 'poly', people: ['wolfgang-palm'],
    text: 'An eight-voice hybrid: digital wavetable oscillators that sweep through stored waveforms, followed by analogue filters. Updated as the Wave 2.2 in 1982 and the Wave 2.3 in 1984.' },
  { id: 'kurzweil-k250', name: 'Kurzweil K250', maker: 'Kurzweil Music Systems', year: '1984', kind: 'poly', people: ['ray-kurzweil'],
    text: 'A 12-voice keyboard with sampled acoustic instruments stored in ROM, developed with advice from Stevie Wonder and known for its piano.' },
  { id: 'emu-sp-1200', name: 'E-mu SP-1200', maker: 'E-mu Systems', year: '1987', kind: 'sequencer', people: ['dave-rossum', 'scott-wedge'],
    text: 'A sampling drum machine with a sequencer and a short, gritty 12-bit sample time, used to build drum loops in late-80s and 90s hip-hop.' },
  { id: 'doepfer-a-100', name: 'Doepfer A-100', maker: 'Doepfer Musikelektronik', year: '1995', kind: 'modular', people: ['dieter-doepfer'],
    text: 'The modular system that set the Eurorack format: 3U panels, a shared power bus and 3.5 mm patch cables, now used by hundreds of module makers.' },
  { id: 'buchla-100', name: 'Buchla 100 series', maker: 'Buchla & Associates', year: '1965', kind: 'modular', people: ['don-buchla'],
    text: 'Don Buchla’s first modular system, built for the San Francisco Tape Music Center. It was played from touch-sensitive plates rather than a piano keyboard and had a step sequencer; Morton Subotnick made Silver Apples of the Moon on one.' },
  { id: 'buchla-200', name: 'Buchla 200 series', maker: 'Buchla & Associates', year: '1970', kind: 'modular', people: ['don-buchla'],
    text: 'Buchla’s second modular series, with complex oscillators, lowpass gates and touch-plate controllers. The Music Easel was built from 200-series circuits in one case.' },
  { id: 'buchla-200e', name: 'Buchla 200e', maker: 'Buchla Electronic Musical Instruments', year: '2004', kind: 'modular', people: ['don-buchla'],
    text: 'A modern update of the 200 series, with the same West Coast modules plus patch memory and MIDI.' },
  { id: 'arp-pro-soloist', name: 'ARP Pro Soloist', maker: 'ARP Instruments', year: '1972', kind: 'mono',
    text: 'A small preset monosynth with 30 fixed sounds chosen by tab switches and a 37-note keyboard that responds to pressure. One of the first commercially successful preset synthesizers.' },
  { id: 'korg-micro-preset', name: 'Korg M-500 Micro-Preset', maker: 'Korg', year: '1977', kind: 'mono',
    text: 'A small single-oscillator monosynth with preset voices chosen by tabs and a “Traveller” slider that moves the filter and resonance together. OMD made the melodic parts of their early records on one.' },
  { id: 'korg-700s', name: 'Korg miniKORG 700S', maker: 'Korg', year: '1974', kind: 'mono', people: ['fumio-mieda'],
    text: 'The second version of Korg’s first synthesizer, the miniKORG 700, with a second oscillator added. The bass of the Human League’s “Being Boiled” was played on one.' },
  { id: 'roland-system-100', name: 'Roland System-100', maker: 'Roland', year: '1975', kind: 'semi-modular', people: ['ikutaro-kakehashi'],
    text: 'A set of small units – the 101 synthesizer, the 102 expander, a mixer, a sequencer and a pair of speakers – wired to play without cables, with patch points for joining them. Roland’s first modular-style system for home studios.' },
  { id: 'roland-system-700', name: 'Roland System-700', maker: 'Roland', year: '1976', kind: 'modular', people: ['ikutaro-kakehashi'],
    text: 'Roland’s large studio modular: cabinets of oscillators, filters, envelopes and sequencers joined by patch cords, in the manner of the big Moog systems.' },
  { id: 'oberheim-ob-x', name: 'Oberheim OB-X', maker: 'Oberheim Electronics', year: '1979', kind: 'poly', people: ['tom-oberheim'],
    text: 'Oberheim’s first polysynth built into a single case, with up to eight voices and patch memory. Its brass and its unison growl are on records by Rush and Japan; the OB-Xa replaced it in 1980.' },
  { id: 'oberheim-ob-8', name: 'Oberheim OB-8', maker: 'Oberheim Electronics', year: '1983', kind: 'poly', people: ['tom-oberheim'],
    text: 'The last of the OB series: an eight-voice polysynth that followed the OB-Xa, with more memories, split and layered keyboard modes and an arpeggiator.' },
  { id: 'roland-jx-8p', name: 'Roland JX-8P', maker: 'Roland', year: '1985', kind: 'poly', people: ['ikutaro-kakehashi'],
    text: 'A six-voice polysynth with two digitally controlled oscillators per voice and a keyboard that responds to velocity and aftertouch. Sounds are edited with buttons and one slider, or with the PG-800 programmer, which puts a knob on each setting.' },
  { id: 'elka-synthex', name: 'Elka Synthex', maker: 'Elka', year: '1981', kind: 'poly',
    text: 'An eight-voice Italian polysynth with two oscillators per voice, split and layered keyboard modes, a sequencer and an arpeggiator. Jean-Michel Jarre used it heavily on Rendez-Vous.' },
  { id: 'roland-sh-09', name: 'Roland SH-09', maker: 'Roland', year: '1978', kind: 'mono', people: ['ikutaro-kakehashi'],
    text: 'A small, cheap one-oscillator Roland monosynth with a sub-oscillator and a resonant filter, sold as an entry-level instrument.' },
  { id: 'roland-jx-3p', name: 'Roland JX-3P', maker: 'Roland', year: '1983', kind: 'poly', people: ['ikutaro-kakehashi'],
    text: 'A six-voice polysynth with two digitally controlled oscillators per voice, a simple step sequencer and one of the first MIDI sockets. Most of its settings were edited with an optional programmer, the PG-200.' },
  { id: 'roland-vp-330', name: 'Roland VP-330 Vocoder Plus', maker: 'Roland', year: '1979', kind: 'poly', people: ['ikutaro-kakehashi'],
    text: 'A keyboard vocoder with its own string and human-voice ensemble sounds, so the keyboard can play a voice through the vocoder or a choir and strings on their own.' },
  { id: 'yamaha-dx100', name: 'Yamaha DX100', maker: 'Yamaha', year: '1985', kind: 'poly', people: ['john-chowning'],
    text: 'A small, cheap four-operator FM synth with mini keys. Its hard, simple bass sounds were used on many house and techno records of the late 1980s.' },
  { id: 'sequential-six-trak', name: 'Sequential Circuits Six-Trak', maker: 'Sequential Circuits', year: '1984', kind: 'poly', people: ['dave-smith'],
    text: 'A six-voice polysynth with one oscillator per voice and a built-in six-track sequencer. Each voice could play a different sound, which made it one of the first multitimbral synthesizers.' },
  { id: 'ems-synthi-a', name: 'EMS Synthi A', maker: 'Electronic Music Studios', year: '1971', kind: 'semi-modular', people: ['david-cockerell', 'peter-zinovieff'],
    text: 'The VCS3’s circuits in a briefcase, with the pin matrix and joystick but no keyboard. The Synthi AKS is the same instrument with a touch keyboard and sequencer in the lid.' },
  { id: 'ems-synthi-100', name: 'EMS Synthi 100', maker: 'Electronic Music Studios', year: '1971', kind: 'modular', people: ['david-cockerell', 'peter-zinovieff'],
    text: 'A desk-sized studio synthesizer built from many VCS3-style voices, with two pin matrices and a digital sequencer. Only around thirty were made, mostly for broadcasters and studios.' },
  { id: 'korg-minikorg-700', name: 'Korg miniKORG 700', maker: 'Korg', year: '1973', kind: 'mono', people: ['tsutomu-katoh'],
    text: 'Korg’s first synthesizer: a small monosynth with its controls on a panel under the front of the keyboard and a ribbon-like “traveler” filter. It was also sold as the Univox Mini-Korg.' },
  { id: 'korg-mono-poly', name: 'Korg Mono/Poly', maker: 'Korg', year: '1981', kind: 'paraphonic', people: ['tsutomu-katoh'],
    text: 'Four oscillators that can be stacked as one big monophonic voice or shared out across four keys through one filter, with an arpeggiator, sync and cross modulation.' },
  { id: 'korg-polysix', name: 'Korg Polysix', maker: 'Korg', year: '1981', kind: 'poly', people: ['tsutomu-katoh'],
    text: 'A cheap six-voice polysynth with patch memory, an arpeggiator, a chorus and phaser, and a chord-memory mode that plays a stored chord from a single key.' },
  { id: 'rhodes-chroma', name: 'Rhodes Chroma', maker: 'Rhodes (CBS)', year: '1982', kind: 'poly',
    text: 'A sixteen-oscillator polysynth designed at ARP and sold under the Rhodes name after ARP closed, programmed by choosing a parameter and moving one slider, with a weighted wooden keyboard.' },
  { id: 'roland-mc-202', name: 'Roland MC-202', maker: 'Roland', year: '1983', kind: 'sequencer', people: ['ikutaro-kakehashi'],
    text: 'A small battery-powered box pairing an SH-101-style one-oscillator voice with a step sequencer, programmed from a row of note buttons. Roland sold it as a MicroComposer.' },
  { id: 'sequential-prophet-vs', name: 'Sequential Circuits Prophet VS', maker: 'Sequential Circuits', year: '1986', kind: 'poly', people: ['dave-smith'],
    text: 'An eight-voice synth that mixes four digital waveforms per voice with a joystick or envelope, a method called vector synthesis, through analogue filters.' },
  { id: 'roland-jv-1080', name: 'Roland JV-1080', maker: 'Roland', year: '1994', kind: 'module', people: ['ikutaro-kakehashi'],
    text: 'A rack-mounted sample-playback synthesizer of the 1990s, with hundreds of preset pianos, strings, pads and electric pianos.' },
  { id: 'sequential-prophet-08', name: 'Dave Smith Instruments Prophet ’08', maker: 'Dave Smith Instruments', year: '2007', kind: 'poly', people: ['dave-smith'],
    text: 'Dave Smith’s return to the analogue polysynth: eight voices of two oscillators with Curtis filters and a step sequencer.' },
  { id: 'sequential-prophet-6', name: 'Sequential Prophet-6', maker: 'Dave Smith Instruments', year: '2015', kind: 'poly', people: ['dave-smith'],
    text: 'A six-voice analogue polysynth with voltage-controlled oscillators and filters in the manner of the Prophet-5, plus patch memory, effects and a sequencer.' },
];
